local dup_table = {
    ["xnzz"] = {["phrase"] = "现在", ["word"] = {"跹"}},
    ["yixk"] = {["phrase"] = "一些", ["word"] = {"怡"}},
    ["iiym"] = {["phrase"] = "使用", ["word"] = {"谥"}},
    ["yisi"] = {["phrase"] = "意思", ["word"] = {"矣"}},
    ["ekir"] = {["phrase"] = "接受", ["word"] = {"颉"}},
    ["guii"] = {["phrase"] = "故事", ["word"] = {"辜"}},
    ["bdbd"] = {["phrase"] = "宝宝", ["word"] = {"刨"}},
    ["hetm"] = {["phrase"] = "合同", ["word"] = {"盍"}},
    ["yudd"] = {["phrase"] = "遇到", ["word"] = {"淤", "渝"}},
    ["yidm"] = {["phrase"] = "移动", ["word"] = {"溢"}},
    ["hvyh"] = {["phrase"] = "会员", ["word"] = {"诙"}},
    ["qidm"] = {["phrase"] = "启动", ["word"] = {"柒"}},
    ["eike"] = {["phrase"] = "即可", ["word"] = {"唧"}},
    ["eydi"] = {["phrase"] = "降低", ["word"] = {"浆"}},
    ["yfgo"] = {["phrase"] = "英国", ["word"] = {"膺"}},
    ["endd"] = {["phrase"] = "见到", ["word"] = {"湔"}},
    ["pwyl"] = {["phrase"] = "培养", ["word"] = {"霈"}},
    ["vtlg"] = {["phrase"] = "战略", ["word"] = {"战"}},
    ["ecvl"] = {["phrase"] = "紧张", ["word"] = {"劲", "筋"}},
    ["xndz"] = {["phrase"] = "现代", ["word"] = {"涎"}},
    ["iiqi"] = {["phrase"] = "时期", ["word"] = {"舐"}},
    ["yipn"] = {["phrase"] = "一片", ["word"] = {"乂"}},
    ["ybxu"] = {["phrase"] = "允许", ["word"] = {"恽"}},
    ["hhbd"] = {["phrase"] = "环保", ["word"] = {"痪"}},
    ["xnde"] = {["phrase"] = "显得", ["word"] = {"洗", "冼"}},
    ["lfrs"] = {["phrase"] = "令人", ["word"] = {"令", "伶"}},
    ["eiyi"] = {["phrase"] = "记忆", ["word"] = {"计"}},
    ["svii"] = {["phrase"] = "随时", ["word"] = {"尿", "碎"}},
    ["viec"] = {["phrase"] = "至今", ["word"] = {"峙"}},
    ["ycdd"] = {["phrase"] = "引导", ["word"] = {"洇"}},
    ["boii"] = {["phrase"] = "博士", ["word"] = {"擘"}},
    ["ytuu"] = {["phrase"] = "演出", ["word"] = {"衍"}},
    ["xiir"] = {["phrase"] = "吸收", ["word"] = {"屣"}},
    ["suvr"] = {["phrase"] = "苏州", ["word"] = {"簌"}},
    ["pcvi"] = {["phrase"] = "品质", ["word"] = {"颦"}},
    ["liul"] = {["phrase"] = "立场", ["word"] = {"历", "励", "厘"}},
    ["yhuy"] = {["phrase"] = "原创", ["word"] = {"辕"}},
    ["vize"] = {["phrase"] = "职责", ["word"] = {"踯"}},
    ["qici"] = {["phrase"] = "其次", ["word"] = {"芪"}},
    ["ydba"] = {["phrase"] = "要把", ["word"] = {"疟"}},
    ["ebdv"] = {["phrase"] = "军队", ["word"] = {"龟"}},
    ["tttd"] = {["phrase"] = "探讨", ["word"] = {"坍"}},
    ["hvkh"] = {["phrase"] = "汇款", ["word"] = {"咴"}},
    ["vmvm"] = {["phrase"] = "种种", ["word"] = {"盅"}},
    ["qidd"] = {["phrase"] = "起到", ["word"] = {"沏"}},
    ["ytul"] = {["phrase"] = "延长", ["word"] = {"餍"}},
    ["mwmw"] = {["phrase"] = "妹妹", ["word"] = {"枚"}},
    ["bici"] = {["phrase"] = "彼此", ["word"] = {"荜", "薜"}},
    ["eici"] = {["phrase"] = "几次", ["word"] = {"蒺"}},
    ["vmwu"] = {["phrase"] = "中午", ["word"] = {"螽"}},
    ["qqdv"] = {["phrase"] = "球队", ["word"] = {"龟"}},
    ["iifl"] = {["phrase"] = "释放", ["word"] = {"势"}},
    ["iitu"] = {["phrase"] = "试图", ["word"] = {"螫"}},
    ["yida"] = {["phrase"] = "一大", ["word"] = {"殪"}},
    ["yikr"] = {["phrase"] = "一口", ["word"] = {"颐"}},
    ["yily"] = {["phrase"] = "一辆", ["word"] = {"毅"}},
    ["bnli"] = {["phrase"] = "便利", ["word"] = {"辨", "辩", "辫"}},
    ["vudo"] = {["phrase"] = "诸多", ["word"] = {"渚", "潴"}},
    ["ekyg"] = {["phrase"] = "节约", ["word"] = {"讦"}},
    ["yiri"] = {["phrase"] = "一日", ["word"] = {"佚"}},
    ["pwfl"] = {["phrase"] = "配方", ["word"] = {"旆"}},
    ["hvhx"] = {["phrase"] = "绘画", ["word"] = {"秽"}},
    ["wwxf"] = {["phrase"] = "卫星", ["word"] = {"惟"}},
    ["euqf"] = {["phrase"] = "剧情", ["word"] = {"雎"}},
    ["qidn"] = {["phrase"] = "起点", ["word"] = {"凄"}},
    ["dlci"] = {["phrase"] = "档次", ["word"] = {"菪"}},
    ["eiho"] = {["phrase"] = "激活", ["word"] = {"稽"}},
    ["eihe"] = {["phrase"] = "集合", ["word"] = {"嵇"}},
    ["eilv"] = {["phrase"] = "纪律", ["word"] = {"乩"}},
    ["yeye"] = {["phrase"] = "爷爷", ["word"] = {"邺"}},
    ["helt"] = {["phrase"] = "荷兰", ["word"] = {"壑"}},
    ["voli"] = {["phrase"] = "着力", ["word"] = {"卓"}},
    ["euzi"] = {["phrase"] = "句子", ["word"] = {"遽"}},
    ["eida"] = {["phrase"] = "极大", ["word"] = {"殛"}},
    ["quuu"] = {["phrase"] = "取出", ["word"] = {"衢"}},
    ["ytve"] = {["phrase"] = "沿着", ["word"] = {"鄢"}},
    ["biii"] = {["phrase"] = "笔试", ["word"] = {"辟"}},
    ["mibu"] = {["phrase"] = "弥补", ["word"] = {"蜜"}},
    ["hzkr"] = {["phrase"] = "海口", ["word"] = {"咳"}},
    ["vidi"] = {["phrase"] = "之地", ["word"] = {"汁"}},
    ["yuwo"] = {["phrase"] = "与我", ["word"] = {"育"}},
    ["vibt"] = {["phrase"] = "值班", ["word"] = {"窒"}},
    ["xizd"] = {["phrase"] = "洗澡", ["word"] = {"蹊"}},
    ["bizi"] = {["phrase"] = "鼻子", ["word"] = {"避", "跸"}},
    ["qfhx"] = {["phrase"] = "清华", ["word"] = {"綮", "黥"}},
    ["yidb"] = {["phrase"] = "一顿", ["word"] = {"浥"}},
    ["gdyh"] = {["phrase"] = "高原", ["word"] = {"羔"}},
    ["butf"] = {["phrase"] = "不停", ["word"] = {"埔"}},
    ["luvi"] = {["phrase"] = "录制", ["word"] = {"舻", "箓"}},
    ["bwpo"] = {["phrase"] = "被迫", ["word"] = {"褙"}},
    ["yhxn"] = {["phrase"] = "原先", ["word"] = {"鸳"}},
    ["xkir"] = {["phrase"] = "携手", ["word"] = {"颉"}},
    ["iiyg"] = {["phrase"] = "十月", ["word"] = {"式", "试"}},
    ["ejul"] = {["phrase"] = "较长", ["word"] = {"轿"}},
    -- ["iirl"] = {["phrase"] = "是让", ["word"] = {"使", "食"}},
    ["lqii"] = {["phrase"] = "流失", ["word"] = {"碌"}},
    ["fufw"] = {["phrase"] = "付费", ["word"] = {"抚", "敷"}},
    ["xywz"] = {["phrase"] = "向外", ["word"] = {"享"}},
    ["dide"] = {["phrase"] = "低的", ["word"] = {"邸"}},
    ["quen"] = {["phrase"] = "区间", ["word"] = {"娶"}},
    ["wuyr"] = {["phrase"] = "无忧", ["word"] = {"诬"}},
    ["bivi"] = {["phrase"] = "壁纸", ["word"] = {"筚"}},
    ["xnee"] = {["phrase"] = "限额", ["word"] = {"岘"}},
    ["enbk"] = {["phrase"] = "鉴别", ["word"] = {"謇"}},
    ["ekiv"] = {["phrase"] = "节水", ["word"] = {"碣"}},
    ["isye"] = {["phrase"] = "深夜", ["word"] = {"诜"}},
    ["eydd"] = {["phrase"] = "降到", ["word"] = {"奖"}},
    ["ekil"] = {["phrase"] = "街上", ["word"] = {"劼"}},
    ["zidt"] = {["phrase"] = "子弹", ["word"] = {"淄"}},
    ["huhh"] = {["phrase"] = "呼唤", ["word"] = {"烀"}},
    ["dtdl"] = {["phrase"] = "但当", ["word"] = {"殚"}},
    ["xgya"] = {["phrase"] = "血压", ["word"] = {"谑"}},
    ["enro"] = {["phrase"] = "减弱", ["word"] = {"僭"}},
    ["xjvs"] = {["phrase"] = "小镇", ["word"] = {"箫"}},
    ["uumo"] = {["phrase"] = "触摸", ["word"] = {"楮"}},
    ["dfyd"] = {["phrase"] = "定要", ["word"] = {"订", "酊"}},
    ["iian"] = {["phrase"] = "是按", ["word"] = {"豕"}},
    ["xihx"] = {["phrase"] = "细化", ["word"] = {"熄"}},
    ["yixc"] = {["phrase"] = "一心", ["word"] = {"羿"}},
    ["dudd"] = {["phrase"] = "督导", ["word"] = {"渎"}},
    ["fudz"] = {["phrase"] = "附带", ["word"] = {"浮"}},
    ["vidv"] = {["phrase"] = "支队", ["word"] = {"沚"}},
    ["fuxf"] = {["phrase"] = "复兴", ["word"] = {"怫"}},
    ["qimj"] = {["phrase"] = "奇妙", ["word"] = {"杞", "桤"}},
    ["eivb"] = {["phrase"] = "基准", ["word"] = {"箕"}},
    ["dmek"] = {["phrase"] = "冻结", ["word"] = {"峒"}},
    ["lian"] = {["phrase"] = "立案", ["word"] = {"吏"}},
    ["iiri"] = {["phrase"] = "十日", ["word"] = {"什", "仕"}},
    ["vizi"] = {["phrase"] = "之子", ["word"] = {"跖"}},
    ["hvym"] = {["phrase"] = "会用", ["word"] = {"诲"}},
    ["yhde"] = {["phrase"] = "远的", ["word"] = {"沅"}},
    ["fucz"] = {["phrase"] = "福彩", ["word"] = {"莩"}},
    ["wtbd"] = {["phrase"] = "晚报", ["word"] = {"剜"}},
    ["fwkf"] = {["phrase"] = "飞快", ["word"] = {"匪", "啡"}},
    ["viio"] = {["phrase"] = "之说", ["word"] = {"智"}},
    ["iiec"] = {["phrase"] = "使劲", ["word"] = {"峙"}},
    ["uaia"] = {["phrase"] = "查杀", ["word"] = {"馇", "碴"}},
    ["enyg"] = {["phrase"] = "简约", ["word"] = {"艰", "戬"}},
    ["drba"] = {["phrase"] = "都把", ["word"] = {"痘"}},
    ["ejyh"] = {["phrase"] = "教员", ["word"] = {"醮"}},
    ["eitj"] = {["phrase"] = "几条", ["word"] = {"圾"}},
    -- ["iuww"] = {["phrase"] = "数为", ["word"] = {"孰"}},
    ["mwym"] = {["phrase"] = "没用", ["word"] = {"霉", "酶"}},
    ["ludi"] = {["phrase"] = "陆地", ["word"] = {"泸", "渌"}},
    ["vtdv"] = {["phrase"] = "战队", ["word"] = {"湛"}},
    ["rude"] = {["phrase"] = "入的", ["word"] = {"濡"}},
    ["yier"] = {["phrase"] = "一二", ["word"] = {"嶷"}},
    ["bukf"] = {["phrase"] = "不快", ["word"] = {"哺"}},
    ["vpfa"] = {["phrase"] = "蒸发", ["word"] = {"拯"}},
    ["qnbi"] = {["phrase"] = "铅笔", ["word"] = {"搴"}},
    ["fuyd"] = {["phrase"] = "服药", ["word"] = {"黻"}},
    ["luzi"] = {["phrase"] = "路子", ["word"] = {"逯"}},
    ["fubj"] = {["phrase"] = "附表", ["word"] = {"斧"}},
    ["ejdh"] = {["phrase"] = "较短", ["word"] = {"湫"}},
    ["wumw"] = {["phrase"] = "妩媚", ["word"] = {"杌"}},
    ["eiej"] = {["phrase"] = "计较", ["word"] = {"岌"}},
    ["iiir"] = {["phrase"] = "是受", ["word"] = {"贳"}},
    ["qiri"] = {["phrase"] = "七日", ["word"] = {"俟"}},
    ["ythh"] = {["phrase"] = "延缓", ["word"] = {"炎", "焱"}},
    ["xjmw"] = {["phrase"] = "小妹", ["word"] = {"骁"}},
    ["bdzi"] = {["phrase"] = "包子", ["word"] = {"趵"}},
    ["dnbd"] = {["phrase"] = "电报", ["word"] = {"奠"}},
    ["wwtn"] = {["phrase"] = "未填", ["word"] = {"畏"}},
    ["yizd"] = {["phrase"] = "一早", ["word"] = {"逸", "劓"}},
    ["eiee"] = {["phrase"] = "饥饿", ["word"] = {"觊"}},
    ["ytup"] = {["phrase"] = "盐城", ["word"] = {"彦"}},
    ["iiln"] = {["phrase"] = "失恋", ["word"] = {"史"}},
    ["sudi"] = {["phrase"] = "速递", ["word"] = {"涑", "觫"}},
    ["yism"] = {["phrase"] = "移送", ["word"] = {"缢"}},
    ["ieuu"] = {["phrase"] = "射出", ["word"] = {"厍"}},
    ["zidn"] = {["phrase"] = "字典", ["word"] = {"姿"}},
    ["nidd"] = {["phrase"] = "你到", ["word"] = {"溺"}},
    ["xkye"] = {["phrase"] = "鞋业", ["word"] = {"邪"}},
    ["wwen"] = {["phrase"] = "未见", ["word"] = {"隈"}},
    ["yihb"] = {["phrase"] = "已婚", ["word"] = {"熠"}},
    ["wwmw"] = {["phrase"] = "唯美", ["word"] = {"闱"}},
    ["wunw"] = {["phrase"] = "屋内", ["word"] = {"物", "妩"}},
    ["qidi"] = {["phrase"] = "启迪", ["word"] = {"漆"}},
    ["ymwt"] = {["phrase"] = "用完", ["word"] = {"壅"}},
    ["dimd"] = {["phrase"] = "地貌", ["word"] = {"柢"}},
    ["ytke"] = {["phrase"] = "眼科", ["word"] = {"郾"}},
    ["iixg"] = {["phrase"] = "史学", ["word"] = {"弑"}},
    ["migm"] = {["phrase"] = "迷宫", ["word"] = {"糜", "麋"}},
    ["iuwt"] = {["phrase"] = "数万", ["word"] = {"塾"}},
    ["vefu"] = {["phrase"] = "这幅", ["word"] = {"蛰", "蜇"}},
    ["zidi"] = {["phrase"] = "子弟", ["word"] = {"滓"}},
    ["vrye"] = {["phrase"] = "昼夜", ["word"] = {"诌"}},
    ["dazz"] = {["phrase"] = "打在", ["word"] = {"跶"}},
    ["hedn"] = {["phrase"] = "核电", ["word"] = {"鹤"}},
    ["iurm"] = {["phrase"] = "殊荣", ["word"] = {"毹"}},
    ["xiyd"] = {["phrase"] = "西药", ["word"] = {"羲"}},
    ["enbd"] = {["phrase"] = "简报", ["word"] = {"剪"}},
    ["buld"] = {["phrase"] = "捕捞", ["word"] = {"卜"}},
    ["yugl"] = {["phrase"] = "浴缸", ["word"] = {"鬻"}},
    ["piii"] = {["phrase"] = "批示", ["word"] = {"辟", "鼙"}},
    ["uefw"] = {["phrase"] = "车费", ["word"] = {"撤"}},
    ["mwgm"] = {["phrase"] = "美工", ["word"] = {"糜"}},
    ["kebk"] = {["phrase"] = "可别", ["word"] = {"客", "疴"}},
    ["yupn"] = {["phrase"] = "余篇", ["word"] = {"臾"}},
    ["ildp"] = {["phrase"] = "上等", ["word"] = {"殇", "觞"}},
    ["eydm"] = {["phrase"] = "江东", ["word"] = {"桨"}},
    ["vudv"] = {["phrase"] = "主队", ["word"] = {"注", "洙"}},
    ["eidj"] = {["phrase"] = "基调", ["word"] = {"汲"}},
    ["eflo"] = {["phrase"] = "经络", ["word"] = {"靖"}},
    ["bwfu"] = {["phrase"] = "背负", ["word"] = {"辈"}},
    ["ejcb"] = {["phrase"] = "缴存", ["word"] = {"藠"}},
    ["yuyr"] = {["phrase"] = "遇有", ["word"] = {"欤"}},
    ["yfbn"] = {["phrase"] = "应变", ["word"] = {"瘿"}},
    ["enzz"] = {["phrase"] = "建在", ["word"] = {"踺"}},
    ["rupc"] = {["phrase"] = "乳品", ["word"] = {"褥"}},
    ["lndz"] = {["phrase"] = "连带", ["word"] = {"涟"}},
    ["eidd"] = {["phrase"] = "即到", ["word"] = {"剞"}},
    ["xuno"] = {["phrase"] = "许诺", ["word"] = {"婿"}},
    ["efxx"] = {["phrase"] = "井下", ["word"] = {"惊", "憬"}},
    ["xfxi"] = {["phrase"] = "星系", ["word"] = {"性", "惺"}},
    ["voyi"] = {["phrase"] = "桌椅", ["word"] = {"酌"}},
    ["iibt"] = {["phrase"] = "石板", ["word"] = {"室"}},
    ["yuyd"] = {["phrase"] = "余姚", ["word"] = {"谕"}},
    ["issi"] = {["phrase"] = "深思", ["word"] = {"绅"}},
    ["xfip"] = {["phrase"] = "兴盛", ["word"] = {"饧"}},
    ["visi"] = {["phrase"] = "致死", ["word"] = {"纸"}},
    ["pudn"] = {["phrase"] = "铺垫", ["word"] = {"濮"}},
    ["fwfw"] = {["phrase"] = "飞飞", ["word"] = {"斐"}},
    ["eqpa"] = {["phrase"] = "就怕", ["word"] = {"臼"}},
    ["iiiu"] = {["phrase"] = "市属", ["word"] = {"蚀"}},
    ["dtfl"] = {["phrase"] = "单方", ["word"] = {"掸"}},
    ["lrmn"] = {["phrase"] = "露面", ["word"] = {"娄", "楼"}},
    ["yryl"] = {["phrase"] = "悠扬", ["word"] = {"幼"}},
    ["pukf"] = {["phrase"] = "普快", ["word"] = {"圃"}},
    ["iivu"] = {["phrase"] = "石柱", ["word"] = {"虱"}},
    ["visb"] = {["phrase"] = "止损", ["word"] = {"织"}},
    ["fpdf"] = {["phrase"] = "封顶", ["word"] = {"沣"}},
    ["luei"] = {["phrase"] = "路基", ["word"] = {"录"}},
    ["uidn"] = {["phrase"] = "吃点", ["word"] = {"鸱"}},
    ["vuzu"] = {["phrase"] = "驻足", ["word"] = {"躅"}},
    ["sidj"] = {["phrase"] = "死掉", ["word"] = {"澌"}},
    ["xfxg"] = {["phrase"] = "性学", ["word"] = {"悻"}},
    ["wwdo"] = {["phrase"] = "为多", ["word"] = {"洧", "渭"}},
    ["wuwl"] = {["phrase"] = "无望", ["word"] = {"务"}},
    ["fsdd"] = {["phrase"] = "分到", ["word"] = {"汾"}},
    ["qkxj"] = {["phrase"] = "切削", ["word"] = {"惬"}},
    ["fuyb"] = {["phrase"] = "浮云", ["word"] = {"讣"}},
    ["eism"] = {["phrase"] = "寄送", ["word"] = {"羁"}},
    ["vuve"] = {["phrase"] = "住着", ["word"] = {"邾", "竺"}},
    ["kekm"] = {["phrase"] = "可控", ["word"] = {"嗑"}},
    ["eiir"] = {["phrase"] = "棘手", ["word"] = {"赍"}},
    ["modd"] = {["phrase"] = "摸到", ["word"] = {"漠"}},
    ["wwdf"] = {["phrase"] = "未定", ["word"] = {"潍"}},
    ["qiir"] = {["phrase"] = "棋手", ["word"] = {"碛"}},
    ["itye"] = {["phrase"] = "山野", ["word"] = {"讪", "鄯"}},
    ["iiky"] = {["phrase"] = "实况", ["word"] = {"嘘"}},
    ["eian"] = {["phrase"] = "吉安", ["word"] = {"棘"}},
    ["ekrl"] = {["phrase"] = "接壤", ["word"] = {"介", "价"}},
    ["ecdd"] = {["phrase"] = "进到", ["word"] = {"浕"}},
    ["eidl"] = {["phrase"] = "激荡", ["word"] = {"济"}},
    ["gvvm"] = {["phrase"] = "贵重", ["word"] = {"簋"}},
    ["xieh"] = {["phrase"] = "席卷", ["word"] = {"隰"}},
    ["eidz"] = {["phrase"] = "几代", ["word"] = {"洎"}},
    ["dugu"] = {["phrase"] = "独孤", ["word"] = {"髑"}},
    ["ecso"] = {["phrase"] = "紧缩", ["word"] = {"缙"}},
    ["lial"] = {["phrase"] = "里昂", ["word"] = {"鲤", "鬲", "鲡"}},
    ["eisv"] = {["phrase"] = "脊髓", ["word"] = {"继"}},
    ["pjxg"] = {["phrase"] = "飘雪", ["word"] = {"瓢"}},
    ["yihx"] = {["phrase"] = "异化", ["word"] = {"移", "黟"}},
    ["eimj"] = {["phrase"] = "几秒", ["word"] = {"机", "极"}},
    ["fuvl"] = {["phrase"] = "腹胀", ["word"] = {"弗"}},
    ["eigv"] = {["phrase"] = "机柜", ["word"] = {"既"}},
    ["hhdd"] = {["phrase"] = "环岛", ["word"] = {"涣", "奂"}},
    ["liln"] = {["phrase"] = "历练", ["word"] = {"鹂"}},
    ["yure"] = {["phrase"] = "预热", ["word"] = {"觎"}},
    ["uiil"] = {["phrase"] = "吃上", ["word"] = {"饬"}},
    ["lidd"] = {["phrase"] = "力道", ["word"] = {"漓"}},
    ["tddd"] = {["phrase"] = "逃到", ["word"] = {"洮"}},
    ["livu"] = {["phrase"] = "立柱", ["word"] = {"蠡"}},
    ["uivu"] = {["phrase"] = "吃住", ["word"] = {"蚩"}},
    ["yuvy"] = {["phrase"] = "预装", ["word"] = {"竽"}},
    ["eeyb"] = {["phrase"] = "厄运", ["word"] = {"讹"}},
    ["wodn"] = {["phrase"] = "我点", ["word"] = {"涡"}},
    ["ximn"] = {["phrase"] = "西面", ["word"] = {"樨"}},
    ["siri"] = {["phrase"] = "四日", ["word"] = {"俟"}},
    ["ftpt"] = {["phrase"] = "反叛", ["word"] = {"番"}},
    ["hvxh"] = {["phrase"] = "回旋", ["word"] = {"恢"}},
    ["xkmd"] = {["phrase"] = "鞋帽", ["word"] = {"楔"}},
    ["erde"] = {["phrase"] = "尔德", ["word"] = {"洱"}},
    ["bzii"] = {["phrase"] = "白石", ["word"] = {"掰"}},
    ["dtvl"] = {["phrase"] = "单张", ["word"] = {"箪"}},
    ["uuiu"] = {["phrase"] = "出书", ["word"] = {"础"}},
    ["ttta"] = {["phrase"] = "坍塌", ["word"] = {"坦"}},
    ["xixx"] = {["phrase"] = "西夏", ["word"] = {"恓"}},
    ["vydn"] = {["phrase"] = "装点", ["word"] = {"妆"}},
    ["lici"] = {["phrase"] = "历次", ["word"] = {"藜"}},
    ["wusm"] = {["phrase"] = "武松", ["word"] = {"骛"}},
    ["xbzi"] = {["phrase"] = "荀子", ["word"] = {"迅"}},
    ["ptvp"] = {["phrase"] = "盘整", ["word"] = {"爿"}},
    ["itbl"] = {["phrase"] = "掸邦", ["word"] = {"单"}},
    ["bulw"] = {["phrase"] = "布雷", ["word"] = {"瓿"}},
    ["eido"] = {["phrase"] = "几多", ["word"] = {"脊"}},
    ["qneq"] = {["phrase"] = "迁就", ["word"] = {"阡"}},
    ["dumo"] = {["phrase"] = "镀膜", ["word"] = {"阇"}},
    ["yuhl"] = {["phrase"] = "余杭", ["word"] = {"煜"}},
    ["lzdl"] = {["phrase"] = "来当", ["word"] = {"涞"}},
    ["xkdu"] = {["phrase"] = "亵渎", ["word"] = {"蟹"}},
    ["yiui"] = {["phrase"] = "一尺", ["word"] = {"轶"}},
    ["eial"] = {["phrase"] = "激昂", ["word"] = {"鲚"}},
    ["ecma"] = {["phrase"] = "金马", ["word"] = {"槿"}},
    ["iudi"] = {["phrase"] = "属地", ["word"] = {"沭"}},
    ["lqdd"] = {["phrase"] = "六道", ["word"] = {"浏"}},
    ["yizr"] = {["phrase"] = "一走", ["word"] = {"遗"}},
    ["wweg"] = {["phrase"] = "味觉", ["word"] = {"巍", "隗", "嵬"}},
    ["eibi"] = {["phrase"] = "击毙", ["word"] = {"疾"}},
    ["qise"] = {["phrase"] = "起色", ["word"] = {"缉"}},
    ["ejkh"] = {["phrase"] = "交款", ["word"] = {"噍"}},
    ["yuqh"] = {["phrase"] = "玉泉", ["word"] = {"狳"}},
    ["viif"] = {["phrase"] = "直率", ["word"] = {"雉"}},
    ["keui"] = {["phrase"] = "可耻", ["word"] = {"蝌"}},
    ["yidk"] = {["phrase"] = "一叠", ["word"] = {"漪"}},
    ["qndo"] = {["phrase"] = "千多", ["word"] = {"潜"}},
    ["eraa"] = {["phrase"] = "儿啊", ["word"] = {"二", "耳"}},
    ["lihh"] = {["phrase"] = "罹患", ["word"] = {"黧"}},
    ["ltdj"] = {["phrase"] = "蓝调", ["word"] = {"澜"}},
    ["eiyt"] = {["phrase"] = "几眼", ["word"] = {"畿"}},
    ["vibc"] = {["phrase"] = "之滨", ["word"] = {"痔"}},
    ["tomd"] = {["phrase"] = "脱毛", ["word"] = {"驮"}},
    ["vafa"] = {["phrase"] = "闸阀", ["word"] = {"揸"}},
    ["xiix"] = {["phrase"] = "洗刷", ["word"] = {"硒"}},
    ["dtba"] = {["phrase"] = "丹巴", ["word"] = {"疸"}},
    ["yikm"] = {["phrase"] = "一空", ["word"] = {"嗌"}},
    ["ekul"] = {["phrase"] = "结肠", ["word"] = {"蚧"}},
    ["hxmi"] = {["phrase"] = "画谜", ["word"] = {"桦", "骅"}},
    ["eiwl"] = {["phrase"] = "既往", ["word"] = {"齑"}},
    ["vpvl"] = {["phrase"] = "整张", ["word"] = {"筝"}},
    ["xydo"] = {["phrase"] = "想多", ["word"] = {"湘"}},
    ["yell"] = {["phrase"] = "野狼", ["word"] = {"野"}},
    ["vifw"] = {["phrase"] = "直飞", ["word"] = {"执"}},
    ["upum"] = {["phrase"] = "成虫", ["word"] = {"盛"}},
    ["wwrl"] = {["phrase"] = "为让", ["word"] = {"位"}},
    ["qiek"] = {["phrase"] = "七届", ["word"] = {"崎"}},
    ["qucz"] = {["phrase"] = "取材", ["word"] = {"蘧"}},
    -- ["iiyb"] = {["phrase"] = "诗云", ["word"] = {"识"}},
    ["ciyg"] = {["phrase"] = "次月", ["word"] = {"差"}},
    ["yium"] = {["phrase"] = "一重", ["word"] = {"螠"}},
    ["fupz"] = {["phrase"] = "复牌", ["word"] = {"孚"}},
    ["mige"] = {["phrase"] = "米格", ["word"] = {"弭"}},
    ["ekkb"] = {["phrase"] = "解困", ["word"] = {"喈"}},
    ["vidl"] = {["phrase"] = "只当", ["word"] = {"觯"}},
    ["lida"] = {["phrase"] = "利达", ["word"] = {"澧"}},
    ["xidh"] = {["phrase"] = "西段", ["word"] = {"潟"}},
    ["xksi"] = {["phrase"] = "血丝", ["word"] = {"绁"}},
    ["fwyf"] = {["phrase"] = "飞鹰", ["word"] = {"诽", "霏"}},
    ["mttl"] = {["phrase"] = "满堂", ["word"] = {"埋"}},
    ["bwle"] = {["phrase"] = "背了", ["word"] = {"邶"}},
    ["yuym"] = {["phrase"] = "御用", ["word"] = {"盂"}},
    ["dokm"] = {["phrase"] = "多孔", ["word"] = {"哚"}},
    ["xidj"] = {["phrase"] = "洗掉", ["word"] = {"浠", "淅"}},
    ["vpyl"] = {["phrase"] = "正阳", ["word"] = {"诤"}},
    ["tomo"] = {["phrase"] = "唾沫", ["word"] = {"椭"}},
    ["luqi"] = {["phrase"] = "撸起", ["word"] = {"氯"}},
    ["iumc"] = {["phrase"] = "庶民", ["word"] = {"树"}},
    ["xkdn"] = {["phrase"] = "鞋垫", ["word"] = {"解", "澥"}},
    ["ydbl"] = {["phrase"] = "要帮", ["word"] = {"窈"}},
    ["liyl"] = {["phrase"] = "李阳", ["word"] = {"雳"}},
    ["qcrd"] = {["phrase"] = "侵扰", ["word"] = {"禽"}},
    ["eiyl"] = {["phrase"] = "几样", ["word"] = {"霁"}},
    ["ydpn"] = {["phrase"] = "药片", ["word"] = {"鹞"}},
    ["yber"] = {["phrase"] = "云儿", ["word"] = {"陨"}},
    ["hvxm"] = {["phrase"] = "灰熊", ["word"] = {"悔"}},
    ["lnda"] = {["phrase"] = "联大", ["word"] = {"殓"}},
    -- ["lihm"] = {["phrase"] = "李红", ["word"] = {"梨"}},
    ["xcci"] = {["phrase"] = "新词", ["word"] = {"莘"}},
    ["zdzo"] = {["phrase"] = "造作", ["word"] = {"遭"}},
    ["bidw"] = {["phrase"] = "必得", ["word"] = {"敝"}},
    ["bwkr"] = {["phrase"] = "被扣", ["word"] = {"贝", "呗"}},
    ["digd"] = {["phrase"] = "底稿", ["word"] = {"底", "骶"}},
    ["hmdn"] = {["phrase"] = "红点", ["word"] = {"鸿"}},
    ["tuio"] = {["phrase"] = "图说", ["word"] = {"屠"}},
    ["suyh"] = {["phrase"] = "溯源", ["word"] = {"酥"}},
    ["bdvs"] = {["phrase"] = "抱枕", ["word"] = {"龅"}},
    ["uaka"] = {["phrase"] = "插卡", ["word"] = {"喳"}},
    ["vlei"] = {["phrase"] = "张继", ["word"] = {"障", "嶂"}},
    ["xnej"] = {["phrase"] = "先教", ["word"] = {"陷"}},
    ["bibl"] = {["phrase"] = "臂膀", ["word"] = {"痹"}},
    ["dkzi"] = {["phrase"] = "碟子", ["word"] = {"迭", "跌"}},
    ["efle"] = {["phrase"] = "静了", ["word"] = {"竞", "竟"}},
    ["gdmi"] = {["phrase"] = "高密", ["word"] = {"槔"}},
    ["qitj"] = {["phrase"] = "起跳", ["word"] = {"起", "圻"}},
    ["uude"] = {["phrase"] = "处得", ["word"] = {"刍"}},
    ["bibi"] = {["phrase"] = "比比", ["word"] = {"毕"}},
    ["kyke"] = {["phrase"] = "旷课", ["word"] = {"贶"}},
    ["ycqk"] = {["phrase"] = "殷切", ["word"] = {"狺"}},
    ["yuda"] = {["phrase"] = "愈大", ["word"] = {"鱼", "渔"}},
    ["wwqn"] = {["phrase"] = "为钱", ["word"] = {"猥"}},
    ["yttn"] = {["phrase"] = "盐田", ["word"] = {"堰"}},
    ["hhbu"] = {["phrase"] = "缓步", ["word"] = {"宦"}},
    ["hemr"] = {["phrase"] = "合谋", ["word"] = {"核", "阂"}},
    ["dotu"] = {["phrase"] = "多图", ["word"] = {"埵"}},
    ["fuuz"] = {["phrase"] = "夫差", ["word"] = {"蜉"}},
    ["soci"] = {["phrase"] = "所赐", ["word"] = {"莎"}},
    ["qiey"] = {["phrase"] = "起降", ["word"] = {"岐"}},
    ["ptpt"] = {["phrase"] = "盼盼", ["word"] = {"番"}},
    ["xidd"] = {["phrase"] = "铣刀", ["word"] = {"溪"}},
    ["yuxk"] = {["phrase"] = "淤血", ["word"] = {"誉"}},
    ["uudh"] = {["phrase"] = "初段", ["word"] = {"滁"}},
    ["eicl"] = {["phrase"] = "机舱", ["word"] = {"荠"}},
    ["pudi"] = {["phrase"] = "铺地", ["word"] = {"瀑"}},
    ["ytie"] = {["phrase"] = "衍射", ["word"] = {"砚"}},
    ["yuey"] = {["phrase"] = "欲将", ["word"] = {"屿", "隅", "嵎"}},
    ["itdo"] = {["phrase"] = "闪躲", ["word"] = {"潸"}},
    ["upmt"] = {["phrase"] = "盛满", ["word"] = {"柽"}},
    ["yctt"] = {["phrase"] = "银滩", ["word"] = {"堙"}},
    ["hudi"] = {["phrase"] = "湖底", ["word"] = {"户", "斛"}},
    ["ithx"] = {["phrase"] = "山花", ["word"] = {"扇", "煽"}},
    ["ipil"] = {["phrase"] = "升上", ["word"] = {"甥"}},
    ["btbw"] = {["phrase"] = "半杯", ["word"] = {"癍"}},
    ["itmc"] = {["phrase"] = "山民", ["word"] = {"栅"}},
    ["iirr"] = {["phrase"] = "食肉", ["word"] = {"似"}},
    ["iipf"] = {["phrase"] = "时评", ["word"] = {"失"}},
    ["lydm"] = {["phrase"] = "两栋", ["word"] = {"梁", "粱"}},
    ["endj"] = {["phrase"] = "减掉", ["word"] = {"渐", "溅"}},
    -- ["lqdt"] = {["phrase"] = "刘丹", ["word"] = {"溜"}},
    ["podd"] = {["phrase"] = "坡道", ["word"] = {"泼"}},
    ["uudf"] = {["phrase"] = "初定", ["word"] = {"雏"}},
    ["hmcb"] = {["phrase"] = "宏村", ["word"] = {"蕻", "薨"}},
    ["rsrr"] = {["phrase"] = "人肉", ["word"] = {"任", "仞"}},
    ["yiuy"] = {["phrase"] = "一床", ["word"] = {"役", "蚁"}},
    ["tmdl"] = {["phrase"] = "同党", ["word"] = {"潼"}},
    ["yfke"] = {["phrase"] = "迎客", ["word"] = {"郢"}},
    ["zibz"] = {["phrase"] = "自白", ["word"] = {"字", "孳"}},
    ["lirl"] = {["phrase"] = "礼让", ["word"] = {"俪", "俚"}},
    ["enve"] = {["phrase"] = "见者", ["word"] = {"舰", "笕"}},
    ["bagd"] = {["phrase"] = "拔高", ["word"] = {"魃"}},
    ["efvl"] = {["phrase"] = "警长", ["word"] = {"劲"}},
    ["nmdn"] = {["phrase"] = "弄点", ["word"] = {"农", "浓"}},
    ["qfif"] = {["phrase"] = "轻率", ["word"] = {"罄"}},
    ["xclr"] = {["phrase"] = "新楼", ["word"] = {"歆"}},
    ["ygka"] = {["phrase"] = "月卡", ["word"] = {"曰", "月"}},
    ["wugp"] = {["phrase"] = "五更", ["word"] = {"戊"}},
    ["dtdk"] = {["phrase"] = "单碟", ["word"] = {"澹"}},
    ["ilxy"] = {["phrase"] = "上香", ["word"] = {"裳"}},
    ["gvms"] = {["phrase"] = "柜门", ["word"] = {"桧"}},
    ["iuiy"] = {["phrase"] = "舒爽", ["word"] = {"叔", "属"}},
    ["ytdd"] = {["phrase"] = "烟道", ["word"] = {"淹", "奄"}},
    ["wuyl"] = {["phrase"] = "无恙", ["word"] = {"雾"}},
    ["ytmk"] = {["phrase"] = "湮灭", ["word"] = {"檐"}},
    ["uipj"] = {["phrase"] = "持票", ["word"] = {"褫"}},
    ["ejbw"] = {["phrase"] = "脚背", ["word"] = {"敫"}},
    ["pzdf"] = {["phrase"] = "排定", ["word"] = {"湃"}},
    ["xiym"] = {["phrase"] = "喜用", ["word"] = {"醯"}},
    ["viiy"] = {["phrase"] = "直爽", ["word"] = {"支"}},
    -- ["vipp"] = {["phrase"] = "志鹏", ["word"] = {"豸"}},
    ["ruce"] = {["phrase"] = "如厕", ["word"] = {"薷"}},
    ["lisd"] = {["phrase"] = "离骚", ["word"] = {"缡"}},
    ["viub"] = {["phrase"] = "之春", ["word"] = {"咫"}},
    ["sokr"] = {["phrase"] = "锁扣", ["word"] = {"唢"}},
    ["luhx"] = {["phrase"] = "芦花", ["word"] = {"虑"}},
    ["iikr"] = {["phrase"] = "适口", ["word"] = {"噬"}},
    ["euml"] = {["phrase"] = "巨蟒", ["word"] = {"榉"}},
    ["bkda"] = {["phrase"] = "别打", ["word"] = {"鳖"}},
    ["mwve"] = {["phrase"] = "没辙", ["word"] = {"郿"}},
    ["vizr"] = {["phrase"] = "直走", ["word"] = {"踬"}},
    ["doku"] = {["phrase"] = "多苦", ["word"] = {"咄"}},
    ["libl"] = {["phrase"] = "立邦", ["word"] = {"疬"}},
    ["ecrv"] = {["phrase"] = "金瑞", ["word"] = {"今"}},
    ["yruz"] = {["phrase"] = "邮差", ["word"] = {"蝣"}},
    ["fupj"] = {["phrase"] = "浮漂", ["word"] = {"凫"}},
    ["qkxn"] = {["phrase"] = "切线", ["word"] = {"慊"}},
    ["dmdd"] = {["phrase"] = "东道", ["word"] = {"冻"}},
    ["lmbi"] = {["phrase"] = "隆鼻", ["word"] = {"窿", "癃"}},
    ["btww"] = {["phrase"] = "班委", ["word"] = {"班", "斑"}},
    ["wuan"] = {["phrase"] = "武安", ["word"] = {"鹉"}},
    ["qfcm"] = {["phrase"] = "青葱", ["word"] = {"檠"}},
    ["hddr"] = {["phrase"] = "好斗", ["word"] = {"灏"}},
    ["lldl"] = {["phrase"] = "浪荡", ["word"] = {"浪"}},
    ["xnce"] = {["phrase"] = "献策", ["word"] = {"苋"}},
    ["yuhd"] = {["phrase"] = "愈好", ["word"] = {"燠"}},
    ["yrla"] = {["phrase"] = "又拉", ["word"] = {"由", "卣"}},
    ["xkdj"] = {["phrase"] = "卸掉", ["word"] = {"瀣"}},
    ["enmz"] = {["phrase"] = "贱卖", ["word"] = {"毽"}},
    ["xfci"] = {["phrase"] = "行刺", ["word"] = {"荥"}},
    ["fwfu"] = {["phrase"] = "肺腑", ["word"] = {"蜚"}},
    ["fuda"] = {["phrase"] = "福大", ["word"] = {"滏"}},
    ["lwyl"] = {["phrase"] = "耒阳", ["word"] = {"诔"}},
    ["fupi"] = {["phrase"] = "麸皮", ["word"] = {"阜"}},
    ["yrro"] = {["phrase"] = "有若", ["word"] = {"侑"}},
    ["livd"] = {["phrase"] = "利爪", ["word"] = {"篱"}},
    ["uuwt"] = {["phrase"] = "出完", ["word"] = {"畜"}},
    -- ["limw"] = {["phrase"] = "李梅", ["word"] = {"粝"}},
    ["isdp"] = {["phrase"] = "神灯", ["word"] = {"渗"}},
    ["idvo"] = {["phrase"] = "烧灼", ["word"] = {"筲", "艄"}},
    ["vhib"] = {["phrase"] = "转瞬", ["word"] = {"馔"}},
    ["bdbn"] = {["phrase"] = "褒贬", ["word"] = {"鸨"}},
    ["didm"] = {["phrase"] = "地洞", ["word"] = {"涤"}},
    ["yaey"] = {["phrase"] = "压降", ["word"] = {"岈"}},
    ["xige"] = {["phrase"] = "洗个", ["word"] = {"觋"}},
    ["gtmw"] = {["phrase"] = "甘美", ["word"] = {"橄"}},
    ["efvd"] = {["phrase"] = "京兆", ["word"] = {"刭"}},
    ["yhky"] = {["phrase"] = "原矿", ["word"] = {"圜"}},
    ["tlxm"] = {["phrase"] = "堂兄", ["word"] = {"棠"}},
    ["surm"] = {["phrase"] = "速溶", ["word"] = {"僳"}},
    ["enma"] = {["phrase"] = "见吗", ["word"] = {"检"}},
    ["yuek"] = {["phrase"] = "郁结", ["word"] = {"峪"}},
    ["lidm"] = {["phrase"] = "立冬", ["word"] = {"溧"}},
    ["kedm"] = {["phrase"] = "可动", ["word"] = {"溘"}},
    ["ycex"] = {["phrase"] = "印加", ["word"] = {"隐"}},
    ["mobd"] = {["phrase"] = "墨宝", ["word"] = {"寞", "瘼"}},
    ["libw"] = {["phrase"] = "立碑", ["word"] = {"疠"}},
    ["ulxk"] = {["phrase"] = "长些", ["word"] = {"惝"}},
    ["diid"] = {["phrase"] = "低烧", ["word"] = {"氐", "砥"}},
    -- ["wwkf"] = {["phrase"] = "为快", ["word"] = {"唯"}},
    ["fuhz"] = {["phrase"] = "福海", ["word"] = {"稃"}},
    ["yikb"] = {["phrase"] = "一捆", ["word"] = {"邑"}},
    ["uumw"] = {["phrase"] = "触媒", ["word"] = {"杵"}},
    ["ulxu"] = {["phrase"] = "长须", ["word"] = {"怅"}},
    ["egkr"] = {["phrase"] = "决口", ["word"] = {"噘"}},
    ["aiey"] = {["phrase"] = "爱将", ["word"] = {"叆"}},
    ["exly"] = {["phrase"] = "加量", ["word"] = {"袈"}},
    ["iimj"] = {["phrase"] = "十秒", ["word"] = {"柿"}},
    ["xgcb"] = {["phrase"] = "雪村", ["word"] = {"茓"}},
    ["sivv"] = {["phrase"] = "丝锥", ["word"] = {"巳"}},
    ["qian"] = {["phrase"] = "奇案", ["word"] = {"妻"}},
    ["pjdz"] = {["phrase"] = "飘带", ["word"] = {"殍"}},
    ["dmxk"] = {["phrase"] = "东邪", ["word"] = {"恫"}},
    ["qicb"] = {["phrase"] = "七寸", ["word"] = {"萁"}},
    ["ydxx"] = {["phrase"] = "咬下", ["word"] = {"爻"}},
    ["ttdi"] = {["phrase"] = "探底", ["word"] = {"潭"}},
    ["xjkz"] = {["phrase"] = "小开", ["word"] = {"哮"}},
    ["qipi"] = {["phrase"] = "漆皮", ["word"] = {"祇"}},
    -- ["bodb"] = {["phrase"] = "伯顿", ["word"] = {"泊"}},
    ["subi"] = {["phrase"] = "速比", ["word"] = {"窣"}},
    ["yfkf"] = {["phrase"] = "硬块", ["word"] = {"罂"}},
    -- ["uphw"] = {["phrase"] = "呈黑", ["word"] = {"程"}},
    -- ["likl"] = {["phrase"] = "利康", ["word"] = {"哩", "呖", "喱"}},
    ["qiej"] = {["phrase"] = "起脚", ["word"] = {"岂", "屺"}},
    -- ["mogm"] = {["phrase"] = "魔宫", ["word"] = {"靺", "麽"}},
    ["qubf"] = {["phrase"] = "曲柄", ["word"] = {"癯"}},
    ["tudd"] = {["phrase"] = "屠刀", ["word"] = {"兔"}},
    ["nker"] = {["phrase"] = "聂耳", ["word"] = {"颞"}},
    ["xupn"] = {["phrase"] = "续篇", ["word"] = {"媭"}},
    ["dkym"] = {["phrase"] = "蝶泳", ["word"] = {"谍"}},
    -- ["iiyc"] = {["phrase"] = "石印", ["word"] = {"诗"}},
    ["yixb"] = {["phrase"] = "依循", ["word"] = {"翼", "悒"}},
    ["lkdd"] = {["phrase"] = "列岛", ["word"] = {"列", "冽", "洌"}},
    ["gmgr"] = {["phrase"] = "公狗", ["word"] = {"贡"}},
    ["eise"] = {["phrase"] = "基色", ["word"] = {"缉"}},
    ["enlt"] = {["phrase"] = "剑兰", ["word"] = {"坚"}},
    ["tddj"] = {["phrase"] = "逃掉", ["word"] = {"滔"}},
    ["duvs"] = {["phrase"] = "毒针", ["word"] = {"厾"}},
    ["bidl"] = {["phrase"] = "必当", ["word"] = {"濞"}},
    ["yauu"] = {["phrase"] = "压出", ["word"] = {"衙"}},
    ["yikv"] = {["phrase"] = "一窥", ["word"] = {"呓"}},
    ["yrye"] = {["phrase"] = "油液", ["word"] = {"邮"}},
    ["endo"] = {["phrase"] = "见多", ["word"] = {"涧"}},
    -- ["qndn"] = {["phrase"] = "前店", ["word"] = {"牵", "鹐"}},
    ["bivl"] = {["phrase"] = "笔账", ["word"] = {"箅"}},
    ["dmdn"] = {["phrase"] = "动点", ["word"] = {"鸫"}},
    ["qizd"] = {["phrase"] = "起早", ["word"] = {"蹊"}},
    ["lqit"] = {["phrase"] = "刘禅", ["word"] = {"馏"}},
    ["yhta"] = {["phrase"] = "愿他", ["word"] = {"垣"}},
    ["iddo"] = {["phrase"] = "稍多", ["word"] = {"潲"}},
    ["yauy"] = {["phrase"] = "牙床", ["word"] = {"蚜"}},
    ["mpum"] = {["phrase"] = "猛冲", ["word"] = {"蜢"}},
    ["eidk"] = {["phrase"] = "急跌", ["word"] = {"奇"}},
    ["pjxx"] = {["phrase"] = "飘下", ["word"] = {"票", "飘"}},
    ["diyd"] = {["phrase"] = "低腰", ["word"] = {"诋"}},
    ["mumd"] = {["phrase"] = "母猫", ["word"] = {"模"}},
    ["yupd"] = {["phrase"] = "浴袍", ["word"] = {"禹"}},
    ["mkvi"] = {["phrase"] = "灭之", ["word"] = {"篾"}},
    ["qiub"] = {["phrase"] = "蕲春", ["word"] = {"蜞"}},
    ["eisr"] = {["phrase"] = "几艘", ["word"] = {"绩"}},
    ["liil"] = {["phrase"] = "李尚", ["word"] = {"砾"}},
    ["vodf"] = {["phrase"] = "酌定", ["word"] = {"濯"}},
    ["yhee"] = {["phrase"] = "员额", ["word"] = {"元", "院"}},
    ["htge"] = {["phrase"] = "焊割", ["word"] = {"邗", "邯"}},
    ["drbd"] = {["phrase"] = "豆包", ["word"] = {"窦"}},
    -- ["ejml"] = {["phrase"] = "较忙", ["word"] = {"骄"}},
    ["iivr"] = {["phrase"] = "十周", ["word"] = {"筮"}},
    ["yiky"] = {["phrase"] = "一筐", ["word"] = {"匜", "咦", "咿"}},
    ["iidb"] = {["phrase"] = "十吨", ["word"] = {"奭"}},
    ["vifr"] = {["phrase"] = "知否", ["word"] = {"贽"}},
    ["wwyc"] = {["phrase"] = "尾音", ["word"] = {"霨"}},
    ["eisd"] = {["phrase"] = "祭扫", ["word"] = {"罽"}},
    -- ["liud"] = {["phrase"] = "历朝", ["word"] = {"蜊"}},
    -- ["isdv"] = {["phrase"] = "神对", ["word"] = {"沈"}},
    ["ytur"] = {["phrase"] = "眼瞅", ["word"] = {"颜", "赝"}},
    -- ["hrri"] = {["phrase"] = "后日", ["word"] = {"侯", "候"}},
    -- ["lwyc"] = {["phrase"] = "雷音", ["word"] = {"酹"}},
    -- ["qicl"] = {["phrase"] = "气藏", ["word"] = {"荠"}},
    -- ["eibo"] = {["phrase"] = "极薄", ["word"] = {"瘠"}},
    -- ["ttbf"] = {["phrase"] = "探病", ["word"] = {"瘫"}},
    -- ["hxri"] = {["phrase"] = "华日", ["word"] = {"华"}},
    -- ["xkio"] = {["phrase"] = "邪说", ["word"] = {"屑"}},
    -- ["bovy"] = {["phrase"] = "波状", ["word"] = {"簸"}},
    -- ["hudh"] = {["phrase"] = "护短", ["word"] = {"沪", "滹"}},
    -- ["yuua"] = {["phrase"] = "鱼叉", ["word"] = {"蜮"}},
    ["lren"] = {["phrase"] = "露肩", ["word"] = {"嵝"}},
    -- ["vumo"] = {["phrase"] = "铸模", ["word"] = {"槠"}},
    ["eeyt"] = {["phrase"] = "恶言", ["word"] = {"垩"}},
    -- ["mibj"] = {["phrase"] = "咪表", ["word"] = {"幂"}},
    -- ["iult"] = {["phrase"] = "熟烂", ["word"] = {"墅"}},
    -- ["eqfa"] = {["phrase"] = "旧法", ["word"] = {"韭"}},
    -- ["qiao"] = {["phrase"] = "奇奥", ["word"] = {"鳍"}},
    ["upmu"] = {["phrase"] = "瞠目", ["word"] = {"枨"}},
    -- ["moci"] = {["phrase"] = "末次", ["word"] = {"摹", "蘑"}},
    -- ["qitt"] = {["phrase"] = "棋坛", ["word"] = {"畦"}},
    -- ["iico"] = {["phrase"] = "失措", ["word"] = {"蓍"}},
    ["lqdj"] = {["phrase"] = "溜掉", ["word"] = {"鎏"}},
    -- ["itmp"] = {["phrase"] = "山盟", ["word"] = {"杉"}},
    ["ycbo"] = {["phrase"] = "音波", ["word"] = {"窨"}},
    -- ["fuut"] = {["phrase"] = "妇产", ["word"] = {"辐", "蝠"}},
    ["yrpf"] = {["phrase"] = "油瓶", ["word"] = {"牖"}},
    -- ["movb"] = {["phrase"] = "摸准", ["word"] = {"貊"}},
    -- ["wwao"] = {["phrase"] = "维奥", ["word"] = {"鲔"}},
    -- ["ximw"] = {["phrase"] = "洗煤", ["word"] = {"檄"}},
    -- ["xnue"] = {["phrase"] = "闲扯", ["word"] = {"蚬"}},
    -- ["vimt"] = {["phrase"] = "枝蔓", ["word"] = {"桎"}},
    -- ["bwlo"] = {["phrase"] = "贝罗", ["word"] = {"背"}},
    -- ["xxqj"] = {["phrase"] = "下桥", ["word"] = {"狭", "狎"}},
    -- ["eika"] = {["phrase"] = "集卡", ["word"] = {"戢"}},
    -- ["viut"] = {["phrase"] = "只产", ["word"] = {"轾", "蛭"}},
    -- ["iumd"] = {["phrase"] = "梳毛", ["word"] = {"术"}},
    -- ["eqbj"] = {["phrase"] = "酒标", ["word"] = {"究", "疚"}},
    -- ["luhl"] = {["phrase"] = "陆航", ["word"] = {"虏"}},
    -- ["kvir"] = {["phrase"] = "魁首", ["word"] = {"馈"}},
    -- ["kfrs"] = {["phrase"] = "快人", ["word"] = {"会", "侩"}},
    -- ["zdhm"] = {["phrase"] = "枣红", ["word"] = {"燥"}},
    -- ["lugh"] = {["phrase"] = "炉管", ["word"] = {"庐"}},
    -- ["nkky"] = {["phrase"] = "镍矿", ["word"] = {"嗫"}},
    ["fupt"] = {["phrase"] = "复盘", ["word"] = {"福"}},
    -- ["xygy"] = {["phrase"] = "向光", ["word"] = {"庠"}},
    ["ecya"] = {["phrase"] = "金牙", ["word"] = {"谨"}},
    -- ["lfmw"] = {["phrase"] = "菱镁", ["word"] = {"棱"}},
    -- ["lirm"] = {["phrase"] = "丽蓉", ["word"] = {"傈"}},
    -- ["xjdo"] = {["phrase"] = "小朵", ["word"] = {"消", "淆"}},
    -- ["ecll"] = {["phrase"] = "金浪", ["word"] = {"巾"}},
    ["lnwz"] = {["phrase"] = "帘外", ["word"] = {"琏"}},
    ["xymn"] = {["phrase"] = "相面", ["word"] = {"橡"}},
    ["bihb"] = {["phrase"] = "逼婚", ["word"] = {"秘", "秕"}},
    ["gunn"] = {["phrase"] = "顾念", ["word"] = {"鹄"}},
    -- ["wudk"] = {["phrase"] = "舞蝶", ["word"] = {"污", "浯"}},
    ["yiix"] = {["phrase"] = "一刷", ["word"] = {"懿"}},
    ["xfxb"] = {["phrase"] = "刑讯", ["word"] = {"兴"}},
    -- ["mdce"] = {["phrase"] = "茅厕", ["word"] = {"茆"}},
    -- ["licl"] = {["phrase"] = "李沧", ["word"] = {"荔", "苈", "莅"}},
    -- ["diqh"] = {["phrase"] = "地权", ["word"] = {"狄"}},
    -- ["duke"] = {["phrase"] = "赌客", ["word"] = {"嘟"}},
    -- ["vvmf"] = {["phrase"] = "追命", ["word"] = {"椎", "骓"}},
    -- ["quex"] = {["phrase"] = "去甲", ["word"] = {"岖"}},
    -- ["migx"] = {["phrase"] = "蜜瓜", ["word"] = {"弥", "縻"}},
    -- ["vucv"] = {["phrase"] = "珠翠", ["word"] = {"茱"}},
    -- ["lmli"] = {["phrase"] = "龙里", ["word"] = {"砻"}},
    -- ["zevr"] = {["phrase"] = "泽州", ["word"] = {"箦"}},
    -- ["eygu"] = {["phrase"] = "讲古", ["word"] = {"强"}},
    -- ["ekbl"] = {["phrase"] = "接棒", ["word"] = {"疥"}},
    -- ["tndp"] = {["phrase"] = "天灯", ["word"] = {"殄"}},
    -- ["pitj"] = {["phrase"] = "皮条", ["word"] = {"圮"}},
    -- ["xkdm"] = {["phrase"] = "谢东", ["word"] = {"渫"}},
    -- ["yiml"] = {["phrase"] = "一忙", ["word"] = {"驿"}},
    ["vuky"] = {["phrase"] = "竹筐", ["word"] = {"嘱"}},
    -- ["yuiy"] = {["phrase"] = "玉霜", ["word"] = {"饫"}},
    -- ["hpuu"] = {["phrase"] = "哼出", ["word"] = {"行", "衡"}},
    -- ["vumd"] = {["phrase"] = "猪毛", ["word"] = {"术"}},
    -- ["svzi"] = {["phrase"] = "穗子", ["word"] = {"遂", "邃"}},
    -- ["dnir"] = {["phrase"] = "点收", ["word"] = {"颠"}},
    -- ["xiih"] = {["phrase"] = "洗涮", ["word"] = {"熹"}},
    -- ["iudv"] = {["phrase"] = "属对", ["word"] = {"殊"}},
    -- ["zimz"] = {["phrase"] = "自卖", ["word"] = {"籽"}},
    -- ["bdrt"] = {["phrase"] = "爆燃", ["word"] = {"堡"}},
    -- ["yhke"] = {["phrase"] = "远客", ["word"] = {"园"}},
    -- ["lqmt"] = {["phrase"] = "流满", ["word"] = {"榴", "骝"}},
    -- ["yikx"] = {["phrase"] = "一跨", ["word"] = {"噫", "翳"}},
    ["mpzl"] = {["phrase"] = "蒙藏", ["word"] = {"勐"}},
    -- ["ebye"] = {["phrase"] = "菌液", ["word"] = {"郡"}},
    ["eivo"] = {["phrase"] = "几桌", ["word"] = {"籍"}},
    -- ["zidk"] = {["phrase"] = "紫蝶", ["word"] = {"咨"}},
    -- ["eini"] = {["phrase"] = "基尼", ["word"] = {"嫉"}},
    -- ["efcd"] = {["phrase"] = "劲草", ["word"] = {"荆"}},
    -- ["aiix"] = {["phrase"] = "爱耍", ["word"] = {"砹"}},
    -- ["eihb"] = {["phrase"] = "击昏", ["word"] = {"积"}},
    ["yelp"] = {["phrase"] = "液冷", ["word"] = {"曳"}},
    -- ["virt"] = {["phrase"] = "织染", ["word"] = {"侄"}},
    -- ["yudk"] = {["phrase"] = "雨蝶", ["word"] = {"浴"}},
    -- ["bicz"] = {["phrase"] = "比才", ["word"] = {"荸"}},
    -- ["liwl"] = {["phrase"] = "力王", ["word"] = {"理"}},
    -- ["qjgo"] = {["phrase"] = "敲过", ["word"] = {"鞘"}},
    -- ["hddi"] = {["phrase"] = "好迪", ["word"] = {"濠"}},
    -- ["lfrr"] = {["phrase"] = "灵肉", ["word"] = {"领"}},
    ["dbzo"] = {["phrase"] = "蹲坐", ["word"] = {"遁"}},
    -- ["qipj"] = {["phrase"] = "期票", ["word"] = {"祈"}},
    -- ["exrt"] = {["phrase"] = "戛然", ["word"] = {"佳"}},
    ["tzsh"] = {["phrase"] = "太酸", ["word"] = {"炱"}},
    -- ["tlre"] = {["phrase"] = "烫热", ["word"] = {"傥"}},
    -- ["uumc"] = {["phrase"] = "初民", ["word"] = {"橱"}},
    ["hpwu"] = {["phrase"] = "蘅芜", ["word"] = {"珩"}},
    -- ["yuma"] = {["phrase"] = "玉马", ["word"] = {"阈"}},
    -- ["dfkr"] = {["phrase"] = "钉扣", ["word"] = {"啶"}},
    -- ["fubt"] = {["phrase"] = "腹板", ["word"] = {"富", "匐"}},
    -- ["idci"] = {["phrase"] = "烧瓷", ["word"] = {"芍"}},
    -- ["fugr"] = {["phrase"] = "扶沟", ["word"] = {"腐"}},
    -- ["wwhw"] = {["phrase"] = "微黑", ["word"] = {"炜"}},
    -- ["tfuz"] = {["phrase"] = "听差", ["word"] = {"蜓"}},
    -- ["dter"] = {["phrase"] = "蛋儿", ["word"] = {"聃"}},
    -- ["yidj"] = {["phrase"] = "移调", ["word"] = {"沂"}},
    -- ["tmdk"] = {["phrase"] = "通牒", ["word"] = {"洞"}},
    -- ["tzct"] = {["phrase"] = "太惨", ["word"] = {"薹"}},
    -- ["wurm"] = {["phrase"] = "无容", ["word"] = {"侮"}},
    ["qice"] = {["phrase"] = "凄恻", ["word"] = {"葺"}},
    ["tibn"] = {["phrase"] = "题匾", ["word"] = {"鹈"}},
    -- ["yhkr"] = {["phrase"] = "源口", ["word"] = {"员", "圆"}},
    -- ["ygml"] = {["phrase"] = "越忙", ["word"] = {"栎"}},
    -- ["viix"] = {["phrase"] = "制刷", ["word"] = {"志"}},
    -- ["ytdt"] = {["phrase"] = "燕丹", ["word"] = {"湮"}},
    -- ["huhb"] = {["phrase"] = "胡混", ["word"] = {"扈"}},
    -- ["wukt"] = {["phrase"] = "勿看", ["word"] = {"吴"}},
    -- ["xnnm"] = {["phrase"] = "鲜浓", ["word"] = {"娴"}},
    -- ["viyb"] = {["phrase"] = "织云", ["word"] = {"识"}},
    -- ["hvdk"] = {["phrase"] = "回跌", ["word"] = {"汇", "洄"}},
    -- ["yrbo"] = {["phrase"] = "又播", ["word"] = {"宥"}},
    -- ["vidj"] = {["phrase"] = "纸雕", ["word"] = {"滞"}},
    -- ["vtlk"] = {["phrase"] = "战列", ["word"] = {"占", "站"}},
    -- ["exlm"] = {["phrase"] = "甲龙", ["word"] = {"驾", "架"}},
    -- ["xcxb"] = {["phrase"] = "新训", ["word"] = {"衅"}},
    -- ["mjce"] = {["phrase"] = "妙策", ["word"] = {"藐"}},
    ["tucd"] = {["phrase"] = "吐槽", ["word"] = {"菟"}},
    -- ["bzrb"] = {["phrase"] = "白润", ["word"] = {"伯", "佰"}},
    ["ziky"] = {["phrase"] = "自况", ["word"] = {"吱", "嗞"}},
    -- ["cvxi"] = {["phrase"] = "翠喜", ["word"] = {"悴", "翠"}},
    -- ["htxx"] = {["phrase"] = "颔下", ["word"] = {"憾"}},
    -- ["ulxm"] = {["phrase"] = "敞胸", ["word"] = {"氅"}},
    -- ["gvmj"] = {["phrase"] = "桂庙", ["word"] = {"柜"}},
    -- ["yubn"] = {["phrase"] = "预编", ["word"] = {"鹆"}},
    -- ["subt"] = {["phrase"] = "速办", ["word"] = {"塑"}},
    -- ["fupd"] = {["phrase"] = "副炮", ["word"] = {"祓"}},
    -- ["bdhs"] = {["phrase"] = "抱恨", ["word"] = {"炮"}},
    -- ["umvl"] = {["phrase"] = "重张", ["word"] = {"艟"}},
    -- ["eila"] = {["phrase"] = "急拉", ["word"] = {"亟"}},
    -- ["iidr"] = {["phrase"] = "市斗", ["word"] = {"湜"}},
    -- ["yfci"] = {["phrase"] = "英雌", ["word"] = {"荥"}},
    -- ["xucb"] = {["phrase"] = "蓄存", ["word"] = {"蓿"}},
    -- ["ihma"] = {["phrase"] = "拴马", ["word"] = {"闩"}},
    -- ["ludb"] = {["phrase"] = "鲁钝", ["word"] = {"漉"}},
    -- ["xuwt"] = {["phrase"] = "续完", ["word"] = {"畜"}},
    -- ["yudr"] = {["phrase"] = "玉斗", ["word"] = {"滪"}},
    -- ["uiiw"] = {["phrase"] = "吃谁", ["word"] = {"敕"}},
    -- ["iydl"] = {["phrase"] = "双档", ["word"] = {"泷"}},
    -- ["itna"] = {["phrase"] = "姗娜", ["word"] = {"嬗"}},
    -- ["yccd"] = {["phrase"] = "阴曹", ["word"] = {"茵"}},
    -- ["ylhy"] = {["phrase"] = "阳黄", ["word"] = {"秧", "烊"}},
    ["vstp"] = {["phrase"] = "真疼", ["word"] = {"畛"}},
    -- ["xbci"] = {["phrase"] = "训词", ["word"] = {"蕈"}},
    -- ["lumi"] = {["phrase"] = "禄米", ["word"] = {"栌"}},
    -- ["ymwl"] = {["phrase"] = "勇往", ["word"] = {"饔"}},
    -- ["livl"] = {["phrase"] = "里长", ["word"] = {"笠"}},
    -- ["idho"] = {["phrase"] = "烧火", ["word"] = {"稍"}},
    -- ["ftht"] = {["phrase"] = "泛函", ["word"] = {"燔"}},
    -- ["humr"] = {["phrase"] = "胡某", ["word"] = {"核"}},
    -- ["pibi"] = {["phrase"] = "疲敝", ["word"] = {"癖"}},
    -- ["nnfu"] = {["phrase"] = "黏附", ["word"] = {"撵", "辇"}},
    -- ["ipio"] = {["phrase"] = "声说", ["word"] = {"省"}},
    -- ["mike"] = {["phrase"] = "米克", ["word"] = {"嘧"}},
    -- ["ztwo"] = {["phrase"] = "赞我", ["word"] = {"昝"}},
    -- ["gxqn"] = {["phrase"] = "挂牵", ["word"] = {"鸹"}},
    -- ["monm"] = {["phrase"] = "摸弄", ["word"] = {"嬷"}},
    -- ["gudo"] = {["phrase"] = "骨朵", ["word"] = {"汩"}},
    -- ["yurt"] = {["phrase"] = "郁然", ["word"] = {"俣"}},
    -- ["lcwl"] = {["phrase"] = "林网", ["word"] = {"璘"}},
    -- ["ierr"] = {["phrase"] = "蛇肉", ["word"] = {"歙"}},
    -- ["qnum"] = {["phrase"] = "谦冲", ["word"] = {"椠"}},
    -- ["fucl"] = {["phrase"] = "伏藏", ["word"] = {"芾"}},
    -- ["eekr"] = {["phrase"] = "恶口", ["word"] = {"颚"}},
    -- ["mwnm"] = {["phrase"] = "美浓", ["word"] = {"媒"}},
    -- ["eeke"] = {["phrase"] = "恶客", ["word"] = {"鄂"}},
    -- ["iuso"] = {["phrase"] = "数所", ["word"] = {"署"}},
    -- ["vldi"] = {["phrase"] = "章帝", ["word"] = {"漳"}},
    -- ["htgr"] = {["phrase"] = "函购", ["word"] = {"顸"}},
    -- ["xkyb"] = {["phrase"] = "叶韵", ["word"] = {"谐"}},
    -- ["xfke"] = {["phrase"] = "刑克", ["word"] = {"邢"}},
    -- ["hvxu"] = {["phrase"] = "会须", ["word"] = {"辉", "翚"}},
    -- ["isnn"] = {["phrase"] = "深念", ["word"] = {"娠"}},
    -- ["lfes"] = {["phrase"] = "灵恩", ["word"] = {"岭", "聆"}},
    -- ["kvkr"] = {["phrase"] = "溃口", ["word"] = {"匮"}},
    -- ["dirm"] = {["phrase"] = "第戎", ["word"] = {"籴"}},
    -- ["sadi"] = {["phrase"] = "萨蒂", ["word"] = {"挲"}},
    -- ["ytmj"] = {["phrase"] = "烟苗", ["word"] = {"阎"}},
    -- ["eiiy"] = {["phrase"] = "极爽", ["word"] = {"屐"}},
    -- ["quhw"] = {["phrase"] = "黢黑", ["word"] = {"黢"}},
    -- ["qnhw"] = {["phrase"] = "浅黑", ["word"] = {"虔"}},
    -- ["lizl"] = {["phrase"] = "礼葬", ["word"] = {"逦", "跞"}},
    -- ["czpp"] = {["phrase"] = "彩棚", ["word"] = {"彩"}},
    -- ["qndj"] = {["phrase"] = "迁调", ["word"] = {"浅"}},
    -- ["qhbw"] = {["phrase"] = "圈杯", ["word"] = {"痊"}},
    -- ["tzse"] = {["phrase"] = "泰瑟", ["word"] = {"邰"}},
    -- ["siks"] = {["phrase"] = "死啃", ["word"] = {"咝"}},
    -- ["qjgl"] = {["phrase"] = "撬杠", ["word"] = {"鞒"}},
    -- ["divy"] = {["phrase"] = "滴状", ["word"] = {"笛"}},
    -- ["guiy"] = {["phrase"] = "孤孀", ["word"] = {"鼓", "毂", "榖"}},
    -- ["viky"] = {["phrase"] = "纸框", ["word"] = {"吱"}},
    -- ["uskb"] = {["phrase"] = "陈坤", ["word"] = {"嗔"}},
    -- ["luuy"] = {["phrase"] = "炉床", ["word"] = {"律"}},
    -- ["xnye"] = {["phrase"] = "涎液", ["word"] = {"酰"}},
    -- ["kdhf"] = {["phrase"] = "考坏", ["word"] = {"㸆"}},
    -- ["ytmd"] = {["phrase"] = "颜貌", ["word"] = {"阉", "阏"}},
    -- ["wodt"] = {["phrase"] = "渥丹", ["word"] = {"渥"}},
    -- ["mndl"] = {["phrase"] = "面档", ["word"] = {"勉"}},
    -- ["euqq"] = {["phrase"] = "菊秋", ["word"] = {"狙"}},
    -- ["bivb"] = {["phrase"] = "鼻准", ["word"] = {"篦"}},
    -- ["ttix"] = {["phrase"] = "炭刷", ["word"] = {"忐"}},
    -- ["vaia"] = {["phrase"] = "扎煞", ["word"] = {"馇"}},
    -- ["xuso"] = {["phrase"] = "须索", ["word"] = {"绪"}},
    -- ["guio"] = {["phrase"] = "告朔", ["word"] = {"瞽"}},
    -- ["boil"] = {["phrase"] = "卜商", ["word"] = {"勃"}},
    -- ["eqmj"] = {["phrase"] = "九秒", ["word"] = {"柩", "桕"}},
    -- ["hodr"] = {["phrase"] = "火斗", ["word"] = {"火"}},
    -- ["xkmc"] = {["phrase"] = "协民", ["word"] = {"械", "榭"}},
    -- ["eenk"] = {["phrase"] = "恶孽", ["word"] = {"婀"}},
    -- ["fudk"] = {["phrase"] = "复迭", ["word"] = {"涪"}},
    -- ["islo"] = {["phrase"] = "沈落", ["word"] = {"肾"}},
    -- ["siva"] = {["phrase"] = "四扎", ["word"] = {"丝"}},
    -- ["mocm"] = {["phrase"] = "默从", ["word"] = {"茉", "蓦"}},
    -- ["fscm"] = {["phrase"] = "分葱", ["word"] = {"棻"}},
    -- ["bidm"] = {["phrase"] = "壁洞", ["word"] = {"滗"}},
    -- ["zidr"] = {["phrase"] = "子都", ["word"] = {"资", "渍"}},
    -- ["fusd"] = {["phrase"] = "拂扫", ["word"] = {"绂"}},
    -- ["lodl"] = {["phrase"] = "洛党", ["word"] = {"泺"}},
    -- ["iedo"] = {["phrase"] = "舍堕", ["word"] = {"奢"}},
    -- ["fuba"] = {["phrase"] = "副把", ["word"] = {"釜"}},
    -- ["gtyg"] = {["phrase"] = "干哕", ["word"] = {"酐"}},
    -- ["luln"] = {["phrase"] = "芦帘", ["word"] = {"鸬"}},
    -- ["mwmo"] = {["phrase"] = "煤末", ["word"] = {"楣"}},
    -- ["tokd"] = {["phrase"] = "托靠", ["word"] = {"鼍"}},
    -- ["rmbj"] = {["phrase"] = "容表", ["word"] = {"冗"}},
    -- ["vurv"] = {["phrase"] = "烛蕊", ["word"] = {"住", "侏"}},
    -- ["djkd"] = {["phrase"] = "吊拷", ["word"] = {"叼"}},
    -- ["hvko"] = {["phrase"] = "恢廓", ["word"] = {"贿"}},
    -- ["xqkm"] = {["phrase"] = "袖孔", ["word"] = {"咻"}},
    -- ["pish"] = {["phrase"] = "砒酸", ["word"] = {"罴"}},
    -- ["qidl"] = {["phrase"] = "戚党", ["word"] = {"泣"}},
    -- ["xipd"] = {["phrase"] = "吸跑", ["word"] = {"夕", "奚", "禊"}},
    -- ["ghbc"] = {["phrase"] = "馆宾", ["word"] = {"冠"}},
    -- ["ybcm"] = {["phrase"] = "允从", ["word"] = {"蕴"}},
    -- ["irbk"] = {["phrase"] = "受瘪", ["word"] = {"兽"}},
    -- ["purt"] = {["phrase"] = "仆然", ["word"] = {"堡"}},
    -- ["envo"] = {["phrase"] = "简擢", ["word"] = {"简"}},
    -- ["tfcz"] = {["phrase"] = "亭彩", ["word"] = {"莛"}},
    ["iipt"] = {["phrase"] = "实盘", ["word"] = {"矢"}},
    -- ["xbdi"] = {["phrase"] = "训迪", ["word"] = {"汛"}},
    -- ["humi"] = {["phrase"] = "忽米", ["word"] = {"槲"}},
    -- ["irbc"] = {["phrase"] = "寿斌", ["word"] = {"守"}},
    -- ["nkzm"] = {["phrase"] = "蹑踪", ["word"] = {"臬"}},
    -- ["lumo"] = {["phrase"] = "戮没", ["word"] = {"橹", "氇"}},
    -- ["hvdr"] = {["phrase"] = "灰豆", ["word"] = {"溃"}},
    -- ["efco"] = {["phrase"] = "惊错", ["word"] = {"菁"}},
    -- ["iddk"] = {["phrase"] = "少迭", ["word"] = {"召"}},
    -- ["ytdk"] = {["phrase"] = "眼蝶", ["word"] = {"沿"}},
    -- ["ytdb"] = {["phrase"] = "烟墩", ["word"] = {"演", "滟"}},
    -- ["ftmf"] = {["phrase"] = "范明", ["word"] = {"梵"}},
    -- ["aofu"] = {["phrase"] = "熬稃", ["word"] = {"螯"}},
    -- ["yuzd"] = {["phrase"] = "舆皂", ["word"] = {"逾"}},
    -- ["guum"] = {["phrase"] = "古虫", ["word"] = {"蛊"}},
    -- ["xukl"] = {["phrase"] = "徐康", ["word"] = {"勖"}},
    -- ["iltk"] = {["phrase"] = "上贴", ["word"] = {"垧", "墒"}},
    -- ["dtkh"] = {["phrase"] = "丹款", ["word"] = {"啖", "赕"}},
    -- ["tamz"] = {["phrase"] = "他买", ["word"] = {"闼"}},
    -- ["fsmd"] = {["phrase"] = "分茅", ["word"] = {"粉", "棼"}},
    -- ["qubn"] = {["phrase"] = "取便", ["word"] = {"鸲"}},
    -- ["herm"] = {["phrase"] = "和戎", ["word"] = {"盒"}},
    -- ["tltk"] = {["phrase"] = "堂帖", ["word"] = {"塘", "趟"}},
    -- ["dava"] = {["phrase"] = "大札", ["word"] = {"笪"}},
    -- ["ytnh"] = {["phrase"] = "妍暖", ["word"] = {"燕", "嫣"}},
    -- ["ghdk"] = {["phrase"] = "官牒", ["word"] = {"涫"}},
    -- ["hhda"] = {["phrase"] = "宦达", ["word"] = {"洹"}},
    -- ["xbuo"] = {["phrase"] = "巡绰", ["word"] = {"循", "徇"}},
    -- ["fukf"] = {["phrase"] = "府快", ["word"] = {"呋"}},
    -- ["uupo"] = {["phrase"] = "怵迫", ["word"] = {"褚"}},
    -- ["ekdk"] = {["phrase"] = "戒牒", ["word"] = {"洁"}},
    -- ["hbdi"] = {["phrase"] = "昏第", ["word"] = {"溷"}},
    -- ["kydu"] = {["phrase"] = "旷度", ["word"] = {"夼"}},
    -- ["tisp"] = {["phrase"] = "替僧", ["word"] = {"绨"}},
    -- ["yriy"] = {["phrase"] = "有双", ["word"] = {"友"}},
    -- ["munt"] = {["phrase"] = "木难", ["word"] = {"牡"}},
    -- ["qidb"] = {["phrase"] = "栖遁", ["word"] = {"淇"}},
    -- ["uvmz"] = {["phrase"] = "椎埋", ["word"] = {"槌"}},
    -- ["yauv"] = {["phrase"] = "牙槌", ["word"] = {"轧"}},
    -- ["huho"] = {["phrase"] = "狐惑", ["word"] = {"煳"}},
    -- ["licd"] = {["phrase"] = "立草", ["word"] = {"莉", "蓠"}},
    -- ["fsrr"] = {["phrase"] = "纷糅", ["word"] = {"偾"}},
    -- ["sodi"] = {["phrase"] = "缩地", ["word"] = {"挲"}},
    -- ["utdz"] = {["phrase"] = "缠带", ["word"] = {"潺"}},
    -- ["fwdb"] = {["phrase"] = "肥遁", ["word"] = {"淝"}},
    -- ["pibk"] = {["phrase"] = "脾憋", ["word"] = {"否", "痞"}},
    -- ["hydb"] = {["phrase"] = "荒顿", ["word"] = {"潢"}},
    -- ["xuky"] = {["phrase"] = "虚诳", ["word"] = {"吁", "嘘"}},
    -- ["tbit"] = {["phrase"] = "豚栅", ["word"] = {"饨"}},
    -- ["pubf"] = {["phrase"] = "铺兵", ["word"] = {"匍"}},
    -- ["ycce"] = {["phrase"] = "隐恻", ["word"] = {"茚"}},
    -- ["lfye"] = {["phrase"] = "灵液", ["word"] = {"酃"}},
    -- ["euxb"] = {["phrase"] = "鞫讯", ["word"] = {"惧"}},
    -- ["aofl"] = {["phrase"] = "骜放", ["word"] = {"拗"}},
    -- ["yuto"] = {["phrase"] = "鹬鸵", ["word"] = {"堉"}},
    -- ["yiro"] = {["phrase"] = "一若", ["word"] = {"佾"}},
    -- ["cmcr"] = {["phrase"] = "丛凑", ["word"] = {"苁"}},
    -- ["vmrv"] = {["phrase"] = "中瑞", ["word"] = {"仲"}},
    -- ["fpee"] = {["phrase"] = "丰额", ["word"] = {"酆"}},
    -- ["wudj"] = {["phrase"] = "乌雕", ["word"] = {"鋈"}},
    -- ["yivv"] = {["phrase"] = "仪缀", ["word"] = {"乙", "已"}},
    -- ["fumz"] = {["phrase"] = "伏埋", ["word"] = {"桴"}},
    -- ["xqdo"] = {["phrase"] = "休惰", ["word"] = {"滫"}},
    -- ["yusl"] = {["phrase"] = "余丧", ["word"] = {"予"}},
    -- ["yurd"] = {["phrase"] = "余饶", ["word"] = {"俞"}},
    -- ["nfdd"] = {["phrase"] = "佞道", ["word"] = {"泞"}},
    -- ["qcdh"] = {["phrase"] = "侵短", ["word"] = {"溱"}},
    -- ["blmf"] = {["phrase"] = "傍明", ["word"] = {"榜"}},
    -- ["bcdr"] = {["phrase"] = "傧豆", ["word"] = {"濒"}},
    -- ["uuzo"] = {["phrase"] = "储佐", ["word"] = {"躇"}},
    -- ["dnlb"] = {["phrase"] = "典论", ["word"] = {"典"}},
    -- ["yluy"] = {["phrase"] = "养疮", ["word"] = {"徉", "蛘"}},
    -- ["engz"] = {["phrase"] = "兼该", ["word"] = {"鞬", "鞯"}},
    -- ["xkrb"] = {["phrase"] = "写润", ["word"] = {"偕"}},
    -- ["xfkd"] = {["phrase"] = "刑拷", ["word"] = {"刑"}},
    -- ["bkdr"] = {["phrase"] = "别都", ["word"] = {"蹩"}},
    -- ["bdcm"] = {["phrase"] = "剥葱", ["word"] = {"葆"}},
    -- ["vuml"] = {["phrase"] = "助忙", ["word"] = {"杼"}},
    -- ["ekif"] = {["phrase"] = "劫帅", ["word"] = {"截"}},
    -- ["qccv"] = {["phrase"] = "勤悴", ["word"] = {"芩"}},
    -- ["qckh"] = {["phrase"] = "勤款", ["word"] = {"嗪"}},
    -- ["bwio"] = {["phrase"] = "北朔", ["word"] = {"臂"}},
    -- ["kvee"] = {["phrase"] = "匮饿", ["word"] = {"岿"}},
    -- ["boft"] = {["phrase"] = "博泛", ["word"] = {"播"}},
    -- ["eeek"] = {["phrase"] = "厄劫", ["word"] = {"阿"}},
    -- ["ytvz"] = {["phrase"] = "厌翟", ["word"] = {"筵"}},
    -- ["ytnk"] = {["phrase"] = "厌蹑", ["word"] = {"妍"}},
    -- ["yhdl"] = {["phrase"] = "原荡", ["word"] = {"渊"}},
    -- ["uuuh"] = {["phrase"] = "厨传", ["word"] = {"蜍"}},
    -- ["cthp"] = {["phrase"] = "参衡", ["word"] = {"黪"}},
    -- ["eirv"] = {["phrase"] = "吉瑞", ["word"] = {"偈"}},
    -- ["tmrl"] = {["phrase"] = "同壤", ["word"] = {"僮"}},
    -- ["herr"] = {["phrase"] = "和揉", ["word"] = {"颌"}},
    -- ["aicv"] = {["phrase"] = "哀悴", ["word"] = {"蔼"}},
    -- ["ulro"] = {["phrase"] = "唱偌", ["word"] = {"倡"}},
    -- ["zekr"] = {["phrase"] = "啧口", ["word"] = {"啧", "赜"}},
    -- ["ithd"] = {["phrase"] = "善好", ["word"] = {"剡"}},
    -- ["tldk"] = {["phrase"] = "堂牒", ["word"] = {"淌", "溏"}},
    -- ["qypu"] = {["phrase"] = "墙铺", ["word"] = {"襁"}},
    -- ["qiqx"] = {["phrase"] = "契洽", ["word"] = {"綦", "憩"}},
    -- ["fusb"] = {["phrase"] = "孚笋", ["word"] = {"罘"}},
    -- ["gunk"] = {["phrase"] = "孤孽", ["word"] = {"姑", "牯"}},
    -- ["xhda"] = {["phrase"] = "宣答", ["word"] = {"渲"}},
    -- ["hhky"] = {["phrase"] = "宦况", ["word"] = {"圜"}},
    -- ["zzbi"] = {["phrase"] = "宰弼", ["word"] = {"宰"}},
    -- ["suxx"] = {["phrase"] = "宿瑕", ["word"] = {"愫"}},
    -- ["eihw"] = {["phrase"] = "寂嘿", ["word"] = {"稷"}},
    -- ["eizl"] = {["phrase"] = "寄赃", ["word"] = {"跻"}},
    -- ["miym"] = {["phrase"] = "密庸", ["word"] = {"谧"}},
    -- ["lfcs"] = {["phrase"] = "岭岑", ["word"] = {"苓"}},
    -- ["wwal"] = {["phrase"] = "嵬昂", ["word"] = {"韦"}},
    -- ["xbyh"] = {["phrase"] = "巡远", ["word"] = {"醺"}},
    -- ["uact"] = {["phrase"] = "差参", ["word"] = {"茬"}},
    -- ["ulao"] = {["phrase"] = "常奥", ["word"] = {"鲳"}},
    -- ["vydi"] = {["phrase"] = "庄地", ["word"] = {"壮"}},
    -- ["yfcu"] = {["phrase"] = "应猝", ["word"] = {"萤"}},
    -- ["bikb"] = {["phrase"] = "弊困", ["word"] = {"吡"}},
    -- ["dlip"] = {["phrase"] = "当生", ["word"] = {"砀"}},
    -- ["xbdo"] = {["phrase"] = "徇铎", ["word"] = {"殉", "洵"}},
    -- ["yuud"] = {["phrase"] = "御朝", ["word"] = {"蝓"}},
    -- ["ulru"] = {["phrase"] = "怅如", ["word"] = {"伥"}},
    -- ["yhte"] = {["phrase"] = "怨慝", ["word"] = {"垸"}},
    -- ["yrko"] = {["phrase"] = "悠阔", ["word"] = {"囿"}},
    -- ["wtce"] = {["phrase"] = "惋恻", ["word"] = {"莞"}},
    -- ["ieqk"] = {["phrase"] = "慑怯", ["word"] = {"舌", "猞"}},
    -- ["gedk"] = {["phrase"] = "戈堞", ["word"] = {"哥"}},
    -- ["dzri"] = {["phrase"] = "戴日", ["word"] = {"傣"}},
    -- ["livm"] = {["phrase"] = "戾种", ["word"] = {"篥"}},
    -- ["pumo"] = {["phrase"] = "扑摸", ["word"] = {"氆"}},
    -- ["tomu"] = {["phrase"] = "托慕", ["word"] = {"柝"}},
    -- ["ylhp"] = {["phrase"] = "扬衡", ["word"] = {"炀"}},
    -- ["piba"] = {["phrase"] = "批把", ["word"] = {"丕"}},
    -- ["uput"] = {["phrase"] = "承禅", ["word"] = {"蛏"}},
    -- ["gmbk"] = {["phrase"] = "拱别", ["word"] = {"宫"}},
    -- ["wann"] = {["phrase"] = "挖年", ["word"] = {"娲"}},
    -- ["eica"] = {["phrase"] = "挤擦", ["word"] = {"蕺"}},
    -- ["vodn"] = {["phrase"] = "捉店", ["word"] = {"涿"}},
    -- ["lnmz"] = {["phrase"] = "敛埋", ["word"] = {"梿"}},
    -- ["vzfl"] = {["phrase"] = "斋房", ["word"] = {"择"}},
    -- ["vtmk"] = {["phrase"] = "斩灭", ["word"] = {"毡", "粘"}},
    -- ["xikh"] = {["phrase"] = "昔款", ["word"] = {"熙"}},
    -- ["mdsu"] = {["phrase"] = "昴宿", ["word"] = {"蝥", "蟊"}},
    -- ["wubk"] = {["phrase"] = "晤别", ["word"] = {"痦", "寤"}},
    -- ["kvko"] = {["phrase"] = "暌阔", ["word"] = {"喟"}},
    -- ["iudr"] = {["phrase"] = "曙斗", ["word"] = {"漱"}},
    -- ["qumq"] = {["phrase"] = "曲谬", ["word"] = {"阒"}},
    -- ["iadh"] = {["phrase"] = "杀断", ["word"] = {"煞"}},
    -- ["iusl"] = {["phrase"] = "束颡", ["word"] = {"纾"}},
    -- ["iddl"] = {["phrase"] = "梢当", ["word"] = {"劭"}},
    -- ["encu"] = {["phrase"] = "检促", ["word"] = {"茧"}},
    -- ["enlj"] = {["phrase"] = "检料", ["word"] = {"鉴"}},
    -- ["bipi"] = {["phrase"] = "比譬", ["word"] = {"裨"}},
    -- ["mdso"] = {["phrase"] = "毛索", ["word"] = {"瞀"}},
    -- ["uitn"] = {["phrase"] = "池田", ["word"] = {"墀"}},
    -- ["iscv"] = {["phrase"] = "沈悴", ["word"] = {"葚"}},
    -- ["zekv"] = {["phrase"] = "泽葵", ["word"] = {"咋"}},
    -- ["ekcl"] = {["phrase"] = "洁藏", ["word"] = {"芥"}},
    -- ["horh"] = {["phrase"] = "活软", ["word"] = {"伙"}},
    -- ["llcl"] = {["phrase"] = "浪苍", ["word"] = {"莨", "蒗"}},
    -- ["yckl"] = {["phrase"] = "淫亢", ["word"] = {"吲"}},
    -- ["lfeh"] = {["phrase"] = "灵狷", ["word"] = {"灵"}},
    -- ["dndr"] = {["phrase"] = "点逗", ["word"] = {"淀"}},
    -- ["ltmj"] = {["phrase"] = "烂妙", ["word"] = {"阑"}},
    -- ["vddk"] = {["phrase"] = "照牒", ["word"] = {"召", "沼"}},
    -- ["ytuz"] = {["phrase"] = "燕钗", ["word"] = {"蜒"}},
    -- ["yaky"] = {["phrase"] = "牙旷", ["word"] = {"呀", "哑"}},
    -- ["qmge"] = {["phrase"] = "琼阁", ["word"] = {"邛"}},
    -- ["ydky"] = {["phrase"] = "瑶筐", ["word"] = {"吆"}},
    -- ["yruy"] = {["phrase"] = "疣疮", ["word"] = {"蚰"}},
    -- ["hdti"] = {["phrase"] = "皓体", ["word"] = {"壕"}},
    -- ["vtdk"] = {["phrase"] = "盏碟", ["word"] = {"沾", "詹"}},
    -- ["mndd"] = {["phrase"] = "眠倒", ["word"] = {"渑"}},
    -- ["rvci"] = {["phrase"] = "睿慈", ["word"] = {"蕤"}},
    -- ["ecna"] = {["phrase"] = "矜纳", ["word"] = {"堇"}},
    -- ["ytuf"] = {["phrase"] = "研揣", ["word"] = {"雁"}},
    -- ["utfp"] = {["phrase"] = "禅锋", ["word"] = {"掺"}},
    -- ["lird"] = {["phrase"] = "离桡", ["word"] = {"例", "俐"}},
    -- ["qqqj"] = {["phrase"] = "秋鞘", ["word"] = {"犰"}},
    -- ["migf"] = {["phrase"] = "秘怪", ["word"] = {"靡"}},
    -- ["uphp"] = {["phrase"] = "秤衡", ["word"] = {"秤"}},
    -- ["uikb"] = {["phrase"] = "笞髡", ["word"] = {"叱"}},
    -- ["ppip"] = {["phrase"] = "篷声", ["word"] = {"砰", "彭"}},
    -- ["somi"] = {["phrase"] = "索秘", ["word"] = {"桫"}},
    -- ["ygpd"] = {["phrase"] = "约炮", ["word"] = {"乐"}},
    -- ["bakb"] = {["phrase"] = "罢困", ["word"] = {"叭", "吧"}},
    -- ["ldbl"] = {["phrase"] = "老蚌", ["word"] = {"痨"}},
    -- ["cmmr"] = {["phrase"] = "聪谋", ["word"] = {"枞"}},
    -- ["iert"] = {["phrase"] = "舍然", ["word"] = {"畲"}},
    -- ["ektl"] = {["phrase"] = "节堂", ["word"] = {"劫", "界"}},
    -- ["hyub"] = {["phrase"] = "荒春", ["word"] = {"蟥"}},
    -- ["yfct"] = {["phrase"] = "荧灿", ["word"] = {"茔"}},
    -- ["yunl"] = {["phrase"] = "萸囊", ["word"] = {"妤"}},
    -- ["huwo"] = {["phrase"] = "虎幄", ["word"] = {"瑚"}},
    -- ["huxk"] = {["phrase"] = "虎蟹", ["word"] = {"怙"}},
    -- ["xugv"] = {["phrase"] = "虚诡", ["word"] = {"魆"}},
    -- ["ctlm"] = {["phrase"] = "蚕笼", ["word"] = {"粲"}},
    -- ["tvhz"] = {["phrase"] = "蜕骸", ["word"] = {"煺"}},
    -- ["piid"] = {["phrase"] = "蜱蛸", ["word"] = {"劈"}},
    -- ["tddf"] = {["phrase"] = "讨定", ["word"] = {"淘"}},
    -- ["vakv"] = {["phrase"] = "诈愧", ["word"] = {"咋"}},
    -- ["vama"] = {["phrase"] = "诈马", ["word"] = {"查", "楂"}},
    -- ["cibn"] = {["phrase"] = "词辨", ["word"] = {"鹚"}},
    -- ["xyvo"] = {["phrase"] = "详酌", ["word"] = {"箱"}},
    -- ["dktt"] = {["phrase"] = "谍探", ["word"] = {"垤"}},
    -- ["ecne"] = {["phrase"] = "谨讷", ["word"] = {"觐"}},
    -- ["gvmt"] = {["phrase"] = "贵满", ["word"] = {"闺", "桂"}},
    -- ["udko"] = {["phrase"] = "超阔", ["word"] = {"嘲"}},
    -- ["lcrr"] = {["phrase"] = "躏蹂", ["word"] = {"赁"}},
    -- ["vhkv"] = {["phrase"] = "转馈", ["word"] = {"啭"}},
    -- ["bndb"] = {["phrase"] = "边墩", ["word"] = {"汴"}},
    -- ["qncr"] = {["phrase"] = "迁凑", ["word"] = {"芡"}},
    -- ["ybkr"] = {["phrase"] = "运口", ["word"] = {"员"}},
    -- ["mido"] = {["phrase"] = "迷夺", ["word"] = {"汨"}},
    -- ["dbzw"] = {["phrase"] = "遁贼", ["word"] = {"蹾"}},
    -- ["ddpc"] = {["phrase"] = "道品", ["word"] = {"祷"}},
    -- ["grbk"] = {["phrase"] = "钩别", ["word"] = {"句"}},
    -- ["coit"] = {["phrase"] = "错闪", ["word"] = {"矬"}},
    -- ["qyyg"] = {["phrase"] = "锵钺", ["word"] = {"羟"}},
    -- ["ljbp"] = {["phrase"] = "镣琫", ["word"] = {"寥"}},
    -- ["ymky"] = {["phrase"] = "雍狂", ["word"] = {"咏", "喁"}},
    -- ["aikm"] = {["phrase"] = "霭空", ["word"] = {"嗌"}},
    -- ["gemk"] = {["phrase"] = "革灭", ["word"] = {"阁", "格"}},
    -- ["exll"] = {["phrase"] = "驾浪", ["word"] = {"甲"}},
    -- ["liaa"] = {["phrase"] = "骊阿", ["word"] = {"鳢"}},
    -- ["qikx"] = {["phrase"] = "骑跨", ["word"] = {"嘁"}},
    -- ["svhz"] = {["phrase"] = "髓海", ["word"] = {"燧"}},
    -- ["einy"] = {["phrase"] = "鸡娘", ["word"] = {"妓"}},
    -- ["ppfp"] = {["phrase"] = "鹏风", ["word"] = {"抨"}},
    -- ["hywo"] = {["phrase"] = "黄幄", ["word"] = {"肓"}},
    -- ["lmlt"] = {["phrase"] = "龙兰", ["word"] = {"垄"}},
    -- ["qjyh"] = {["phrase"] = "侨苑", ["word"] = {"谯"}},
    -- ["nqfl"] = {["phrase"] = "牛房", ["word"] = {"拗"}},
    -- ["lldo"] = {["phrase"] = "浪多", ["word"] = {"朗"}},
    -- ["muco"] = {["phrase"] = "穆厝", ["word"] = {"暮", "苜"}},
    -- ["kvdr"] = {["phrase"] = "魁斗", ["word"] = {"溃"}},
    -- ["vlmi"] = {["phrase"] = "张咪", ["word"] = {"樟"}},
    -- ["liwa"] = {["phrase"] = "里瓦", ["word"] = {"立"}},
    -- ["zort"] = {["phrase"] = "作染", ["word"] = {"坐"}},
    -- ["eumk"] = {["phrase"] = "俱灭", ["word"] = {"驹", "橘", "枸", "椐"}},
    -- ["gubk"] = {["phrase"] = "古憋", ["word"] = {"谷", "痼"}},
    -- ["yhce"] = {["phrase"] = "圆测", ["word"] = {"芫"}},
    -- ["ptdb"] = {["phrase"] = "盘蹲", ["word"] = {"泮"}},
    -- ["qila"] = {["phrase"] = "耆腊", ["word"] = {"亟"}},
    -- ["uikd"] = {["phrase"] = "赤尻", ["word"] = {"哧"}},
    -- ["kzmj"] = {["phrase"] = "开庙", ["word"] = {"闿"}}
}

return dup_table
