local dup_table = {
	["xnzz"] = { ["phrase"] = "现在", ["word"] = { "跹" } },
	["yixk"] = { ["phrase"] = "一些", ["word"] = { "怡" } },
	["iiym"] = { ["phrase"] = "使用", ["word"] = { "谥" } },
	["yisi"] = { ["phrase"] = "意思", ["word"] = { "矣" } },
	["ekir"] = { ["phrase"] = "接受", ["word"] = { "颉" } },
	["guii"] = { ["phrase"] = "故事", ["word"] = { "辜" } },
	["bdbd"] = { ["phrase"] = "宝宝", ["word"] = { "刨" } },
	["yudd"] = { ["phrase"] = "遇到", ["word"] = { "淤", "渝" } },
	["hetm"] = { ["phrase"] = "合同", ["word"] = { "盍" } },
	["yidm"] = { ["phrase"] = "移动", ["word"] = { "溢" } },
	["hvyh"] = { ["phrase"] = "会员", ["word"] = { "诙" } },
	["qidm"] = { ["phrase"] = "启动", ["word"] = { "柒" } },
	["eike"] = { ["phrase"] = "即可", ["word"] = { "唧" } },
	["eydi"] = { ["phrase"] = "降低", ["word"] = { "浆" } },
	["yfgo"] = { ["phrase"] = "英国", ["word"] = { "膺" } },
	["endd"] = { ["phrase"] = "见到", ["word"] = { "湔" } },
	["pwyl"] = { ["phrase"] = "培养", ["word"] = { "霈" } },
	["ecvl"] = { ["phrase"] = "紧张", ["word"] = { "劲", "筋" } },
	["xndz"] = { ["phrase"] = "现代", ["word"] = { "涎" } },
	["iiqi"] = { ["phrase"] = "时期", ["word"] = { "舐" } },
	["yipn"] = { ["phrase"] = "一片", ["word"] = { "乂" } },
	["ybxu"] = { ["phrase"] = "允许", ["word"] = { "恽" } },
	["xnde"] = { ["phrase"] = "显得", ["word"] = { "洗", "冼" } },
	["lfrs"] = { ["phrase"] = "令人", ["word"] = { "令", "伶" } },
	["eiyi"] = { ["phrase"] = "记忆", ["word"] = { "计" } },
	["svii"] = { ["phrase"] = "随时", ["word"] = { "尿", "碎" } },
	["viec"] = { ["phrase"] = "至今", ["word"] = { "峙" } },
	["ycdd"] = { ["phrase"] = "引导", ["word"] = { "洇" } },
	["boii"] = { ["phrase"] = "博士", ["word"] = { "擘" } },
	["ytuu"] = { ["phrase"] = "演出", ["word"] = { "衍" } },
	["suvr"] = { ["phrase"] = "苏州", ["word"] = { "簌" } },
	["pcvi"] = { ["phrase"] = "品质", ["word"] = { "颦" } },
	["hhbd"] = { ["phrase"] = "环保", ["word"] = { "痪" } },
	["xiir"] = { ["phrase"] = "吸收", ["word"] = { "屣" } },
	["liul"] = { ["phrase"] = "立场", ["word"] = { "历", "励", "厘" } },
	["yhuy"] = { ["phrase"] = "原创", ["word"] = { "辕" } },
	["vize"] = { ["phrase"] = "职责", ["word"] = { "踯" } },
	["qici"] = { ["phrase"] = "其次", ["word"] = { "芪" } },
	["vtlg"] = { ["phrase"] = "战略", ["word"] = { "战" } },
	["ydba"] = { ["phrase"] = "要把", ["word"] = { "疟" } },
	["ebdv"] = { ["phrase"] = "军队", ["word"] = { "龟" } },
	["tttd"] = { ["phrase"] = "探讨", ["word"] = { "坍" } },
	["hvkh"] = { ["phrase"] = "汇款", ["word"] = { "咴" } },
	["vmvm"] = { ["phrase"] = "种种", ["word"] = { "盅" } },
	["qidd"] = { ["phrase"] = "起到", ["word"] = { "沏" } },
	["ytul"] = { ["phrase"] = "延长", ["word"] = { "餍" } },
	["mwmw"] = { ["phrase"] = "妹妹", ["word"] = { "枚" } },
	["bici"] = { ["phrase"] = "彼此", ["word"] = { "荜", "薜" } },
	["eici"] = { ["phrase"] = "几次", ["word"] = { "蒺" } },
	["vmwu"] = { ["phrase"] = "中午", ["word"] = { "螽" } },
	["qqdv"] = { ["phrase"] = "球队", ["word"] = { "龟" } },
	["iifl"] = { ["phrase"] = "释放", ["word"] = { "势" } },
	["iitu"] = { ["phrase"] = "试图", ["word"] = { "螫" } },
	["yida"] = { ["phrase"] = "一大", ["word"] = { "殪" } },
	["yikr"] = { ["phrase"] = "一口", ["word"] = { "颐" } },
	["yily"] = { ["phrase"] = "一辆", ["word"] = { "毅" } },
	["bdzi"] = { ["phrase"] = "包子", ["word"] = { "趵" } },
	["bnli"] = { ["phrase"] = "便利", ["word"] = { "辨", "辩", "辫" } },
	["vudo"] = { ["phrase"] = "诸多", ["word"] = { "渚", "潴" } },
	["ekyg"] = { ["phrase"] = "节约", ["word"] = { "讦" } },
	["yiri"] = { ["phrase"] = "一日", ["word"] = { "佚" } },
	["pwfl"] = { ["phrase"] = "配方", ["word"] = { "旆" } },
	["wwxf"] = { ["phrase"] = "卫星", ["word"] = { "惟" } },
	["euqf"] = { ["phrase"] = "剧情", ["word"] = { "雎" } },
	["qidn"] = { ["phrase"] = "起点", ["word"] = { "凄" } },
	["dlci"] = { ["phrase"] = "档次", ["word"] = { "菪" } },
	["eiho"] = { ["phrase"] = "激活", ["word"] = { "稽" } },
	["eihe"] = { ["phrase"] = "集合", ["word"] = { "嵇" } },
	["eilv"] = { ["phrase"] = "纪律", ["word"] = { "乩" } },
	["yeye"] = { ["phrase"] = "爷爷", ["word"] = { "邺" } },
	["helt"] = { ["phrase"] = "荷兰", ["word"] = { "壑" } },
	["voli"] = { ["phrase"] = "着力", ["word"] = { "卓" } },
	["euzi"] = { ["phrase"] = "句子", ["word"] = { "遽" } },
	["eida"] = { ["phrase"] = "极大", ["word"] = { "殛" } },
	["quuu"] = { ["phrase"] = "取出", ["word"] = { "衢" } },
	["ytve"] = { ["phrase"] = "沿着", ["word"] = { "鄢" } },
	["biii"] = { ["phrase"] = "笔试", ["word"] = { "辟" } },
	["mibu"] = { ["phrase"] = "弥补", ["word"] = { "蜜" } },
	["hzkr"] = { ["phrase"] = "海口", ["word"] = { "咳" } },
	["yuwo"] = { ["phrase"] = "与我", ["word"] = { "育" } },
	["vibt"] = { ["phrase"] = "值班", ["word"] = { "窒" } },
	["xizd"] = { ["phrase"] = "洗澡", ["word"] = { "蹊" } },
	["bizi"] = { ["phrase"] = "鼻子", ["word"] = { "避", "跸" } },
	["qfhx"] = { ["phrase"] = "清华", ["word"] = { "綮", "黥" } },
	["yidb"] = { ["phrase"] = "一顿", ["word"] = { "浥" } },
	["gdyh"] = { ["phrase"] = "高原", ["word"] = { "羔" } },
	["butf"] = { ["phrase"] = "不停", ["word"] = { "埔" } },
	["luvi"] = { ["phrase"] = "录制", ["word"] = { "舻", "箓" } },
	["bwpo"] = { ["phrase"] = "被迫", ["word"] = { "褙" } },
	["yhxn"] = { ["phrase"] = "原先", ["word"] = { "鸳" } },
	["xkir"] = { ["phrase"] = "携手", ["word"] = { "颉" } },
	["iiyg"] = { ["phrase"] = "十月", ["word"] = { "式", "试" } },
	["ejul"] = { ["phrase"] = "较长", ["word"] = { "轿" } },
	["lqii"] = { ["phrase"] = "流失", ["word"] = { "碌" } },
	["fufw"] = { ["phrase"] = "付费", ["word"] = { "抚", "敷" } },
	["xywz"] = { ["phrase"] = "向外", ["word"] = { "享" } },
	["dide"] = { ["phrase"] = "低的", ["word"] = { "邸" } },
	["wuyr"] = { ["phrase"] = "无忧", ["word"] = { "诬" } },
	["quen"] = { ["phrase"] = "区间", ["word"] = { "娶" } },
	["bivi"] = { ["phrase"] = "壁纸", ["word"] = { "筚" } },
	["xnee"] = { ["phrase"] = "限额", ["word"] = { "岘" } },
	["enbk"] = { ["phrase"] = "鉴别", ["word"] = { "謇" } },
	["ekiv"] = { ["phrase"] = "节水", ["word"] = { "碣" } },
	["isye"] = { ["phrase"] = "深夜", ["word"] = { "诜" } },
	["eydd"] = { ["phrase"] = "降到", ["word"] = { "奖" } },
	["ekil"] = { ["phrase"] = "街上", ["word"] = { "劼" } },
	["zidt"] = { ["phrase"] = "子弹", ["word"] = { "淄" } },
	["huhh"] = { ["phrase"] = "呼唤", ["word"] = { "烀" } },
	["dtdl"] = { ["phrase"] = "但当", ["word"] = { "殚" } },
	["enro"] = { ["phrase"] = "减弱", ["word"] = { "僭" } },
	["xjvs"] = { ["phrase"] = "小镇", ["word"] = { "箫" } },
	["uumo"] = { ["phrase"] = "触摸", ["word"] = { "楮" } },
	["iian"] = { ["phrase"] = "是按", ["word"] = { "豕" } },
	["xihx"] = { ["phrase"] = "细化", ["word"] = { "熄" } },
	["yixc"] = { ["phrase"] = "一心", ["word"] = { "羿" } },
	["dudd"] = { ["phrase"] = "督导", ["word"] = { "渎" } },
	["fudz"] = { ["phrase"] = "附带", ["word"] = { "浮" } },
	["vidv"] = { ["phrase"] = "支队", ["word"] = { "沚" } },
	["fuxf"] = { ["phrase"] = "复兴", ["word"] = { "怫" } },
	["bzii"] = { ["phrase"] = "百事", ["word"] = { "掰" } },
	["qimj"] = { ["phrase"] = "奇妙", ["word"] = { "杞", "桤" } },
	["eivb"] = { ["phrase"] = "基准", ["word"] = { "箕" } },
	["dmek"] = { ["phrase"] = "冻结", ["word"] = { "峒" } },
	["lian"] = { ["phrase"] = "立案", ["word"] = { "吏" } },
	["vizi"] = { ["phrase"] = "之子", ["word"] = { "跖" } },
	["hvym"] = { ["phrase"] = "会用", ["word"] = { "诲" } },
	["yhde"] = { ["phrase"] = "远的", ["word"] = { "沅" } },
	["fucz"] = { ["phrase"] = "福彩", ["word"] = { "莩" } },
	["wtbd"] = { ["phrase"] = "晚报", ["word"] = { "剜" } },
	["fwkf"] = { ["phrase"] = "飞快", ["word"] = { "匪", "啡" } },
	["viio"] = { ["phrase"] = "之说", ["word"] = { "智" } },
	["iiec"] = { ["phrase"] = "使劲", ["word"] = { "峙" } },
	["uaia"] = { ["phrase"] = "查杀", ["word"] = { "馇", "碴" } },
	["enyg"] = { ["phrase"] = "简约", ["word"] = { "艰", "戬" } },
	["drba"] = { ["phrase"] = "都把", ["word"] = { "痘" } },
	["eitj"] = { ["phrase"] = "几条", ["word"] = { "圾" } },
	["iuww"] = { ["phrase"] = "数为", ["word"] = { "孰" } },
	["mwym"] = { ["phrase"] = "没用", ["word"] = { "霉", "酶" } },
	["ludi"] = { ["phrase"] = "陆地", ["word"] = { "泸", "渌" } },
	["vtdv"] = { ["phrase"] = "战队", ["word"] = { "湛" } },
	["yier"] = { ["phrase"] = "一二", ["word"] = { "嶷" } },
	["bukf"] = { ["phrase"] = "不快", ["word"] = { "哺" } },
	["vpfa"] = { ["phrase"] = "蒸发", ["word"] = { "拯" } },
	["qnbi"] = { ["phrase"] = "铅笔", ["word"] = { "搴" } },
	["fuyd"] = { ["phrase"] = "服药", ["word"] = { "黻" } },
	["luzi"] = { ["phrase"] = "路子", ["word"] = { "逯" } },
	["fubj"] = { ["phrase"] = "附表", ["word"] = { "斧" } },
	["ejdh"] = { ["phrase"] = "较短", ["word"] = { "湫" } },
	["wumw"] = { ["phrase"] = "妩媚", ["word"] = { "杌" } },
	["eiej"] = { ["phrase"] = "计较", ["word"] = { "岌" } },
	["qiri"] = { ["phrase"] = "七日", ["word"] = { "俟" } },
	["ythh"] = { ["phrase"] = "延缓", ["word"] = { "炎", "焱" } },
	["xjmw"] = { ["phrase"] = "小妹", ["word"] = { "骁" } },
	["dnbd"] = { ["phrase"] = "电报", ["word"] = { "奠" } },
	["wwtn"] = { ["phrase"] = "未填", ["word"] = { "畏" } },
	["yizd"] = { ["phrase"] = "一早", ["word"] = { "逸", "劓" } },
	["eiee"] = { ["phrase"] = "饥饿", ["word"] = { "觊" } },
	["iiln"] = { ["phrase"] = "失恋", ["word"] = { "史" } },
	["yism"] = { ["phrase"] = "移送", ["word"] = { "缢" } },
	["zidn"] = { ["phrase"] = "字典", ["word"] = { "姿" } },
	["wwen"] = { ["phrase"] = "未见", ["word"] = { "隈" } },
	["yihb"] = { ["phrase"] = "已婚", ["word"] = { "熠" } },
	["wwmw"] = { ["phrase"] = "唯美", ["word"] = { "闱" } },
	["wunw"] = { ["phrase"] = "屋内", ["word"] = { "物", "妩" } },
	["qidi"] = { ["phrase"] = "启迪", ["word"] = { "漆" } },
	["ymwt"] = { ["phrase"] = "用完", ["word"] = { "壅" } },
	["dimd"] = { ["phrase"] = "地貌", ["word"] = { "柢" } },
	["ytke"] = { ["phrase"] = "眼科", ["word"] = { "郾" } },
	["migm"] = { ["phrase"] = "迷宫", ["word"] = { "糜", "麋" } },
	["iuwt"] = { ["phrase"] = "数万", ["word"] = { "塾" } },
	["vefu"] = { ["phrase"] = "这幅", ["word"] = { "蛰", "蜇" } },
	["zidi"] = { ["phrase"] = "子弟", ["word"] = { "滓" } },
	["vrye"] = { ["phrase"] = "昼夜", ["word"] = { "诌" } },
	["dazz"] = { ["phrase"] = "打在", ["word"] = { "跶" } },
	["hedn"] = { ["phrase"] = "核电", ["word"] = { "鹤" } },
	["iurm"] = { ["phrase"] = "殊荣", ["word"] = { "毹" } },
	["xiyd"] = { ["phrase"] = "西药", ["word"] = { "羲" } },
	["enbd"] = { ["phrase"] = "简报", ["word"] = { "剪" } },
	["buld"] = { ["phrase"] = "捕捞", ["word"] = { "卜" } },
	["yugl"] = { ["phrase"] = "浴缸", ["word"] = { "鬻" } },
	["piii"] = { ["phrase"] = "批示", ["word"] = { "辟", "鼙" } },
	["uefw"] = { ["phrase"] = "车费", ["word"] = { "撤" } },
	["mwgm"] = { ["phrase"] = "美工", ["word"] = { "糜" } },
	["enzz"] = { ["phrase"] = "健在", ["word"] = { "踺" } },
	["kebk"] = { ["phrase"] = "可别", ["word"] = { "客", "疴" } },
	["yupn"] = { ["phrase"] = "余篇", ["word"] = { "臾" } },
	["ildp"] = { ["phrase"] = "上等", ["word"] = { "殇", "觞" } },
	["vudv"] = { ["phrase"] = "主队", ["word"] = { "注", "洙" } },
	["eydm"] = { ["phrase"] = "江东", ["word"] = { "桨" } },
	["eidj"] = { ["phrase"] = "基调", ["word"] = { "汲" } },
	["eflo"] = { ["phrase"] = "经络", ["word"] = { "靖" } },
	["bwfu"] = { ["phrase"] = "背负", ["word"] = { "辈" } },
	["ejcb"] = { ["phrase"] = "缴存", ["word"] = { "藠" } },
	["yuyr"] = { ["phrase"] = "遇有", ["word"] = { "欤" } },
	["yfbn"] = { ["phrase"] = "应变", ["word"] = { "瘿" } },
	["rupc"] = { ["phrase"] = "乳品", ["word"] = { "褥" } },
	["lndz"] = { ["phrase"] = "连带", ["word"] = { "涟" } },
	["eidd"] = { ["phrase"] = "即到", ["word"] = { "剞" } },
	["xuno"] = { ["phrase"] = "许诺", ["word"] = { "婿" } },
	["xfxi"] = { ["phrase"] = "星系", ["word"] = { "性", "惺" } },
	["voyi"] = { ["phrase"] = "桌椅", ["word"] = { "酌" } },
	["iibt"] = { ["phrase"] = "石板", ["word"] = { "室" } },
	["yuyd"] = { ["phrase"] = "余姚", ["word"] = { "谕" } },
	["issi"] = { ["phrase"] = "深思", ["word"] = { "绅" } },
	["xfip"] = { ["phrase"] = "兴盛", ["word"] = { "饧" } },
	["visi"] = { ["phrase"] = "致死", ["word"] = { "纸" } },
	["pudn"] = { ["phrase"] = "铺垫", ["word"] = { "濮" } },
	["fwfw"] = { ["phrase"] = "飞飞", ["word"] = { "斐" } },
	["eqpa"] = { ["phrase"] = "就怕", ["word"] = { "臼" } },
	["iixg"] = { ["phrase"] = "嗜血", ["word"] = { "弑" } },
	["dtfl"] = { ["phrase"] = "单方", ["word"] = { "掸" } },
	["lrmn"] = { ["phrase"] = "露面", ["word"] = { "娄", "楼" } },
	["yryl"] = { ["phrase"] = "悠扬", ["word"] = { "幼" } },
	["pukf"] = { ["phrase"] = "普快", ["word"] = { "圃" } },
	["iivu"] = { ["phrase"] = "石柱", ["word"] = { "虱" } },
	["visb"] = { ["phrase"] = "止损", ["word"] = { "织" } },
	["fpdf"] = { ["phrase"] = "封顶", ["word"] = { "沣" } },
	["luei"] = { ["phrase"] = "路基", ["word"] = { "录" } },
	["uidn"] = { ["phrase"] = "吃点", ["word"] = { "鸱" } },
	["vuzu"] = { ["phrase"] = "驻足", ["word"] = { "躅" } },
	["sidj"] = { ["phrase"] = "死掉", ["word"] = { "澌" } },
	["xfxg"] = { ["phrase"] = "性学", ["word"] = { "悻" } },
	["wuwl"] = { ["phrase"] = "无望", ["word"] = { "务" } },
	["fsdd"] = { ["phrase"] = "分到", ["word"] = { "汾" } },
	["qkxj"] = { ["phrase"] = "切削", ["word"] = { "惬" } },
	["fuyb"] = { ["phrase"] = "浮云", ["word"] = { "讣" } },
	["iiri"] = { ["phrase"] = "时日", ["word"] = { "什", "仕" } },
	["eism"] = { ["phrase"] = "寄送", ["word"] = { "羁" } },
	["vuve"] = { ["phrase"] = "住着", ["word"] = { "邾", "竺" } },
	["kekm"] = { ["phrase"] = "可控", ["word"] = { "嗑" } },
	["eiir"] = { ["phrase"] = "棘手", ["word"] = { "赍" } },
	["modd"] = { ["phrase"] = "摸到", ["word"] = { "漠" } },
	["wwdf"] = { ["phrase"] = "未定", ["word"] = { "潍" } },
	["xksi"] = { ["phrase"] = "血丝", ["word"] = { "绁" } },
	["qiir"] = { ["phrase"] = "棋手", ["word"] = { "碛" } },
	["itye"] = { ["phrase"] = "山野", ["word"] = { "讪", "鄯" } },
	["iiky"] = { ["phrase"] = "实况", ["word"] = { "嘘" } },
	["ekrl"] = { ["phrase"] = "接壤", ["word"] = { "介", "价" } },
	["ecdd"] = { ["phrase"] = "进到", ["word"] = { "浕" } },
	["eidl"] = { ["phrase"] = "激荡", ["word"] = { "济" } },
	["iiiu"] = { ["phrase"] = "实属", ["word"] = { "蚀" } },
	["gvvm"] = { ["phrase"] = "贵重", ["word"] = { "簋" } },
	["xieh"] = { ["phrase"] = "席卷", ["word"] = { "隰" } },
	["eidz"] = { ["phrase"] = "几代", ["word"] = { "洎" } },
	["dugu"] = { ["phrase"] = "独孤", ["word"] = { "髑" } },
	["ecso"] = { ["phrase"] = "紧缩", ["word"] = { "缙" } },
	["eisv"] = { ["phrase"] = "脊髓", ["word"] = { "继" } },
	["pjxg"] = { ["phrase"] = "飘雪", ["word"] = { "瓢" } },
	["yihx"] = { ["phrase"] = "异化", ["word"] = { "移", "黟" } },
	["efxx"] = { ["phrase"] = "惊吓", ["word"] = { "惊", "憬" } },
	["eimj"] = { ["phrase"] = "几秒", ["word"] = { "机", "极" } },
	["fuvl"] = { ["phrase"] = "腹胀", ["word"] = { "弗" } },
	["eigv"] = { ["phrase"] = "机柜", ["word"] = { "既" } },
	["ytup"] = { ["phrase"] = "严惩", ["word"] = { "彦" } },
	["liln"] = { ["phrase"] = "历练", ["word"] = { "鹂" } },
	["uiil"] = { ["phrase"] = "吃上", ["word"] = { "饬" } },
	["yure"] = { ["phrase"] = "预热", ["word"] = { "觎" } },
	["lidd"] = { ["phrase"] = "力道", ["word"] = { "漓" } },
	["tddd"] = { ["phrase"] = "逃到", ["word"] = { "洮" } },
	["uivu"] = { ["phrase"] = "吃住", ["word"] = { "蚩" } },
	["yuvy"] = { ["phrase"] = "预装", ["word"] = { "竽" } },
	["eeyb"] = { ["phrase"] = "厄运", ["word"] = { "讹" } },
	["wodn"] = { ["phrase"] = "我点", ["word"] = { "涡" } },
	["ximn"] = { ["phrase"] = "西面", ["word"] = { "樨" } },
	["ftpt"] = { ["phrase"] = "反叛", ["word"] = { "番" } },
	["hvxh"] = { ["phrase"] = "回旋", ["word"] = { "恢" } },
	["xkmd"] = { ["phrase"] = "鞋帽", ["word"] = { "楔" } },
	["dtvl"] = { ["phrase"] = "单张", ["word"] = { "箪" } },
	["uuiu"] = { ["phrase"] = "出书", ["word"] = { "础" } },
	["ttta"] = { ["phrase"] = "坍塌", ["word"] = { "坦" } },
	["xixx"] = { ["phrase"] = "西夏", ["word"] = { "恓" } },
	["vydn"] = { ["phrase"] = "装点", ["word"] = { "妆" } },
	["lici"] = { ["phrase"] = "历次", ["word"] = { "藜" } },
	["wusm"] = { ["phrase"] = "武松", ["word"] = { "骛" } },
	["yuxk"] = { ["phrase"] = "淤血", ["word"] = { "誉" } },
	["xbzi"] = { ["phrase"] = "荀子", ["word"] = { "迅" } },
	["ptvp"] = { ["phrase"] = "盘整", ["word"] = { "爿" } },
	["eido"] = { ["phrase"] = "几多", ["word"] = { "脊" } },
	["qneq"] = { ["phrase"] = "迁就", ["word"] = { "阡" } },
	["dumo"] = { ["phrase"] = "镀膜", ["word"] = { "阇" } },
	["lzdl"] = { ["phrase"] = "来当", ["word"] = { "涞" } },
	["yuhl"] = { ["phrase"] = "余杭", ["word"] = { "煜" } },
	["xkdu"] = { ["phrase"] = "亵渎", ["word"] = { "蟹" } },
	["yiui"] = { ["phrase"] = "一尺", ["word"] = { "轶" } },
	["eial"] = { ["phrase"] = "激昂", ["word"] = { "鲚" } },
	["ecma"] = { ["phrase"] = "金马", ["word"] = { "槿" } },
	["iudi"] = { ["phrase"] = "属地", ["word"] = { "沭" } },
	["lqdd"] = { ["phrase"] = "六道", ["word"] = { "浏" } },
	["yizr"] = { ["phrase"] = "一走", ["word"] = { "遗" } },
	["wweg"] = { ["phrase"] = "味觉", ["word"] = { "巍", "隗", "嵬" } },
	["eibi"] = { ["phrase"] = "击毙", ["word"] = { "疾" } },
	["qise"] = { ["phrase"] = "起色", ["word"] = { "缉" } },
	["iiir"] = { ["phrase"] = "失手", ["word"] = { "贳" } },
	["ejkh"] = { ["phrase"] = "交款", ["word"] = { "噍" } },
	["yuqh"] = { ["phrase"] = "玉泉", ["word"] = { "狳" } },
	["ytie"] = { ["phrase"] = "颜射", ["word"] = { "砚" } },
	["viif"] = { ["phrase"] = "直率", ["word"] = { "雉" } },
	["keui"] = { ["phrase"] = "可耻", ["word"] = { "蝌" } },
	["yidk"] = { ["phrase"] = "一叠", ["word"] = { "漪" } },
	["qndo"] = { ["phrase"] = "千多", ["word"] = { "潜" } },
}

return dup_table
