local dup_table = {
    ["vidu"] = {["phrase"] = "制度", ["word"] = {"汁"}},
    ["yidk"] = {["phrase"] = "一定", ["word"] = {"漪"}},
    ["yidm"] = {["phrase"] = "一点", ["word"] = {"溢"}},
    ["jmdj"] = {["phrase"] = "简单", ["word"] = {"渐", "溅"}},
    ["sudu"] = {["phrase"] = "速度", ["word"] = {"涑", "觫"}},
    ["uiui"] = {["phrase"] = "实施", ["word"] = {"蚀"}},
    ["yijm"] = {["phrase"] = "意见", ["word"] = {"镒"}},
    ["yjjk"] = {["phrase"] = "眼睛", ["word"] = {"铅"}},
    ["jisr"] = {["phrase"] = "计算", ["word"] = {"绩"}},
    ["vifu"] = {["phrase"] = "支付", ["word"] = {"挚"}},
    ["yibm"] = {["phrase"] = "一边", ["word"] = {"益"}},
    ["jike"] = {["phrase"] = "即可", ["word"] = {"唧"}},
    ["mwnm"] = {["phrase"] = "每年", ["word"] = {"媒"}},
    ["ykgo"] = {["phrase"] = "英国", ["word"] = {"膺"}},
    ["ykwf"] = {["phrase"] = "英文", ["word"] = {"赢", "嬴"}},
    ["qidd"] = {["phrase"] = "期待", ["word"] = {"沏"}},
    ["jbll"] = {["phrase"] = "尽量", ["word"] = {"巾"}},
    ["yidj"] = {["phrase"] = "一旦", ["word"] = {"沂"}},
    ["yikk"] = {["phrase"] = "一块", ["word"] = {"贻"}},
    ["jiyu"] = {["phrase"] = "基于", ["word"] = {"计"}},
    ["ufru"] = {["phrase"] = "深入", ["word"] = {"什", "伸"}},
    ["xmde"] = {["phrase"] = "显得", ["word"] = {"洗", "冼"}},
    ["jkcd"] = {["phrase"] = "精彩", ["word"] = {"荆"}},
    ["yixl"] = {["phrase"] = "一项", ["word"] = {"怿", "翌"}},
    ["didm"] = {["phrase"] = "地点", ["word"] = {"涤"}},
    ["uivi"] = {["phrase"] = "是指", ["word"] = {"虱"}},
    ["vgvl"] = {["phrase"] = "症状", ["word"] = {"筝"}},
    ["bmhc"] = {["phrase"] = "编号", ["word"] = {"扁", "煸"}},
    ["yikr"] = {["phrase"] = "一款", ["word"] = {"颐"}},
    ["fuvl"] = {["phrase"] = "服装", ["word"] = {"弗"}},
    ["svhz"] = {["phrase"] = "随后", ["word"] = {"燧"}},
    ["jxju"] = {["phrase"] = "家具", ["word"] = {"镓"}},
    ["uiqu"] = {["phrase"] = "失去", ["word"] = {"舐"}},
    ["vize"] = {["phrase"] = "职责", ["word"] = {"踯"}},
    ["yivc"] = {["phrase"] = "依照", ["word"] = {"彝"}},
    ["ycba"] = {["phrase"] = "要把", ["word"] = {"疟"}},
    ["xbxb"] = {["phrase"] = "信心", ["word"] = {"衅"}},
    ["uiyc"] = {["phrase"] = "是要", ["word"] = {"诗"}},
    ["gemk"] = {["phrase"] = "革命", ["word"] = {"阁", "格"}},
    ["jydv"] = {["phrase"] = "军队", ["word"] = {"龟"}},
    ["ykcy"] = {["phrase"] = "英寸", ["word"] = {"英", "莹"}},
    ["yiwd"] = {["phrase"] = "以外", ["word"] = {"亦", "奕"}},
    ["yrxn"] = {["phrase"] = "院校", ["word"] = {"鸳"}},
    ["luqu"] = {["phrase"] = "录取", ["word"] = {"氯"}},
    ["yudk"] = {["phrase"] = "预订", ["word"] = {"浴"}},
    ["uiti"] = {["phrase"] = "试题", ["word"] = {"螫"}},
    ["gsgu"] = {["phrase"] = "巩固", ["word"] = {"汞"}},
    ["qiqr"] = {["phrase"] = "齐全", ["word"] = {"欺"}},
    ["vifh"] = {["phrase"] = "脂肪", ["word"] = {"摭"}},
    ["ybqk"] = {["phrase"] = "引擎", ["word"] = {"狺"}},
    ["mwmw"] = {["phrase"] = "妹妹", ["word"] = {"枚"}},
    ["jidj"] = {["phrase"] = "鸡蛋", ["word"] = {"汲"}},
    ["lujk"] = {["phrase"] = "路径", ["word"] = {"铝"}},
    ["qqdv"] = {["phrase"] = "球队", ["word"] = {"龟"}},
    ["furf"] = {["phrase"] = "夫人", ["word"] = {"佛"}},
    ["yida"] = {["phrase"] = "一大", ["word"] = {"殪"}},
    ["vudo"] = {["phrase"] = "诸多", ["word"] = {"渚", "潴"}},
    ["jmmm"] = {["phrase"] = "见面", ["word"] = {"槛"}},
    ["qmjk"] = {["phrase"] = "前景", ["word"] = {"铅"}},
    ["hvhx"] = {["phrase"] = "绘画", ["word"] = {"秽"}},
    ["licd"] = {["phrase"] = "理财", ["word"] = {"莉", "蓠"}},
    ["bcbn"] = {["phrase"] = "报表", ["word"] = {"鸨"}},
    ["yizd"] = {["phrase"] = "已在", ["word"] = {"逸", "劓"}},
    ["qidm"] = {["phrase"] = "起点", ["word"] = {"柒"}},
    ["bukf"] = {["phrase"] = "不肯", ["word"] = {"哺"}},
    ["jiho"] = {["phrase"] = "激活", ["word"] = {"稽"}},
    ["jihe"] = {["phrase"] = "集合", ["word"] = {"嵇"}},
    ["jilv"] = {["phrase"] = "纪律", ["word"] = {"乩"}},
    ["yeye"] = {["phrase"] = "爷爷", ["word"] = {"邺"}},
    ["huxk"] = {["phrase"] = "户型", ["word"] = {"怙"}},
    ["yiiu"] = {["phrase"] = "一处", ["word"] = {"轶"}},
    ["jida"] = {["phrase"] = "极大", ["word"] = {"殛"}},
    ["yjve"] = {["phrase"] = "沿着", ["word"] = {"鄢"}},
    ["lldm"] = {["phrase"] = "亮点", ["word"] = {"梁", "粱"}},
    ["hedk"] = {["phrase"] = "核定", ["word"] = {"河", "涸"}},
    ["yuwo"] = {["phrase"] = "与我", ["word"] = {"育"}},
    ["yukk"] = {["phrase"] = "愉快", ["word"] = {"圄"}},
    ["qkhx"] = {["phrase"] = "清华", ["word"] = {"綮", "黥"}},
    ["yaii"] = {["phrase"] = "牙齿", ["word"] = {"衙"}},
    ["tcfh"] = {["phrase"] = "套房", ["word"] = {"焘"}},
    ["jpdk"] = {["phrase"] = "界定", ["word"] = {"洁"}},
    ["iuui"] = {["phrase"] = "出示", ["word"] = {"础"}},
    ["bwpo"] = {["phrase"] = "被迫", ["word"] = {"褙"}},
    ["xmuh"] = {["phrase"] = "线上", ["word"] = {"燹"}},
    ["jbdd"] = {["phrase"] = "近代", ["word"] = {"浕"}},
    ["jmbh"] = {["phrase"] = "肩膀", ["word"] = {"煎"}},
    ["fufw"] = {["phrase"] = "付费", ["word"] = {"抚", "敷"}},
    ["zidr"] = {["phrase"] = "字段", ["word"] = {"资", "渍"}},
    ["vjlk"] = {["phrase"] = "占领", ["word"] = {"占", "站"}},
    ["uidr"] = {["phrase"] = "时段", ["word"] = {"湜"}},
    ["gsgr"] = {["phrase"] = "公关", ["word"] = {"贡"}},
    ["dide"] = {["phrase"] = "低的", ["word"] = {"邸"}},
    ["ufsu"] = {["phrase"] = "申诉", ["word"] = {"绅"}},
    ["xmee"] = {["phrase"] = "限额", ["word"] = {"岘"}},
    ["livi"] = {["phrase"] = "理智", ["word"] = {"蠡"}},
    ["jpuv"] = {["phrase"] = "节水", ["word"] = {"碣"}},
    ["jqjl"] = {["phrase"] = "就将", ["word"] = {"舅"}},
    ["ufye"] = {["phrase"] = "深夜", ["word"] = {"诜"}},
    ["jibu"] = {["phrase"] = "既不", ["word"] = {"疾"}},
    ["lidd"] = {["phrase"] = "历代", ["word"] = {"漓"}},
    ["suyh"] = {["phrase"] = "素养", ["word"] = {"酥"}},
    ["fuyb"] = {["phrase"] = "复印", ["word"] = {"讣"}},
    ["iuih"] = {["phrase"] = "出场", ["word"] = {"蜍"}},
    ["yjii"] = {["phrase"] = "延迟", ["word"] = {"衍"}},
    ["xtya"] = {["phrase"] = "血压", ["word"] = {"谑"}},
    ["jmro"] = {["phrase"] = "减弱", ["word"] = {"僭"}},
    ["liwd"] = {["phrase"] = "例外", ["word"] = {"离", "璃"}},
    ["jmbk"] = {["phrase"] = "兼并", ["word"] = {"謇"}},
    ["iumo"] = {["phrase"] = "触摸", ["word"] = {"楮"}},
    ["uian"] = {["phrase"] = "是按", ["word"] = {"豕"}},
    ["xihx"] = {["phrase"] = "细化", ["word"] = {"熄"}},
    ["yixb"] = {["phrase"] = "一心", ["word"] = {"翼", "悒"}},
    ["qimj"] = {["phrase"] = "期满", ["word"] = {"杞", "桤"}},
    ["grbk"] = {["phrase"] = "官兵", ["word"] = {"官"}},
    ["yily"] = {["phrase"] = "一轮", ["word"] = {"毅"}},
    ["buld"] = {["phrase"] = "不来", ["word"] = {"卜"}},
    ["wudk"] = {["phrase"] = "屋顶", ["word"] = {"污", "浯"}},
    ["yuuh"] = {["phrase"] = "遇上", ["word"] = {"熨"}},
    ["vidv"] = {["phrase"] = "支队", ["word"] = {"沚"}},
    ["viyb"] = {["phrase"] = "指引", ["word"] = {"识"}},
    ["ijdz"] = {["phrase"] = "颤抖", ["word"] = {"潺"}},
    ["yyss"] = {["phrase"] = "运送", ["word"] = {"纭"}},
    ["jmvj"] = {["phrase"] = "建站", ["word"] = {"笺"}},
    ["jmgz"] = {["phrase"] = "建构", ["word"] = {"鞬", "鞯"}},
    ["lian"] = {["phrase"] = "立案", ["word"] = {"吏"}},
    ["qipj"] = {["phrase"] = "期盼", ["word"] = {"祈"}},
    ["yrde"] = {["phrase"] = "远的", ["word"] = {"沅"}},
    ["mcsi"] = {["phrase"] = "貌似", ["word"] = {"蝥", "蟊"}},
    ["viuo"] = {["phrase"] = "之说", ["word"] = {"智"}},
    ["iaua"] = {["phrase"] = "查杀", ["word"] = {"馇", "碴"}},
    ["gcmk"] = {["phrase"] = "高明", ["word"] = {"槁"}},
    ["mmdm"] = {["phrase"] = "缅甸", ["word"] = {"沔", "湎"}},
    ["jiug"] = {["phrase"] = "计生", ["word"] = {"戟"}},
    ["dzba"] = {["phrase"] = "都把", ["word"] = {"痘"}},
    ["zdbu"] = {["phrase"] = "再不", ["word"] = {"宰"}},
    ["yipn"] = {["phrase"] = "一票", ["word"] = {"乂"}},
    ["bwuz"] = {["phrase"] = "备受", ["word"] = {"孛"}},
    ["xink"] = {["phrase"] = "西宁", ["word"] = {"嬉"}},
    ["uuww"] = {["phrase"] = "数为", ["word"] = {"孰"}},
    ["iajx"] = {["phrase"] = "差价", ["word"] = {"镲"}},
    ["vjdv"] = {["phrase"] = "战队", ["word"] = {"湛"}},
    ["rude"] = {["phrase"] = "入的", ["word"] = {"濡"}},
    ["yier"] = {["phrase"] = "一二", ["word"] = {"嶷"}},
    ["mogu"] = {["phrase"] = "蘑菇", ["word"] = {"摩", "磨"}},
    ["vgfa"] = {["phrase"] = "蒸发", ["word"] = {"拯"}},
    ["iumk"] = {["phrase"] = "出名", ["word"] = {"樗"}},
    ["jivj"] = {["phrase"] = "激战", ["word"] = {"笈"}},
    ["pmmk"] = {["phrase"] = "片名", ["word"] = {"骈"}},
    ["wujk"] = {["phrase"] = "武警", ["word"] = {"铻", "鼯"}},
    ["uiln"] = {["phrase"] = "史料", ["word"] = {"史"}},
    ["fjuf"] = {["phrase"] = "翻身", ["word"] = {"矾"}},
    ["yiiy"] = {["phrase"] = "乙醇", ["word"] = {"役", "蚁"}},
    ["pmhc"] = {["phrase"] = "偏好", ["word"] = {"扁"}},
    ["yicy"] = {["phrase"] = "一寸", ["word"] = {"荑"}},
    ["wumw"] = {["phrase"] = "妩媚", ["word"] = {"杌"}},
    ["hsds"] = {["phrase"] = "轰动", ["word"] = {"泓"}},
    ["xnmw"] = {["phrase"] = "小妹", ["word"] = {"骁"}},
    ["fuzc"] = {["phrase"] = "浮躁", ["word"] = {"跗"}},
    ["juzu"] = {["phrase"] = "剧组", ["word"] = {"遽"}},
    ["hxmu"] = {["phrase"] = "花木", ["word"] = {"桦", "骅"}},
    ["wuyr"] = {["phrase"] = "无缘", ["word"] = {"诬"}},
    ["jiee"] = {["phrase"] = "饥饿", ["word"] = {"觊"}},
    ["yjig"] = {["phrase"] = "盐城", ["word"] = {"魇"}},
    ["cjlm"] = {["phrase"] = "残联", ["word"] = {"粲"}},
    ["tofu"] = {["phrase"] = "托福", ["word"] = {"拓"}},
    ["jkvl"] = {["phrase"] = "精装", ["word"] = {"劲"}},
    ["uzbk"] = {["phrase"] = "手柄", ["word"] = {"兽"}},
    ["ybvg"] = {["phrase"] = "印证", ["word"] = {"龈"}},
    ["ddru"] = {["phrase"] = "带入", ["word"] = {"傣"}},
    ["fuiz"] = {["phrase"] = "复仇", ["word"] = {"蜉"}},
    ["xpye"] = {["phrase"] = "鞋业", ["word"] = {"邪"}},
    ["uuhu"] = {["phrase"] = "疏忽", ["word"] = {"秫", "黍"}},
    ["ujcy"] = {["phrase"] = "闪存", ["word"] = {"芟"}},
    ["ueii"] = {["phrase"] = "奢侈", ["word"] = {"厍"}},
    ["wwmw"] = {["phrase"] = "唯美", ["word"] = {"闱"}},
    ["wunw"] = {["phrase"] = "屋内", ["word"] = {"物", "妩"}},
    ["cvmm"] = {["phrase"] = "催眠", ["word"] = {"毳"}},
    ["anbm"] = {["phrase"] = "岸边", ["word"] = {"案"}},
    ["yjke"] = {["phrase"] = "眼科", ["word"] = {"郾"}},
    ["xiuj"] = {["phrase"] = "西山", ["word"] = {"豨"}},
    ["viuf"] = {["phrase"] = "之神", ["word"] = {"雉"}},
    ["vhmu"] = {["phrase"] = "账目", ["word"] = {"樟"}},
    ["vipd"] = {["phrase"] = "指派", ["word"] = {"制", "祗"}},
    ["viju"] = {["phrase"] = "之举", ["word"] = {"帙"}},
    ["yiru"] = {["phrase"] = "一如", ["word"] = {"佚"}},
    ["tsmk"] = {["phrase"] = "同名", ["word"] = {"桐"}},
    ["iidn"] = {["phrase"] = "吃掉", ["word"] = {"鸱"}},
    ["buvc"] = {["phrase"] = "不着", ["word"] = {"簿"}},
    ["ssds"] = {["phrase"] = "松动", ["word"] = {"凇", "淞"}},
    ["vzye"] = {["phrase"] = "昼夜", ["word"] = {"诌"}},
    ["lowf"] = {["phrase"] = "螺纹", ["word"] = {"雒"}},
    ["quii"] = {["phrase"] = "去吃", ["word"] = {"衢"}},
    ["iefw"] = {["phrase"] = "车费", ["word"] = {"撤"}},
    ["hjfg"] = {["phrase"] = "寒风", ["word"] = {"捍"}},
    ["vuzi"] = {["phrase"] = "竹子", ["word"] = {"躅"}},
    ["isvl"] = {["phrase"] = "重装", ["word"] = {"艟"}},
    ["uudc"] = {["phrase"] = "疏导", ["word"] = {"澍"}},
    ["zidk"] = {["phrase"] = "自定", ["word"] = {"咨"}},
    ["vudv"] = {["phrase"] = "主队", ["word"] = {"注", "洙"}},
    ["jiwj"] = {["phrase"] = "几万", ["word"] = {"玑"}},
    ["vibc"] = {["phrase"] = "质保", ["word"] = {"痔"}},
    ["jklo"] = {["phrase"] = "经络", ["word"] = {"靖"}},
    ["ykmm"] = {["phrase"] = "迎面", ["word"] = {"楹"}},
    ["huhu"] = {["phrase"] = "呼呼", ["word"] = {"戽"}},
    ["xihj"] = {["phrase"] = "西汉", ["word"] = {"稀", "烯"}},
    ["yziz"] = {["phrase"] = "忧愁", ["word"] = {"蝣"}},
    ["qmyz"] = {["phrase"] = "前有", ["word"] = {"谴"}},
    ["xuno"] = {["phrase"] = "许诺", ["word"] = {"婿"}},
    ["yjhj"] = {["phrase"] = "严寒", ["word"] = {"焰"}},
    ["jkxx"] = {["phrase"] = "井下", ["word"] = {"惊", "憬"}},
    ["lkds"] = {["phrase"] = "灵动", ["word"] = {"泠"}},
    ["hrdd"] = {["phrase"] = "还贷", ["word"] = {"涣", "奂"}},
    ["jicu"] = {["phrase"] = "急促", ["word"] = {"蒺"}},
    ["ihxm"] = {["phrase"] = "长线", ["word"] = {"氅"}},
    ["fwfw"] = {["phrase"] = "飞飞", ["word"] = {"斐"}},
    ["jqpa"] = {["phrase"] = "就怕", ["word"] = {"臼"}},
    ["jink"] = {["phrase"] = "济宁", ["word"] = {"犄"}},
    ["jldd"] = {["phrase"] = "将带", ["word"] = {"奖"}},
    ["monm"] = {["phrase"] = "末年", ["word"] = {"嬷"}},
    ["jbry"] = {["phrase"] = "浸润", ["word"] = {"仅"}},
    ["lkks"] = {["phrase"] = "凌空", ["word"] = {"呤", "囹"}},
    ["ichu"] = {["phrase"] = "巢湖", ["word"] = {"炒", "焯"}},
    ["yayy"] = {["phrase"] = "亚运", ["word"] = {"讶"}},
    ["xnkk"] = {["phrase"] = "小块", ["word"] = {"嚣"}},
    ["vimb"] = {["phrase"] = "殖民", ["word"] = {"枳"}},
    ["wwdo"] = {["phrase"] = "为多", ["word"] = {"洧", "渭"}},
    ["qpxn"] = {["phrase"] = "切削", ["word"] = {"慊"}},
    ["bmzc"] = {["phrase"] = "编造", ["word"] = {"遍"}},
    ["yjif"] = {["phrase"] = "烟尘", ["word"] = {"雁"}},
    ["mibi"] = {["phrase"] = "密闭", ["word"] = {"蜜"}},
    ["jiyt"] = {["phrase"] = "集约", ["word"] = {"畿"}},
    ["qimb"] = {["phrase"] = "器皿", ["word"] = {"棋", "骐"}},
    ["nikk"] = {["phrase"] = "你快", ["word"] = {"匿"}},
    ["yzyj"] = {["phrase"] = "油烟", ["word"] = {"羑"}},
    ["jujb"] = {["phrase"] = "距今", ["word"] = {"飓"}},
    ["jnuh"] = {["phrase"] = "脚上", ["word"] = {"礁"}},
    ["vuve"] = {["phrase"] = "住着", ["word"] = {"邾", "竺"}},
    ["izrf"] = {["phrase"] = "仇人", ["word"] = {"雠"}},
    ["jnyh"] = {["phrase"] = "教养", ["word"] = {"醮"}},
    ["ujye"] = {["phrase"] = "山野", ["word"] = {"讪", "鄯"}},
    ["jian"] = {["phrase"] = "吉安", ["word"] = {"棘"}},
    ["xpdi"] = {["phrase"] = "鞋底", ["word"] = {"蟹"}},
    ["xikj"] = {["phrase"] = "细看", ["word"] = {"吸", "唏"}},
    ["hetm"] = {["phrase"] = "和田", ["word"] = {"盍"}},
    ["yizy"] = {["phrase"] = "一尊", ["word"] = {"迤"}},
    ["hrbi"] = {["phrase"] = "环比", ["word"] = {"宦"}},
    ["xmnm"] = {["phrase"] = "现年", ["word"] = {"娴"}},
    ["wutk"] = {["phrase"] = "舞厅", ["word"] = {"圬"}},
    ["jidd"] = {["phrase"] = "几代", ["word"] = {"剞"}},
    ["jbso"] = {["phrase"] = "紧缩", ["word"] = {"缙"}},
    ["jucj"] = {["phrase"] = "聚餐", ["word"] = {"苣"}},
    ["guuu"] = {["phrase"] = "古树", ["word"] = {"辜"}},
    ["bojb"] = {["phrase"] = "铂金", ["word"] = {"钵", "铂"}},
    ["wwtn"] = {["phrase"] = "微调", ["word"] = {"畏"}},
    ["jisv"] = {["phrase"] = "脊髓", ["word"] = {"继"}},
    ["ihxk"] = {["phrase"] = "长兴", ["word"] = {"惝"}},
    ["yihx"] = {["phrase"] = "异化", ["word"] = {"移", "黟"}},
    ["yuyr"] = {["phrase"] = "余元", ["word"] = {"欤"}},
    ["yyls"] = {["phrase"] = "云龙", ["word"] = {"耘"}},
    ["lquu"] = {["phrase"] = "柳树", ["word"] = {"碌"}},
    ["xpyb"] = {["phrase"] = "谐音", ["word"] = {"谐"}},
    ["jigv"] = {["phrase"] = "机柜", ["word"] = {"既"}},
    ["volu"] = {["phrase"] = "着陆", ["word"] = {"卓"}},
    ["qidu"] = {["phrase"] = "气度", ["word"] = {"漆"}},
    ["gcyh"] = {["phrase"] = "羔羊", ["word"] = {"羔"}},
    ["hxru"] = {["phrase"] = "划入", ["word"] = {"华"}},
    ["jicd"] = {["phrase"] = "基材", ["word"] = {"蓟"}},
    ["liln"] = {["phrase"] = "理疗", ["word"] = {"鹂"}},
    ["xbju"] = {["phrase"] = "新居", ["word"] = {"锌"}},
    ["yure"] = {["phrase"] = "预热", ["word"] = {"觎"}},
    ["qlji"] = {["phrase"] = "羟基", ["word"] = {"镪"}},
    ["ujhd"] = {["phrase"] = "山海", ["word"] = {"剡"}},
    ["xipd"] = {["phrase"] = "洗牌", ["word"] = {"夕", "奚", "禊"}},
    ["fusd"] = {["phrase"] = "复赛", ["word"] = {"绂"}},
    ["hudu"] = {["phrase"] = "弧度", ["word"] = {"户", "斛"}},
    ["xpmc"] = {["phrase"] = "鞋帽", ["word"] = {"械", "榭"}},
    ["erde"] = {["phrase"] = "尔德", ["word"] = {"洱"}},
    ["bagd"] = {["phrase"] = "把该", ["word"] = {"魃"}},
    ["tjta"] = {["phrase"] = "坍塌", ["word"] = {"坦"}},
    ["tibn"] = {["phrase"] = "体表", ["word"] = {"鹈"}},
    ["vjmk"] = {["phrase"] = "站名", ["word"] = {"毡", "粘"}},
    ["xmzz"] = {["phrase"] = "先走", ["word"] = {"跹"}},
    ["xixx"] = {["phrase"] = "西夏", ["word"] = {"恓"}},
    ["jqbj"] = {["phrase"] = "旧版", ["word"] = {"究", "疚"}},
    ["xidj"] = {["phrase"] = "西单", ["word"] = {"浠", "淅"}},
    ["yjdd"] = {["phrase"] = "眼袋", ["word"] = {"淹", "奄"}},
    ["xnvs"] = {["phrase"] = "消肿", ["word"] = {"箫"}},
    ["qkuf"] = {["phrase"] = "情深", ["word"] = {"罄"}},
    ["hvcs"] = {["phrase"] = "慧聪", ["word"] = {"荟"}},
    ["bcvs"] = {["phrase"] = "包中", ["word"] = {"龅"}},
    ["jido"] = {["phrase"] = "几多", ["word"] = {"脊"}},
    ["qicj"] = {["phrase"] = "凄惨", ["word"] = {"芑", "蕲"}},
    ["qmjq"] = {["phrase"] = "迁就", ["word"] = {"钎"}},
    ["bwuj"] = {["phrase"] = "被删", ["word"] = {"鐾"}},
    ["dumo"] = {["phrase"] = "镀膜", ["word"] = {"阇"}},
    ["uiru"] = {["phrase"] = "驶入", ["word"] = {"什", "仕"}},
    ["vizu"] = {["phrase"] = "知足", ["word"] = {"跖"}},
    ["yjmd"] = {["phrase"] = "掩埋", ["word"] = {"阉", "阏"}},
    ["xnds"] = {["phrase"] = "晓东", ["word"] = {"潇"}},
    ["tixp"] = {["phrase"] = "题写", ["word"] = {"悌"}},
    ["tvhz"] = {["phrase"] = "退后", ["word"] = {"煺"}},
    ["hvds"] = {["phrase"] = "挥动", ["word"] = {"浍"}},
    ["jbma"] = {["phrase"] = "金马", ["word"] = {"槿"}},
    ["qmbu"] = {["phrase"] = "前部", ["word"] = {"搴"}},
    ["jpyk"] = {["phrase"] = "接应", ["word"] = {"诘"}},
    ["jidk"] = {["phrase"] = "既定", ["word"] = {"奇"}},
    ["gsbk"] = {["phrase"] = "工兵", ["word"] = {"宫"}},
    ["jitj"] = {["phrase"] = "祭坛", ["word"] = {"圾"}},
    ["svuu"] = {["phrase"] = "岁数", ["word"] = {"尿", "碎"}},
    ["visu"] = {["phrase"] = "质素", ["word"] = {"纸"}},
    ["gujk"] = {["phrase"] = "古井", ["word"] = {"钴", "锢"}},
    ["yiku"] = {["phrase"] = "衣裤", ["word"] = {"医"}},
    ["biuu"] = {["phrase"] = "避暑", ["word"] = {"辟"}},
    ["gojy"] = {["phrase"] = "国君", ["word"] = {"帼"}},
    ["fukf"] = {["phrase"] = "复垦", ["word"] = {"呋"}},
    ["qise"] = {["phrase"] = "起色", ["word"] = {"缉"}},
    ["vjmj"] = {["phrase"] = "沾满", ["word"] = {"栈"}},
    ["xiuh"] = {["phrase"] = "席上", ["word"] = {"熹"}},
    ["yucy"] = {["phrase"] = "渔村", ["word"] = {"芋", "萸"}},
    ["lidm"] = {["phrase"] = "离店", ["word"] = {"溧"}},
    ["kdjb"] = {["phrase"] = "开进", ["word"] = {"锴"}},
    ["jisj"] = {["phrase"] = "集散", ["word"] = {"级", "纪"}},
    ["siks"] = {["phrase"] = "司空", ["word"] = {"咝"}},
    ["lmdz"] = {["phrase"] = "脸都", ["word"] = {"涟"}},
    ["lqjp"] = {["phrase"] = "六届", ["word"] = {"镠"}},
    ["pudc"] = {["phrase"] = "扑到", ["word"] = {"溥"}},
    ["qmdo"] = {["phrase"] = "千多", ["word"] = {"潜"}},
    ["eraa"] = {["phrase"] = "儿啊", ["word"] = {"二", "耳"}},
    ["jxlm"] = {["phrase"] = "价廉", ["word"] = {"驾", "架"}},
    ["jiyj"] = {["phrase"] = "几眼", ["word"] = {"讥", "记"}},
    ["vafa"] = {["phrase"] = "闸阀", ["word"] = {"揸"}},
    ["ueqk"] = {["phrase"] = "社情", ["word"] = {"舌", "猞"}},
    ["jldu"] = {["phrase"] = "江都", ["word"] = {"浆"}},
    ["xiux"] = {["phrase"] = "洗刷", ["word"] = {"硒"}},
    ["yiyk"] = {["phrase"] = "亦应", ["word"] = {"诒"}},
    ["djba"] = {["phrase"] = "丹巴", ["word"] = {"疸"}},
    ["jmci"] = {["phrase"] = "见此", ["word"] = {"茧"}},
    ["pcds"] = {["phrase"] = "跑动", ["word"] = {"泡", "匏"}},
    ["wubk"] = {["phrase"] = "无病", ["word"] = {"痦", "寤"}},
    ["lkys"] = {["phrase"] = "领用", ["word"] = {"羚", "零"}},
    ["xnkz"] = {["phrase"] = "小口", ["word"] = {"哮"}},
    ["uivr"] = {["phrase"] = "师专", ["word"] = {"筮"}},
    ["xldo"] = {["phrase"] = "想多", ["word"] = {"湘"}},
    ["jmdd"] = {["phrase"] = "肩带", ["word"] = {"湔"}},
    ["vifw"] = {["phrase"] = "直飞", ["word"] = {"执"}},
    ["mmdd"] = {["phrase"] = "面带", ["word"] = {"渑"}},
    ["luvu"] = {["phrase"] = "露珠", ["word"] = {"舻", "箓"}},
    ["jbdy"] = {["phrase"] = "金盾", ["word"] = {"津", "浸"}},
    ["ssys"] = {["phrase"] = "怂恿", ["word"] = {"讼"}},
    ["cibn"] = {["phrase"] = "此表", ["word"] = {"鹚"}},
    ["gcjk"] = {["phrase"] = "告警", ["word"] = {"镐", "锆"}},
    ["yhiy"] = {["phrase"] = "阳春", ["word"] = {"徉", "蛘"}},
    ["yjwh"] = {["phrase"] = "阎王", ["word"] = {"琰"}},
    ["fupd"] = {["phrase"] = "复牌", ["word"] = {"祓"}},
    ["hvyh"] = {["phrase"] = "惠阳", ["word"] = {"诙"}},
    ["mige"] = {["phrase"] = "米格", ["word"] = {"弭"}},
    ["lida"] = {["phrase"] = "利达", ["word"] = {"澧"}},
    ["bwle"] = {["phrase"] = "背了", ["word"] = {"邶"}},
    ["fuhz"] = {["phrase"] = "附后", ["word"] = {"稃"}},
    ["jmlt"] = {["phrase"] = "鉴略", ["word"] = {"坚"}},
    ["duvs"] = {["phrase"] = "杜仲", ["word"] = {"厾"}},
    ["qizd"] = {["phrase"] = "骑在", ["word"] = {"蹊"}},
    ["tomo"] = {["phrase"] = "唾沫", ["word"] = {"椭"}},
    ["xpdm"] = {["phrase"] = "鞋垫", ["word"] = {"渫"}},
    ["yuwd"] = {["phrase"] = "域外", ["word"] = {"玉", "瑜"}},
    ["yjvz"] = {["phrase"] = "兖州", ["word"] = {"筵"}},
    ["yyer"] = {["phrase"] = "云儿", ["word"] = {"陨"}},
    ["xlyy"] = {["phrase"] = "祥云", ["word"] = {"详"}},
    ["yjmk"] = {["phrase"] = "严明", ["word"] = {"檐"}},
    ["hctu"] = {["phrase"] = "好图", ["word"] = {"壕"}},
    ["ihxi"] = {["phrase"] = "唱戏", ["word"] = {"怅"}},
    ["lmda"] = {["phrase"] = "联大", ["word"] = {"殓"}},
    ["furc"] = {["phrase"] = "富饶", ["word"] = {"付", "俯", "傅"}},
    ["yugl"] = {["phrase"] = "余光", ["word"] = {"鬻"}},
    ["bibu"] = {["phrase"] = "必不", ["word"] = {"毕"}},
    ["bizu"] = {["phrase"] = "鼻祖", ["word"] = {"避", "跸"}},
    ["uifg"] = {["phrase"] = "适逢", ["word"] = {"拭"}},
    ["mobd"] = {["phrase"] = "膜拜", ["word"] = {"寞", "瘼"}},
    ["zczo"] = {["phrase"] = "造作", ["word"] = {"遭"}},
    ["hjgr"] = {["phrase"] = "焊管", ["word"] = {"顸"}},
    ["bduu"] = {["phrase"] = "柏树", ["word"] = {"掰"}},
    ["gzbk"] = {["phrase"] = "诟病", ["word"] = {"句"}},
    ["bidw"] = {["phrase"] = "必得", ["word"] = {"敝"}},
    ["jinu"] = {["phrase"] = "激怒", ["word"] = {"嫉"}},
    ["yudd"] = {["phrase"] = "玉带", ["word"] = {"淤", "渝"}},
    ["yrfu"] = {["phrase"] = "远赴", ["word"] = {"掾"}},
    ["dsxk"] = {["phrase"] = "东兴", ["word"] = {"恫"}},
    ["xyyh"] = {["phrase"] = "驯养", ["word"] = {"醺"}},
    ["tuuo"] = {["phrase"] = "图说", ["word"] = {"屠"}},
    ["iaka"] = {["phrase"] = "插卡", ["word"] = {"喳"}},
    ["uiuj"] = {["phrase"] = "石山", ["word"] = {"饰"}},
    ["jxly"] = {["phrase"] = "加仑", ["word"] = {"袈"}},
    ["yiyy"] = {["phrase"] = "意蕴", ["word"] = {"议"}},
    ["hckk"] = {["phrase"] = "好快", ["word"] = {"嚆"}},
    ["jimb"] = {["phrase"] = "机敏", ["word"] = {"骥"}},
    ["qmdj"] = {["phrase"] = "签单", ["word"] = {"浅"}},
    ["jkle"] = {["phrase"] = "静了", ["word"] = {"竞", "竟"}},
    ["miyz"] = {["phrase"] = "密友", ["word"] = {"谜", "醚"}},
    ["qipb"] = {["phrase"] = "七品", ["word"] = {"祺"}},
    ["huhh"] = {["phrase"] = "护航", ["word"] = {"烀"}},
    ["xyzu"] = {["phrase"] = "寻租", ["word"] = {"迅"}},
    ["iude"] = {["phrase"] = "处得", ["word"] = {"刍"}},
    ["pibu"] = {["phrase"] = "坯布", ["word"] = {"癖"}},
    ["ljmj"] = {["phrase"] = "烂漫", ["word"] = {"阑"}},
    ["yjyy"] = {["phrase"] = "烟云", ["word"] = {"酽"}},
    ["klke"] = {["phrase"] = "旷课", ["word"] = {"贶"}},
    ["yuda"] = {["phrase"] = "愈大", ["word"] = {"鱼", "渔"}},
    ["tjff"] = {["phrase"] = "碳粉", ["word"] = {"摊"}},
    ["qnmm"] = {["phrase"] = "桥面", ["word"] = {"橇"}},
    ["kdmj"] = {["phrase"] = "开满", ["word"] = {"闿"}},
    ["fugr"] = {["phrase"] = "副官", ["word"] = {"腐"}},
    ["lumh"] = {["phrase"] = "鲁莽", ["word"] = {"驴"}},
    ["xydc"] = {["phrase"] = "寻到", ["word"] = {"浔"}},
    ["uzbc"] = {["phrase"] = "收报", ["word"] = {"守"}},
    ["liul"] = {["phrase"] = "李爽", ["word"] = {"砾"}},
    ["yuhd"] = {["phrase"] = "遇害", ["word"] = {"燠"}},
    ["ujmc"] = {["phrase"] = "山猫", ["word"] = {"栅"}},
    ["tomb"] = {["phrase"] = "脱敏", ["word"] = {"驼", "柁"}},
    ["fuif"] = {["phrase"] = "浮沉", ["word"] = {"辅", "蚨"}},
    ["djdk"] = {["phrase"] = "淡定", ["word"] = {"澹"}},
    ["ycpd"] = {["phrase"] = "要拍", ["word"] = {"夭"}},
    ["vihu"] = {["phrase"] = "支护", ["word"] = {"秩"}},
    ["uudu"] = {["phrase"] = "熟读", ["word"] = {"沭"}},
    ["fjmf"] = {["phrase"] = "烦闷", ["word"] = {"梵"}},
    ["uhxy"] = {["phrase"] = "上旬", ["word"] = {"裳"}},
    ["hupk"] = {["phrase"] = "互评", ["word"] = {"祜"}},
    ["grdk"] = {["phrase"] = "灌顶", ["word"] = {"涫"}},
    ["huwj"] = {["phrase"] = "护腕", ["word"] = {"琥"}},
    ["gomg"] = {["phrase"] = "过猛", ["word"] = {"粿"}},
    ["yjue"] = {["phrase"] = "衍射", ["word"] = {"砚"}},
    ["sikk"] = {["phrase"] = "四块", ["word"] = {"嗣"}},
    ["xmuj"] = {["phrase"] = "仙山", ["word"] = {"馅"}},
    ["lqdd"] = {["phrase"] = "留待", ["word"] = {"浏"}},
    ["ujdo"] = {["phrase"] = "闪躲", ["word"] = {"潸"}},
    ["tikr"] = {["phrase"] = "提款", ["word"] = {"嚏"}},
    ["lmjn"] = {["phrase"] = "炼焦", ["word"] = {"镰"}},
    ["ujhx"] = {["phrase"] = "山花", ["word"] = {"扇", "煽"}},
    ["bjbw"] = {["phrase"] = "半杯", ["word"] = {"癍"}},
    ["bmlu"] = {["phrase"] = "边路", ["word"] = {"辨", "辩", "辫"}},
    ["lqdj"] = {["phrase"] = "刘丹", ["word"] = {"鎏"}},
    ["hdkk"] = {["phrase"] = "还快", ["word"] = {"嗐"}},
    ["vjdk"] = {["phrase"] = "站定", ["word"] = {"沾", "詹"}},
    ["bczu"] = {["phrase"] = "包租", ["word"] = {"趵"}},
    ["tdfu"] = {["phrase"] = "太傅", ["word"] = {"泰"}},
    ["lrwu"] = {["phrase"] = "乱舞", ["word"] = {"挛"}},
    ["ykke"] = {["phrase"] = "迎客", ["word"] = {"郢"}},
    ["jmve"] = {["phrase"] = "见者", ["word"] = {"舰", "笕"}},
    ["ytka"] = {["phrase"] = "月卡", ["word"] = {"曰", "月"}},
    ["livl"] = {["phrase"] = "粒状", ["word"] = {"笠"}},
    ["yiuk"] = {["phrase"] = "一甩", ["word"] = {"饴"}},
    ["iivi"] = {["phrase"] = "迟滞", ["word"] = {"蚩"}},
    ["jkfu"] = {["phrase"] = "警服", ["word"] = {"旌"}},
    ["jigj"] = {["phrase"] = "肌酐", ["word"] = {"麂"}},
    ["xkxu"] = {["phrase"] = "兴许", ["word"] = {"性", "惺"}},
    ["wwyc"] = {["phrase"] = "卫药", ["word"] = {"霨"}},
    ["sitc"] = {["phrase"] = "四套", ["word"] = {"寺"}},
    ["jnbw"] = {["phrase"] = "脚背", ["word"] = {"敫"}},
    ["wwkf"] = {["phrase"] = "围垦", ["word"] = {"唯"}},
    ["bidc"] = {["phrase"] = "逼到", ["word"] = {"弊"}},
    ["hemm"] = {["phrase"] = "河面", ["word"] = {"阖"}},
    ["rudk"] = {["phrase"] = "入定", ["word"] = {"洳"}},
    ["keiu"] = {["phrase"] = "可出", ["word"] = {"蝌"}},
    ["ruce"] = {["phrase"] = "如厕", ["word"] = {"薷"}},
    ["luhx"] = {["phrase"] = "芦花", ["word"] = {"虑"}},
    ["bpda"] = {["phrase"] = "别打", ["word"] = {"鳖"}},
    ["mwve"] = {["phrase"] = "没辙", ["word"] = {"郿"}},
    ["yuid"] = {["phrase"] = "玉柴", ["word"] = {"蝓"}},
    ["licu"] = {["phrase"] = "力促", ["word"] = {"藜"}},
    ["djvl"] = {["phrase"] = "淡妆", ["word"] = {"箪"}},
    ["dojl"] = {["phrase"] = "多讲", ["word"] = {"铎"}},
    ["tcdd"] = {["phrase"] = "套袋", ["word"] = {"洮"}},
    ["qipu"] = {["phrase"] = "棋谱", ["word"] = {"祇"}},
    ["siij"] = {["phrase"] = "私产", ["word"] = {"蛳", "厮"}},
    ["jbrv"] = {["phrase"] = "金瑞", ["word"] = {"今"}},
    ["xikh"] = {["phrase"] = "西康", ["word"] = {"熙"}},
    ["yuhl"] = {["phrase"] = "玉皇", ["word"] = {"煜"}},
    ["fudk"] = {["phrase"] = "福鼎", ["word"] = {"涪"}},
    ["bjww"] = {["phrase"] = "班委", ["word"] = {"班", "斑"}},
    ["wuan"] = {["phrase"] = "武安", ["word"] = {"鹉"}},
    ["rudc"] = {["phrase"] = "入道", ["word"] = {"溽"}},
    ["xipk"] = {["phrase"] = "西平", ["word"] = {"禧"}},
    ["bouu"] = {["phrase"] = "波束", ["word"] = {"擘"}},
    ["jbvl"] = {["phrase"] = "金装", ["word"] = {"劲", "筋"}},
    ["yzjy"] = {["phrase"] = "友军", ["word"] = {"铀", "鼬"}},
    ["xmce"] = {["phrase"] = "献策", ["word"] = {"苋"}},
    ["biuy"] = {["phrase"] = "笔顺", ["word"] = {"璧", "襞"}},
    ["yzla"] = {["phrase"] = "又拉", ["word"] = {"由", "卣"}},
    ["xpdn"] = {["phrase"] = "卸掉", ["word"] = {"解", "澥"}},
    ["sodu"] = {["phrase"] = "所读", ["word"] = {"挲"}},
    ["fuda"] = {["phrase"] = "福大", ["word"] = {"滏"}},
    ["kedm"] = {["phrase"] = "客店", ["word"] = {"溘"}},
    ["yzro"] = {["phrase"] = "有若", ["word"] = {"侑"}},
    ["wunk"] = {["phrase"] = "武宁", ["word"] = {"牾"}},
    ["hcdu"] = {["phrase"] = "豪赌", ["word"] = {"濠"}},
    ["limw"] = {["phrase"] = "李梅", ["word"] = {"粝"}},
    ["jnil"] = {["phrase"] = "叫床", ["word"] = {"轿"}},
    ["ucvo"] = {["phrase"] = "烧灼", ["word"] = {"筲", "艄"}},
    ["tckd"] = {["phrase"] = "逃开", ["word"] = {"叨"}},
    ["uhxr"] = {["phrase"] = "上选", ["word"] = {"赏"}},
    ["jkdg"] = {["phrase"] = "警灯", ["word"] = {"泾"}},
    ["hzru"] = {["phrase"] = "后入", ["word"] = {"侯", "候"}},
    ["xige"] = {["phrase"] = "洗个", ["word"] = {"觋"}},
    ["gjmw"] = {["phrase"] = "甘美", ["word"] = {"橄"}},
    ["ysdy"] = {["phrase"] = "拥趸", ["word"] = {"泳", "涌"}},
    ["jumk"] = {["phrase"] = "剧名", ["word"] = {"驹", "橘", "枸", "椐"}},
    ["jmma"] = {["phrase"] = "见吗", ["word"] = {"检"}},
    ["iitn"] = {["phrase"] = "齿条", ["word"] = {"墀"}},
    ["tjju"] = {["phrase"] = "炭疽", ["word"] = {"镡"}},
    ["gudg"] = {["phrase"] = "孤灯", ["word"] = {"觚"}},
    ["libw"] = {["phrase"] = "立碑", ["word"] = {"疠"}},
    ["jxjr"] = {["phrase"] = "家眷", ["word"] = {"颊"}},
    ["jmuj"] = {["phrase"] = "尖山", ["word"] = {"饯"}},
    ["ditd"] = {["phrase"] = "地台", ["word"] = {"坻"}},
    ["dcpc"] = {["phrase"] = "道袍", ["word"] = {"祷"}},
    ["yiky"] = {["phrase"] = "一捆", ["word"] = {"匜", "咦", "咿"}},
    ["yjir"] = {["phrase"] = "言传", ["word"] = {"颜", "赝"}},
    ["iumw"] = {["phrase"] = "触媒", ["word"] = {"杵"}},
    ["bwuk"] = {["phrase"] = "被甩", ["word"] = {"碚"}},
    ["hvkh"] = {["phrase"] = "惠康", ["word"] = {"咴"}},
    ["jxll"] = {["phrase"] = "加量", ["word"] = {"甲"}},
    ["lldg"] = {["phrase"] = "亮灯", ["word"] = {"良"}},
    ["yuyk"] = {["phrase"] = "育英", ["word"] = {"语", "雩"}},
    ["ifyj"] = {["phrase"] = "陈言", ["word"] = {"谶"}},
    ["luln"] = {["phrase"] = "炉料", ["word"] = {"鸬"}},
    ["sivv"] = {["phrase"] = "丝锥", ["word"] = {"巳"}},
    ["tmdk"] = {["phrase"] = "天顶", ["word"] = {"湉"}},
    ["qian"] = {["phrase"] = "奇案", ["word"] = {"妻"}},
    ["gjdg"] = {["phrase"] = "干等", ["word"] = {"泔"}},
    ["fuff"] = {["phrase"] = "福分", ["word"] = {"扶", "拂", "麸"}},
    ["vhju"] = {["phrase"] = "章句", ["word"] = {"幛"}},
    ["ycxx"] = {["phrase"] = "咬下", ["word"] = {"爻"}},
    ["hedn"] = {["phrase"] = "喝掉", ["word"] = {"鹤"}},
    ["ighw"] = {["phrase"] = "呈黑", ["word"] = {"程"}},
    ["modd"] = {["phrase"] = "末代", ["word"] = {"漠"}},
    ["nper"] = {["phrase"] = "聂耳", ["word"] = {"颞"}},
    ["uikr"] = {["phrase"] = "十款", ["word"] = {"噬"}},
    ["uiyb"] = {["phrase"] = "石印", ["word"] = {"识"}},
    ["dgvj"] = {["phrase"] = "灯盏", ["word"] = {"凳"}},
    ["jxcj"] = {["phrase"] = "加餐", ["word"] = {"荚"}},
    ["hcku"] = {["phrase"] = "好酷", ["word"] = {"嚎", "嗥"}},
    ["jise"] = {["phrase"] = "基色", ["word"] = {"缉"}},
    ["yriy"] = {["phrase"] = "元春", ["word"] = {"辕"}},
    ["dumd"] = {["phrase"] = "督脉", ["word"] = {"椟"}},
    ["jimj"] = {["phrase"] = "挤满", ["word"] = {"机", "极"}},
    ["jmlj"] = {["phrase"] = "剑兰", ["word"] = {"鉴"}},
    ["ijyj"] = {["phrase"] = "谗言", ["word"] = {"谄"}},
    ["qidn"] = {["phrase"] = "起吊", ["word"] = {"凄"}},
    ["yikv"] = {["phrase"] = "一窥", ["word"] = {"呓"}},
    ["yzye"] = {["phrase"] = "油液", ["word"] = {"邮"}},
    ["wwen"] = {["phrase"] = "韦恩", ["word"] = {"隈"}},
    ["jmdo"] = {["phrase"] = "见多", ["word"] = {"涧"}},
    ["lumk"] = {["phrase"] = "鹿鸣", ["word"] = {"闾", "榈"}},
    ["qmcc"] = {["phrase"] = "浅草", ["word"] = {"荨"}},
    ["yrta"] = {["phrase"] = "愿他", ["word"] = {"垣"}},
    ["viph"] = {["phrase"] = "之旁", ["word"] = {"炙"}},
    ["ucdo"] = {["phrase"] = "稍多", ["word"] = {"潲"}},
    ["wupg"] = {["phrase"] = "吴鹏", ["word"] = {"午"}},
    ["uuwd"] = {["phrase"] = "书外", ["word"] = {"戍"}},
    ["pnxx"] = {["phrase"] = "飘下", ["word"] = {"票", "飘"}},
    ["qicu"] = {["phrase"] = "气促", ["word"] = {"芪"}},
    ["juxb"] = {["phrase"] = "居心", ["word"] = {"惧"}},
    ["jxbk"] = {["phrase"] = "甲兵", ["word"] = {"痂"}},
    ["vidj"] = {["phrase"] = "制单", ["word"] = {"滞"}},
    ["iipj"] = {["phrase"] = "池畔", ["word"] = {"褫"}},
    ["yuyy"] = {["phrase"] = "语云", ["word"] = {"谀"}},
    ["yree"] = {["phrase"] = "员额", ["word"] = {"元", "院"}},
    ["jiuj"] = {["phrase"] = "积善", ["word"] = {"饥", "矶"}},
    ["yedk"] = {["phrase"] = "也定", ["word"] = {"冶"}},
    ["hjge"] = {["phrase"] = "焊割", ["word"] = {"邗", "邯"}},
    ["yuxk"] = {["phrase"] = "欲行", ["word"] = {"誉"}},
    ["tjtd"] = {["phrase"] = "澹台", ["word"] = {"坍"}},
    ["vuky"] = {["phrase"] = "助困", ["word"] = {"嘱"}},
    ["magu"] = {["phrase"] = "麻姑", ["word"] = {"摩"}},
    ["ybkl"] = {["phrase"] = "银矿", ["word"] = {"吲"}},
    ["ufdv"] = {["phrase"] = "神对", ["word"] = {"沈"}},
    ["guyk"] = {["phrase"] = "孤影", ["word"] = {"诂", "酤"}},
    ["yjiz"] = {["phrase"] = "眼瞅", ["word"] = {"蜒"}},
    ["subu"] = {["phrase"] = "素不", ["word"] = {"窣"}},
    ["tokd"] = {["phrase"] = "脱开", ["word"] = {"鼍"}},
    ["jibo"] = {["phrase"] = "极薄", ["word"] = {"瘠"}},
    ["djkh"] = {["phrase"] = "单抗", ["word"] = {"啖", "赕"}},
    ["voyu"] = {["phrase"] = "捉鱼", ["word"] = {"酌"}},
    ["yyxi"] = {["phrase"] = "云溪", ["word"] = {"恽"}},
    ["xpuo"] = {["phrase"] = "邪说", ["word"] = {"屑"}},
    ["lisf"] = {["phrase"] = "李森", ["word"] = {"罹"}},
    ["pudu"] = {["phrase"] = "普度", ["word"] = {"瀑"}},
    ["jldm"] = {["phrase"] = "讲点", ["word"] = {"桨"}},
    ["ufnn"] = {["phrase"] = "神鸟", ["word"] = {"娠"}},
    ["lugh"] = {["phrase"] = "鹿港", ["word"] = {"庐"}},
    ["yuia"] = {["phrase"] = "鱼叉", ["word"] = {"蜮"}},
    ["xmmn"] = {["phrase"] = "线描", ["word"] = {"鹇"}},
    ["lihu"] = {["phrase"] = "立户", ["word"] = {"黎"}},
    ["vumo"] = {["phrase"] = "铸模", ["word"] = {"槠"}},
    ["jqfa"] = {["phrase"] = "旧法", ["word"] = {"韭"}},
    ["lumu"] = {["phrase"] = "卢姆", ["word"] = {"栌"}},
    ["qiao"] = {["phrase"] = "奇奥", ["word"] = {"鳍"}},
    ["ffdd"] = {["phrase"] = "粉黛", ["word"] = {"汾"}},
    ["jpuf"] = {["phrase"] = "洁身", ["word"] = {"截"}},
    ["qitj"] = {["phrase"] = "棋坛", ["word"] = {"起", "圻"}},
    -- ["uico"] = {["phrase"] = "失措", ["word"] = {"蓍"}},
    -- ["ybdd"] = {["phrase"] = "音带", ["word"] = {"洇"}},
    -- ["jujk"] = {["phrase"] = "巨鲸", ["word"] = {"锯", "锔"}},
    -- ["ybbo"] = {["phrase"] = "音波", ["word"] = {"窨"}},
    -- ["xblr"] = {["phrase"] = "心乱", ["word"] = {"歆"}},
    -- ["qijr"] = {["phrase"] = "七卷", ["word"] = {"颀"}},
    -- ["jmzz"] = {["phrase"] = "捡走", ["word"] = {"踺"}},
    -- ["ghfg"] = {["phrase"] = "罡风", ["word"] = {"扛", "缸"}},
    -- ["wwao"] = {["phrase"] = "维奥", ["word"] = {"鲔"}},
    -- ["ximw"] = {["phrase"] = "洗煤", ["word"] = {"檄"}},
    -- ["xmie"] = {["phrase"] = "闲扯", ["word"] = {"蚬"}},
    -- ["furz"] = {["phrase"] = "腐肉", ["word"] = {"俘"}},
    -- ["bwlo"] = {["phrase"] = "贝罗", ["word"] = {"背"}},
    -- ["ykbn"] = {["phrase"] = "应标", ["word"] = {"瘿"}},
    -- ["jika"] = {["phrase"] = "集卡", ["word"] = {"戢"}},
    -- ["dmbd"] = {["phrase"] = "电白", ["word"] = {"奠"}},
    -- ["uumc"] = {["phrase"] = "梳毛", ["word"] = {"树"}},
    -- ["somu"] = {["phrase"] = "索姆", ["word"] = {"桫"}},
    -- ["hvxm"] = {["phrase"] = "徽县", ["word"] = {"悔"}},
    -- ["yell"] = {["phrase"] = "液量", ["word"] = {"野"}},
    -- ["qnuf"] = {["phrase"] = "桥身", ["word"] = {"雀"}},
    -- ["bigg"] = {["phrase"] = "笔耕", ["word"] = {"弼"}},
    -- ["vfju"] = {["phrase"] = "针具", ["word"] = {"针"}},
    -- ["wwqn"] = {["phrase"] = "危桥", ["word"] = {"猥"}},
    -- ["fupj"] = {["phrase"] = "复盘", ["word"] = {"凫"}},
    -- ["jbya"] = {["phrase"] = "金牙", ["word"] = {"谨"}},
    -- ["yuuy"] = {["phrase"] = "虞舜", ["word"] = {"饫"}},
    -- ["nsdn"] = {["phrase"] = "弄掉", ["word"] = {"农", "浓"}},
    -- ["lkmw"] = {["phrase"] = "菱镁", ["word"] = {"棱"}},
    -- ["jpul"] = {["phrase"] = "结霜", ["word"] = {"劼"}},
    -- ["qqrj"] = {["phrase"] = "虬髯", ["word"] = {"仇"}},
    -- ["xndo"] = {["phrase"] = "小朵", ["word"] = {"消", "淆"}},
    -- ["piku"] = {["phrase"] = "皮裤", ["word"] = {"啤", "噼"}},
    -- ["thxm"] = {["phrase"] = "唐县", ["word"] = {"棠"}},
    -- ["sids"] = {["phrase"] = "四栋", ["word"] = {"汜"}},
    -- ["qlpi"] = {["phrase"] = "墙皮", ["word"] = {"襁"}},
    -- ["dimd"] = {["phrase"] = "地脉", ["word"] = {"柢"}},
    -- ["yiux"] = {["phrase"] = "一刷", ["word"] = {"懿"}},
    -- ["mcce"] = {["phrase"] = "茅厕", ["word"] = {"茆"}},
    -- ["jmzj"] = {["phrase"] = "坚赞", ["word"] = {"践"}},
    -- ["jpil"] = {["phrase"] = "疥疮", ["word"] = {"蚧"}},
    -- ["yjhh"] = {["phrase"] = "雁行", ["word"] = {"炎", "焱"}},
    -- ["duke"] = {["phrase"] = "赌客", ["word"] = {"嘟"}},
    -- ["yupd"] = {["phrase"] = "鱼排", ["word"] = {"禹"}},
    -- ["jkmg"] = {["phrase"] = "惊梦", ["word"] = {"粳"}},
    -- ["migx"] = {["phrase"] = "蜜瓜", ["word"] = {"弥", "縻"}},
    -- ["pwyk"] = {["phrase"] = "培英", ["word"] = {"醅"}},
    -- ["vucv"] = {["phrase"] = "珠翠", ["word"] = {"茱"}},
    -- ["gekl"] = {["phrase"] = "铬矿", ["word"] = {"嗝"}},
    -- ["vumd"] = {["phrase"] = "主脉", ["word"] = {"术"}},
    -- ["gsgw"] = {["phrase"] = "供给", ["word"] = {"攻"}},
    -- ["bivu"] = {["phrase"] = "闭住", ["word"] = {"筚"}},
    -- ["gzmk"] = {["phrase"] = "狗命", ["word"] = {"枸"}},
    -- ["yziy"] = {["phrase"] = "游春", ["word"] = {"蚰"}},
    -- ["hsig"] = {["phrase"] = "红橙", ["word"] = {"虹"}},
    -- ["uumd"] = {["phrase"] = "赎买", ["word"] = {"术"}},
    -- ["hvdr"] = {["phrase"] = "会断", ["word"] = {"溃"}},
    -- ["xkkd"] = {["phrase"] = "行楷", ["word"] = {"刑"}},
    -- ["xiur"] = {["phrase"] = "洗涮", ["word"] = {"屣"}},
    -- ["uudv"] = {["phrase"] = "属对", ["word"] = {"殊"}},
    -- ["idvc"] = {["phrase"] = "拆招", ["word"] = {"豺"}},
    -- ["ihri"] = {["phrase"] = "长日", ["word"] = {"伥"}},
    -- ["yrke"] = {["phrase"] = "远客", ["word"] = {"园"}},
    -- ["jpmk"] = {["phrase"] = "街名", ["word"] = {"桔"}},
    -- ["yikx"] = {["phrase"] = "一跨", ["word"] = {"噫", "翳"}},
    -- ["xkxb"] = {["phrase"] = "型芯", ["word"] = {"兴"}},
    -- ["xiij"] = {["phrase"] = "析产", ["word"] = {"蜥"}},
    -- ["fukc"] = {["phrase"] = "赴考", ["word"] = {"咐", "赙"}},
    -- ["hodr"] = {["phrase"] = "祸端", ["word"] = {"火"}},
    -- ["yrdy"] = {["phrase"] = "远遁", ["word"] = {"湲"}},
    -- ["dnkd"] = {["phrase"] = "调开", ["word"] = {"叼"}},
    -- ["zimz"] = {["phrase"] = "自谋", ["word"] = {"籽"}},
    -- ["ybcd"] = {["phrase"] = "因材", ["word"] = {"茵"}},
    -- ["yupn"] = {["phrase"] = "鱼漂", ["word"] = {"臾"}},
    -- ["jyye"] = {["phrase"] = "菌液", ["word"] = {"郡"}},
    -- ["jivo"] = {["phrase"] = "几桌", ["word"] = {"籍"}},
    -- ["dkkr"] = {["phrase"] = "顶宽", ["word"] = {"啶"}},
    -- ["uucy"] = {["phrase"] = "数寸", ["word"] = {"菽"}},
    -- ["xidd"] = {["phrase"] = "细带", ["word"] = {"溪"}},
    -- ["vuql"] = {["phrase"] = "筑墙", ["word"] = {"助"}},
    -- ["mody"] = {["phrase"] = "莫顿", ["word"] = {"没", "殁"}},
    -- ["aiux"] = {["phrase"] = "爱耍", ["word"] = {"砹"}},
    -- ["grwf"] = {["phrase"] = "官文", ["word"] = {"瓘"}},
    -- ["wjbd"] = {["phrase"] = "完败", ["word"] = {"剜"}},
    -- ["yuky"] = {["phrase"] = "玉昆", ["word"] = {"吁", "喁"}},
    -- ["bdfu"] = {["phrase"] = "摆幅", ["word"] = {"捭"}},
    -- ["qngo"] = {["phrase"] = "敲过", ["word"] = {"鞘"}},
    -- ["xidy"] = {["phrase"] = "西顿", ["word"] = {"玺"}},
    -- ["fucz"] = {["phrase"] = "辐辏", ["word"] = {"莩"}},
    -- ["dyzo"] = {["phrase"] = "蹲坐", ["word"] = {"遁"}},
    -- ["kegg"] = {["phrase"] = "可耕", ["word"] = {"髁"}},
    -- ["fjjt"] = {["phrase"] = "反觉", ["word"] = {"幡"}},
    -- ["hukj"] = {["phrase"] = "互看", ["word"] = {"唬"}},
    -- ["tjdk"] = {["phrase"] = "谈定", ["word"] = {"澹"}},
    -- ["gjvg"] = {["phrase"] = "干政", ["word"] = {"竿"}},
    -- ["thre"] = {["phrase"] = "烫热", ["word"] = {"傥"}},
    -- ["bipu"] = {["phrase"] = "婢仆", ["word"] = {"裨"}},
    -- ["dzbd"] = {["phrase"] = "斗败", ["word"] = {"窦"}},
    -- ["ysky"] = {["phrase"] = "永坤", ["word"] = {"咏", "喁"}},
    -- ["yuma"] = {["phrase"] = "玉马", ["word"] = {"阈"}},
    -- ["fubj"] = {["phrase"] = "腹板", ["word"] = {"斧"}},
    -- ["eeyk"] = {["phrase"] = "恶鹰", ["word"] = {"谔"}},
    -- ["wwhw"] = {["phrase"] = "微黑", ["word"] = {"炜"}},
    -- ["yubn"] = {["phrase"] = "鱼鳔", ["word"] = {"鹆"}},
    -- ["djer"] = {["phrase"] = "蛋儿", ["word"] = {"聃"}},
    -- ["zidn"] = {["phrase"] = "紫貂", ["word"] = {"姿"}},
    -- ["qice"] = {["phrase"] = "凄恻", ["word"] = {"葺"}},
    -- ["yjkk"] = {["phrase"] = "眼快", ["word"] = {"唁"}},
    -- ["viux"] = {["phrase"] = "制刷", ["word"] = {"志"}},
    -- ["yisu"] = {["phrase"] = "易俗", ["word"] = {"矣"}},
    -- ["fujn"] = {["phrase"] = "复交", ["word"] = {"幞"}},
    -- ["yzbo"] = {["phrase"] = "又播", ["word"] = {"宥"}},
    -- ["xpsu"] = {["phrase"] = "歇宿", ["word"] = {"绁"}},
    -- ["hcdr"] = {["phrase"] = "号段", ["word"] = {"灏"}},
    -- ["mnce"] = {["phrase"] = "妙策", ["word"] = {"藐"}},
    -- ["yjtn"] = {["phrase"] = "眼跳", ["word"] = {"堰"}},
    -- ["hudh"] = {["phrase"] = "湖荡", ["word"] = {"沪", "滹"}},
    -- ["bnmu"] = {["phrase"] = "标目", ["word"] = {"杓"}},
    -- ["gejl"] = {["phrase"] = "各讲", ["word"] = {"镉"}},
    -- ["mgqn"] = {["phrase"] = "猛敲", ["word"] = {"獴"}},
    -- ["dich"] = {["phrase"] = "底舱", ["word"] = {"荻"}},
    -- ["tjdu"] = {["phrase"] = "贪渎", ["word"] = {"潭"}},
    -- ["uult"] = {["phrase"] = "术略", ["word"] = {"墅"}},
    -- ["hjxx"] = {["phrase"] = "颔下", ["word"] = {"憾"}},
    -- ["vldn"] = {["phrase"] = "撞掉", ["word"] = {"妆"}},
    -- ["humu"] = {["phrase"] = "护目", ["word"] = {"槲"}},
    -- ["xxkj"] = {["phrase"] = "瞎侃", ["word"] = {"匣", "呷"}},
    -- ["jila"] = {["phrase"] = "急拉", ["word"] = {"亟"}},
    -- ["wudj"] = {["phrase"] = "武旦", ["word"] = {"鋈"}},
    -- ["ykci"] = {["phrase"] = "英雌", ["word"] = {"萤"}},
    -- ["yucc"] = {["phrase"] = "浴槽", ["word"] = {"蔚"}},
    -- ["grbc"] = {["phrase"] = "管保", ["word"] = {"冠"}},
    -- ["jmbd"] = {["phrase"] = "建白", ["word"] = {"剪"}},
    -- ["gcmu"] = {["phrase"] = "槁木", ["word"] = {"槔"}},
    -- ["urma"] = {["phrase"] = "拴马", ["word"] = {"闩"}},
    -- ["iiuw"] = {["phrase"] = "吃谁", ["word"] = {"敕"}},
    -- ["zidu"] = {["phrase"] = "自渎", ["word"] = {"滓"}},
    -- ["ujna"] = {["phrase"] = "姗娜", ["word"] = {"嬗"}},
    -- ["uirr"] = {["phrase"] = "湿软", ["word"] = {"似"}},
    -- ["izhk"] = {["phrase"] = "愁怀", ["word"] = {"稠"}},
    -- ["hccc"] = {["phrase"] = "薅草", ["word"] = {"薅"}},
    -- ["hsdn"] = {["phrase"] = "轰掉", ["word"] = {"鸿"}},
    -- ["jmrz"] = {["phrase"] = "煎肉", ["word"] = {"健"}},
    -- ["kldi"] = {["phrase"] = "旷地", ["word"] = {"夼"}},
    -- ["lukk"] = {["phrase"] = "陆块", ["word"] = {"吕", "赂"}},
    -- ["vfmh"] = {["phrase"] = "真忙", ["word"] = {"榛"}},
    -- ["luzu"] = {["phrase"] = "卤族", ["word"] = {"逯"}},
    -- ["dudd"] = {["phrase"] = "肚带", ["word"] = {"渎"}},
    -- ["dpzu"] = {["phrase"] = "跌足", ["word"] = {"迭", "跌"}},
    -- ["ximb"] = {["phrase"] = "细民", ["word"] = {"皙"}},
    -- ["qtmf"] = {["phrase"] = "缺门", ["word"] = {"榷"}},
    -- ["ximn"] = {["phrase"] = "细描", ["word"] = {"樨"}},
    -- ["gunn"] = {["phrase"] = "孤鸟", ["word"] = {"鹄"}},
    -- ["hgii"] = {["phrase"] = "哼哧", ["word"] = {"行", "衡"}},
    -- ["ucho"] = {["phrase"] = "烧火", ["word"] = {"稍"}},
    -- ["hzku"] = {["phrase"] = "齁苦", ["word"] = {"喉"}},
    -- ["xmdz"] = {["phrase"] = "仙都", ["word"] = {"涎"}},
    -- ["bigu"] = {["phrase"] = "辟谷", ["word"] = {"髀"}},
    -- ["uguo"] = {["phrase"] = "声说", ["word"] = {"省"}},
    -- ["qiru"] = {["phrase"] = "欺辱", ["word"] = {"俟"}},
    -- ["mike"] = {["phrase"] = "米克", ["word"] = {"嘧"}},
    -- ["zjwo"] = {["phrase"] = "赞我", ["word"] = {"昝"}},
    -- ["xbcu"] = {["phrase"] = "心粗", ["word"] = {"莘"}},
    -- ["gudo"] = {["phrase"] = "骨朵", ["word"] = {"汩"}},
    -- ["qmxt"] = {["phrase"] = "浅学", ["word"] = {"悭"}},
    -- ["wwcc"] = {["phrase"] = "喂草", ["word"] = {"蔚"}},
    -- ["rucc"] = {["phrase"] = "如草", ["word"] = {"蓐"}},
    -- ["szku"] = {["phrase"] = "搜酷", ["word"] = {"嗾"}},
    -- ["piuu"] = {["phrase"] = "皮书", ["word"] = {"辟", "鼙"}},
    -- ["dund"] = {["phrase"] = "毒奶", ["word"] = {"犊"}},
    -- ["diuj"] = {["phrase"] = "递嬗", ["word"] = {"碲"}},
    -- ["eeke"] = {["phrase"] = "恶客", ["word"] = {"鄂"}},
    -- ["uuso"] = {["phrase"] = "数所", ["word"] = {"署"}},
    -- ["yuzd"] = {["phrase"] = "余载", ["word"] = {"逾"}},
    -- ["wwuc"] = {["phrase"] = "尾梢", ["word"] = {"尉"}},
    -- ["tomi"] = {["phrase"] = "托米", ["word"] = {"柝"}},
    -- ["eeyb"] = {["phrase"] = "恶因", ["word"] = {"讹"}},
    -- ["xkke"] = {["phrase"] = "刑克", ["word"] = {"邢"}},
    -- ["uizj"] = {["phrase"] = "诗赞", ["word"] = {"逝"}},
    -- ["mhcc"] = {["phrase"] = "芒草", ["word"] = {"莽"}},
    -- ["jmmz"] = {["phrase"] = "奸谋", ["word"] = {"毽"}},
    -- ["uimj"] = {["phrase"] = "士曼", ["word"] = {"柿"}},
    -- ["yjdk"] = {["phrase"] = "言定", ["word"] = {"沿"}},
    -- ["pitu"] = {["phrase"] = "辟土", ["word"] = {"埤"}},
    -- ["xuyk"] = {["phrase"] = "虚应", ["word"] = {"酗"}},
    -- ["yusy"] = {["phrase"] = "玉笋", ["word"] = {"纡"}},
    -- ["quhw"] = {["phrase"] = "黢黑", ["word"] = {"黢"}},
    -- ["jisd"] = {["phrase"] = "祭赛", ["word"] = {"罽"}},
    -- ["qmhw"] = {["phrase"] = "浅黑", ["word"] = {"虔"}},
    -- ["aiky"] = {["phrase"] = "爱困", ["word"] = {"嗳"}},
    -- ["iivj"] = {["phrase"] = "翅展", ["word"] = {"篪"}},
    -- ["bchs"] = {["phrase"] = "暴洪", ["word"] = {"炮"}},
    -- ["jidz"] = {["phrase"] = "箕斗", ["word"] = {"洎"}},
    -- ["yzcy"] = {["phrase"] = "犹存", ["word"] = {"莸"}},
    -- ["qmdn"] = {["phrase"] = "迁调", ["word"] = {"牵", "鹐"}},
    -- ["qrbw"] = {["phrase"] = "圈杯", ["word"] = {"痊"}},
    -- ["tdse"] = {["phrase"] = "泰瑟", ["word"] = {"邰"}},
    -- ["yudr"] = {["phrase"] = "预断", ["word"] = {"滪"}},
    -- ["qubf"] = {["phrase"] = "曲本", ["word"] = {"癯"}},
    -- ["xmbm"] = {["phrase"] = "舷边", ["word"] = {"痫"}},
    -- ["xmye"] = {["phrase"] = "涎液", ["word"] = {"酰"}},
    -- ["yhhy"] = {["phrase"] = "洋荤", ["word"] = {"秧", "烊"}},
    -- ["eeyt"] = {["phrase"] = "恶月", ["word"] = {"垩"}},
    -- ["tsdk"] = {["phrase"] = "同定", ["word"] = {"洞"}},
    -- ["juqq"] = {["phrase"] = "菊秋", ["word"] = {"狙"}},
    -- ["yjil"] = {["phrase"] = "岩床", ["word"] = {"餍"}},
    -- ["tkiz"] = {["phrase"] = "挺丑", ["word"] = {"蜓"}},
    -- ["tjux"] = {["phrase"] = "炭刷", ["word"] = {"忐"}},
    -- ["vaua"] = {["phrase"] = "扎煞", ["word"] = {"馇"}},
    -- ["xuso"] = {["phrase"] = "须索", ["word"] = {"绪"}},
    -- ["guuo"] = {["phrase"] = "告朔", ["word"] = {"瞽"}},
    -- ["xycc"] = {["phrase"] = "熏草", ["word"] = {"荨"}},
    -- ["yssy"] = {["phrase"] = "饔飧", ["word"] = {"甬"}},
    -- ["hvdk"] = {["phrase"] = "回定", ["word"] = {"汇", "洄"}},
    -- ["jicj"] = {["phrase"] = "集餐", ["word"] = {"芨"}},
    -- ["zoky"] = {["phrase"] = "坐困", ["word"] = {"嘬"}},
    -- ["hvxi"] = {["phrase"] = "回戏", ["word"] = {"辉", "翚"}},
    -- ["uflo"] = {["phrase"] = "沈落", ["word"] = {"肾"}},
    -- ["siva"] = {["phrase"] = "四扎", ["word"] = {"丝"}},
    -- ["sadu"] = {["phrase"] = "撒督", ["word"] = {"挲"}},
    -- ["yunl"] = {["phrase"] = "渔娘", ["word"] = {"妤"}},
    -- ["ijuz"] = {["phrase"] = "缠手", ["word"] = {"孱"}},
    -- ["tomd"] = {["phrase"] = "托买", ["word"] = {"驮"}},
    -- ["zhci"] = {["phrase"] = "脏词", ["word"] = {"藏"}},
    -- ["uedo"] = {["phrase"] = "舍堕", ["word"] = {"奢"}},
    -- ["fuba"] = {["phrase"] = "副把", ["word"] = {"釜"}},
    -- ["vuhv"] = {["phrase"] = "珠灰", ["word"] = {"炷"}},
    -- ["piou"] = {["phrase"] = "匹偶", ["word"] = {"脾", "睥"}},
    -- ["fupu"] = {["phrase"] = "匐匍", ["word"] = {"阜"}},
    -- ["lzmn"] = {["phrase"] = "露苗", ["word"] = {"娄", "楼"}},
    -- ["mwmo"] = {["phrase"] = "煤末", ["word"] = {"楣"}},
    -- ["xpdj"] = {["phrase"] = "械弹", ["word"] = {"瀣"}},
    -- ["bouz"] = {["phrase"] = "搏手", ["word"] = {"饽"}},
    -- ["vurv"] = {["phrase"] = "烛蕊", ["word"] = {"住", "侏"}},
    -- ["hvko"] = {["phrase"] = "恢廓", ["word"] = {"贿"}},
    -- ["ufku"] = {["phrase"] = "神枯", ["word"] = {"呻"}},
    -- ["igmi"] = {["phrase"] = "乘幂", ["word"] = {"枨"}},
    -- ["lwyc"] = {["phrase"] = "勒腰", ["word"] = {"酹"}},
    -- ["xidh"] = {["phrase"] = "洗荡", ["word"] = {"潟"}},
    -- ["vamc"] = {["phrase"] = "诈冒", ["word"] = {"栅"}},
    -- ["xkou"] = {["phrase"] = "姓欧", ["word"] = {"星", "腥"}},
    -- ["uobm"] = {["phrase"] = "朔边", ["word"] = {"槊"}},
    -- ["kvdr"] = {["phrase"] = "亏短", ["word"] = {"溃"}},
    -- ["ljdj"] = {["phrase"] = "懒蛋", ["word"] = {"澜"}},
    -- ["ludu"] = {["phrase"] = "禄蠹", ["word"] = {"泸", "渌"}},
    -- ["viky"] = {["phrase"] = "志昆", ["word"] = {"吱"}},
    -- ["jxcy"] = {["phrase"] = "甲存", ["word"] = {"葭"}},
    -- ["pibk"] = {["phrase"] = "疲病", ["word"] = {"否", "痞"}},
    -- ["jmvo"] = {["phrase"] = "简擢", ["word"] = {"简"}},
    -- ["ykdy"] = {["phrase"] = "英吨", ["word"] = {"滢"}},
    -- ["vfjr"] = {["phrase"] = "赈捐", ["word"] = {"帧"}},
    -- ["doti"] = {["phrase"] = "多提", ["word"] = {"埵"}},
    -- ["gukk"] = {["phrase"] = "骨筷", ["word"] = {"咕", "固"}},
    -- ["lumo"] = {["phrase"] = "戮没", ["word"] = {"橹", "氇"}},
    -- ["yicr"] = {["phrase"] = "异爨", ["word"] = {"苡"}},
    -- ["quty"] = {["phrase"] = "曲屯", ["word"] = {"趣"}},
    -- ["gubk"] = {["phrase"] = "痼病", ["word"] = {"谷", "痼"}},
    -- ["ffmd"] = {["phrase"] = "氛霾", ["word"] = {"粉", "棼"}},
    -- ["uefj"] = {["phrase"] = "社饭", ["word"] = {"折"}},
    -- ["mjdy"] = {["phrase"] = "曼顿", ["word"] = {"漫"}},
    -- ["jkco"] = {["phrase"] = "惊错", ["word"] = {"菁"}},
    -- ["fucy"] = {["phrase"] = "富村", ["word"] = {"菔"}},
    -- ["vodn"] = {["phrase"] = "琢雕", ["word"] = {"涿"}},
    -- ["gedk"] = {["phrase"] = "割顶", ["word"] = {"哥"}},
    -- ["gukg"] = {["phrase"] = "古坑", ["word"] = {"呱"}},
    -- ["njty"] = {["phrase"] = "南屯", ["word"] = {"赧"}},
    -- ["lslu"] = {["phrase"] = "龙路", ["word"] = {"砻"}},
    -- ["liil"] = {["phrase"] = "李闯", ["word"] = {"历", "励", "厘"}},
    -- ["jkvd"] = {["phrase"] = "京债", ["word"] = {"刭"}},
    -- ["bcrh"] = {["phrase"] = "保禳", ["word"] = {"煲"}},
    -- ["uuuy"] = {["phrase"] = "倏瞬", ["word"] = {"叔", "属"}},
    -- ["bhmf"] = {["phrase"] = "傍门", ["word"] = {"榜"}},
    -- ["uhtk"] = {["phrase"] = "商亭", ["word"] = {"垧", "墒"}},
    -- ["dava"] = {["phrase"] = "大札", ["word"] = {"笪"}},
    -- ["dazz"] = {["phrase"] = "大走", ["word"] = {"跶"}},
    -- ["hrda"] = {["phrase"] = "宦达", ["word"] = {"洹"}},
    -- ["ybbb"] = {["phrase"] = "寅宾", ["word"] = {"寅"}},
    -- ["xyio"] = {["phrase"] = "巡绰", ["word"] = {"循", "徇"}},
    -- ["dink"] = {["phrase"] = "底宁", ["word"] = {"嫡"}},
    -- ["yjmj"] = {["phrase"] = "延蔓", ["word"] = {"阎"}},
    -- ["iupo"] = {["phrase"] = "怵迫", ["word"] = {"褚"}},
    -- ["pubf"] = {["phrase"] = "扑奔", ["word"] = {"匍"}},
    -- ["jncj"] = {["phrase"] = "教参", ["word"] = {"艽"}},
    -- ["vodr"] = {["phrase"] = "斫断", ["word"] = {"浞"}},
    -- ["bcbd"] = {["phrase"] = "暴白", ["word"] = {"刨"}},
    -- ["hvuc"] = {["phrase"] = "会哨", ["word"] = {"卉"}},
    -- ["qnuj"] = {["phrase"] = "桥山", ["word"] = {"壳"}},
    -- ["juhk"] = {["phrase"] = "沮坏", ["word"] = {"焗"}},
    -- ["yjry"] = {["phrase"] = "淹润", ["word"] = {"俨"}},
    -- ["thdk"] = {["phrase"] = "汤鼎", ["word"] = {"淌", "溏"}},
    -- ["lnjl"] = {["phrase"] = "燎浆", ["word"] = {"钌"}},
    -- ["yaiv"] = {["phrase"] = "牙槌", ["word"] = {"轧"}},
    -- ["huho"] = {["phrase"] = "狐惑", ["word"] = {"煳"}},
    -- ["lisd"] = {["phrase"] = "理塞", ["word"] = {"缡"}},
    -- ["hrbd"] = {["phrase"] = "环拜", ["word"] = {"痪"}},
    -- ["jnkh"] = {["phrase"] = "矫亢", ["word"] = {"噍"}},
    -- ["xizd"] = {["phrase"] = "细崽", ["word"] = {"蹊"}},
    -- ["jtyk"] = {["phrase"] = "绝缨", ["word"] = {"谲"}},
    -- ["fucc"] = {["phrase"] = "腐草", ["word"] = {"苻"}},
    -- ["xukl"] = {["phrase"] = "虚诳", ["word"] = {"勖"}},
    -- ["iumc"] = {["phrase"] = "触冒", ["word"] = {"橱"}},
    -- ["xydu"] = {["phrase"] = "训读", ["word"] = {"汛"}},
    -- ["bicu"] = {["phrase"] = "逼促", ["word"] = {"荜", "薜"}},
    -- ["qlmk"] = {["phrase"] = "锵鸣", ["word"] = {"樯"}},
    -- ["xlgy"] = {["phrase"] = "镶滚", ["word"] = {"庠"}},
    -- ["tcdj"] = {["phrase"] = "陶诞", ["word"] = {"滔"}},
    -- ["ybce"] = {["phrase"] = "隐恻", ["word"] = {"茚"}},
    -- ["ybko"] = {["phrase"] = "隐括", ["word"] = {"喑"}},
    -- ["liid"] = {["phrase"] = "离拆", ["word"] = {"蜊"}},
    -- ["lkye"] = {["phrase"] = "灵液", ["word"] = {"酃"}},
    -- ["iiul"] = {["phrase"] = "驰爽", ["word"] = {"饬"}},
    -- ["yuto"] = {["phrase"] = "鹬鸵", ["word"] = {"堉"}},
    -- ["yiro"] = {["phrase"] = "一若", ["word"] = {"佾"}},
    -- ["dkjr"] = {["phrase"] = "丁绢", ["word"] = {"锭"}},
    -- ["yjnk"] = {["phrase"] = "严凝", ["word"] = {"妍"}},
    -- ["vsrv"] = {["phrase"] = "中瑞", ["word"] = {"仲"}},
    -- ["fgee"] = {["phrase"] = "丰额", ["word"] = {"酆"}},
    -- ["juuj"] = {["phrase"] = "举善", ["word"] = {"矩"}},
    -- ["qnyh"] = {["phrase"] = "乔样", ["word"] = {"谯"}},
    -- ["yaiy"] = {["phrase"] = "亚纯", ["word"] = {"蚜"}},
    -- ["jndh"] = {["phrase"] = "交党", ["word"] = {"湫"}},
    -- ["ijju"] = {["phrase"] = "产具", ["word"] = {"镡"}},
    -- ["qbdh"] = {["phrase"] = "亲党", ["word"] = {"溱"}},
    -- ["xpzy"] = {["phrase"] = "亵尊", ["word"] = {"躞"}},
    -- ["lkrs"] = {["phrase"] = "令容", ["word"] = {"令", "伶"}},
    -- ["yivv"] = {["phrase"] = "仪缀", ["word"] = {"乙", "已"}},
    -- ["rfsr"] = {["phrase"] = "任算", ["word"] = {"纫", "纴"}},
    -- ["xqdo"] = {["phrase"] = "休惰", ["word"] = {"滫"}},
    -- ["siru"] = {["phrase"] = "似如", ["word"] = {"俟"}},
    -- ["yuzy"] = {["phrase"] = "余尊", ["word"] = {"迂", "遇"}},
    -- ["suvr"] = {["phrase"] = "俗馔", ["word"] = {"簌"}},
    -- ["jumj"] = {["phrase"] = "倨嫚", ["word"] = {"柜"}},
    -- ["yjnh"] = {["phrase"] = "偃囊", ["word"] = {"燕", "嫣"}},
    -- ["iuzo"] = {["phrase"] = "储佐", ["word"] = {"躇"}},
    -- ["yrky"] = {["phrase"] = "元昆", ["word"] = {"圜"}},
    -- ["bkuk"] = {["phrase"] = "兵帅", ["word"] = {"饼", "屏"}},
    -- ["bkmb"] = {["phrase"] = "兵民", ["word"] = {"柄", "槟"}},
    -- ["mcjt"] = {["phrase"] = "冒橛", ["word"] = {"锚"}},
    -- ["rsbj"] = {["phrase"] = "冗绊", ["word"] = {"冗"}},
    -- ["nkdd"] = {["phrase"] = "凝待", ["word"] = {"泞"}},
    -- ["iudh"] = {["phrase"] = "出挡", ["word"] = {"滁"}},
    -- ["jiij"] = {["phrase"] = "击馋", ["word"] = {"虮"}},
    -- ["hjdk"] = {["phrase"] = "函订", ["word"] = {"涵"}},
    -- ["ffmb"] = {["phrase"] = "分民", ["word"] = {"粪"}},
    -- ["lpdd"] = {["phrase"] = "列代", ["word"] = {"列", "冽", "洌"}},
    -- ["bccs"] = {["phrase"] = "剥葱", ["word"] = {"苞"}},
    -- ["lptd"] = {["phrase"] = "劣汰", ["word"] = {"趔"}},
    -- ["qbcv"] = {["phrase"] = "勤悴", ["word"] = {"芩"}},
    -- ["bwuo"] = {["phrase"] = "北朔", ["word"] = {"臂"}},
    -- ["kvee"] = {["phrase"] = "匮饿", ["word"] = {"岿"}},
    -- ["bomb"] = {["phrase"] = "博敏", ["word"] = {"柏"}},
    -- ["lupn"] = {["phrase"] = "卤剽", ["word"] = {"褛"}},
    -- ["xpfj"] = {["phrase"] = "卸帆", ["word"] = {"挟"}},
    -- ["tdsh"] = {["phrase"] = "台桑", ["word"] = {"炱"}},
    -- ["sidj"] = {["phrase"] = "司旦", ["word"] = {"澌"}},
    -- ["iikd"] = {["phrase"] = "吃开", ["word"] = {"哧"}},
    -- ["jirv"] = {["phrase"] = "吉瑞", ["word"] = {"偈"}},
    -- ["pish"] = {["phrase"] = "否桑", ["word"] = {"罴"}},
    -- ["hjhk"] = {["phrase"] = "含怀", ["word"] = {"焓"}},
    -- ["herr"] = {["phrase"] = "和软", ["word"] = {"颌"}},
    -- ["aicv"] = {["phrase"] = "哀悴", ["word"] = {"蔼"}},
    -- ["pbvu"] = {["phrase"] = "品柱", ["word"] = {"颦"}},
    -- ["ihro"] = {["phrase"] = "唱偌", ["word"] = {"倡"}},
    -- ["kvxl"] = {["phrase"] = "夔襄", ["word"] = {"悝"}},
    -- ["qiqx"] = {["phrase"] = "契洽", ["word"] = {"綦", "憩"}},
    -- ["nujn"] = {["phrase"] = "奴角", ["word"] = {"钕"}},
    -- ["lrwj"] = {["phrase"] = "娈婉", ["word"] = {"銮"}},
    -- ["ufbp"] = {["phrase"] = "审别", ["word"] = {"瘆"}},
    -- ["kebk"] = {["phrase"] = "客兵", ["word"] = {"客", "疴"}},
    -- ["kemg"] = {["phrase"] = "客梦", ["word"] = {"棵", "骒"}},
    -- ["xrda"] = {["phrase"] = "宣答", ["word"] = {"渲"}},
    -- ["suxx"] = {["phrase"] = "宿瑕", ["word"] = {"愫"}},
    -- ["jihw"] = {["phrase"] = "寂嘿", ["word"] = {"稷"}},
    -- ["mibj"] = {["phrase"] = "密办", ["word"] = {"幂"}},
    -- ["svzu"] = {["phrase"] = "岁租", ["word"] = {"遂", "邃"}},
    -- ["tpjk"] = {["phrase"] = "帖经", ["word"] = {"帖"}},
    -- ["ihao"] = {["phrase"] = "常奥", ["word"] = {"鲳"}},
    -- ["luwu"] = {["phrase"] = "庐伍", ["word"] = {"率"}},
    -- ["ykcu"] = {["phrase"] = "应猝", ["word"] = {"荥"}},
    -- ["yirv"] = {["phrase"] = "异瑞", ["word"] = {"亿"}},
    -- ["vhlp"] = {["phrase"] = "张列", ["word"] = {"彰"}},
    -- ["vhdu"] = {["phrase"] = "张独", ["word"] = {"漳"}},
    -- ["migf"] = {["phrase"] = "弥亘", ["word"] = {"靡"}},
    -- ["xydo"] = {["phrase"] = "徇铎", ["word"] = {"殉", "洵"}},
    -- ["yrte"] = {["phrase"] = "怨慝", ["word"] = {"垸"}},
    -- ["yzko"] = {["phrase"] = "悠阔", ["word"] = {"囿"}},
    -- ["wjce"] = {["phrase"] = "惋恻", ["word"] = {"莞"}},
    -- ["izrc"] = {["phrase"] = "愁扰", ["word"] = {"俦"}},
    -- ["gjmg"] = {["phrase"] = "感梦", ["word"] = {"杆", "柑"}},
    -- ["yrkr"] = {["phrase"] = "愿款", ["word"] = {"员", "圆"}},
    -- ["hudg"] = {["phrase"] = "户等", ["word"] = {"瓠"}},
    -- ["pumo"] = {["phrase"] = "扑摸", ["word"] = {"氆"}},
    -- ["pitp"] = {["phrase"] = "批帖", ["word"] = {"坯"}},
    -- ["piba"] = {["phrase"] = "批把", ["word"] = {"丕"}},
    -- ["voff"] = {["phrase"] = "拙分", ["word"] = {"擢"}},
    -- ["jica"] = {["phrase"] = "挤擦", ["word"] = {"蕺"}},
    -- ["cofg"] = {["phrase"] = "挫锋", ["word"] = {"搓"}},
    -- ["jpmb"] = {["phrase"] = "捷敏", ["word"] = {"楷"}},
    -- ["tjbf"] = {["phrase"] = "探本", ["word"] = {"瘫"}},
    -- ["lmmz"] = {["phrase"] = "敛眸", ["word"] = {"梿"}},
    -- ["voco"] = {["phrase"] = "斫锉", ["word"] = {"著"}},
    -- ["xikk"] = {["phrase"] = "晞块", ["word"] = {"嘻"}},
    -- ["kvko"] = {["phrase"] = "暌阔", ["word"] = {"喟"}},
    -- ["quen"] = {["phrase"] = "曲恩", ["word"] = {"娶"}},
    -- ["qumq"] = {["phrase"] = "曲谬", ["word"] = {"阒"}},
    -- ["mumd"] = {["phrase"] = "木脉", ["word"] = {"模"}},
    -- ["yhdy"] = {["phrase"] = "杨楯", ["word"] = {"殃", "洋", "漾", "泱"}},
    -- ["uudr"] = {["phrase"] = "树端", ["word"] = {"漱"}},
    -- ["bidm"] = {["phrase"] = "毕典", ["word"] = {"滗"}},
    -- ["mcso"] = {["phrase"] = "毛索", ["word"] = {"瞀"}},
    -- ["qbry"] = {["phrase"] = "沁润", ["word"] = {"侵", "衾"}},
    -- ["ufcv"] = {["phrase"] = "沈悴", ["word"] = {"葚"}},
    -- ["yzdy"] = {["phrase"] = "油墩", ["word"] = {"油"}},
    -- ["podd"] = {["phrase"] = "泼黛", ["word"] = {"泼"}},
    -- ["zekv"] = {["phrase"] = "泽葵", ["word"] = {"咋"}},
    -- ["digd"] = {["phrase"] = "涤溉", ["word"] = {"底", "骶"}},
    -- ["hydu"] = {["phrase"] = "混渎", ["word"] = {"溷"}},
    -- ["ljmn"] = {["phrase"] = "烂妙", ["word"] = {"婪"}},
    -- ["ukwu"] = {["phrase"] = "率舞", ["word"] = {"率"}},
    -- ["yuuc"] = {["phrase"] = "玉杓", ["word"] = {"尉"}},
    -- ["yubg"] = {["phrase"] = "玉琫", ["word"] = {"窳"}},
    -- ["hrky"] = {["phrase"] = "环琨", ["word"] = {"圜"}},
    -- ["livd"] = {["phrase"] = "理债", ["word"] = {"篱"}},
    -- ["qsge"] = {["phrase"] = "琼阁", ["word"] = {"邛"}},
    -- ["ycky"] = {["phrase"] = "瑶琨", ["word"] = {"吆"}},
    -- ["ufdp"] = {["phrase"] = "甚迭", ["word"] = {"渗"}},
    -- ["dmlb"] = {["phrase"] = "电临", ["word"] = {"典"}},
    -- ["dmdr"] = {["phrase"] = "电断", ["word"] = {"淀"}},
    -- ["jldy"] = {["phrase"] = "疆顿", ["word"] = {"酱"}},
    -- ["ykch"] = {["phrase"] = "盈藏", ["word"] = {"荧"}},
    -- ["pjpu"] = {["phrase"] = "盘璞", ["word"] = {"襻"}},
    -- ["viuy"] = {["phrase"] = "直顺", ["word"] = {"支"}},
    -- ["vftp"] = {["phrase"] = "真帖", ["word"] = {"畛"}},
    -- ["xrdy"] = {["phrase"] = "眩顿", ["word"] = {"泫"}},
    -- ["jbna"] = {["phrase"] = "矜纳", ["word"] = {"堇"}},
    -- ["uipf"] = {["phrase"] = "石盆", ["word"] = {"失"}},
    -- ["lulr"] = {["phrase"] = "碌乱", ["word"] = {"颅"}},
    -- ["bivl"] = {["phrase"] = "碧幢", ["word"] = {"箅"}},
    -- ["likl"] = {["phrase"] = "礼贶", ["word"] = {"哩", "呖", "喱"}},
    -- ["fubb"] = {["phrase"] = "祓殡", ["word"] = {"宓"}},
    -- ["jiry"] = {["phrase"] = "积润", ["word"] = {"伎"}},
    -- ["vhrj"] = {["phrase"] = "章然", ["word"] = {"仉"}},
    -- ["jqmj"] = {["phrase"] = "纠缦", ["word"] = {"柩", "桕"}},
    -- ["hsbk"] = {["phrase"] = "红兵", ["word"] = {"訇"}},
    -- ["jtfg"] = {["phrase"] = "绝峰", ["word"] = {"抉"}},
    -- ["cvxu"] = {["phrase"] = "翠虚", ["word"] = {"悴", "翠"}},
    -- ["gggr"] = {["phrase"] = "耕灌", ["word"] = {"赓"}},
    -- ["vcdk"] = {["phrase"] = "肇定", ["word"] = {"召", "沼"}},
    -- ["xpdy"] = {["phrase"] = "胁盾", ["word"] = {"泻"}},
    -- ["jpco"] = {["phrase"] = "节错", ["word"] = {"藉"}},
    -- ["juuk"] = {["phrase"] = "苴衰", ["word"] = {"局", "居"}},
    -- ["ykcj"] = {["phrase"] = "荧灿", ["word"] = {"蓥"}},
    -- ["huwo"] = {["phrase"] = "虎幄", ["word"] = {"瑚"}},
    -- ["xuky"] = {["phrase"] = "虚困", ["word"] = {"吁", "嘘"}},
    -- ["xugv"] = {["phrase"] = "虚诡", ["word"] = {"魆"}},
    -- ["xupn"] = {["phrase"] = "虚飘", ["word"] = {"媭"}},
    -- ["gunk"] = {["phrase"] = "蛊佞", ["word"] = {"姑", "牯"}},
    -- ["mjjy"] = {["phrase"] = "蛮军", ["word"] = {"幔", "镘"}},
    -- ["qqmh"] = {["phrase"] = "裘莽", ["word"] = {"楸"}},
    -- ["eeuk"] = {["phrase"] = "讹衰", ["word"] = {"屙"}},
    -- ["vakv"] = {["phrase"] = "诈愧", ["word"] = {"咋"}},
    -- ["vama"] = {["phrase"] = "诈马", ["word"] = {"查", "楂"}},
    -- ["xlvo"] = {["phrase"] = "详酌", ["word"] = {"箱"}},
    -- ["ijuy"] = {["phrase"] = "谄顺", ["word"] = {"羼"}},
    -- ["ijmz"] = {["phrase"] = "谗谋", ["word"] = {"骣"}},
    -- ["jbne"] = {["phrase"] = "谨讷", ["word"] = {"觐"}},
    -- ["fudz"] = {["phrase"] = "负斗", ["word"] = {"浮"}},
    -- ["xmou"] = {["phrase"] = "贤耦", ["word"] = {"腺"}},
    -- ["gvmj"] = {["phrase"] = "贵满", ["word"] = {"柜"}},
    -- ["vvsz"] = {["phrase"] = "赘叟", ["word"] = {"缒"}},
    -- ["iigd"] = {["phrase"] = "赤盖", ["word"] = {"魑"}},
    -- ["icko"] = {["phrase"] = "超阔", ["word"] = {"嘲"}},
    -- ["qucj"] = {["phrase"] = "趋参", ["word"] = {"苣"}},
    -- ["tafu"] = {["phrase"] = "踏伏", ["word"] = {"拓"}},
    -- ["vrkv"] = {["phrase"] = "转馈", ["word"] = {"啭"}},
    -- ["qmcr"] = {["phrase"] = "迁窜", ["word"] = {"芡"}},
    -- ["mido"] = {["phrase"] = "迷夺", ["word"] = {"汨"}},
    -- ["bicz"] = {["phrase"] = "逼凑", ["word"] = {"荸"}},
    -- ["biuo"] = {["phrase"] = "逼烁", ["word"] = {"臂"}},
    -- ["dyzw"] = {["phrase"] = "遁贼", ["word"] = {"蹾"}},
    -- ["qqdh"] = {["phrase"] = "遒宕", ["word"] = {"湫"}},
    -- ["dczj"] = {["phrase"] = "道簪", ["word"] = {"蹈"}},
    -- ["yiry"] = {["phrase"] = "遗润", ["word"] = {"仪", "伊", "依"}},
    -- ["luhl"] = {["phrase"] = "录黄", ["word"] = {"虏"}},
    -- ["pudn"] = {["phrase"] = "铺调", ["word"] = {"濮"}},
    -- ["jrjn"] = {["phrase"] = "镌噍", ["word"] = {"镌"}},
    -- ["tizj"] = {["phrase"] = "题赞", ["word"] = {"蹄"}},
    -- ["eekr"] = {["phrase"] = "额款", ["word"] = {"颚"}},
    -- ["xlmn"] = {["phrase"] = "飨庙", ["word"] = {"橡"}},
    -- ["xycu"] = {["phrase"] = "驯粗", ["word"] = {"蕈"}},
    -- ["qubn"] = {["phrase"] = "驱镳", ["word"] = {"鸲"}},
    -- ["liaa"] = {["phrase"] = "骊阿", ["word"] = {"鳢"}},
    -- ["qikx"] = {["phrase"] = "骑跨", ["word"] = {"嘁"}},
    -- ["kvxr"] = {["phrase"] = "魁选", ["word"] = {"愦"}},
    -- ["yupb"] = {["phrase"] = "鱼品", ["word"] = {"舆"}},
    -- ["luiy"] = {["phrase"] = "鲈莼", ["word"] = {"律"}},
    -- ["hlwo"] = {["phrase"] = "黄幄", ["word"] = {"肓"}},
    -- ["ddrh"] = {["phrase"] = "黛壤", ["word"] = {"黛"}},
    -- ["lsbu"] = {["phrase"] = "龙步", ["word"] = {"窿", "癃"}},
    -- ["uada"] = {["phrase"] = "沙大", ["word"] = {"鲨"}},
    -- ["uady"] = {["phrase"] = "沙墩", ["word"] = {"裟"}},
    -- ["ihnj"] = {["phrase"] = "厂南", ["word"] = {"嫦"}},
    -- ["lhdo"] = {["phrase"] = "浪多", ["word"] = {"朗"}},
    -- ["dsdd"] = {["phrase"] = "东岱", ["word"] = {"冻"}},
    -- ["bocy"] = {["phrase"] = "博村", ["word"] = {"菠"}},
    -- ["muco"] = {["phrase"] = "穆厝", ["word"] = {"暮", "苜"}},
    -- ["ycnd"] = {["phrase"] = "姚鼐", ["word"] = {"姚"}},
    -- ["liwa"] = {["phrase"] = "里瓦", ["word"] = {"立"}},
    -- ["gsgf"] = {["phrase"] = "公根", ["word"] = {"巩"}},
    -- ["yrce"] = {["phrase"] = "圆测", ["word"] = {"芫"}},
    -- ["qila"] = {["phrase"] = "耆腊", ["word"] = {"亟"}},
    -- ["yelp"] = {["phrase"] = "野猎", ["word"] = {"曳"}}
}

return dup_table
