local dup_table = {
	["vidu"] = { ["phrase"] = "制度", ["word"] = { "汁" } },
	["yidk"] = { ["phrase"] = "一定", ["word"] = { "漪" } },
	["yidm"] = { ["phrase"] = "一点", ["word"] = { "溢" } },
	["jmdj"] = { ["phrase"] = "简单", ["word"] = { "渐", "溅" } },
	["sudu"] = { ["phrase"] = "速度", ["word"] = { "涑", "觫" } },
	["uiui"] = { ["phrase"] = "事实", ["word"] = { "蚀" } },
	["yijm"] = { ["phrase"] = "意见", ["word"] = { "镒" } },
	["yjjk"] = { ["phrase"] = "眼睛", ["word"] = { "铅" } },
	["jisr"] = { ["phrase"] = "计算", ["word"] = { "绩" } },
	["yibm"] = { ["phrase"] = "一边", ["word"] = { "益" } },
	["jike"] = { ["phrase"] = "即可", ["word"] = { "唧" } },
	["mwnm"] = { ["phrase"] = "每年", ["word"] = { "媒" } },
	["ykgo"] = { ["phrase"] = "英国", ["word"] = { "膺" } },
	["ykwf"] = { ["phrase"] = "英文", ["word"] = { "赢", "嬴" } },
	["qidd"] = { ["phrase"] = "期待", ["word"] = { "沏" } },
	["jbll"] = { ["phrase"] = "尽量", ["word"] = { "巾" } },
	["vifu"] = { ["phrase"] = "支付", ["word"] = { "挚" } },
	["yidj"] = { ["phrase"] = "一旦", ["word"] = { "沂" } },
	["yikk"] = { ["phrase"] = "一块", ["word"] = { "贻" } },
	["jiyu"] = { ["phrase"] = "基于", ["word"] = { "计" } },
	["ufru"] = { ["phrase"] = "深入", ["word"] = { "什", "伸" } },
	["xmde"] = { ["phrase"] = "显得", ["word"] = { "洗", "冼" } },
	["jkcd"] = { ["phrase"] = "精彩", ["word"] = { "荆" } },
	["yixl"] = { ["phrase"] = "一项", ["word"] = { "怿", "翌" } },
	["didm"] = { ["phrase"] = "地点", ["word"] = { "涤" } },
	["uivi"] = { ["phrase"] = "是指", ["word"] = { "虱" } },
	["yikr"] = { ["phrase"] = "一款", ["word"] = { "颐" } },
	["bmhc"] = { ["phrase"] = "编号", ["word"] = { "扁", "煸" } },
	["fuvl"] = { ["phrase"] = "服装", ["word"] = { "弗" } },
	["vgvl"] = { ["phrase"] = "症状", ["word"] = { "筝" } },
	["svhz"] = { ["phrase"] = "随后", ["word"] = { "燧" } },
	["jxju"] = { ["phrase"] = "家具", ["word"] = { "镓" } },
	["uiqu"] = { ["phrase"] = "失去", ["word"] = { "舐" } },
	["vize"] = { ["phrase"] = "职责", ["word"] = { "踯" } },
	["yivc"] = { ["phrase"] = "依照", ["word"] = { "彝" } },
	["ycba"] = { ["phrase"] = "要把", ["word"] = { "疟" } },
	["xbxb"] = { ["phrase"] = "信心", ["word"] = { "衅" } },
	["uiyc"] = { ["phrase"] = "是要", ["word"] = { "诗" } },
	["gemk"] = { ["phrase"] = "革命", ["word"] = { "阁", "格" } },
	["jydv"] = { ["phrase"] = "军队", ["word"] = { "龟" } },
	["ykcy"] = { ["phrase"] = "英寸", ["word"] = { "英", "莹" } },
	["yrxn"] = { ["phrase"] = "院校", ["word"] = { "鸳" } },
	["luqu"] = { ["phrase"] = "录取", ["word"] = { "氯" } },
	["uiti"] = { ["phrase"] = "试题", ["word"] = { "螫" } },
	["gsgu"] = { ["phrase"] = "巩固", ["word"] = { "汞" } },
	["qiqr"] = { ["phrase"] = "齐全", ["word"] = { "欺" } },
	["vifh"] = { ["phrase"] = "脂肪", ["word"] = { "摭" } },
	["ybqk"] = { ["phrase"] = "引擎", ["word"] = { "狺" } },
	["mwmw"] = { ["phrase"] = "妹妹", ["word"] = { "枚" } },
	["jidj"] = { ["phrase"] = "鸡蛋", ["word"] = { "汲" } },
	["lujk"] = { ["phrase"] = "路径", ["word"] = { "铝" } },
	["yiwd"] = { ["phrase"] = "意外", ["word"] = { "亦", "奕" } },
	["qqdv"] = { ["phrase"] = "球队", ["word"] = { "龟" } },
	["furf"] = { ["phrase"] = "夫人", ["word"] = { "佛" } },
	["yida"] = { ["phrase"] = "一大", ["word"] = { "殪" } },
	["vudo"] = { ["phrase"] = "诸多", ["word"] = { "渚", "潴" } },
	["jmmm"] = { ["phrase"] = "见面", ["word"] = { "槛" } },
	["qmjk"] = { ["phrase"] = "前景", ["word"] = { "铅" } },
	["licd"] = { ["phrase"] = "理财", ["word"] = { "莉", "蓠" } },
	["yizd"] = { ["phrase"] = "已在", ["word"] = { "逸", "劓" } },
	["qidm"] = { ["phrase"] = "起点", ["word"] = { "柒" } },
	["bukf"] = { ["phrase"] = "不肯", ["word"] = { "哺" } },
	["jiho"] = { ["phrase"] = "激活", ["word"] = { "稽" } },
	["jihe"] = { ["phrase"] = "集合", ["word"] = { "嵇" } },
	["jilv"] = { ["phrase"] = "纪律", ["word"] = { "乩" } },
	["yeye"] = { ["phrase"] = "爷爷", ["word"] = { "邺" } },
	["huxk"] = { ["phrase"] = "户型", ["word"] = { "怙" } },
	["yiiu"] = { ["phrase"] = "一处", ["word"] = { "轶" } },
	["jida"] = { ["phrase"] = "极大", ["word"] = { "殛" } },
	["yjve"] = { ["phrase"] = "沿着", ["word"] = { "鄢" } },
	["lldm"] = { ["phrase"] = "亮点", ["word"] = { "梁", "粱" } },
	["hedk"] = { ["phrase"] = "核定", ["word"] = { "河", "涸" } },
	["yuwo"] = { ["phrase"] = "与我", ["word"] = { "育" } },
	["yukk"] = { ["phrase"] = "愉快", ["word"] = { "圄" } },
	["zidr"] = { ["phrase"] = "字段", ["word"] = { "资", "渍" } },
	["qkhx"] = { ["phrase"] = "清华", ["word"] = { "綮", "黥" } },
	["yaii"] = { ["phrase"] = "牙齿", ["word"] = { "衙" } },
	["tcfh"] = { ["phrase"] = "套房", ["word"] = { "焘" } },
	["jpdk"] = { ["phrase"] = "界定", ["word"] = { "洁" } },
	["iuui"] = { ["phrase"] = "出示", ["word"] = { "础" } },
	["bwpo"] = { ["phrase"] = "被迫", ["word"] = { "褙" } },
	["jmbk"] = { ["phrase"] = "兼并", ["word"] = { "謇" } },
	["xmuh"] = { ["phrase"] = "线上", ["word"] = { "燹" } },
	["jbdd"] = { ["phrase"] = "近代", ["word"] = { "浕" } },
	["jmbh"] = { ["phrase"] = "肩膀", ["word"] = { "煎" } },
	["fufw"] = { ["phrase"] = "付费", ["word"] = { "抚", "敷" } },
	["yiiy"] = { ["phrase"] = "乙醇", ["word"] = { "役", "蚁" } },
	["vjlk"] = { ["phrase"] = "占领", ["word"] = { "占", "站" } },
	["uidr"] = { ["phrase"] = "时段", ["word"] = { "湜" } },
	["gsgr"] = { ["phrase"] = "公关", ["word"] = { "贡" } },
	["dide"] = { ["phrase"] = "低的", ["word"] = { "邸" } },
	["ufsu"] = { ["phrase"] = "申诉", ["word"] = { "绅" } },
	["xmee"] = { ["phrase"] = "限额", ["word"] = { "岘" } },
	["livi"] = { ["phrase"] = "理智", ["word"] = { "蠡" } },
	["jpuv"] = { ["phrase"] = "节水", ["word"] = { "碣" } },
	["jqjl"] = { ["phrase"] = "就将", ["word"] = { "舅" } },
	["ufye"] = { ["phrase"] = "深夜", ["word"] = { "诜" } },
	["jibu"] = { ["phrase"] = "既不", ["word"] = { "疾" } },
	["lidd"] = { ["phrase"] = "历代", ["word"] = { "漓" } },
	["suyh"] = { ["phrase"] = "素养", ["word"] = { "酥" } },
	["fuyb"] = { ["phrase"] = "复印", ["word"] = { "讣" } },
	["iuih"] = { ["phrase"] = "出场", ["word"] = { "蜍" } },
	["yjii"] = { ["phrase"] = "延迟", ["word"] = { "衍" } },
	["jmro"] = { ["phrase"] = "减弱", ["word"] = { "僭" } },
	["liwd"] = { ["phrase"] = "例外", ["word"] = { "离", "璃" } },
	["iumo"] = { ["phrase"] = "触摸", ["word"] = { "楮" } },
	["uian"] = { ["phrase"] = "是按", ["word"] = { "豕" } },
	["xihx"] = { ["phrase"] = "细化", ["word"] = { "熄" } },
	["yixb"] = { ["phrase"] = "一心", ["word"] = { "翼", "悒" } },
	["yily"] = { ["phrase"] = "一轮", ["word"] = { "毅" } },
	["buld"] = { ["phrase"] = "不来", ["word"] = { "卜" } },
	["wudk"] = { ["phrase"] = "屋顶", ["word"] = { "污", "浯" } },
	["yuuh"] = { ["phrase"] = "遇上", ["word"] = { "熨" } },
	["vidv"] = { ["phrase"] = "支队", ["word"] = { "沚" } },
	["viyb"] = { ["phrase"] = "指引", ["word"] = { "识" } },
	["uiuj"] = { ["phrase"] = "屎山", ["word"] = { "饰" } },
	["zdbu"] = { ["phrase"] = "在不", ["word"] = { "宰" } },
	["ijdz"] = { ["phrase"] = "颤抖", ["word"] = { "潺" } },
	["yyss"] = { ["phrase"] = "运送", ["word"] = { "纭" } },
	["jmvj"] = { ["phrase"] = "建站", ["word"] = { "笺" } },
	["jmgz"] = { ["phrase"] = "建构", ["word"] = { "鞬", "鞯" } },
	["lian"] = { ["phrase"] = "立案", ["word"] = { "吏" } },
	["qipj"] = { ["phrase"] = "期盼", ["word"] = { "祈" } },
	["yrde"] = { ["phrase"] = "远的", ["word"] = { "沅" } },
	["mcsi"] = { ["phrase"] = "貌似", ["word"] = { "蝥", "蟊" } },
	["viuo"] = { ["phrase"] = "之说", ["word"] = { "智" } },
	["iaua"] = { ["phrase"] = "查杀", ["word"] = { "馇", "碴" } },
	["gcmk"] = { ["phrase"] = "高明", ["word"] = { "槁" } },
	["mmdm"] = { ["phrase"] = "缅甸", ["word"] = { "沔", "湎" } },
	["jiug"] = { ["phrase"] = "计生", ["word"] = { "戟" } },
	["dzba"] = { ["phrase"] = "都把", ["word"] = { "痘" } },
	["yipn"] = { ["phrase"] = "一票", ["word"] = { "乂" } },
	["bwuz"] = { ["phrase"] = "备受", ["word"] = { "孛" } },
	["xink"] = { ["phrase"] = "西宁", ["word"] = { "嬉" } },
	["uuww"] = { ["phrase"] = "数为", ["word"] = { "孰" } },
	["iajx"] = { ["phrase"] = "差价", ["word"] = { "镲" } },
	["vjdv"] = { ["phrase"] = "战队", ["word"] = { "湛" } },
	["yier"] = { ["phrase"] = "一二", ["word"] = { "嶷" } },
	["mogu"] = { ["phrase"] = "蘑菇", ["word"] = { "摩", "磨" } },
	["vgfa"] = { ["phrase"] = "蒸发", ["word"] = { "拯" } },
	["iumk"] = { ["phrase"] = "出名", ["word"] = { "樗" } },
	["jivj"] = { ["phrase"] = "激战", ["word"] = { "笈" } },
	["pmmk"] = { ["phrase"] = "片名", ["word"] = { "骈" } },
	["wujk"] = { ["phrase"] = "武警", ["word"] = { "铻", "鼯" } },
	["uiln"] = { ["phrase"] = "史料", ["word"] = { "史" } },
	["fjuf"] = { ["phrase"] = "翻身", ["word"] = { "矾" } },
	["pmhc"] = { ["phrase"] = "偏好", ["word"] = { "扁" } },
	["yicy"] = { ["phrase"] = "一寸", ["word"] = { "荑" } },
	["wumw"] = { ["phrase"] = "妩媚", ["word"] = { "杌" } },
	["hsds"] = { ["phrase"] = "轰动", ["word"] = { "泓" } },
	["xnmw"] = { ["phrase"] = "小妹", ["word"] = { "骁" } },
	["fuzc"] = { ["phrase"] = "浮躁", ["word"] = { "跗" } },
	["juzu"] = { ["phrase"] = "剧组", ["word"] = { "遽" } },
	["hxmu"] = { ["phrase"] = "花木", ["word"] = { "桦", "骅" } },
	["wuyr"] = { ["phrase"] = "无缘", ["word"] = { "诬" } },
	["jiee"] = { ["phrase"] = "饥饿", ["word"] = { "觊" } },
	["cjlm"] = { ["phrase"] = "残联", ["word"] = { "粲" } },
	["jkvl"] = { ["phrase"] = "精装", ["word"] = { "劲" } },
	["uzbk"] = { ["phrase"] = "手柄", ["word"] = { "兽" } },
	["ybvg"] = { ["phrase"] = "印证", ["word"] = { "龈" } },
	["fuiz"] = { ["phrase"] = "复仇", ["word"] = { "蜉" } },
	["uuhu"] = { ["phrase"] = "疏忽", ["word"] = { "秫", "黍" } },
	["ujcy"] = { ["phrase"] = "闪存", ["word"] = { "芟" } },
	["ueii"] = { ["phrase"] = "奢侈", ["word"] = { "厍" } },
	["wwmw"] = { ["phrase"] = "唯美", ["word"] = { "闱" } },
	["wunw"] = { ["phrase"] = "屋内", ["word"] = { "物", "妩" } },
	["cvmm"] = { ["phrase"] = "催眠", ["word"] = { "毳" } },
	["anbm"] = { ["phrase"] = "岸边", ["word"] = { "案" } },
	["yjke"] = { ["phrase"] = "眼科", ["word"] = { "郾" } },
	["xiuj"] = { ["phrase"] = "西山", ["word"] = { "豨" } },
	["viuf"] = { ["phrase"] = "之神", ["word"] = { "雉" } },
	["vhmu"] = { ["phrase"] = "账目", ["word"] = { "樟" } },
	["vipd"] = { ["phrase"] = "指派", ["word"] = { "制", "祗" } },
	["viju"] = { ["phrase"] = "之举", ["word"] = { "帙" } },
	["yiru"] = { ["phrase"] = "一如", ["word"] = { "佚" } },
	["tsmk"] = { ["phrase"] = "同名", ["word"] = { "桐" } },
	["iidn"] = { ["phrase"] = "吃掉", ["word"] = { "鸱" } },
	["ssds"] = { ["phrase"] = "松动", ["word"] = { "凇", "淞" } },
	["vzye"] = { ["phrase"] = "昼夜", ["word"] = { "诌" } },
	["lowf"] = { ["phrase"] = "螺纹", ["word"] = { "雒" } },
	["quii"] = { ["phrase"] = "去吃", ["word"] = { "衢" } },
	["iefw"] = { ["phrase"] = "车费", ["word"] = { "撤" } },
	["hjfg"] = { ["phrase"] = "寒风", ["word"] = { "捍" } },
	["vuzi"] = { ["phrase"] = "竹子", ["word"] = { "躅" } },
	["isvl"] = { ["phrase"] = "重装", ["word"] = { "艟" } },
	["uudc"] = { ["phrase"] = "疏导", ["word"] = { "澍" } },
	["zidk"] = { ["phrase"] = "自定", ["word"] = { "咨" } },
	["vudv"] = { ["phrase"] = "主队", ["word"] = { "注", "洙" } },
	["jiwj"] = { ["phrase"] = "几万", ["word"] = { "玑" } },
	["vibc"] = { ["phrase"] = "质保", ["word"] = { "痔" } },
	["jklo"] = { ["phrase"] = "经络", ["word"] = { "靖" } },
	["ykmm"] = { ["phrase"] = "迎面", ["word"] = { "楹" } },
	["huhu"] = { ["phrase"] = "呼呼", ["word"] = { "戽" } },
	["yziz"] = { ["phrase"] = "忧愁", ["word"] = { "蝣" } },
	["qmyz"] = { ["phrase"] = "前有", ["word"] = { "谴" } },
	["xpur"] = { ["phrase"] = "血栓", ["word"] = { "颉" } },
	["xuno"] = { ["phrase"] = "许诺", ["word"] = { "婿" } },
	["yjhj"] = { ["phrase"] = "严寒", ["word"] = { "焰" } },
	["lkds"] = { ["phrase"] = "灵动", ["word"] = { "泠" } },
	["hrdd"] = { ["phrase"] = "还贷", ["word"] = { "涣", "奂" } },
	["jicu"] = { ["phrase"] = "急促", ["word"] = { "蒺" } },
	["ihxm"] = { ["phrase"] = "长线", ["word"] = { "氅" } },
	["fwfw"] = { ["phrase"] = "飞飞", ["word"] = { "斐" } },
	["jqpa"] = { ["phrase"] = "就怕", ["word"] = { "臼" } },
	["jink"] = { ["phrase"] = "济宁", ["word"] = { "犄" } },
	["jldd"] = { ["phrase"] = "将带", ["word"] = { "奖" } },
	["monm"] = { ["phrase"] = "末年", ["word"] = { "嬷" } },
	["jbry"] = { ["phrase"] = "浸润", ["word"] = { "仅" } },
	["lkks"] = { ["phrase"] = "凌空", ["word"] = { "呤", "囹" } },
	["ichu"] = { ["phrase"] = "巢湖", ["word"] = { "炒", "焯" } },
	["xnkk"] = { ["phrase"] = "小块", ["word"] = { "嚣" } },
	["vimb"] = { ["phrase"] = "殖民", ["word"] = { "枳" } },
	["qpxn"] = { ["phrase"] = "切削", ["word"] = { "慊" } },
	["bmzc"] = { ["phrase"] = "编造", ["word"] = { "遍" } },
	["yjif"] = { ["phrase"] = "烟尘", ["word"] = { "雁" } },
	["mibi"] = { ["phrase"] = "密闭", ["word"] = { "蜜" } },
	["jiyt"] = { ["phrase"] = "集约", ["word"] = { "畿" } },
	["qimb"] = { ["phrase"] = "器皿", ["word"] = { "棋", "骐" } },
	["nikk"] = { ["phrase"] = "你快", ["word"] = { "匿" } },
	["yzyj"] = { ["phrase"] = "油烟", ["word"] = { "羑" } },
	["jujb"] = { ["phrase"] = "距今", ["word"] = { "飓" } },
	["jnuh"] = { ["phrase"] = "脚上", ["word"] = { "礁" } },
	["vuve"] = { ["phrase"] = "住着", ["word"] = { "邾", "竺" } },
	["izrf"] = { ["phrase"] = "仇人", ["word"] = { "雠" } },
	["jnyh"] = { ["phrase"] = "教养", ["word"] = { "醮" } },
	["ujye"] = { ["phrase"] = "山野", ["word"] = { "讪", "鄯" } },
	["xpdi"] = { ["phrase"] = "鞋底", ["word"] = { "蟹" } },
	["xikj"] = { ["phrase"] = "细看", ["word"] = { "吸", "唏" } },
	["hetm"] = { ["phrase"] = "和田", ["word"] = { "盍" } },
	["yizy"] = { ["phrase"] = "一尊", ["word"] = { "迤" } },
	["hrbi"] = { ["phrase"] = "环比", ["word"] = { "宦" } },
	["xmnm"] = { ["phrase"] = "现年", ["word"] = { "娴" } },
	["wutk"] = { ["phrase"] = "舞厅", ["word"] = { "圬" } },
	["jidd"] = { ["phrase"] = "几代", ["word"] = { "剞" } },
	["jbso"] = { ["phrase"] = "紧缩", ["word"] = { "缙" } },
	["jucj"] = { ["phrase"] = "聚餐", ["word"] = { "苣" } },
	["guuu"] = { ["phrase"] = "古树", ["word"] = { "辜" } },
	["bojb"] = { ["phrase"] = "铂金", ["word"] = { "钵", "铂" } },
	["wwtn"] = { ["phrase"] = "微调", ["word"] = { "畏" } },
	["jisv"] = { ["phrase"] = "脊髓", ["word"] = { "继" } },
	["yihx"] = { ["phrase"] = "异化", ["word"] = { "移", "黟" } },
	["jkxx"] = { ["phrase"] = "惊吓", ["word"] = { "惊", "憬" } },
	["yuyr"] = { ["phrase"] = "余元", ["word"] = { "欤" } },
	["yyls"] = { ["phrase"] = "云龙", ["word"] = { "耘" } },
	["lquu"] = { ["phrase"] = "柳树", ["word"] = { "碌" } },
	["xpyb"] = { ["phrase"] = "谐音", ["word"] = { "谐" } },
	["jigv"] = { ["phrase"] = "机柜", ["word"] = { "既" } },
	["volu"] = { ["phrase"] = "着陆", ["word"] = { "卓" } },
	["qidu"] = { ["phrase"] = "气度", ["word"] = { "漆" } },
	["gcyh"] = { ["phrase"] = "羔羊", ["word"] = { "羔" } },
	["hxru"] = { ["phrase"] = "划入", ["word"] = { "华" } },
	["yjig"] = { ["phrase"] = "严惩", ["word"] = { "魇" } },
	["jicd"] = { ["phrase"] = "基材", ["word"] = { "蓟" } },
	["liln"] = { ["phrase"] = "理疗", ["word"] = { "鹂" } },
	["xbju"] = { ["phrase"] = "新居", ["word"] = { "锌" } },
	["yure"] = { ["phrase"] = "预热", ["word"] = { "觎" } },
	["ujhd"] = { ["phrase"] = "山海", ["word"] = { "剡" } },
	["xipd"] = { ["phrase"] = "洗牌", ["word"] = { "夕", "奚", "禊" } },
	["fusd"] = { ["phrase"] = "复赛", ["word"] = { "绂" } },
	["hudu"] = { ["phrase"] = "弧度", ["word"] = { "户", "斛" } },
	["xpmc"] = { ["phrase"] = "鞋帽", ["word"] = { "械", "榭" } },
	["bagd"] = { ["phrase"] = "把该", ["word"] = { "魃" } },
	["tjta"] = { ["phrase"] = "坍塌", ["word"] = { "坦" } },
	["tibn"] = { ["phrase"] = "体表", ["word"] = { "鹈" } },
	["vjmk"] = { ["phrase"] = "站名", ["word"] = { "毡", "粘" } },
	["xmzz"] = { ["phrase"] = "先走", ["word"] = { "跹" } },
	["xixx"] = { ["phrase"] = "西夏", ["word"] = { "恓" } },
	["jqbj"] = { ["phrase"] = "旧版", ["word"] = { "究", "疚" } },
	["yjdd"] = { ["phrase"] = "眼袋", ["word"] = { "淹", "奄" } },
	["xnvs"] = { ["phrase"] = "消肿", ["word"] = { "箫" } },
	["qkuf"] = { ["phrase"] = "情深", ["word"] = { "罄" } },
	["xidj"] = { ["phrase"] = "西单", ["word"] = { "浠", "淅" } },
	["hvcs"] = { ["phrase"] = "慧聪", ["word"] = { "荟" } },
	["jido"] = { ["phrase"] = "几多", ["word"] = { "脊" } },
	["qicj"] = { ["phrase"] = "凄惨", ["word"] = { "芑", "蕲" } },
	["qmjq"] = { ["phrase"] = "迁就", ["word"] = { "钎" } },
	["bwuj"] = { ["phrase"] = "被删", ["word"] = { "鐾" } },
	["dumo"] = { ["phrase"] = "镀膜", ["word"] = { "阇" } },
	["uiru"] = { ["phrase"] = "驶入", ["word"] = { "什", "仕" } },
	["vizu"] = { ["phrase"] = "知足", ["word"] = { "跖" } },
	["yjmd"] = { ["phrase"] = "掩埋", ["word"] = { "阉", "阏" } },
	["xnds"] = { ["phrase"] = "晓东", ["word"] = { "潇" } },
	["tixp"] = { ["phrase"] = "题写", ["word"] = { "悌" } },
	["tvhz"] = { ["phrase"] = "退后", ["word"] = { "煺" } },
	["hvds"] = { ["phrase"] = "挥动", ["word"] = { "浍" } },
	["jbma"] = { ["phrase"] = "金马", ["word"] = { "槿" } },
	["qmbu"] = { ["phrase"] = "前部", ["word"] = { "搴" } },
	["jpyk"] = { ["phrase"] = "接应", ["word"] = { "诘" } },
	["jidk"] = { ["phrase"] = "既定", ["word"] = { "奇" } },
	["gsbk"] = { ["phrase"] = "工兵", ["word"] = { "宫" } },
	["jitj"] = { ["phrase"] = "祭坛", ["word"] = { "圾" } },
	["svuu"] = { ["phrase"] = "岁数", ["word"] = { "尿", "碎" } },
	["visu"] = { ["phrase"] = "质素", ["word"] = { "纸" } },
	["gujk"] = { ["phrase"] = "古井", ["word"] = { "钴", "锢" } },
	["yiku"] = { ["phrase"] = "衣裤", ["word"] = { "医" } },
	["gojy"] = { ["phrase"] = "国君", ["word"] = { "帼" } },
	["fukf"] = { ["phrase"] = "复垦", ["word"] = { "呋" } },
	["qise"] = { ["phrase"] = "起色", ["word"] = { "缉" } },
	["vjmj"] = { ["phrase"] = "沾满", ["word"] = { "栈" } },
	["xiuh"] = { ["phrase"] = "席上", ["word"] = { "熹" } },
}

return dup_table
