local dup_table = {
    ["xuyk"] = {["phrase"] = "需要", ["word"] = {"酗"}},
    ["vidu"] = {["phrase"] = "制度", ["word"] = {"汁"}},
    ["yihb"] = {["phrase"] = "以后", ["word"] = {"熠"}},
    ["viyb"] = {["phrase"] = "只有", ["word"] = {"识"}},
    ["yidm"] = {["phrase"] = "一点", ["word"] = {"溢"}},
    ["jihw"] = {["phrase"] = "计划", ["word"] = {"稷"}},
    ["vkdk"] = {["phrase"] = "找到", ["word"] = {"召", "沼"}},
    ["jmdj"] = {["phrase"] = "简单", ["word"] = {"渐", "溅"}},
    ["sudu"] = {["phrase"] = "速度", ["word"] = {"涑", "觫"}},
    ["uiui"] = {["phrase"] = "实施", ["word"] = {"蚀"}},
    ["likl"] = {["phrase"] = "离开", ["word"] = {"哩", "呖", "喱"}},
    ["yijm"] = {["phrase"] = "意见", ["word"] = {"镒"}},
    ["yudk"] = {["phrase"] = "遇到", ["word"] = {"浴"}},
    ["jisr"] = {["phrase"] = "计算", ["word"] = {"绩"}},
    ["vifu"] = {["phrase"] = "支付", ["word"] = {"挚"}},
    ["yibm"] = {["phrase"] = "一边", ["word"] = {"益"}},
    ["fujn"] = {["phrase"] = "附近", ["word"] = {"幞"}},
    ["jike"] = {["phrase"] = "即可", ["word"] = {"唧"}},
    ["mznm"] = {["phrase"] = "每年", ["word"] = {"媒"}},
    ["y;go"] = {["phrase"] = "英国", ["word"] = {"膺"}},
    ["y;wf"] = {["phrase"] = "英文", ["word"] = {"赢", "嬴"}},
    ["hvdk"] = {["phrase"] = "回到", ["word"] = {"汇", "洄"}},
    ["vibc"] = {["phrase"] = "指标", ["word"] = {"痔"}},
    ["jxkb"] = {["phrase"] = "接口", ["word"] = {"喈"}},
    ["qidl"] = {["phrase"] = "期待", ["word"] = {"泣"}},
    ["sikk"] = {["phrase"] = "思考", ["word"] = {"嗣"}},
    ["yidj"] = {["phrase"] = "一旦", ["word"] = {"沂"}},
    ["yiky"] = {["phrase"] = "一块", ["word"] = {"匜", "咦", "咿"}},
    ["jiyu"] = {["phrase"] = "基于", ["word"] = {"计"}},
    ["ufru"] = {["phrase"] = "深入", ["word"] = {"什", "伸"}},
    ["xmde"] = {["phrase"] = "显得", ["word"] = {"洗", "冼"}},
    ["yixd"] = {["phrase"] = "一项", ["word"] = {"刈"}},
    ["didm"] = {["phrase"] = "地点", ["word"] = {"涤"}},
    ["uivi"] = {["phrase"] = "是指", ["word"] = {"虱"}},
    ["yikr"] = {["phrase"] = "一款", ["word"] = {"颐"}},
    ["uiyb"] = {["phrase"] = "是由", ["word"] = {"识"}},
    ["ykpn"] = {["phrase"] = "药品", ["word"] = {"鹞"}},
    ["jwju"] = {["phrase"] = "家具", ["word"] = {"镓"}},
    ["uiqu"] = {["phrase"] = "失去", ["word"] = {"舐"}},
    ["vize"] = {["phrase"] = "职责", ["word"] = {"踯"}},
    ["jxdk"] = {["phrase"] = "街道", ["word"] = {"洁"}},
    ["ykba"] = {["phrase"] = "要把", ["word"] = {"疟"}},
    ["tsdk"] = {["phrase"] = "通道", ["word"] = {"洞"}},
    ["yiyk"] = {["phrase"] = "医药", ["word"] = {"诒"}},
    ["yidk"] = {["phrase"] = "一道", ["word"] = {"漪"}},
    ["jpdv"] = {["phrase"] = "军队", ["word"] = {"龟"}},
    ["yikk"] = {["phrase"] = "依靠", ["word"] = {"贻"}},
    ["luqu"] = {["phrase"] = "录取", ["word"] = {"氯"}},
    ["uiti"] = {["phrase"] = "试题", ["word"] = {"螫"}},
    ["gsgu"] = {["phrase"] = "巩固", ["word"] = {"汞"}},
    ["yily"] = {["phrase"] = "一律", ["word"] = {"毅"}},
    ["qiqr"] = {["phrase"] = "齐全", ["word"] = {"欺"}},
    ["jizl"] = {["phrase"] = "记载", ["word"] = {"跻"}},
    ["fudk"] = {["phrase"] = "辅导", ["word"] = {"涪"}},
    ["vifh"] = {["phrase"] = "脂肪", ["word"] = {"摭"}},
    ["jnll"] = {["phrase"] = "进来", ["word"] = {"巾"}},
    ["jidj"] = {["phrase"] = "鸡蛋", ["word"] = {"汲"}},
    ["fuyb"] = {["phrase"] = "富有", ["word"] = {"讣"}},
    ["grdk"] = {["phrase"] = "管道", ["word"] = {"涫"}},
    ["qqdv"] = {["phrase"] = "球队", ["word"] = {"龟"}},
    ["wudk"] = {["phrase"] = "舞蹈", ["word"] = {"污", "浯"}},
    ["buld"] = {["phrase"] = "不良", ["word"] = {"卜"}},
    ["furf"] = {["phrase"] = "夫人", ["word"] = {"佛"}},
    ["yida"] = {["phrase"] = "一大", ["word"] = {"殪"}},
    ["yikb"] = {["phrase"] = "一口", ["word"] = {"邑"}},
    ["qicl"] = {["phrase"] = "器材", ["word"] = {"荠"}},
    ["yrtx"] = {["phrase"] = "原帖", ["word"] = {"塬"}},
    ["vudo"] = {["phrase"] = "诸多", ["word"] = {"渚", "潴"}},
    ["jmmm"] = {["phrase"] = "见面", ["word"] = {"槛"}},
    ["licl"] = {["phrase"] = "理财", ["word"] = {"荔", "苈", "莅"}},
    ["jiyn"] = {["phrase"] = "基因", ["word"] = {"鸡"}},
    ["yixc"] = {["phrase"] = "一笑", ["word"] = {"羿"}},
    ["qidm"] = {["phrase"] = "起点", ["word"] = {"柒"}},
    ["bukf"] = {["phrase"] = "不肯", ["word"] = {"哺"}},
    ["jiho"] = {["phrase"] = "激活", ["word"] = {"稽"}},
    ["jihe"] = {["phrase"] = "集合", ["word"] = {"嵇"}},
    ["yeye"] = {["phrase"] = "爷爷", ["word"] = {"邺"}},
    ["ykjd"] = {["phrase"] = "要将", ["word"] = {"铫"}},
    ["mucl"] = {["phrase"] = "木材", ["word"] = {"募"}},
    ["yiiu"] = {["phrase"] = "一处", ["word"] = {"轶"}},
    ["tjdk"] = {["phrase"] = "谈到", ["word"] = {"澹"}},
    ["jida"] = {["phrase"] = "极大", ["word"] = {"殛"}},
    ["yjve"] = {["phrase"] = "沿着", ["word"] = {"鄢"}},
    ["lddm"] = {["phrase"] = "亮点", ["word"] = {"梁", "粱"}},
    ["yuwo"] = {["phrase"] = "与我", ["word"] = {"育"}},
    ["yuky"] = {["phrase"] = "愉快", ["word"] = {"吁", "喁"}},
    ["yaii"] = {["phrase"] = "牙齿", ["word"] = {"衙"}},
    ["tkfh"] = {["phrase"] = "套房", ["word"] = {"焘"}},
    ["iuui"] = {["phrase"] = "出示", ["word"] = {"础"}},
    ["bzpo"] = {["phrase"] = "被迫", ["word"] = {"褙"}},
    ["tamz"] = {["phrase"] = "他没", ["word"] = {"闼"}},
    ["xmuh"] = {["phrase"] = "线上", ["word"] = {"燹"}},
    ["jmbh"] = {["phrase"] = "肩膀", ["word"] = {"煎"}},
    ["xdwz"] = {["phrase"] = "香味", ["word"] = {"享"}},
    ["zidr"] = {["phrase"] = "字段", ["word"] = {"资", "渍"}},
    ["uidr"] = {["phrase"] = "时段", ["word"] = {"湜"}},
    ["gsgr"] = {["phrase"] = "公关", ["word"] = {"贡"}},
    ["dide"] = {["phrase"] = "低的", ["word"] = {"邸"}},
    ["ufsu"] = {["phrase"] = "申诉", ["word"] = {"绅"}},
    ["xmee"] = {["phrase"] = "限额", ["word"] = {"岘"}},
    ["fuvl"] = {["phrase"] = "负债", ["word"] = {"弗"}},
    ["livi"] = {["phrase"] = "理智", ["word"] = {"蠡"}},
    ["jxuv"] = {["phrase"] = "节水", ["word"] = {"碣"}},
    ["qrjw"] = {["phrase"] = "全家", ["word"] = {"铨"}},
    ["ufye"] = {["phrase"] = "深夜", ["word"] = {"诜"}},
    ["hedk"] = {["phrase"] = "河道", ["word"] = {"河", "涸"}},
    ["jibu"] = {["phrase"] = "既不", ["word"] = {"疾"}},
    ["suyh"] = {["phrase"] = "素养", ["word"] = {"酥"}},
    ["iuih"] = {["phrase"] = "出场", ["word"] = {"蜍"}},
    ["yjii"] = {["phrase"] = "延迟", ["word"] = {"衍"}},
    ["xtya"] = {["phrase"] = "血压", ["word"] = {"谑"}},
    ["jmro"] = {["phrase"] = "减弱", ["word"] = {"僭"}},
    ["liwl"] = {["phrase"] = "例外", ["word"] = {"理"}},
    ["ubbc"] = {["phrase"] = "手表", ["word"] = {"守"}},
    ["liqd"] = {["phrase"] = "李强", ["word"] = {"猁"}},
    ["hdjw"] = {["phrase"] = "皇家", ["word"] = {"凰", "幌"}},
    ["iumo"] = {["phrase"] = "触摸", ["word"] = {"楮"}},
    ["vjdk"] = {["phrase"] = "占到", ["word"] = {"沾", "詹"}},
    ["uian"] = {["phrase"] = "是按", ["word"] = {"豕"}},
    ["qimj"] = {["phrase"] = "期满", ["word"] = {"杞", "桤"}},
    ["wuxw"] = {["phrase"] = "武侠", ["word"] = {"怃", "忤"}},
    ["yuuh"] = {["phrase"] = "遇上", ["word"] = {"熨"}},
    ["vidv"] = {["phrase"] = "支队", ["word"] = {"沚"}},
    ["ypss"] = {["phrase"] = "运送", ["word"] = {"纭"}},
    ["jmvj"] = {["phrase"] = "建站", ["word"] = {"笺"}},
    ["libl"] = {["phrase"] = "李白", ["word"] = {"疬"}},
    ["lian"] = {["phrase"] = "立案", ["word"] = {"吏"}},
    ["qipj"] = {["phrase"] = "期盼", ["word"] = {"祈"}},
    ["yrde"] = {["phrase"] = "远的", ["word"] = {"沅"}},
    ["fucl"] = {["phrase"] = "福彩", ["word"] = {"芾"}},
    ["mksi"] = {["phrase"] = "貌似", ["word"] = {"蝥", "蟊"}},
    ["viuo"] = {["phrase"] = "之说", ["word"] = {"智"}},
    ["ckmz"] = {["phrase"] = "草莓", ["word"] = {"糙"}},
    ["iaua"] = {["phrase"] = "查杀", ["word"] = {"馇", "碴"}},
    ["jiny"] = {["phrase"] = "妓女", ["word"] = {"妓"}},
    ["mmdm"] = {["phrase"] = "缅甸", ["word"] = {"沔", "湎"}},
    ["jiug"] = {["phrase"] = "计生", ["word"] = {"戟"}},
    ["dbba"] = {["phrase"] = "都把", ["word"] = {"痘"}},
    ["zlbu"] = {["phrase"] = "再不", ["word"] = {"宰"}},
    ["yugl"] = {["phrase"] = "与该", ["word"] = {"鬻"}},
    ["vjdv"] = {["phrase"] = "战队", ["word"] = {"湛"}},
    ["rude"] = {["phrase"] = "入的", ["word"] = {"濡"}},
    ["yier"] = {["phrase"] = "一二", ["word"] = {"嶷"}},
    ["mogu"] = {["phrase"] = "蘑菇", ["word"] = {"摩", "磨"}},
    ["vgfa"] = {["phrase"] = "蒸发", ["word"] = {"拯"}},
    ["zibz"] = {["phrase"] = "自卑", ["word"] = {"字", "孳"}},
    ["jivj"] = {["phrase"] = "激战", ["word"] = {"笈"}},
    ["hsbk"] = {["phrase"] = "红包", ["word"] = {"訇"}},
    ["fjuf"] = {["phrase"] = "翻身", ["word"] = {"矾"}},
    ["hjdk"] = {["phrase"] = "喊道", ["word"] = {"涵"}},
    ["jmmz"] = {["phrase"] = "健美", ["word"] = {"毽"}},
    ["hsds"] = {["phrase"] = "轰动", ["word"] = {"泓"}},
    ["juzu"] = {["phrase"] = "剧组", ["word"] = {"遽"}},
    ["hwmu"] = {["phrase"] = "花木", ["word"] = {"桦", "骅"}},
    ["wuyr"] = {["phrase"] = "无缘", ["word"] = {"诬"}},
    ["jiee"] = {["phrase"] = "饥饿", ["word"] = {"觊"}},
    ["yjig"] = {["phrase"] = "盐城", ["word"] = {"魇"}},
    ["cjlm"] = {["phrase"] = "残联", ["word"] = {"粲"}},
    ["tofu"] = {["phrase"] = "托福", ["word"] = {"拓"}},
    ["j;vd"] = {["phrase"] = "精装", ["word"] = {"刭"}},
    ["jxmk"] = {["phrase"] = "睫毛", ["word"] = {"桔"}},
    ["yell"] = {["phrase"] = "也来", ["word"] = {"野"}},
    ["ynvg"] = {["phrase"] = "印证", ["word"] = {"龈"}},
    ["dlru"] = {["phrase"] = "带入", ["word"] = {"傣"}},
    ["xxye"] = {["phrase"] = "鞋业", ["word"] = {"邪"}},
    ["uuhu"] = {["phrase"] = "疏忽", ["word"] = {"秫", "黍"}},
    ["ueii"] = {["phrase"] = "奢侈", ["word"] = {"厍"}},
    ["cvmm"] = {["phrase"] = "催眠", ["word"] = {"毳"}},
    ["anbm"] = {["phrase"] = "岸边", ["word"] = {"案"}},
    ["yjke"] = {["phrase"] = "眼科", ["word"] = {"郾"}},
    ["xiuj"] = {["phrase"] = "西山", ["word"] = {"豨"}},
    ["viuf"] = {["phrase"] = "之神", ["word"] = {"雉"}},
    ["vhmu"] = {["phrase"] = "账目", ["word"] = {"樟"}},
    ["viju"] = {["phrase"] = "之举", ["word"] = {"帙"}},
    ["yiru"] = {["phrase"] = "一如", ["word"] = {"佚"}},
    ["jdyn"] = {["phrase"] = "江阴", ["word"] = {"姜"}},
    ["ssds"] = {["phrase"] = "松动", ["word"] = {"凇", "淞"}},
    ["vbye"] = {["phrase"] = "昼夜", ["word"] = {"诌"}},
    ["lowf"] = {["phrase"] = "螺纹", ["word"] = {"雒"}},
    ["quii"] = {["phrase"] = "去吃", ["word"] = {"衢"}},
    ["jmbk"] = {["phrase"] = "简报", ["word"] = {"謇"}},
    ["yrdl"] = {["phrase"] = "元代", ["word"] = {"渊"}},
    ["hjfg"] = {["phrase"] = "寒风", ["word"] = {"捍"}},
    ["zimz"] = {["phrase"] = "姊妹", ["word"] = {"籽"}},
    ["ykxx"] = {["phrase"] = "要写", ["word"] = {"爻"}},
    ["sitc"] = {["phrase"] = "四条", ["word"] = {"寺"}},
    ["vuzi"] = {["phrase"] = "竹子", ["word"] = {"躅"}},
    ["hddb"] = {["phrase"] = "黄豆", ["word"] = {"潢"}},
    ["uiln"] = {["phrase"] = "石林", ["word"] = {"史"}},
    ["yipn"] = {["phrase"] = "一品", ["word"] = {"乂"}},
    ["djdk"] = {["phrase"] = "但到", ["word"] = {"澹"}},
    ["iizk"] = {["phrase"] = "迟早", ["word"] = {"踟"}},
    ["vudv"] = {["phrase"] = "主队", ["word"] = {"注", "洙"}},
    ["jiwj"] = {["phrase"] = "几万", ["word"] = {"玑"}},
    ["j;lo"] = {["phrase"] = "经络", ["word"] = {"靖"}},
    ["y;mm"] = {["phrase"] = "迎面", ["word"] = {"楹"}},
    ["y;bn"] = {["phrase"] = "迎宾", ["word"] = {"瘿"}},
    ["huhu"] = {["phrase"] = "呼呼", ["word"] = {"戽"}},
    ["xihj"] = {["phrase"] = "西汉", ["word"] = {"稀", "烯"}},
    ["jxbl"] = {["phrase"] = "洁白", ["word"] = {"疥"}},
    ["jidk"] = {["phrase"] = "即到", ["word"] = {"奇"}},
    ["wzjw"] = {["phrase"] = "为佳", ["word"] = {"帏"}},
    ["xcxd"] = {["phrase"] = "潇湘", ["word"] = {"削"}},
    ["ximx"] = {["phrase"] = "熄灭", ["word"] = {"粞"}},
    ["quhw"] = {["phrase"] = "区划", ["word"] = {"黢"}},
    ["xuno"] = {["phrase"] = "许诺", ["word"] = {"婿"}},
    ["xrjd"] = {["phrase"] = "宣讲", ["word"] = {"券"}},
    ["yjhj"] = {["phrase"] = "严寒", ["word"] = {"焰"}},
    ["uhtk"] = {["phrase"] = "商讨", ["word"] = {"垧", "墒"}},
    ["gsbk"] = {["phrase"] = "公报", ["word"] = {"宫"}},
    ["l;ds"] = {["phrase"] = "灵动", ["word"] = {"泠"}},
    ["pcxd"] = {["phrase"] = "飘香", ["word"] = {"剽"}},
    ["tmdk"] = {["phrase"] = "天道", ["word"] = {"湉"}},
    ["jicu"] = {["phrase"] = "急促", ["word"] = {"蒺"}},
    ["yuyk"] = {["phrase"] = "余姚", ["word"] = {"语", "雩"}},
    ["uiky"] = {["phrase"] = "石块", ["word"] = {"嘘"}},
    ["lizl"] = {["phrase"] = "立在", ["word"] = {"逦", "跞"}},
    ["q;ck"] = {["phrase"] = "青草", ["word"] = {"苘"}},
    ["ihxm"] = {["phrase"] = "长线", ["word"] = {"氅"}},
    ["ykky"] = {["phrase"] = "要快", ["word"] = {"吆"}},
    ["jqpa"] = {["phrase"] = "就怕", ["word"] = {"臼"}},
    ["monm"] = {["phrase"] = "末年", ["word"] = {"嬷"}},
    ["ykbl"] = {["phrase"] = "摇摆", ["word"] = {"窈"}},
    ["l;ks"] = {["phrase"] = "凌空", ["word"] = {"呤", "囹"}},
    ["ikhu"] = {["phrase"] = "巢湖", ["word"] = {"炒", "焯"}},
    ["wzdo"] = {["phrase"] = "为多", ["word"] = {"洧", "渭"}},
    ["yjif"] = {["phrase"] = "烟尘", ["word"] = {"雁"}},
    ["mibi"] = {["phrase"] = "密闭", ["word"] = {"蜜"}},
    ["jiyt"] = {["phrase"] = "集约", ["word"] = {"畿"}},
    ["ynjd"] = {["phrase"] = "银奖", ["word"] = {"铟"}},
    ["ybyj"] = {["phrase"] = "油烟", ["word"] = {"羑"}},
    ["jcuh"] = {["phrase"] = "脚上", ["word"] = {"礁"}},
    ["vuve"] = {["phrase"] = "住着", ["word"] = {"邾", "竺"}},
    ["ibrf"] = {["phrase"] = "仇人", ["word"] = {"雠"}},
    ["juhk"] = {["phrase"] = "句号", ["word"] = {"焗"}},
    ["fumz"] = {["phrase"] = "赴美", ["word"] = {"桴"}},
    ["jcyh"] = {["phrase"] = "教养", ["word"] = {"醮"}},
    ["gekl"] = {["phrase"] = "隔开", ["word"] = {"嗝"}},
    ["ujye"] = {["phrase"] = "山野", ["word"] = {"讪", "鄯"}},
    ["jian"] = {["phrase"] = "吉安", ["word"] = {"棘"}},
    ["xxdi"] = {["phrase"] = "鞋底", ["word"] = {"蟹"}},
    ["xikj"] = {["phrase"] = "细看", ["word"] = {"吸", "唏"}},
    ["ybyn"] = {["phrase"] = "又因", ["word"] = {"诱"}},
    ["hetm"] = {["phrase"] = "和田", ["word"] = {"盍"}},
    ["bodb"] = {["phrase"] = "搏斗", ["word"] = {"泊"}},
    ["pibk"] = {["phrase"] = "皮包", ["word"] = {"否", "痞"}},
    ["hrbi"] = {["phrase"] = "环比", ["word"] = {"宦"}},
    ["xmnm"] = {["phrase"] = "现年", ["word"] = {"娴"}},
    ["jidl"] = {["phrase"] = "几代", ["word"] = {"济"}},
    ["jnso"] = {["phrase"] = "紧缩", ["word"] = {"缙"}},
    ["jucj"] = {["phrase"] = "聚餐", ["word"] = {"苣"}},
    ["yilx"] = {["phrase"] = "一列", ["word"] = {"意", "翊"}},
    ["guuu"] = {["phrase"] = "古树", ["word"] = {"辜"}},
    ["jisv"] = {["phrase"] = "脊髓", ["word"] = {"继"}},
    ["xixx"] = {["phrase"] = "吸血", ["word"] = {"恓"}},
    ["hrky"] = {["phrase"] = "欢快", ["word"] = {"圜"}},
    ["yuxd"] = {["phrase"] = "预想", ["word"] = {"愉"}},
    ["yuyr"] = {["phrase"] = "余元", ["word"] = {"欤"}},
    ["bizl"] = {["phrase"] = "比在", ["word"] = {"鼻"}},
    ["ypls"] = {["phrase"] = "云龙", ["word"] = {"耘"}},
    ["lquu"] = {["phrase"] = "柳树", ["word"] = {"碌"}},
    ["jigv"] = {["phrase"] = "机柜", ["word"] = {"既"}},
    ["yusl"] = {["phrase"] = "预赛", ["word"] = {"予"}},
    ["volu"] = {["phrase"] = "着陆", ["word"] = {"卓"}},
    ["qidu"] = {["phrase"] = "气度", ["word"] = {"漆"}},
    ["gkyh"] = {["phrase"] = "羔羊", ["word"] = {"羔"}},
    ["hwru"] = {["phrase"] = "划入", ["word"] = {"华"}},
    ["jicl"] = {["phrase"] = "基材", ["word"] = {"荠"}},
    ["wubk"] = {["phrase"] = "五保", ["word"] = {"痦", "寤"}},
    ["xnju"] = {["phrase"] = "新居", ["word"] = {"锌"}},
    ["yure"] = {["phrase"] = "预热", ["word"] = {"觎"}},
    ["qdji"] = {["phrase"] = "羟基", ["word"] = {"镪"}},
    ["viky"] = {["phrase"] = "之快", ["word"] = {"吱"}},
    ["bovb"] = {["phrase"] = "亳州", ["word"] = {"舶", "箔"}},
    ["hudu"] = {["phrase"] = "弧度", ["word"] = {"户", "斛"}},
    ["erde"] = {["phrase"] = "尔德", ["word"] = {"洱"}},
    ["tjta"] = {["phrase"] = "坍塌", ["word"] = {"坦"}},
    ["liln"] = {["phrase"] = "莅临", ["word"] = {"鹂"}},
    ["wuwl"] = {["phrase"] = "屋外", ["word"] = {"务"}},
    ["jqbj"] = {["phrase"] = "旧版", ["word"] = {"究", "疚"}},
    ["suxx"] = {["phrase"] = "速写", ["word"] = {"愫"}},
    ["xmmn"] = {["phrase"] = "先民", ["word"] = {"鹇"}},
    ["xidj"] = {["phrase"] = "西单", ["word"] = {"浠", "淅"}},
    ["xcvs"] = {["phrase"] = "消肿", ["word"] = {"箫"}},
    ["q;uf"] = {["phrase"] = "情深", ["word"] = {"罄"}},
    ["hvcs"] = {["phrase"] = "慧聪", ["word"] = {"荟"}},
    ["bkvs"] = {["phrase"] = "包中", ["word"] = {"龅"}},
    ["jido"] = {["phrase"] = "几多", ["word"] = {"脊"}},
    ["qicj"] = {["phrase"] = "凄惨", ["word"] = {"芑", "蕲"}},
    ["qmjq"] = {["phrase"] = "迁就", ["word"] = {"钎"}},
    ["bzuj"] = {["phrase"] = "被删", ["word"] = {"鐾"}},
    ["dumo"] = {["phrase"] = "镀膜", ["word"] = {"阇"}},
    ["uiru"] = {["phrase"] = "驶入", ["word"] = {"什", "仕"}},
    ["vizu"] = {["phrase"] = "知足", ["word"] = {"跖"}},
    ["xcds"] = {["phrase"] = "晓东", ["word"] = {"潇"}},
    ["gubk"] = {["phrase"] = "古堡", ["word"] = {"谷", "痼"}},
    ["hvds"] = {["phrase"] = "挥动", ["word"] = {"浍"}},
    ["jnma"] = {["phrase"] = "金马", ["word"] = {"槿"}},
    ["qmbu"] = {["phrase"] = "前部", ["word"] = {"搴"}},
    ["jitj"] = {["phrase"] = "祭坛", ["word"] = {"圾"}},
    ["svuu"] = {["phrase"] = "岁数", ["word"] = {"尿", "碎"}},
    ["yayn"] = {["phrase"] = "牙龈", ["word"] = {"鸦"}},
    ["visu"] = {["phrase"] = "质素", ["word"] = {"纸"}},
    ["yiku"] = {["phrase"] = "衣裤", ["word"] = {"医"}},
    ["biuu"] = {["phrase"] = "避暑", ["word"] = {"辟"}},
    ["fukf"] = {["phrase"] = "复垦", ["word"] = {"呋"}},
    ["qise"] = {["phrase"] = "起色", ["word"] = {"缉"}},
    ["vjmj"] = {["phrase"] = "沾满", ["word"] = {"栈"}},
    ["xiuh"] = {["phrase"] = "席上", ["word"] = {"熹"}},
    ["mgqn"] = {["phrase"] = "猛禽", ["word"] = {"獴"}},
    ["lidm"] = {["phrase"] = "离店", ["word"] = {"溧"}},
    ["viuy"] = {["phrase"] = "直率", ["word"] = {"支"}},
    ["jisj"] = {["phrase"] = "集散", ["word"] = {"级", "纪"}},
    ["siks"] = {["phrase"] = "司空", ["word"] = {"咝"}},
    ["vrub"] = {["phrase"] = "转手", ["word"] = {"馔"}},
    ["qmdo"] = {["phrase"] = "千多", ["word"] = {"潜"}},
    ["jxyk"] = {["phrase"] = "解药", ["word"] = {"诘"}},
    ["jimb"] = {["phrase"] = "计谋", ["word"] = {"骥"}},
    ["xxyb"] = {["phrase"] = "写有", ["word"] = {"谐"}},
    ["eraa"] = {["phrase"] = "儿啊", ["word"] = {"二", "耳"}},
    ["jwlm"] = {["phrase"] = "价廉", ["word"] = {"驾", "架"}},
    ["jiyj"] = {["phrase"] = "几眼", ["word"] = {"讥", "记"}},
    ["jcml"] = {["phrase"] = "叫卖", ["word"] = {"骄"}},
    ["vafa"] = {["phrase"] = "闸阀", ["word"] = {"揸"}},
    ["jddu"] = {["phrase"] = "江都", ["word"] = {"浆"}},
    ["vibx"] = {["phrase"] = "之别", ["word"] = {"痣"}},
    ["jivb"] = {["phrase"] = "几周", ["word"] = {"箕"}},
    ["tczk"] = {["phrase"] = "跳蚤", ["word"] = {"迢"}},
    ["djba"] = {["phrase"] = "丹巴", ["word"] = {"疸"}},
    ["lmmz"] = {["phrase"] = "联袂", ["word"] = {"梿"}},
    ["jmci"] = {["phrase"] = "见此", ["word"] = {"茧"}},
    ["pkds"] = {["phrase"] = "跑动", ["word"] = {"泡", "匏"}},
    ["l;ys"] = {["phrase"] = "领用", ["word"] = {"羚", "零"}},
    ["uivr"] = {["phrase"] = "师专", ["word"] = {"筮"}},
    ["xddo"] = {["phrase"] = "想多", ["word"] = {"湘"}},
    ["mmdl"] = {["phrase"] = "面带", ["word"] = {"勉"}},
    ["luvu"] = {["phrase"] = "露珠", ["word"] = {"舻", "箓"}},
    ["ssys"] = {["phrase"] = "怂恿", ["word"] = {"讼"}},
    ["xmdz"] = {["phrase"] = "先得", ["word"] = {"涎"}},
    ["xukl"] = {["phrase"] = "虚开", ["word"] = {"勖"}},
    ["yjdb"] = {["phrase"] = "烟斗", ["word"] = {"演", "滟"}},
    ["yjwh"] = {["phrase"] = "阎王", ["word"] = {"琰"}},
    ["hvyh"] = {["phrase"] = "惠阳", ["word"] = {"诙"}},
    ["mige"] = {["phrase"] = "米格", ["word"] = {"弭"}},
    ["lida"] = {["phrase"] = "利达", ["word"] = {"澧"}},
    ["vidl"] = {["phrase"] = "纸袋", ["word"] = {"觯"}},
    ["bzle"] = {["phrase"] = "背了", ["word"] = {"邶"}},
    ["jmlt"] = {["phrase"] = "鉴略", ["word"] = {"坚"}},
    ["duvs"] = {["phrase"] = "杜仲", ["word"] = {"厾"}},
    ["tomo"] = {["phrase"] = "唾沫", ["word"] = {"椭"}},
    ["xxdm"] = {["phrase"] = "鞋垫", ["word"] = {"渫"}},
    ["uipl"] = {["phrase"] = "实拍", ["word"] = {"释"}},
    ["jihb"] = {["phrase"] = "季后", ["word"] = {"积"}},
    ["bihb"] = {["phrase"] = "壁厚", ["word"] = {"秘", "秕"}},
    ["lqjp"] = {["phrase"] = "刘军", ["word"] = {"镠"}},
    ["yper"] = {["phrase"] = "云儿", ["word"] = {"陨"}},
    ["yelp"] = {["phrase"] = "叶轮", ["word"] = {"曳"}},
    ["jivk"] = {["phrase"] = "几招", ["word"] = {"笄"}},
    ["yiml"] = {["phrase"] = "义卖", ["word"] = {"驿"}},
    ["hktu"] = {["phrase"] = "好图", ["word"] = {"壕"}},
    ["ihxi"] = {["phrase"] = "唱戏", ["word"] = {"怅"}},
    ["lmda"] = {["phrase"] = "联大", ["word"] = {"殓"}},
    ["bibu"] = {["phrase"] = "必不", ["word"] = {"毕"}},
    ["bizu"] = {["phrase"] = "鼻祖", ["word"] = {"避", "跸"}},
    ["uifg"] = {["phrase"] = "适逢", ["word"] = {"拭"}},
    ["zkzo"] = {["phrase"] = "造作", ["word"] = {"遭"}},
    ["hjgr"] = {["phrase"] = "焊管", ["word"] = {"顸"}},
    ["bluu"] = {["phrase"] = "柏树", ["word"] = {"掰"}},
    ["yidb"] = {["phrase"] = "一抖", ["word"] = {"浥"}},
    ["yrxn"] = {["phrase"] = "圆心", ["word"] = {"鸳"}},
    ["jinu"] = {["phrase"] = "激怒", ["word"] = {"嫉"}},
    ["yrfu"] = {["phrase"] = "远赴", ["word"] = {"掾"}},
    ["xpyh"] = {["phrase"] = "驯养", ["word"] = {"醺"}},
    ["yuvk"] = {["phrase"] = "预兆", ["word"] = {"龉"}},
    ["tuuo"] = {["phrase"] = "图说", ["word"] = {"屠"}},
    ["iaka"] = {["phrase"] = "插卡", ["word"] = {"喳"}},
    ["uiuj"] = {["phrase"] = "石山", ["word"] = {"饰"}},
    ["qmdj"] = {["phrase"] = "签单", ["word"] = {"浅"}},
    ["j;le"] = {["phrase"] = "静了", ["word"] = {"竞", "竟"}},
    ["huhh"] = {["phrase"] = "护航", ["word"] = {"烀"}},
    ["yedk"] = {["phrase"] = "也到", ["word"] = {"冶"}},
    ["xpzu"] = {["phrase"] = "寻租", ["word"] = {"迅"}},
    ["uumc"] = {["phrase"] = "树苗", ["word"] = {"树"}},
    ["iude"] = {["phrase"] = "处得", ["word"] = {"刍"}},
    ["pibu"] = {["phrase"] = "坯布", ["word"] = {"癖"}},
    ["ljmj"] = {["phrase"] = "烂漫", ["word"] = {"阑"}},
    ["yjyp"] = {["phrase"] = "烟云", ["word"] = {"严", "谚"}},
    ["kdke"] = {["phrase"] = "旷课", ["word"] = {"贶"}},
    ["yuda"] = {["phrase"] = "愈大", ["word"] = {"鱼", "渔"}},
    ["iumc"] = {["phrase"] = "出苗", ["word"] = {"橱"}},
    ["tjff"] = {["phrase"] = "碳粉", ["word"] = {"摊"}},
    ["qcmm"] = {["phrase"] = "桥面", ["word"] = {"橇"}},
    ["klmj"] = {["phrase"] = "开满", ["word"] = {"闿"}},
    ["yhyn"] = {["phrase"] = "养阴", ["word"] = {"鸯"}},
    ["fugr"] = {["phrase"] = "副官", ["word"] = {"腐"}},
    ["bzuk"] = {["phrase"] = "被烧", ["word"] = {"碚"}},
    ["lumh"] = {["phrase"] = "鲁莽", ["word"] = {"驴"}},
    ["ubbk"] = {["phrase"] = "收报", ["word"] = {"兽"}},
    ["uudc"] = {["phrase"] = "输掉", ["word"] = {"澍"}},
    ["yuhl"] = {["phrase"] = "遇害", ["word"] = {"煜"}},
    ["fuif"] = {["phrase"] = "浮沉", ["word"] = {"辅", "蚨"}},
    ["vihu"] = {["phrase"] = "支护", ["word"] = {"秩"}},
    ["uudu"] = {["phrase"] = "熟读", ["word"] = {"沭"}},
    ["fjmf"] = {["phrase"] = "烦闷", ["word"] = {"梵"}},
    ["viik"] = {["phrase"] = "治超", ["word"] = {"蜘"}},
    ["ighp"] = {["phrase"] = "成婚", ["word"] = {"秤"}},
    ["huwj"] = {["phrase"] = "护腕", ["word"] = {"琥"}},
    ["gomg"] = {["phrase"] = "过猛", ["word"] = {"粿"}},
    ["yjue"] = {["phrase"] = "衍射", ["word"] = {"砚"}},
    ["kakb"] = {["phrase"] = "卡口", ["word"] = {"咔"}},
    ["xmuj"] = {["phrase"] = "仙山", ["word"] = {"馅"}},
    ["ujdo"] = {["phrase"] = "闪躲", ["word"] = {"潸"}},
    ["tikr"] = {["phrase"] = "提款", ["word"] = {"嚏"}},
    ["yiuk"] = {["phrase"] = "一勺", ["word"] = {"饴"}},
    ["xdmn"] = {["phrase"] = "乡民", ["word"] = {"橡"}},
    ["xink"] = {["phrase"] = "洗脑", ["word"] = {"嬉"}},
    ["bmlu"] = {["phrase"] = "边路", ["word"] = {"辨", "辩", "辫"}},
    ["lqdj"] = {["phrase"] = "刘丹", ["word"] = {"鎏"}},
    ["bkzu"] = {["phrase"] = "包租", ["word"] = {"趵"}},
    ["tlfu"] = {["phrase"] = "太傅", ["word"] = {"泰"}},
    ["luln"] = {["phrase"] = "绿林", ["word"] = {"鸬"}},
    ["iigd"] = {["phrase"] = "吃光", ["word"] = {"魑"}},
    ["lrwu"] = {["phrase"] = "乱舞", ["word"] = {"挛"}},
    ["y;ke"] = {["phrase"] = "迎客", ["word"] = {"郢"}},
    ["movb"] = {["phrase"] = "魔咒", ["word"] = {"貊"}},
    ["jmve"] = {["phrase"] = "见者", ["word"] = {"舰", "笕"}},
    ["viib"] = {["phrase"] = "之仇", ["word"] = {"咫"}},
    ["bmdb"] = {["phrase"] = "扁豆", ["word"] = {"汴"}},
    ["ytka"] = {["phrase"] = "月卡", ["word"] = {"曰", "月"}},
    ["livd"] = {["phrase"] = "粒状", ["word"] = {"篱"}},
    ["iivi"] = {["phrase"] = "迟滞", ["word"] = {"蚩"}},
    ["bikb"] = {["phrase"] = "闭口", ["word"] = {"吡"}},
    ["j;fu"] = {["phrase"] = "警服", ["word"] = {"旌"}},
    ["yjdk"] = {["phrase"] = "烟道", ["word"] = {"沿"}},
    ["yibx"] = {["phrase"] = "一别", ["word"] = {"癔"}},
    ["jigj"] = {["phrase"] = "肌酐", ["word"] = {"麂"}},
    ["jxcl"] = {["phrase"] = "劫财", ["word"] = {"芥"}},
    ["lkbl"] = {["phrase"] = "老白", ["word"] = {"痨"}},
    ["zivk"] = {["phrase"] = "自找", ["word"] = {"訾"}},
    ["x;xu"] = {["phrase"] = "兴许", ["word"] = {"性", "惺"}},
    ["eeyk"] = {["phrase"] = "扼要", ["word"] = {"谔"}},
    ["lmjn"] = {["phrase"] = "炼金", ["word"] = {"镰"}},
    ["wzkf"] = {["phrase"] = "围垦", ["word"] = {"唯"}},
    ["hemm"] = {["phrase"] = "河面", ["word"] = {"阖"}},
    ["keiu"] = {["phrase"] = "可出", ["word"] = {"蝌"}},
    ["ruce"] = {["phrase"] = "如厕", ["word"] = {"薷"}},
    ["bzuz"] = {["phrase"] = "被谁", ["word"] = {"孛"}},
    ["ihxw"] = {["phrase"] = "场下", ["word"] = {"敞"}},
    ["qiqx"] = {["phrase"] = "妻妾", ["word"] = {"綦", "憩"}},
    ["bxda"] = {["phrase"] = "别打", ["word"] = {"鳖"}},
    ["mzve"] = {["phrase"] = "没辙", ["word"] = {"郿"}},
    ["jcmx"] = {["phrase"] = "剿灭", ["word"] = {"校"}},
    ["licu"] = {["phrase"] = "力促", ["word"] = {"藜"}},
    ["dojd"] = {["phrase"] = "多讲", ["word"] = {"剁"}},
    ["jrjn"] = {["phrase"] = "卷进", ["word"] = {"镌"}},
    ["qipu"] = {["phrase"] = "棋谱", ["word"] = {"祇"}},
    ["siij"] = {["phrase"] = "私产", ["word"] = {"蛳", "厮"}},
    ["jnrv"] = {["phrase"] = "金瑞", ["word"] = {"今"}},
    ["ighw"] = {["phrase"] = "成化", ["word"] = {"程"}},
    ["xikh"] = {["phrase"] = "西康", ["word"] = {"熙"}},
    ["vimb"] = {["phrase"] = "智谋", ["word"] = {"枳"}},
    ["yuhd"] = {["phrase"] = "玉皇", ["word"] = {"燠"}},
    ["vuky"] = {["phrase"] = "注会", ["word"] = {"嘱"}},
    ["pojd"] = {["phrase"] = "迫降", ["word"] = {"䥽"}},
    ["wuan"] = {["phrase"] = "武安", ["word"] = {"鹉"}},
    ["rudk"] = {["phrase"] = "入道", ["word"] = {"洳"}},
    ["bouu"] = {["phrase"] = "波束", ["word"] = {"擘"}},
    ["iikd"] = {["phrase"] = "痴狂", ["word"] = {"哧"}},
    ["xupn"] = {["phrase"] = "续聘", ["word"] = {"媭"}},
    ["xmce"] = {["phrase"] = "献策", ["word"] = {"苋"}},
    ["bibl"] = {["phrase"] = "必败", ["word"] = {"痹"}},
    ["ybla"] = {["phrase"] = "又拉", ["word"] = {"由", "卣"}},
    ["ijmz"] = {["phrase"] = "谄媚", ["word"] = {"骣"}},
    ["sodu"] = {["phrase"] = "所读", ["word"] = {"挲"}},
    ["fuda"] = {["phrase"] = "福大", ["word"] = {"滏"}},
    ["kedm"] = {["phrase"] = "客店", ["word"] = {"溘"}},
    ["ybro"] = {["phrase"] = "有若", ["word"] = {"侑"}},
    ["hkdu"] = {["phrase"] = "豪赌", ["word"] = {"濠"}},
    ["j;xx"] = {["phrase"] = "精血", ["word"] = {"惊", "憬"}},
    ["jwbk"] = {["phrase"] = "嘉宝", ["word"] = {"痂"}},
    ["ukvo"] = {["phrase"] = "烧灼", ["word"] = {"筲", "艄"}},
    ["jcil"] = {["phrase"] = "交差", ["word"] = {"轿"}},
    ["uhxr"] = {["phrase"] = "上选", ["word"] = {"赏"}},
    ["j;dg"] = {["phrase"] = "警灯", ["word"] = {"泾"}},
    ["xxrb"] = {["phrase"] = "蟹肉", ["word"] = {"偕"}},
    ["piud"] = {["phrase"] = "砒霜", ["word"] = {"劈"}},
    ["wutk"] = {["phrase"] = "五套", ["word"] = {"圬"}},
    ["lukk"] = {["phrase"] = "路考", ["word"] = {"吕", "赂"}},
    ["hbru"] = {["phrase"] = "后入", ["word"] = {"侯", "候"}},
    ["xige"] = {["phrase"] = "洗个", ["word"] = {"觋"}},
    ["uddl"] = {["phrase"] = "双带", ["word"] = {"泷"}},
    ["ynkl"] = {["phrase"] = "引开", ["word"] = {"吲"}},
    ["bidb"] = {["phrase"] = "鼻窦", ["word"] = {"泌"}},
    ["jmma"] = {["phrase"] = "见吗", ["word"] = {"检"}},
    ["tjju"] = {["phrase"] = "炭疽", ["word"] = {"镡"}},
    ["gudg"] = {["phrase"] = "孤灯", ["word"] = {"觚"}},
    ["jwjr"] = {["phrase"] = "家眷", ["word"] = {"颊"}},
    ["wofz"] = {["phrase"] = "我飞", ["word"] = {"挝"}},
    ["jmuj"] = {["phrase"] = "尖山", ["word"] = {"饯"}},
    ["wzhw"] = {["phrase"] = "伟华", ["word"] = {"炜"}},
    ["blrb"] = {["phrase"] = "白肉", ["word"] = {"伯", "佰"}},
    ["bidc"] = {["phrase"] = "笔调", ["word"] = {"弊"}},
    ["pzyk"] = {["phrase"] = "配药", ["word"] = {"醅"}},
    ["thdk"] = {["phrase"] = "躺倒", ["word"] = {"淌", "溏"}},
    ["yjir"] = {["phrase"] = "言传", ["word"] = {"颜", "赝"}},
    ["luhl"] = {["phrase"] = "陆海", ["word"] = {"虏"}},
    ["hvkh"] = {["phrase"] = "惠康", ["word"] = {"咴"}},
    ["lddg"] = {["phrase"] = "亮灯", ["word"] = {"良"}},
    ["ifyj"] = {["phrase"] = "陈言", ["word"] = {"谶"}},
    ["vupl"] = {["phrase"] = "竹排", ["word"] = {"竹"}},
    ["sivv"] = {["phrase"] = "丝锥", ["word"] = {"巳"}},
    ["qian"] = {["phrase"] = "奇案", ["word"] = {"妻"}},
    ["gjdg"] = {["phrase"] = "干等", ["word"] = {"泔"}},
    ["fuff"] = {["phrase"] = "福分", ["word"] = {"扶", "拂", "麸"}},
    ["vhju"] = {["phrase"] = "章句", ["word"] = {"幛"}},
    ["zidk"] = {["phrase"] = "自导", ["word"] = {"咨"}},
    ["hvik"] = {["phrase"] = "回潮", ["word"] = {"蛔"}},
    ["nxer"] = {["phrase"] = "聂耳", ["word"] = {"颞"}},
    ["uikr"] = {["phrase"] = "十款", ["word"] = {"噬"}},
    ["juml"] = {["phrase"] = "拒买", ["word"] = {"榉"}},
    ["jugk"] = {["phrase"] = "居高", ["word"] = {"鞫"}},
    ["qmhw"] = {["phrase"] = "铅华", ["word"] = {"虔"}},
    ["dgvj"] = {["phrase"] = "灯盏", ["word"] = {"凳"}},
    ["jwcj"] = {["phrase"] = "加餐", ["word"] = {"荚"}},
    ["hkku"] = {["phrase"] = "好酷", ["word"] = {"嚎", "嗥"}},
    ["jnvl"] = {["phrase"] = "金寨", ["word"] = {"劲", "筋"}},
    ["jise"] = {["phrase"] = "基色", ["word"] = {"缉"}},
    ["jimj"] = {["phrase"] = "挤满", ["word"] = {"机", "极"}},
    ["grbc"] = {["phrase"] = "贯标", ["word"] = {"冠"}},
    ["jmlj"] = {["phrase"] = "剑兰", ["word"] = {"鉴"}},
    ["ijyj"] = {["phrase"] = "谗言", ["word"] = {"谄"}},
    ["mgzl"] = {["phrase"] = "蒙在", ["word"] = {"勐"}},
    ["yikv"] = {["phrase"] = "一窥", ["word"] = {"呓"}},
    ["ybye"] = {["phrase"] = "油液", ["word"] = {"邮"}},
    ["wzen"] = {["phrase"] = "韦恩", ["word"] = {"隈"}},
    ["yswl"] = {["phrase"] = "永外", ["word"] = {"饔"}},
    ["jmdo"] = {["phrase"] = "见多", ["word"] = {"涧"}},
    ["ukdl"] = {["phrase"] = "捎带", ["word"] = {"劭"}},
    ["wzqn"] = {["phrase"] = "为亲", ["word"] = {"猥"}},
    ["yrta"] = {["phrase"] = "愿他", ["word"] = {"垣"}},
    ["viph"] = {["phrase"] = "之旁", ["word"] = {"炙"}},
    ["ukdo"] = {["phrase"] = "稍多", ["word"] = {"潲"}},
    ["wupg"] = {["phrase"] = "吴鹏", ["word"] = {"午"}},
    ["xibx"] = {["phrase"] = "惜别", ["word"] = {"窸"}},
    ["qicu"] = {["phrase"] = "气促", ["word"] = {"芪"}},
    ["vidj"] = {["phrase"] = "制单", ["word"] = {"滞"}},
    ["iipj"] = {["phrase"] = "池畔", ["word"] = {"褫"}},
    ["yree"] = {["phrase"] = "员额", ["word"] = {"元", "院"}},
    ["jiuj"] = {["phrase"] = "积善", ["word"] = {"饥", "矶"}},
    ["hjge"] = {["phrase"] = "焊割", ["word"] = {"邗", "邯"}},
    ["lkck"] = {["phrase"] = "老曹", ["word"] = {"落"}},
    ["kebk"] = {["phrase"] = "科宝", ["word"] = {"客", "疴"}},
    ["wzyn"] = {["phrase"] = "尾音", ["word"] = {"诿"}},
    ["jisk"] = {["phrase"] = "祭扫", ["word"] = {"给"}},
    ["magu"] = {["phrase"] = "麻姑", ["word"] = {"摩"}},
    ["ufdv"] = {["phrase"] = "神对", ["word"] = {"沈"}},
    ["subu"] = {["phrase"] = "素不", ["word"] = {"窣"}},
    ["jibo"] = {["phrase"] = "极薄", ["word"] = {"瘠"}},
    ["djkh"] = {["phrase"] = "单抗", ["word"] = {"啖", "赕"}},
    ["voyu"] = {["phrase"] = "捉鱼", ["word"] = {"酌"}},
    ["ypxi"] = {["phrase"] = "云溪", ["word"] = {"恽"}},
    ["jmzz"] = {["phrase"] = "奸贼", ["word"] = {"踺"}},
    ["geik"] = {["phrase"] = "各朝", ["word"] = {"蛤"}},
    ["xxuo"] = {["phrase"] = "邪说", ["word"] = {"屑"}},
    ["kugk"] = {["phrase"] = "枯槁", ["word"] = {"骷"}},
    ["lisf"] = {["phrase"] = "李森", ["word"] = {"罹"}},
    ["vjmk"] = {["phrase"] = "毡帽", ["word"] = {"毡", "粘"}},
    ["pudu"] = {["phrase"] = "普度", ["word"] = {"瀑"}},
    ["jddm"] = {["phrase"] = "讲点", ["word"] = {"桨"}},
    ["lugh"] = {["phrase"] = "鹿港", ["word"] = {"庐"}},
    ["yuia"] = {["phrase"] = "鱼叉", ["word"] = {"蜮"}},
    ["lihu"] = {["phrase"] = "立户", ["word"] = {"黎"}},
    ["fgdx"] = {["phrase"] = "凤蝶", ["word"] = {"沨"}},
    ["vumo"] = {["phrase"] = "铸模", ["word"] = {"槠"}},
    ["wunk"] = {["phrase"] = "无脑", ["word"] = {"牾"}},
    ["jqfa"] = {["phrase"] = "旧法", ["word"] = {"韭"}},
    ["lumu"] = {["phrase"] = "卢姆", ["word"] = {"栌"}},
    ["qiao"] = {["phrase"] = "奇奥", ["word"] = {"鳍"}},
    ["jxuf"] = {["phrase"] = "洁身", ["word"] = {"截"}},
    ["qitj"] = {["phrase"] = "棋坛", ["word"] = {"起", "圻"}},
    ["uico"] = {["phrase"] = "失措", ["word"] = {"蓍"}},
    ["hjxx"] = {["phrase"] = "寒邪", ["word"] = {"憾"}},
    ["qimb"] = {["phrase"] = "奇谋", ["word"] = {"棋", "骐"}},
    ["ynbo"] = {["phrase"] = "音波", ["word"] = {"窨"}},
    ["xnlr"] = {["phrase"] = "心乱", ["word"] = {"歆"}},
    ["voyn"] = {["phrase"] = "浊音", ["word"] = {"诼"}},
    ["qijr"] = {["phrase"] = "七卷", ["word"] = {"颀"}},
    ["ghfg"] = {["phrase"] = "罡风", ["word"] = {"扛", "缸"}},
    ["wzao"] = {["phrase"] = "维奥", ["word"] = {"鲔"}},
    ["xmie"] = {["phrase"] = "闲扯", ["word"] = {"蚬"}},
    ["bzlo"] = {["phrase"] = "贝罗", ["word"] = {"背"}},
    ["digd"] = {["phrase"] = "地广", ["word"] = {"底", "骶"}},
    ["jwly"] = {["phrase"] = "加氯", ["word"] = {"袈"}},
    ["jika"] = {["phrase"] = "集卡", ["word"] = {"戢"}},
    ["somu"] = {["phrase"] = "索姆", ["word"] = {"桫"}},
    ["hvxm"] = {["phrase"] = "徽县", ["word"] = {"悔"}},
    ["gkmk"] = {["phrase"] = "高帽", ["word"] = {"槁"}},
    ["qcuf"] = {["phrase"] = "桥身", ["word"] = {"雀"}},
    ["bigg"] = {["phrase"] = "笔耕", ["word"] = {"弼"}},
    -- ["vfju"] = {["phrase"] = "针具", ["word"] = {"针"}},
    -- ["fupj"] = {["phrase"] = "复盘", ["word"] = {"凫"}},
    -- ["eeuk"] = {["phrase"] = "恶少", ["word"] = {"屙"}},
    -- ["djdl"] = {["phrase"] = "担待", ["word"] = {"殚"}},
    -- ["jnya"] = {["phrase"] = "金牙", ["word"] = {"谨"}},
    -- ["bagd"] = {["phrase"] = "扒光", ["word"] = {"魃"}},
    -- ["qqrj"] = {["phrase"] = "虬髯", ["word"] = {"仇"}},
    -- ["xcdo"] = {["phrase"] = "小朵", ["word"] = {"消", "淆"}},
    -- ["xckk"] = {["phrase"] = "小考", ["word"] = {"嚣"}},
    -- ["sivk"] = {["phrase"] = "四招", ["word"] = {"司", "笥"}},
    -- ["piku"] = {["phrase"] = "皮裤", ["word"] = {"啤", "噼"}},
    -- ["thxm"] = {["phrase"] = "唐县", ["word"] = {"棠"}},
    -- ["iikb"] = {["phrase"] = "吃口", ["word"] = {"叱"}},
    -- ["sids"] = {["phrase"] = "四栋", ["word"] = {"汜"}},
    -- ["qdpi"] = {["phrase"] = "墙皮", ["word"] = {"襁"}},
    -- ["mkce"] = {["phrase"] = "茅厕", ["word"] = {"茆"}},
    -- ["jmzj"] = {["phrase"] = "坚赞", ["word"] = {"践"}},
    -- ["yjhh"] = {["phrase"] = "雁行", ["word"] = {"炎", "焱"}},
    -- ["duke"] = {["phrase"] = "赌客", ["word"] = {"嘟"}},
    -- ["qmzk"] = {["phrase"] = "乾造", ["word"] = {"遣"}},
    -- ["vfyp"] = {["phrase"] = "真晕", ["word"] = {"诊"}},
    -- ["jwzk"] = {["phrase"] = "假造", ["word"] = {"迦", "跏"}},
    -- ["j;mg"] = {["phrase"] = "惊梦", ["word"] = {"粳"}},
    -- ["vucv"] = {["phrase"] = "珠翠", ["word"] = {"茱"}},
    -- ["vuml"] = {["phrase"] = "主脉", ["word"] = {"杼"}},
    -- ["yubn"] = {["phrase"] = "玉斌", ["word"] = {"鹆"}},
    -- ["bivu"] = {["phrase"] = "闭住", ["word"] = {"筚"}},
    -- ["hsig"] = {["phrase"] = "红橙", ["word"] = {"虹"}},
    -- ["hvdr"] = {["phrase"] = "会断", ["word"] = {"溃"}},
    -- ["dkpc"] = {["phrase"] = "倒票", ["word"] = {"祷"}},
    -- ["dmub"] = {["phrase"] = "点收", ["word"] = {"碘"}},
    -- ["xiur"] = {["phrase"] = "洗涮", ["word"] = {"屣"}},
    -- ["uudv"] = {["phrase"] = "属对", ["word"] = {"殊"}},
    -- ["hrdx"] = {["phrase"] = "换碟", ["word"] = {"漶"}},
    -- ["ihri"] = {["phrase"] = "长日", ["word"] = {"伥"}},
    -- ["yunx"] = {["phrase"] = "余孽", ["word"] = {"妪"}},
    -- ["yrke"] = {["phrase"] = "远客", ["word"] = {"园"}},
    -- ["iivk"] = {["phrase"] = "池沼", ["word"] = {"齿", "笞"}},
    -- ["lodl"] = {["phrase"] = "洛带", ["word"] = {"泺"}},
    -- ["xiij"] = {["phrase"] = "析产", ["word"] = {"蜥"}},
    -- ["xxmc"] = {["phrase"] = "蟹苗", ["word"] = {"械", "榭"}},
    -- ["hodr"] = {["phrase"] = "祸端", ["word"] = {"火"}},
    -- ["y;ck"] = {["phrase"] = "樱草", ["word"] = {"营"}},
    -- ["ziky"] = {["phrase"] = "字块", ["word"] = {"吱", "嗞"}},
    -- ["yjip"] = {["phrase"] = "艳春", ["word"] = {"彦"}},
    -- ["jpye"] = {["phrase"] = "菌液", ["word"] = {"郡"}},
    -- ["bidl"] = {["phrase"] = "笔袋", ["word"] = {"濞"}},
    -- ["jivo"] = {["phrase"] = "几桌", ["word"] = {"籍"}},
    -- ["d;kr"] = {["phrase"] = "顶宽", ["word"] = {"啶"}},
    -- ["gedk"] = {["phrase"] = "各岛", ["word"] = {"哥"}},
    -- ["zidx"] = {["phrase"] = "紫蝶", ["word"] = {"恣"}},
    -- ["j;ck"] = {["phrase"] = "劲草", ["word"] = {"警"}},
    -- ["tsdl"] = {["phrase"] = "统带", ["word"] = {"潼"}},
    -- ["grwf"] = {["phrase"] = "官文", ["word"] = {"瓘"}},
    -- ["bojd"] = {["phrase"] = "播讲", ["word"] = {"钹"}},
    -- ["heck"] = {["phrase"] = "禾草", ["word"] = {"荷", "菏"}},
    -- ["blfu"] = {["phrase"] = "摆幅", ["word"] = {"捭"}},
    -- ["qcgo"] = {["phrase"] = "敲过", ["word"] = {"鞘"}},
    -- ["hvck"] = {["phrase"] = "会操", ["word"] = {"茴"}},
    -- ["jmck"] = {["phrase"] = "键槽", ["word"] = {"菅"}},
    -- ["bivl"] = {["phrase"] = "逼债", ["word"] = {"箅"}},
    -- ["puck"] = {["phrase"] = "蒲草", ["word"] = {"菩"}},
    -- ["ujck"] = {["phrase"] = "山草", ["word"] = {"苫"}},
    -- ["dpzo"] = {["phrase"] = "蹲坐", ["word"] = {"遁"}},
    -- ["kegg"] = {["phrase"] = "可耕", ["word"] = {"髁"}},
    -- ["fjjt"] = {["phrase"] = "反觉", ["word"] = {"幡"}},
    -- ["hukj"] = {["phrase"] = "互看", ["word"] = {"唬"}},
    -- ["piub"] = {["phrase"] = "劈手", ["word"] = {"屁", "砒"}},
    -- ["yaky"] = {["phrase"] = "压块", ["word"] = {"呀", "哑"}},
    -- ["qiib"] = {["phrase"] = "奇丑", ["word"] = {"蜞"}},
    -- ["uaxd"] = {["phrase"] = "沙箱", ["word"] = {"刹"}},
    -- ["gjvg"] = {["phrase"] = "干政", ["word"] = {"竿"}},
    -- ["thre"] = {["phrase"] = "烫热", ["word"] = {"傥"}},
    -- ["yhhy"] = {["phrase"] = "洋槐", ["word"] = {"秧", "烊"}},
    -- ["jwrk"] = {["phrase"] = "加扰", ["word"] = {"伽"}},
    -- ["bipu"] = {["phrase"] = "婢仆", ["word"] = {"裨"}},
    -- ["yuma"] = {["phrase"] = "玉马", ["word"] = {"阈"}},
    -- ["fubj"] = {["phrase"] = "腹板", ["word"] = {"斧"}},
    -- ["djer"] = {["phrase"] = "蛋儿", ["word"] = {"聃"}},
    -- ["basl"] = {["phrase"] = "罢赛", ["word"] = {"巴"}},
    -- ["vjlk"] = {["phrase"] = "粘牢", ["word"] = {"占", "站"}},
    -- ["zivb"] = {["phrase"] = "子洲", ["word"] = {"龇"}},
    -- ["qice"] = {["phrase"] = "凄恻", ["word"] = {"葺"}},
    -- ["yjkk"] = {["phrase"] = "研考", ["word"] = {"唁"}},
    -- ["xikk"] = {["phrase"] = "戏考", ["word"] = {"嘻"}},
    -- ["huhb"] = {["phrase"] = "狐猴", ["word"] = {"扈"}},
    -- ["yisu"] = {["phrase"] = "易俗", ["word"] = {"矣"}},
    -- ["hupk"] = {["phrase"] = "虎跑", ["word"] = {"祜"}},
    -- ["ybbo"] = {["phrase"] = "又播", ["word"] = {"宥"}},
    -- ["xxsu"] = {["phrase"] = "歇宿", ["word"] = {"绁"}},
    -- ["hkdr"] = {["phrase"] = "号段", ["word"] = {"灏"}},
    -- ["mcce"] = {["phrase"] = "妙策", ["word"] = {"藐"}},
    -- ["hudh"] = {["phrase"] = "湖荡", ["word"] = {"沪", "滹"}},
    -- ["bcmu"] = {["phrase"] = "标目", ["word"] = {"杓"}},
    -- ["dich"] = {["phrase"] = "底舱", ["word"] = {"荻"}},
    -- ["tjdu"] = {["phrase"] = "贪渎", ["word"] = {"潭"}},
    -- ["uult"] = {["phrase"] = "术略", ["word"] = {"墅"}},
    -- ["gbbk"] = {["phrase"] = "狗宝", ["word"] = {"句"}},
    -- ["humu"] = {["phrase"] = "护目", ["word"] = {"槲"}},
    -- ["bivb"] = {["phrase"] = "臂肘", ["word"] = {"篦"}},
    -- ["xwkj"] = {["phrase"] = "瞎侃", ["word"] = {"匣", "呷"}},
    -- ["yunl"] = {["phrase"] = "芋艿", ["word"] = {"妤"}},
    -- ["jila"] = {["phrase"] = "急拉", ["word"] = {"亟"}},
    -- ["uidb"] = {["phrase"] = "市斗", ["word"] = {"奭"}},
    -- ["wudj"] = {["phrase"] = "武旦", ["word"] = {"鋈"}},
    -- ["y;ci"] = {["phrase"] = "英雌", ["word"] = {"萤"}},
    -- ["grbk"] = {["phrase"] = "管保", ["word"] = {"官"}},
    -- ["gkmu"] = {["phrase"] = "槁木", ["word"] = {"槔"}},
    -- ["geuk"] = {["phrase"] = "鸽哨", ["word"] = {"饹", "硌"}},
    -- ["urma"] = {["phrase"] = "拴马", ["word"] = {"闩"}},
    -- ["zidu"] = {["phrase"] = "自渎", ["word"] = {"滓"}},
    -- ["yukk"] = {["phrase"] = "预考", ["word"] = {"圄"}},
    -- ["ujna"] = {["phrase"] = "姗娜", ["word"] = {"嬗"}},
    -- ["uirr"] = {["phrase"] = "湿软", ["word"] = {"似"}},
    -- ["kddi"] = {["phrase"] = "旷地", ["word"] = {"夼"}},
    -- ["vfmh"] = {["phrase"] = "真忙", ["word"] = {"榛"}},
    -- ["djvl"] = {["phrase"] = "丹寨", ["word"] = {"箪"}},
    -- ["luzu"] = {["phrase"] = "卤族", ["word"] = {"逯"}},
    -- ["yisl"] = {["phrase"] = "义赛", ["word"] = {"绎"}},
    -- ["rudc"] = {["phrase"] = "入调", ["word"] = {"溽"}},
    -- ["dxzu"] = {["phrase"] = "跌足", ["word"] = {"迭", "跌"}},
    -- ["iibx"] = {["phrase"] = "吃瘪", ["word"] = {"瘛"}},
    -- ["jmnz"] = {["phrase"] = "贱内", ["word"] = {"犍"}},
    -- ["ximn"] = {["phrase"] = "细民", ["word"] = {"樨"}},
    -- ["jxil"] = {["phrase"] = "解差", ["word"] = {"蚧"}},
    -- ["qtmf"] = {["phrase"] = "缺门", ["word"] = {"榷"}},
    -- ["ukdk"] = {["phrase"] = "烧到", ["word"] = {"召"}},
    -- ["hgii"] = {["phrase"] = "哼哧", ["word"] = {"行", "衡"}},
    -- ["ukho"] = {["phrase"] = "烧火", ["word"] = {"稍"}},
    -- ["hjhk"] = {["phrase"] = "喊好", ["word"] = {"焓"}},
    -- ["hbku"] = {["phrase"] = "齁苦", ["word"] = {"喉"}},
    -- ["bigu"] = {["phrase"] = "辟谷", ["word"] = {"髀"}},
    -- ["iajx"] = {["phrase"] = "插接", ["word"] = {"镲"}},
    -- ["uguo"] = {["phrase"] = "声说", ["word"] = {"省"}},
    -- ["qiru"] = {["phrase"] = "欺辱", ["word"] = {"俟"}},
    -- ["mike"] = {["phrase"] = "米克", ["word"] = {"嘧"}},
    -- ["zjwo"] = {["phrase"] = "赞我", ["word"] = {"昝"}},
    -- ["eeyb"] = {["phrase"] = "恶有", ["word"] = {"讹"}},
    -- ["xncu"] = {["phrase"] = "心粗", ["word"] = {"莘"}},
    -- ["gudo"] = {["phrase"] = "骨朵", ["word"] = {"汩"}},
    -- ["qmxt"] = {["phrase"] = "浅学", ["word"] = {"悭"}},
    -- ["sbku"] = {["phrase"] = "搜酷", ["word"] = {"嗾"}},
    -- ["piuu"] = {["phrase"] = "皮书", ["word"] = {"辟", "鼙"}},
    -- ["diuj"] = {["phrase"] = "递嬗", ["word"] = {"碲"}},
    -- ["xudx"] = {["phrase"] = "续跌", ["word"] = {"洫"}},
    -- ["eeke"] = {["phrase"] = "恶客", ["word"] = {"鄂"}},
    -- ["uuso"] = {["phrase"] = "数所", ["word"] = {"署"}},
    -- ["tomi"] = {["phrase"] = "托米", ["word"] = {"柝"}},
    -- ["tixp"] = {["phrase"] = "提讯", ["word"] = {"悌"}},
    -- ["x;ke"] = {["phrase"] = "刑克", ["word"] = {"邢"}},
    -- ["uizj"] = {["phrase"] = "诗赞", ["word"] = {"逝"}},
    -- ["cikb"] = {["phrase"] = "磁扣", ["word"] = {"呲"}},
    -- ["vbkk"] = {["phrase"] = "周考", ["word"] = {"周", "啁"}},
    -- ["uimj"] = {["phrase"] = "士曼", ["word"] = {"柿"}},
    -- ["pitu"] = {["phrase"] = "辟土", ["word"] = {"埤"}},
    -- ["gemk"] = {["phrase"] = "戈矛", ["word"] = {"阁", "格"}},
    -- ["iivj"] = {["phrase"] = "翅展", ["word"] = {"篪"}},
    -- ["bkhs"] = {["phrase"] = "暴洪", ["word"] = {"炮"}},
    -- ["jtyk"] = {["phrase"] = "诀要", ["word"] = {"谲"}},
    -- ["tlse"] = {["phrase"] = "泰瑟", ["word"] = {"邰"}},
    -- ["fzcl"] = {["phrase"] = "非才", ["word"] = {"芾"}},
    -- ["yudr"] = {["phrase"] = "预断", ["word"] = {"滪"}},
    -- ["lkyp"] = {["phrase"] = "老运", ["word"] = {"醪"}},
    -- ["qubf"] = {["phrase"] = "曲本", ["word"] = {"癯"}},
    -- ["xmbm"] = {["phrase"] = "舷边", ["word"] = {"痫"}},
    -- ["yjnk"] = {["phrase"] = "延脑", ["word"] = {"妍"}},
    -- ["xmye"] = {["phrase"] = "涎液", ["word"] = {"酰"}},
    -- ["fubx"] = {["phrase"] = "赋别", ["word"] = {"父"}},
    -- ["yjmk"] = {["phrase"] = "颜貌", ["word"] = {"檐"}},
    -- ["yhhp"] = {["phrase"] = "洋荤", ["word"] = {"炀"}},
    -- ["eeyt"] = {["phrase"] = "恶月", ["word"] = {"垩"}},
    -- ["jink"] = {["phrase"] = "激恼", ["word"] = {"犄"}},
    -- ["yrky"] = {["phrase"] = "圆块", ["word"] = {"圜"}},
    -- ["yuuy"] = {["phrase"] = "于帅", ["word"] = {"饫"}},
    -- ["juqq"] = {["phrase"] = "菊秋", ["word"] = {"狙"}},
    -- ["vaua"] = {["phrase"] = "扎煞", ["word"] = {"馇"}},
    -- ["xuso"] = {["phrase"] = "须索", ["word"] = {"绪"}},
    -- ["guuo"] = {["phrase"] = "告朔", ["word"] = {"瞽"}},
    -- ["lmwz"] = {["phrase"] = "帘帷", ["word"] = {"琏"}},
    -- ["yuid"] = {["phrase"] = "愈疮", ["word"] = {"蝓"}},
    -- ["jicj"] = {["phrase"] = "集餐", ["word"] = {"芨"}},
    -- ["hvxi"] = {["phrase"] = "回戏", ["word"] = {"辉", "翚"}},
    -- ["uflo"] = {["phrase"] = "沈落", ["word"] = {"肾"}},
    -- ["siva"] = {["phrase"] = "四扎", ["word"] = {"丝"}},
    -- ["sadu"] = {["phrase"] = "撒督", ["word"] = {"挲"}},
    -- ["gbmk"] = {["phrase"] = "狗毛", ["word"] = {"枸"}},
    -- ["zhci"] = {["phrase"] = "脏词", ["word"] = {"藏"}},
    -- ["uedo"] = {["phrase"] = "舍堕", ["word"] = {"奢"}},
    -- ["fuba"] = {["phrase"] = "副把", ["word"] = {"釜"}},
    -- ["vuhv"] = {["phrase"] = "珠灰", ["word"] = {"炷"}},
    -- ["piou"] = {["phrase"] = "匹偶", ["word"] = {"脾", "睥"}},
    -- ["fupu"] = {["phrase"] = "匐匍", ["word"] = {"阜"}},
    -- ["mzmo"] = {["phrase"] = "煤末", ["word"] = {"楣"}},
    -- ["xxdj"] = {["phrase"] = "械弹", ["word"] = {"瀣"}},
    -- ["vurv"] = {["phrase"] = "烛蕊", ["word"] = {"住", "侏"}},
    -- ["hvko"] = {["phrase"] = "恢廓", ["word"] = {"贿"}},
    -- ["ufku"] = {["phrase"] = "神枯", ["word"] = {"呻"}},
    -- ["wugp"] = {["phrase"] = "舞棍", ["word"] = {"戊"}},
    -- ["igmi"] = {["phrase"] = "乘幂", ["word"] = {"枨"}},
    -- ["xidh"] = {["phrase"] = "洗荡", ["word"] = {"潟"}},
    -- ["x;ou"] = {["phrase"] = "姓欧", ["word"] = {"星", "腥"}},
    -- ["xipk"] = {["phrase"] = "吸跑", ["word"] = {"禧"}},
    -- ["uuuy"] = {["phrase"] = "疏率", ["word"] = {"叔", "属"}},
    -- ["hdxw"] = {["phrase"] = "荒遐", ["word"] = {"恍", "惶"}},
    -- ["uobm"] = {["phrase"] = "朔边", ["word"] = {"槊"}},
    -- ["kvdr"] = {["phrase"] = "亏短", ["word"] = {"溃"}},
    -- ["ljdj"] = {["phrase"] = "懒蛋", ["word"] = {"澜"}},
    -- ["ludu"] = {["phrase"] = "禄蠹", ["word"] = {"泸", "渌"}},
    -- ["bkbn"] = {["phrase"] = "薄鬓", ["word"] = {"鸨"}},
    -- ["qxxn"] = {["phrase"] = "惬心", ["word"] = {"慊"}},
    -- ["jmvo"] = {["phrase"] = "简擢", ["word"] = {"简"}},
    -- ["vfjr"] = {["phrase"] = "赈捐", ["word"] = {"帧"}},
    -- ["doti"] = {["phrase"] = "多提", ["word"] = {"埵"}},
    -- ["juud"] = {["phrase"] = "居孀", ["word"] = {"剧"}},
    -- ["x;kd"] = {["phrase"] = "姓匡", ["word"] = {"刑"}},
    -- ["sirk"] = {["phrase"] = "肆扰", ["word"] = {"伺"}},
    -- ["lumo"] = {["phrase"] = "戮没", ["word"] = {"橹", "氇"}},
    -- ["yicr"] = {["phrase"] = "异爨", ["word"] = {"苡"}},
    -- ["pavb"] = {["phrase"] = "琶洲", ["word"] = {"爬", "筢"}},
    -- ["vulx"] = {["phrase"] = "猪鬣", ["word"] = {"翥"}},
    -- ["uefj"] = {["phrase"] = "社饭", ["word"] = {"折"}},
    -- ["j;co"] = {["phrase"] = "惊错", ["word"] = {"菁"}},
    -- ["tokd"] = {["phrase"] = "驮筐", ["word"] = {"鼍"}},
    -- ["gukg"] = {["phrase"] = "古坑", ["word"] = {"呱"}},
    -- ["lslu"] = {["phrase"] = "龙路", ["word"] = {"砻"}},
    -- ["liid"] = {["phrase"] = "李闯", ["word"] = {"蜊"}},
    -- ["j;vl"] = {["phrase"] = "京债", ["word"] = {"劲"}},
    -- ["bkrh"] = {["phrase"] = "保禳", ["word"] = {"煲"}},
    -- ["bhmf"] = {["phrase"] = "傍门", ["word"] = {"榜"}},
    -- ["juck"] = {["phrase"] = "具草", ["word"] = {"莒", "蒟"}},
    -- ["piib"] = {["phrase"] = "匹俦", ["word"] = {"蚍"}},
    -- ["ujbl"] = {["phrase"] = "善败", ["word"] = {"单"}},
    -- ["popx"] = {["phrase"] = "坡撇", ["word"] = {"繁"}},
    -- ["dava"] = {["phrase"] = "大札", ["word"] = {"笪"}},
    -- ["hrda"] = {["phrase"] = "宦达", ["word"] = {"洹"}},
    -- ["xpio"] = {["phrase"] = "巡绰", ["word"] = {"循", "徇"}},
    -- ["uunx"] = {["phrase"] = "庶孽", ["word"] = {"恕"}},
    -- ["yjmj"] = {["phrase"] = "延蔓", ["word"] = {"阎"}},
    -- ["tmqx"] = {["phrase"] = "忝窃", ["word"] = {"舔"}},
    -- ["iupo"] = {["phrase"] = "怵迫", ["word"] = {"褚"}},
    -- ["pubf"] = {["phrase"] = "扑奔", ["word"] = {"匍"}},
    -- ["jccj"] = {["phrase"] = "教参", ["word"] = {"艽"}},
    -- ["vodr"] = {["phrase"] = "斫断", ["word"] = {"浞"}},
    -- ["qcuj"] = {["phrase"] = "桥山", ["word"] = {"壳"}},
    -- ["qicb"] = {["phrase"] = "气凑", ["word"] = {"萁"}},
    -- ["yaiv"] = {["phrase"] = "牙槌", ["word"] = {"轧"}},
    -- ["huho"] = {["phrase"] = "狐惑", ["word"] = {"煳"}},
    -- ["jckh"] = {["phrase"] = "矫亢", ["word"] = {"噍"}},
    -- ["lulx"] = {["phrase"] = "胪列", ["word"] = {"卤"}},
    -- ["iumk"] = {["phrase"] = "触冒", ["word"] = {"樗"}},
    -- ["xpdu"] = {["phrase"] = "训读", ["word"] = {"汛"}},
    -- ["ifkb"] = {["phrase"] = "趁口", ["word"] = {"嗔"}},
    -- ["bicu"] = {["phrase"] = "逼促", ["word"] = {"荜", "薜"}},
    -- ["dpjw"] = {["phrase"] = "遁甲", ["word"] = {"镦"}},
    -- ["biuy"] = {["phrase"] = "避衰", ["word"] = {"璧", "襞"}},
    -- ["tkdj"] = {["phrase"] = "陶诞", ["word"] = {"滔"}},
    -- ["luik"] = {["phrase"] = "陆钞", ["word"] = {"辂"}},
    -- ["ynce"] = {["phrase"] = "隐恻", ["word"] = {"茚"}},
    -- ["ynko"] = {["phrase"] = "隐括", ["word"] = {"喑"}},
    -- ["liil"] = {["phrase"] = "离拆", ["word"] = {"历", "励", "厘"}},
    -- ["l;ye"] = {["phrase"] = "灵液", ["word"] = {"酃"}},
    -- ["yuto"] = {["phrase"] = "鹬鸵", ["word"] = {"堉"}},
    -- ["yiro"] = {["phrase"] = "一若", ["word"] = {"佾"}},
    -- ["d;jr"] = {["phrase"] = "丁绢", ["word"] = {"锭"}},
    -- ["uhdp"] = {["phrase"] = "上顿", ["word"] = {"殇", "觞"}},
    -- ["vsrv"] = {["phrase"] = "中瑞", ["word"] = {"仲"}},
    -- ["fgee"] = {["phrase"] = "丰额", ["word"] = {"酆"}},
    -- ["juuj"] = {["phrase"] = "举善", ["word"] = {"矩"}},
    -- ["qcyh"] = {["phrase"] = "乔样", ["word"] = {"谯"}},
    -- ["lrwz"] = {["phrase"] = "乱危", ["word"] = {"孪"}},
    -- ["jcdh"] = {["phrase"] = "交党", ["word"] = {"湫"}},
    -- ["jccb"] = {["phrase"] = "交凑", ["word"] = {"藠"}},
    -- ["ijju"] = {["phrase"] = "产具", ["word"] = {"镡"}},
    -- ["qndh"] = {["phrase"] = "亲党", ["word"] = {"溱"}},
    -- ["l;rs"] = {["phrase"] = "令容", ["word"] = {"令", "伶"}},
    -- ["yifb"] = {["phrase"] = "以否", ["word"] = {"挹"}},
    -- ["yivv"] = {["phrase"] = "仪缀", ["word"] = {"乙", "已"}},
    -- ["rfsr"] = {["phrase"] = "任算", ["word"] = {"纫", "纴"}},
    -- ["fusb"] = {["phrase"] = "伏薮", ["word"] = {"罘"}},
    -- ["xqdo"] = {["phrase"] = "休惰", ["word"] = {"滫"}},
    -- ["ybrk"] = {["phrase"] = "优饶", ["word"] = {"佑"}},
    -- ["siru"] = {["phrase"] = "似如", ["word"] = {"俟"}},
    -- ["suvr"] = {["phrase"] = "俗馔", ["word"] = {"簌"}},
    -- ["yirk"] = {["phrase"] = "倚桡", ["word"] = {"倚"}},
    -- ["jxtl"] = {["phrase"] = "借胎", ["word"] = {"劫", "界"}},
    -- ["jumj"] = {["phrase"] = "倨嫚", ["word"] = {"柜"}},
    -- ["yjnh"] = {["phrase"] = "偃囊", ["word"] = {"燕", "嫣"}},
    -- ["bndb"] = {["phrase"] = "傧豆", ["word"] = {"滨", "殡"}},
    -- ["iuzo"] = {["phrase"] = "储佐", ["word"] = {"躇"}},
    -- ["bakb"] = {["phrase"] = "八口", ["word"] = {"叭", "吧"}},
    -- ["b;uk"] = {["phrase"] = "兵梢", ["word"] = {"饼", "屏"}},
    -- ["b;mb"] = {["phrase"] = "兵谋", ["word"] = {"柄", "槟"}},
    -- ["juzk"] = {["phrase"] = "具造", ["word"] = {"踞"}},
    -- ["mkjt"] = {["phrase"] = "冒橛", ["word"] = {"锚"}},
    -- ["rsbj"] = {["phrase"] = "冗绊", ["word"] = {"冗"}},
    -- ["iudh"] = {["phrase"] = "出挡", ["word"] = {"滁"}},
    -- ["jiij"] = {["phrase"] = "击馋", ["word"] = {"虮"}},
    -- ["bkcs"] = {["phrase"] = "剥葱", ["word"] = {"苞"}},
    -- ["qrjd"] = {["phrase"] = "劝奖", ["word"] = {"券"}},
    -- ["qncv"] = {["phrase"] = "勤悴", ["word"] = {"芩"}},
    -- ["bzuo"] = {["phrase"] = "北朔", ["word"] = {"臂"}},
    -- ["kvee"] = {["phrase"] = "匮饿", ["word"] = {"岿"}},
    -- ["ludb"] = {["phrase"] = "卢都", ["word"] = {"漉"}},
    -- ["xxfj"] = {["phrase"] = "卸帆", ["word"] = {"挟"}},
    -- ["tlsh"] = {["phrase"] = "台桑", ["word"] = {"炱"}},
    -- ["sidj"] = {["phrase"] = "司旦", ["word"] = {"澌"}},
    -- ["jirv"] = {["phrase"] = "吉瑞", ["word"] = {"偈"}},
    -- ["tsmk"] = {["phrase"] = "同貌", ["word"] = {"桐"}},
    -- ["pish"] = {["phrase"] = "否桑", ["word"] = {"罴"}},
    -- ["ivmz"] = {["phrase"] = "吹梅", ["word"] = {"槌"}},
    -- ["herk"] = {["phrase"] = "和扰", ["word"] = {"合", "何"}},
    -- ["herr"] = {["phrase"] = "和软", ["word"] = {"颌"}},
    -- ["gunk"] = {["phrase"] = "咕呶", ["word"] = {"姑", "牯"}},
    -- ["aicv"] = {["phrase"] = "哀悴", ["word"] = {"蔼"}},
    -- ["pnvu"] = {["phrase"] = "品柱", ["word"] = {"颦"}},
    -- ["ihro"] = {["phrase"] = "唱偌", ["word"] = {"倡"}},
    -- ["guyk"] = {["phrase"] = "固要", ["word"] = {"诂", "酤"}},
    -- ["tmtx"] = {["phrase"] = "填帖", ["word"] = {"忝"}},
    -- ["lrwj"] = {["phrase"] = "娈婉", ["word"] = {"銮"}},
    -- ["guuk"] = {["phrase"] = "孤劭", ["word"] = {"古"}},
    -- ["guik"] = {["phrase"] = "孤超", ["word"] = {"轱", "蛄"}},
    -- ["kemg"] = {["phrase"] = "客梦", ["word"] = {"棵", "骒"}},
    -- ["xrda"] = {["phrase"] = "宣答", ["word"] = {"渲"}},
    -- ["jiwl"] = {["phrase"] = "寄外", ["word"] = {"齑"}},
    -- ["mibj"] = {["phrase"] = "密办", ["word"] = {"幂"}},
    -- ["jumk"] = {["phrase"] = "居贸", ["word"] = {"驹", "橘", "枸", "椐"}},
    -- ["ujpl"] = {["phrase"] = "山牌", ["word"] = {"禅"}},
    -- ["ujmc"] = {["phrase"] = "山苗", ["word"] = {"栅"}},
    -- ["ujhd"] = {["phrase"] = "山荒", ["word"] = {"剡"}},
    -- ["svzu"] = {["phrase"] = "岁租", ["word"] = {"遂", "邃"}},
    -- ["xpdc"] = {["phrase"] = "巡掉", ["word"] = {"浔"}},
    -- ["ihao"] = {["phrase"] = "常奥", ["word"] = {"鲳"}},
    -- ["p;cp"] = {["phrase"] = "平存", ["word"] = {"苹", "萍"}},
    -- ["yknd"] = {["phrase"] = "幺娘", ["word"] = {"姚"}},
    -- ["luwu"] = {["phrase"] = "庐伍", ["word"] = {"率"}},
    -- ["y;cu"] = {["phrase"] = "应猝", ["word"] = {"荥"}},
    -- ["dund"] = {["phrase"] = "度娘", ["word"] = {"犊"}},
    -- ["yirv"] = {["phrase"] = "异瑞", ["word"] = {"亿"}},
    -- ["qimx"] = {["phrase"] = "弃蔑", ["word"] = {"栖", "槭"}},
    -- ["vhdu"] = {["phrase"] = "张独", ["word"] = {"漳"}},
    -- ["migf"] = {["phrase"] = "弥亘", ["word"] = {"靡"}},
    -- ["vgvl"] = {["phrase"] = "征债", ["word"] = {"筝"}},
    -- ["xpdo"] = {["phrase"] = "徇铎", ["word"] = {"殉", "洵"}},
    -- ["yrte"] = {["phrase"] = "怨慝", ["word"] = {"垸"}},
    -- ["eeck"] = {["phrase"] = "恶草", ["word"] = {"萼"}},
    -- ["ybko"] = {["phrase"] = "悠阔", ["word"] = {"囿"}},
    -- ["wjce"] = {["phrase"] = "惋恻", ["word"] = {"莞"}},
    -- ["cjhp"] = {["phrase"] = "惭魂", ["word"] = {"黪"}},
    -- ["gjmg"] = {["phrase"] = "感梦", ["word"] = {"杆", "柑"}},
    -- ["yrkr"] = {["phrase"] = "愿款", ["word"] = {"员", "圆"}},
    -- ["hudg"] = {["phrase"] = "户等", ["word"] = {"瓠"}},
    -- ["pumo"] = {["phrase"] = "扑摸", ["word"] = {"氆"}},
    -- ["piba"] = {["phrase"] = "批把", ["word"] = {"丕"}},
    -- ["ibhk"] = {["phrase"] = "抽号", ["word"] = {"稠"}},
    -- ["voff"] = {["phrase"] = "拙分", ["word"] = {"擢"}},
    -- ["visb"] = {["phrase"] = "指嗾", ["word"] = {"织"}},
    -- ["jica"] = {["phrase"] = "挤擦", ["word"] = {"蕺"}},
    -- ["cofg"] = {["phrase"] = "挫锋", ["word"] = {"搓"}},
    -- ["vhlp"] = {["phrase"] = "掌纶", ["word"] = {"彰"}},
    -- ["tjbf"] = {["phrase"] = "探本", ["word"] = {"瘫"}},
    -- ["voco"] = {["phrase"] = "斫锉", ["word"] = {"著"}},
    -- ["kvko"] = {["phrase"] = "暌阔", ["word"] = {"喟"}},
    -- ["quen"] = {["phrase"] = "曲恩", ["word"] = {"娶"}},
    -- ["qumq"] = {["phrase"] = "曲谬", ["word"] = {"阒"}},
    -- ["ytml"] = {["phrase"] = "月脉", ["word"] = {"栎"}},
    -- ["lldl"] = {["phrase"] = "来代", ["word"] = {"涞"}},
    -- ["uusl"] = {["phrase"] = "树塞", ["word"] = {"纾"}},
    -- ["uudr"] = {["phrase"] = "树端", ["word"] = {"漱"}},
    -- ["hekk"] = {["phrase"] = "核考", ["word"] = {"呵", "嗬"}},
    -- ["tmdp"] = {["phrase"] = "殄沌", ["word"] = {"殄"}},
    -- ["bidm"] = {["phrase"] = "毕典", ["word"] = {"滗"}},
    -- ["mkso"] = {["phrase"] = "毛索", ["word"] = {"瞀"}},
    -- ["ufcv"] = {["phrase"] = "沈悴", ["word"] = {"葚"}},
    -- ["ufdp"] = {["phrase"] = "沈遁", ["word"] = {"渗"}},
    -- ["jurk"] = {["phrase"] = "沮扰", ["word"] = {"倨"}},
    -- ["zekv"] = {["phrase"] = "泽葵", ["word"] = {"咋"}},
    -- ["lhcl"] = {["phrase"] = "浪猜", ["word"] = {"莨", "蒗"}},
    -- ["hpdu"] = {["phrase"] = "混渎", ["word"] = {"溷"}},
    -- ["yjil"] = {["phrase"] = "燕钗", ["word"] = {"餍"}},
    -- ["uywu"] = {["phrase"] = "率舞", ["word"] = {"率"}},
    -- ["yubg"] = {["phrase"] = "玉琫", ["word"] = {"窳"}},
    -- ["dmlb"] = {["phrase"] = "玷漏", ["word"] = {"典"}},
    -- ["livl"] = {["phrase"] = "理债", ["word"] = {"笠"}},
    -- ["liml"] = {["phrase"] = "理脉", ["word"] = {"粒", "枥", "栎", "骊"}},
    -- ["qsge"] = {["phrase"] = "琼阁", ["word"] = {"邛"}},
    -- ["dmdr"] = {["phrase"] = "电断", ["word"] = {"淀"}},
    -- ["yiiy"] = {["phrase"] = "疑揣", ["word"] = {"役", "蚁"}},
    -- ["jwll"] = {["phrase"] = "痂癞", ["word"] = {"甲"}},
    -- ["iiuw"] = {["phrase"] = "痴耍", ["word"] = {"敕"}},
    -- ["y;ch"] = {["phrase"] = "盈藏", ["word"] = {"荧"}},
    -- ["pjpu"] = {["phrase"] = "盘璞", ["word"] = {"襻"}},
    -- ["xdgy"] = {["phrase"] = "相乖", ["word"] = {"庠"}},
    -- ["jxmb"] = {["phrase"] = "睫眸", ["word"] = {"楷"}},
    -- ["jnna"] = {["phrase"] = "矜纳", ["word"] = {"堇"}},
    -- ["uipf"] = {["phrase"] = "石盆", ["word"] = {"失"}},
    -- ["podb"] = {["phrase"] = "破斗", ["word"] = {"泊"}},
    -- ["lulr"] = {["phrase"] = "碌乱", ["word"] = {"颅"}},
    -- ["pcxx"] = {["phrase"] = "票写", ["word"] = {"票", "飘"}},
    -- ["ijjd"] = {["phrase"] = "禅讲", ["word"] = {"镵"}},
    -- ["jiuy"] = {["phrase"] = "积衰", ["word"] = {"屐"}},
    -- ["vhrj"] = {["phrase"] = "章然", ["word"] = {"仉"}},
    -- ["xidx"] = {["phrase"] = "系谍", ["word"] = {"汐"}},
    -- ["jqmj"] = {["phrase"] = "纠缦", ["word"] = {"柩", "桕"}},
    -- ["jtfg"] = {["phrase"] = "绝峰", ["word"] = {"抉"}},
    -- ["cvxu"] = {["phrase"] = "翠虚", ["word"] = {"悴", "翠"}},
    -- ["gggr"] = {["phrase"] = "耕灌", ["word"] = {"赓"}},
    -- ["pmmk"] = {["phrase"] = "胼冒", ["word"] = {"骈"}},
    -- ["fuhz"] = {["phrase"] = "腹黑", ["word"] = {"稃"}},
    -- ["jxco"] = {["phrase"] = "节错", ["word"] = {"藉"}},
    -- ["hdib"] = {["phrase"] = "荒畴", ["word"] = {"蟥"}},
    -- ["y;cj"] = {["phrase"] = "荧灿", ["word"] = {"蓥"}},
    -- ["huwo"] = {["phrase"] = "虎幄", ["word"] = {"瑚"}},
    -- ["xugv"] = {["phrase"] = "虚诡", ["word"] = {"魆"}},
    -- ["piuk"] = {["phrase"] = "蜱蛸", ["word"] = {"譬"}},
    -- ["qqmh"] = {["phrase"] = "裘莽", ["word"] = {"楸"}},
    -- ["eenk"] = {["phrase"] = "讹闹", ["word"] = {"婀"}},
    -- ["vakv"] = {["phrase"] = "诈愧", ["word"] = {"咋"}},
    -- ["vama"] = {["phrase"] = "诈马", ["word"] = {"查", "楂"}},
    -- ["xdvo"] = {["phrase"] = "详酌", ["word"] = {"箱"}},
    -- ["wukw"] = {["phrase"] = "诬夸", ["word"] = {"呜"}},
    -- ["mbsp"] = {["phrase"] = "谋孙", ["word"] = {"缪"}},
    -- ["jnne"] = {["phrase"] = "谨讷", ["word"] = {"觐"}},
    -- ["xmou"] = {["phrase"] = "贤耦", ["word"] = {"腺"}},
    -- ["gvmj"] = {["phrase"] = "贵满", ["word"] = {"柜"}},
    -- ["ikko"] = {["phrase"] = "超阔", ["word"] = {"嘲"}},
    -- ["qucj"] = {["phrase"] = "趋参", ["word"] = {"苣"}},
    -- ["tafu"] = {["phrase"] = "踏伏", ["word"] = {"拓"}},
    -- ["vrkv"] = {["phrase"] = "转馈", ["word"] = {"啭"}},
    -- ["jcbx"] = {["phrase"] = "较别", ["word"] = {"皎"}},
    -- ["qmcr"] = {["phrase"] = "迁窜", ["word"] = {"芡"}},
    -- ["lmdx"] = {["phrase"] = "连叠", ["word"] = {"奁"}},
    -- ["mido"] = {["phrase"] = "迷夺", ["word"] = {"汨"}},
    -- ["bicb"] = {["phrase"] = "逼凑", ["word"] = {"蓖"}},
    -- ["biuo"] = {["phrase"] = "逼烁", ["word"] = {"臂"}},
    -- ["qqdh"] = {["phrase"] = "遒宕", ["word"] = {"湫"}},
    -- ["dkzj"] = {["phrase"] = "道簪", ["word"] = {"蹈"}},
    -- ["x;kp"] = {["phrase"] = "醒困", ["word"] = {"形"}},
    -- ["yekd"] = {["phrase"] = "野圹", ["word"] = {"咽"}},
    -- ["ludx"] = {["phrase"] = "录牒", ["word"] = {"滤"}},
    -- ["dcvk"] = {["phrase"] = "钓罩", ["word"] = {"貂"}},
    -- ["pudc"] = {["phrase"] = "铺调", ["word"] = {"溥"}},
    -- ["hpub"] = {["phrase"] = "阍守", ["word"] = {"馄"}},
    -- ["lbmn"] = {["phrase"] = "陋民", ["word"] = {"娄", "楼"}},
    -- ["xmzz"] = {["phrase"] = "险贼", ["word"] = {"跹"}},
    -- ["lumk"] = {["phrase"] = "露卯", ["word"] = {"闾", "榈"}},
    -- ["lurk"] = {["phrase"] = "露桡", ["word"] = {"侣"}},
    -- ["hjdx"] = {["phrase"] = "韩蝶", ["word"] = {"瀚"}},
    -- ["tizj"] = {["phrase"] = "题赞", ["word"] = {"蹄"}},
    -- ["eekr"] = {["phrase"] = "额款", ["word"] = {"颚"}},
    -- ["jirk"] = {["phrase"] = "饥扰", ["word"] = {"佶"}},
    -- ["xpcu"] = {["phrase"] = "驯粗", ["word"] = {"蕈"}},
    -- ["qubn"] = {["phrase"] = "驱摈", ["word"] = {"鸲"}},
    -- ["nujn"] = {["phrase"] = "驽筋", ["word"] = {"钕"}},
    -- ["liaa"] = {["phrase"] = "骊阿", ["word"] = {"鳢"}},
    -- ["qidb"] = {["phrase"] = "骑斗", ["word"] = {"淇"}},
    -- ["kvxr"] = {["phrase"] = "魁选", ["word"] = {"愦"}},
    -- ["povk"] = {["phrase"] = "魄兆", ["word"] = {"笸"}},
    -- ["yupn"] = {["phrase"] = "鱼品", ["word"] = {"臾"}},
    -- ["lndx"] = {["phrase"] = "鳞叠", ["word"] = {"凛"}},
    -- ["hdwo"] = {["phrase"] = "黄幄", ["word"] = {"肓"}},
    -- ["dlrh"] = {["phrase"] = "黛壤", ["word"] = {"黛"}},
    -- ["fupz"] = {["phrase"] = "黻佩", ["word"] = {"孚"}},
    -- ["lsbu"] = {["phrase"] = "龙步", ["word"] = {"窿", "癃"}},
    -- ["thtk"] = {["phrase"] = "唐陶", ["word"] = {"塘", "趟"}},
    -- ["uada"] = {["phrase"] = "沙大", ["word"] = {"鲨"}},
    -- ["ihnj"] = {["phrase"] = "厂南", ["word"] = {"嫦"}},
    -- ["lhdo"] = {["phrase"] = "浪多", ["word"] = {"朗"}},
    -- ["muco"] = {["phrase"] = "穆厝", ["word"] = {"暮", "苜"}},
    -- ["liwa"] = {["phrase"] = "里瓦", ["word"] = {"立"}},
    -- ["hbzk"] = {["phrase"] = "猴枣", ["word"] = {"逅", "齁"}},
    -- ["gsgf"] = {["phrase"] = "公根", ["word"] = {"巩"}},
    -- ["yrce"] = {["phrase"] = "圆测", ["word"] = {"芫"}},
    -- ["dink"] = {["phrase"] = "敌脑", ["word"] = {"嫡"}},
    -- ["lddx"] = {["phrase"] = "凉碟", ["word"] = {"凉"}},
    -- ["qila"] = {["phrase"] = "耆腊", ["word"] = {"亟"}}
}

return dup_table
