local dup_table = {
	["vidu"] = { ["phrase"] = "制度", ["word"] = { "汁" } },
	["jihw"] = { ["phrase"] = "计划", ["word"] = { "稷" } },
	["xuyk"] = { ["phrase"] = "需要", ["word"] = { "酗" } },
	["yihb"] = { ["phrase"] = "以后", ["word"] = { "熠" } },
	["viyb"] = { ["phrase"] = "只有", ["word"] = { "识" } },
	["yidm"] = { ["phrase"] = "一点", ["word"] = { "溢" } },
	["jtdy"] = { ["phrase"] = "决定", ["word"] = { "角" } },
	["vkdk"] = { ["phrase"] = "找到", ["word"] = { "召", "沼" } },
	["jmdj"] = { ["phrase"] = "简单", ["word"] = { "渐", "溅" } },
	["sudu"] = { ["phrase"] = "速度", ["word"] = { "涑", "觫" } },
	["uiui"] = { ["phrase"] = "事实", ["word"] = { "蚀" } },
	["likl"] = { ["phrase"] = "离开", ["word"] = { "哩", "呖", "喱" } },
	["yijm"] = { ["phrase"] = "意见", ["word"] = { "镒" } },
	["yudk"] = { ["phrase"] = "遇到", ["word"] = { "浴" } },
	["yumy"] = { ["phrase"] = "域名", ["word"] = { "驭" } },
	["jisr"] = { ["phrase"] = "计算", ["word"] = { "绩" } },
	["yibm"] = { ["phrase"] = "一边", ["word"] = { "益" } },
	["xdyy"] = { ["phrase"] = "相应", ["word"] = { "详" } },
	["fujn"] = { ["phrase"] = "附近", ["word"] = { "幞" } },
	["jike"] = { ["phrase"] = "即可", ["word"] = { "唧" } },
	["mznm"] = { ["phrase"] = "每年", ["word"] = { "媒" } },
	["yygo"] = { ["phrase"] = "英国", ["word"] = { "膺" } },
	["yywf"] = { ["phrase"] = "英文", ["word"] = { "赢", "嬴" } },
	["hvdk"] = { ["phrase"] = "回到", ["word"] = { "汇", "洄" } },
	["jxkb"] = { ["phrase"] = "接口", ["word"] = { "喈" } },
	["qidl"] = { ["phrase"] = "期待", ["word"] = { "泣" } },
	["vifu"] = { ["phrase"] = "支付", ["word"] = { "挚" } },
	["sikk"] = { ["phrase"] = "思考", ["word"] = { "嗣" } },
	["yidj"] = { ["phrase"] = "一旦", ["word"] = { "沂" } },
	["yiky"] = { ["phrase"] = "一块", ["word"] = { "匜", "咦", "咿" } },
	["jiyu"] = { ["phrase"] = "基于", ["word"] = { "计" } },
	["ufru"] = { ["phrase"] = "深入", ["word"] = { "什", "伸" } },
	["xmde"] = { ["phrase"] = "显得", ["word"] = { "洗", "冼" } },
	["vibc"] = { ["phrase"] = "指标", ["word"] = { "痔" } },
	["yixd"] = { ["phrase"] = "一项", ["word"] = { "刈" } },
	["didm"] = { ["phrase"] = "地点", ["word"] = { "涤" } },
	["uivi"] = { ["phrase"] = "是指", ["word"] = { "虱" } },
	["jiby"] = { ["phrase"] = "疾病", ["word"] = { "寂" } },
	["yikr"] = { ["phrase"] = "一款", ["word"] = { "颐" } },
	["uiyb"] = { ["phrase"] = "是由", ["word"] = { "识" } },
	["ykpn"] = { ["phrase"] = "药品", ["word"] = { "鹞" } },
	["jwju"] = { ["phrase"] = "家具", ["word"] = { "镓" } },
	["uiqu"] = { ["phrase"] = "失去", ["word"] = { "舐" } },
	["vize"] = { ["phrase"] = "职责", ["word"] = { "踯" } },
	["jxdk"] = { ["phrase"] = "街道", ["word"] = { "洁" } },
	["ykba"] = { ["phrase"] = "要把", ["word"] = { "疟" } },
	["tsdk"] = { ["phrase"] = "通道", ["word"] = { "洞" } },
	["yiyk"] = { ["phrase"] = "医药", ["word"] = { "诒" } },
	["yidk"] = { ["phrase"] = "一道", ["word"] = { "漪" } },
	["jpdv"] = { ["phrase"] = "军队", ["word"] = { "龟" } },
	["yikk"] = { ["phrase"] = "依靠", ["word"] = { "贻" } },
	["luqu"] = { ["phrase"] = "录取", ["word"] = { "氯" } },
	["uiti"] = { ["phrase"] = "试题", ["word"] = { "螫" } },
	["gsgu"] = { ["phrase"] = "巩固", ["word"] = { "汞" } },
	["qiqr"] = { ["phrase"] = "齐全", ["word"] = { "欺" } },
	["jizl"] = { ["phrase"] = "记载", ["word"] = { "跻" } },
	["fudk"] = { ["phrase"] = "辅导", ["word"] = { "涪" } },
	["vifh"] = { ["phrase"] = "脂肪", ["word"] = { "摭" } },
	["jnll"] = { ["phrase"] = "进来", ["word"] = { "巾" } },
	["jidj"] = { ["phrase"] = "鸡蛋", ["word"] = { "汲" } },
	["fuyb"] = { ["phrase"] = "富有", ["word"] = { "讣" } },
	["grdk"] = { ["phrase"] = "管道", ["word"] = { "涫" } },
	["qqdv"] = { ["phrase"] = "球队", ["word"] = { "龟" } },
	["wudk"] = { ["phrase"] = "舞蹈", ["word"] = { "污", "浯" } },
	["buld"] = { ["phrase"] = "不良", ["word"] = { "卜" } },
	["furf"] = { ["phrase"] = "夫人", ["word"] = { "佛" } },
	["yida"] = { ["phrase"] = "一大", ["word"] = { "殪" } },
	["yikb"] = { ["phrase"] = "一口", ["word"] = { "邑" } },
	["qicl"] = { ["phrase"] = "器材", ["word"] = { "荠" } },
	["yrtx"] = { ["phrase"] = "原帖", ["word"] = { "塬" } },
	["vudo"] = { ["phrase"] = "诸多", ["word"] = { "渚", "潴" } },
	["jmmm"] = { ["phrase"] = "见面", ["word"] = { "槛" } },
	["jiyn"] = { ["phrase"] = "基因", ["word"] = { "鸡" } },
	["licl"] = { ["phrase"] = "理财", ["word"] = { "荔", "苈", "莅" } },
	["yixc"] = { ["phrase"] = "一笑", ["word"] = { "羿" } },
	["qidm"] = { ["phrase"] = "起点", ["word"] = { "柒" } },
	["bukf"] = { ["phrase"] = "不肯", ["word"] = { "哺" } },
	["jiho"] = { ["phrase"] = "激活", ["word"] = { "稽" } },
	["jihe"] = { ["phrase"] = "集合", ["word"] = { "嵇" } },
	["jilv"] = { ["phrase"] = "纪律", ["word"] = { "乩" } },
	["yeye"] = { ["phrase"] = "爷爷", ["word"] = { "邺" } },
	["ykjd"] = { ["phrase"] = "要将", ["word"] = { "铫" } },
	["mucl"] = { ["phrase"] = "木材", ["word"] = { "募" } },
	["yiiu"] = { ["phrase"] = "一处", ["word"] = { "轶" } },
	["tjdk"] = { ["phrase"] = "谈到", ["word"] = { "澹" } },
	["jida"] = { ["phrase"] = "极大", ["word"] = { "殛" } },
	["yjve"] = { ["phrase"] = "沿着", ["word"] = { "鄢" } },
	["lddm"] = { ["phrase"] = "亮点", ["word"] = { "梁", "粱" } },
	["yuwo"] = { ["phrase"] = "与我", ["word"] = { "育" } },
	["yuky"] = { ["phrase"] = "愉快", ["word"] = { "吁", "喁" } },
	["zidr"] = { ["phrase"] = "字段", ["word"] = { "资", "渍" } },
	["yaii"] = { ["phrase"] = "牙齿", ["word"] = { "衙" } },
	["tkfh"] = { ["phrase"] = "套房", ["word"] = { "焘" } },
	["xrdy"] = { ["phrase"] = "选定", ["word"] = { "泫" } },
	["iuui"] = { ["phrase"] = "出示", ["word"] = { "础" } },
	["bzpo"] = { ["phrase"] = "被迫", ["word"] = { "褙" } },
	["tamz"] = { ["phrase"] = "他没", ["word"] = { "闼" } },
	["xmuh"] = { ["phrase"] = "线上", ["word"] = { "燹" } },
	["jmbh"] = { ["phrase"] = "肩膀", ["word"] = { "煎" } },
	["xdwz"] = { ["phrase"] = "香味", ["word"] = { "享" } },
	["hsbk"] = { ["phrase"] = "红包", ["word"] = { "訇" } },
	["uidr"] = { ["phrase"] = "时段", ["word"] = { "湜" } },
	["gsgr"] = { ["phrase"] = "公关", ["word"] = { "贡" } },
	["dide"] = { ["phrase"] = "低的", ["word"] = { "邸" } },
	["ufsu"] = { ["phrase"] = "申诉", ["word"] = { "绅" } },
	["xmee"] = { ["phrase"] = "限额", ["word"] = { "岘" } },
	["fuvl"] = { ["phrase"] = "负债", ["word"] = { "弗" } },
	["livi"] = { ["phrase"] = "理智", ["word"] = { "蠡" } },
	["jxuv"] = { ["phrase"] = "节水", ["word"] = { "碣" } },
	["yiby"] = { ["phrase"] = "一并", ["word"] = { "疫", "痍", "肄" } },
	["qrjw"] = { ["phrase"] = "全家", ["word"] = { "铨" } },
	["ufye"] = { ["phrase"] = "深夜", ["word"] = { "诜" } },
	["hedk"] = { ["phrase"] = "河道", ["word"] = { "河", "涸" } },
	["jibu"] = { ["phrase"] = "既不", ["word"] = { "疾" } },
	["suyh"] = { ["phrase"] = "素养", ["word"] = { "酥" } },
	["iuih"] = { ["phrase"] = "出场", ["word"] = { "蜍" } },
	["yjii"] = { ["phrase"] = "延迟", ["word"] = { "衍" } },
	["jmro"] = { ["phrase"] = "减弱", ["word"] = { "僭" } },
	["liwl"] = { ["phrase"] = "例外", ["word"] = { "理" } },
	["ubbc"] = { ["phrase"] = "手表", ["word"] = { "守" } },
	["liqd"] = { ["phrase"] = "李强", ["word"] = { "猁" } },
	["hdjw"] = { ["phrase"] = "皇家", ["word"] = { "凰", "幌" } },
	["iumo"] = { ["phrase"] = "触摸", ["word"] = { "楮" } },
	["vjdk"] = { ["phrase"] = "占到", ["word"] = { "沾", "詹" } },
	["uian"] = { ["phrase"] = "是按", ["word"] = { "豕" } },
	["wuxw"] = { ["phrase"] = "武侠", ["word"] = { "怃", "忤" } },
	["yuuh"] = { ["phrase"] = "遇上", ["word"] = { "熨" } },
	["vidv"] = { ["phrase"] = "支队", ["word"] = { "沚" } },
	["hddb"] = { ["phrase"] = "黄豆", ["word"] = { "潢" } },
	["uiuj"] = { ["phrase"] = "屎山", ["word"] = { "饰" } },
	["zlbu"] = { ["phrase"] = "在不", ["word"] = { "宰" } },
	["ypss"] = { ["phrase"] = "运送", ["word"] = { "纭" } },
	["jmvj"] = { ["phrase"] = "建站", ["word"] = { "笺" } },
	["libl"] = { ["phrase"] = "李白", ["word"] = { "疬" } },
	["lian"] = { ["phrase"] = "立案", ["word"] = { "吏" } },
	["qipj"] = { ["phrase"] = "期盼", ["word"] = { "祈" } },
	["xxdy"] = { ["phrase"] = "协定", ["word"] = { "泻" } },
	["yrde"] = { ["phrase"] = "远的", ["word"] = { "沅" } },
	["fucl"] = { ["phrase"] = "福彩", ["word"] = { "芾" } },
	["mksi"] = { ["phrase"] = "貌似", ["word"] = { "蝥", "蟊" } },
	["viuo"] = { ["phrase"] = "之说", ["word"] = { "智" } },
	["ckmz"] = { ["phrase"] = "草莓", ["word"] = { "糙" } },
	["iaua"] = { ["phrase"] = "查杀", ["word"] = { "馇", "碴" } },
	["mmdm"] = { ["phrase"] = "缅甸", ["word"] = { "沔", "湎" } },
	["jiug"] = { ["phrase"] = "计生", ["word"] = { "戟" } },
	["dbba"] = { ["phrase"] = "都把", ["word"] = { "痘" } },
	["uhxy"] = { ["phrase"] = "上行", ["word"] = { "裳" } },
	["vjdv"] = { ["phrase"] = "战队", ["word"] = { "湛" } },
	["yier"] = { ["phrase"] = "一二", ["word"] = { "嶷" } },
	["mogu"] = { ["phrase"] = "蘑菇", ["word"] = { "摩", "磨" } },
	["vgfa"] = { ["phrase"] = "蒸发", ["word"] = { "拯" } },
	["zibz"] = { ["phrase"] = "自卑", ["word"] = { "字", "孳" } },
	["gojy"] = { ["phrase"] = "郭靖", ["word"] = { "帼" } },
	["jivj"] = { ["phrase"] = "激战", ["word"] = { "笈" } },
	["fjuf"] = { ["phrase"] = "翻身", ["word"] = { "矾" } },
	["hjdk"] = { ["phrase"] = "喊道", ["word"] = { "涵" } },
	["jmmz"] = { ["phrase"] = "健美", ["word"] = { "毽" } },
	["hsds"] = { ["phrase"] = "轰动", ["word"] = { "泓" } },
	["juzu"] = { ["phrase"] = "剧组", ["word"] = { "遽" } },
	["hwmu"] = { ["phrase"] = "花木", ["word"] = { "桦", "骅" } },
	["wuyr"] = { ["phrase"] = "无缘", ["word"] = { "诬" } },
	["jiee"] = { ["phrase"] = "饥饿", ["word"] = { "觊" } },
	["cjlm"] = { ["phrase"] = "残联", ["word"] = { "粲" } },
	["jyvd"] = { ["phrase"] = "精装", ["word"] = { "刭" } },
	["jxmk"] = { ["phrase"] = "睫毛", ["word"] = { "桔" } },
	["yell"] = { ["phrase"] = "也来", ["word"] = { "野" } },
	["ubby"] = { ["phrase"] = "手柄", ["word"] = { "瘦" } },
	["ynvg"] = { ["phrase"] = "印证", ["word"] = { "龈" } },
	["xixx"] = { ["phrase"] = "吸血", ["word"] = { "恓" } },
	["uuhu"] = { ["phrase"] = "疏忽", ["word"] = { "秫", "黍" } },
	["ueii"] = { ["phrase"] = "奢侈", ["word"] = { "厍" } },
	["cvmm"] = { ["phrase"] = "催眠", ["word"] = { "毳" } },
	["anbm"] = { ["phrase"] = "岸边", ["word"] = { "案" } },
	["yjke"] = { ["phrase"] = "眼科", ["word"] = { "郾" } },
	["xiuj"] = { ["phrase"] = "西山", ["word"] = { "豨" } },
	["viuf"] = { ["phrase"] = "之神", ["word"] = { "雉" } },
	["vhmu"] = { ["phrase"] = "账目", ["word"] = { "樟" } },
	["viju"] = { ["phrase"] = "之举", ["word"] = { "帙" } },
	["yiru"] = { ["phrase"] = "一如", ["word"] = { "佚" } },
	["jdyn"] = { ["phrase"] = "江阴", ["word"] = { "姜" } },
	["ssds"] = { ["phrase"] = "松动", ["word"] = { "凇", "淞" } },
	["vbye"] = { ["phrase"] = "昼夜", ["word"] = { "诌" } },
	["lowf"] = { ["phrase"] = "螺纹", ["word"] = { "雒" } },
	["quii"] = { ["phrase"] = "去吃", ["word"] = { "衢" } },
	["jmbk"] = { ["phrase"] = "简报", ["word"] = { "謇" } },
	["yrdl"] = { ["phrase"] = "元代", ["word"] = { "渊" } },
	["hjfg"] = { ["phrase"] = "寒风", ["word"] = { "捍" } },
	["zimz"] = { ["phrase"] = "姊妹", ["word"] = { "籽" } },
	["ykxx"] = { ["phrase"] = "要写", ["word"] = { "爻" } },
	["sitc"] = { ["phrase"] = "四条", ["word"] = { "寺" } },
	["vuzi"] = { ["phrase"] = "竹子", ["word"] = { "躅" } },
	["uiln"] = { ["phrase"] = "石林", ["word"] = { "史" } },
	["yipn"] = { ["phrase"] = "一品", ["word"] = { "乂" } },
	["djdk"] = { ["phrase"] = "但到", ["word"] = { "澹" } },
	["zidy"] = { ["phrase"] = "自定", ["word"] = { "滋" } },
	["iizk"] = { ["phrase"] = "迟早", ["word"] = { "踟" } },
	["vudv"] = { ["phrase"] = "主队", ["word"] = { "注", "洙" } },
	["jiwj"] = { ["phrase"] = "几万", ["word"] = { "玑" } },
	["jylo"] = { ["phrase"] = "经络", ["word"] = { "靖" } },
	["yymm"] = { ["phrase"] = "迎面", ["word"] = { "楹" } },
	["yybn"] = { ["phrase"] = "迎宾", ["word"] = { "瘿" } },
	["huhu"] = { ["phrase"] = "呼呼", ["word"] = { "戽" } },
	["yjyy"] = { ["phrase"] = "眼影", ["word"] = { "酽" } },
	["jxbl"] = { ["phrase"] = "洁白", ["word"] = { "疥" } },
	["yrdy"] = { ["phrase"] = "原定", ["word"] = { "湲" } },
	["jidk"] = { ["phrase"] = "即到", ["word"] = { "奇" } },
	["wzjw"] = { ["phrase"] = "为佳", ["word"] = { "帏" } },
	["xcxd"] = { ["phrase"] = "潇湘", ["word"] = { "削" } },
	["ximx"] = { ["phrase"] = "熄灭", ["word"] = { "粞" } },
	["xxur"] = { ["phrase"] = "血栓", ["word"] = { "颉" } },
	["quhw"] = { ["phrase"] = "区划", ["word"] = { "黢" } },
	["xuno"] = { ["phrase"] = "许诺", ["word"] = { "婿" } },
	["xrjd"] = { ["phrase"] = "宣讲", ["word"] = { "券" } },
	["yjhj"] = { ["phrase"] = "严寒", ["word"] = { "焰" } },
	["uhtk"] = { ["phrase"] = "商讨", ["word"] = { "垧", "墒" } },
	["gsbk"] = { ["phrase"] = "公报", ["word"] = { "宫" } },
	["lyds"] = { ["phrase"] = "灵动", ["word"] = { "泠" } },
	["pcxd"] = { ["phrase"] = "飘香", ["word"] = { "剽" } },
	["tmdk"] = { ["phrase"] = "天道", ["word"] = { "湉" } },
	["jicu"] = { ["phrase"] = "急促", ["word"] = { "蒺" } },
	["yuyk"] = { ["phrase"] = "余姚", ["word"] = { "语", "雩" } },
	["uiky"] = { ["phrase"] = "石块", ["word"] = { "嘘" } },
	["lizl"] = { ["phrase"] = "立在", ["word"] = { "逦", "跞" } },
	["qyck"] = { ["phrase"] = "青草", ["word"] = { "苘" } },
	["ihxm"] = { ["phrase"] = "长线", ["word"] = { "氅" } },
	["ykky"] = { ["phrase"] = "要快", ["word"] = { "吆" } },
	["jwly"] = { ["phrase"] = "贾玲", ["word"] = { "袈" } },
	["jqpa"] = { ["phrase"] = "就怕", ["word"] = { "臼" } },
	["jiny"] = { ["phrase"] = "济宁", ["word"] = { "妓" } },
	["monm"] = { ["phrase"] = "末年", ["word"] = { "嬷" } },
	["ykbl"] = { ["phrase"] = "摇摆", ["word"] = { "窈" } },
	["lyks"] = { ["phrase"] = "凌空", ["word"] = { "呤", "囹" } },
	["ikhu"] = { ["phrase"] = "巢湖", ["word"] = { "炒", "焯" } },
	["wzdo"] = { ["phrase"] = "为多", ["word"] = { "洧", "渭" } },
	["yjif"] = { ["phrase"] = "烟尘", ["word"] = { "雁" } },
	["mibi"] = { ["phrase"] = "密闭", ["word"] = { "蜜" } },
	["jiyt"] = { ["phrase"] = "集约", ["word"] = { "畿" } },
	["ynjd"] = { ["phrase"] = "银奖", ["word"] = { "铟" } },
	["ybyj"] = { ["phrase"] = "油烟", ["word"] = { "羑" } },
	["ybjy"] = { ["phrase"] = "幽静", ["word"] = { "铀", "鼬" } },
	["jcuh"] = { ["phrase"] = "脚上", ["word"] = { "礁" } },
	["vuve"] = { ["phrase"] = "住着", ["word"] = { "邾", "竺" } },
	["ibrf"] = { ["phrase"] = "仇人", ["word"] = { "雠" } },
	["juhk"] = { ["phrase"] = "句号", ["word"] = { "焗" } },
	["fumz"] = { ["phrase"] = "赴美", ["word"] = { "桴" } },
	["jcyh"] = { ["phrase"] = "教养", ["word"] = { "醮" } },
	["gekl"] = { ["phrase"] = "隔开", ["word"] = { "嗝" } },
	["ujye"] = { ["phrase"] = "山野", ["word"] = { "讪", "鄯" } },
	["xxdi"] = { ["phrase"] = "鞋底", ["word"] = { "蟹" } },
	["xikj"] = { ["phrase"] = "细看", ["word"] = { "吸", "唏" } },
	["ybyn"] = { ["phrase"] = "又因", ["word"] = { "诱" } },
	["hetm"] = { ["phrase"] = "和田", ["word"] = { "盍" } },
	["bodb"] = { ["phrase"] = "搏斗", ["word"] = { "泊" } },
	["pibk"] = { ["phrase"] = "皮包", ["word"] = { "否", "痞" } },
	["hrbi"] = { ["phrase"] = "环比", ["word"] = { "宦" } },
	["xmnm"] = { ["phrase"] = "现年", ["word"] = { "娴" } },
	["jidl"] = { ["phrase"] = "几代", ["word"] = { "济" } },
	["jnso"] = { ["phrase"] = "紧缩", ["word"] = { "缙" } },
	["jucj"] = { ["phrase"] = "聚餐", ["word"] = { "苣" } },
	["yilx"] = { ["phrase"] = "一列", ["word"] = { "意", "翊" } },
	["guuu"] = { ["phrase"] = "古树", ["word"] = { "辜" } },
	["jisv"] = { ["phrase"] = "脊髓", ["word"] = { "继" } },
	["hrky"] = { ["phrase"] = "欢快", ["word"] = { "圜" } },
	["yuxd"] = { ["phrase"] = "预想", ["word"] = { "愉" } },
	["yuyr"] = { ["phrase"] = "余元", ["word"] = { "欤" } },
	["bizl"] = { ["phrase"] = "比在", ["word"] = { "鼻" } },
	["ypls"] = { ["phrase"] = "云龙", ["word"] = { "耘" } },
	["lquu"] = { ["phrase"] = "柳树", ["word"] = { "碌" } },
	["jigv"] = { ["phrase"] = "机柜", ["word"] = { "既" } },
	["yusl"] = { ["phrase"] = "预赛", ["word"] = { "予" } },
	["volu"] = { ["phrase"] = "着陆", ["word"] = { "卓" } },
	["qidu"] = { ["phrase"] = "气度", ["word"] = { "漆" } },
	["gkyh"] = { ["phrase"] = "羔羊", ["word"] = { "羔" } },
	["hwru"] = { ["phrase"] = "划入", ["word"] = { "华" } },
	["yjig"] = { ["phrase"] = "严惩", ["word"] = { "魇" } },
	["jicl"] = { ["phrase"] = "基材", ["word"] = { "荠" } },
	["xnju"] = { ["phrase"] = "新居", ["word"] = { "锌" } },
	["yure"] = { ["phrase"] = "预热", ["word"] = { "觎" } },
	["viky"] = { ["phrase"] = "之快", ["word"] = { "吱" } },
	["bovb"] = { ["phrase"] = "亳州", ["word"] = { "舶", "箔" } },
	["hudu"] = { ["phrase"] = "弧度", ["word"] = { "户", "斛" } },
	["erde"] = { ["phrase"] = "尔德", ["word"] = { "洱" } },
	["njty"] = { ["phrase"] = "难听", ["word"] = { "赧" } },
	["tjta"] = { ["phrase"] = "坍塌", ["word"] = { "坦" } },
	["liln"] = { ["phrase"] = "莅临", ["word"] = { "鹂" } },
	["wuwl"] = { ["phrase"] = "屋外", ["word"] = { "务" } },
	["jqbj"] = { ["phrase"] = "旧版", ["word"] = { "究", "疚" } },
	["suxx"] = { ["phrase"] = "速写", ["word"] = { "愫" } },
	["xmmn"] = { ["phrase"] = "先民", ["word"] = { "鹇" } },
	["xcvs"] = { ["phrase"] = "消肿", ["word"] = { "箫" } },
	["qyuf"] = { ["phrase"] = "情深", ["word"] = { "罄" } },
	["xidj"] = { ["phrase"] = "西单", ["word"] = { "浠", "淅" } },
	["hvcs"] = { ["phrase"] = "慧聪", ["word"] = { "荟" } },
	["jido"] = { ["phrase"] = "几多", ["word"] = { "脊" } },
	["qicj"] = { ["phrase"] = "凄惨", ["word"] = { "芑", "蕲" } },
	["qmjq"] = { ["phrase"] = "迁就", ["word"] = { "钎" } },
	["quty"] = { ["phrase"] = "去听", ["word"] = { "趣" } },
	["ciby"] = { ["phrase"] = "此病", ["word"] = { "兹" } },
	["bzuj"] = { ["phrase"] = "被删", ["word"] = { "鐾" } },
	["dumo"] = { ["phrase"] = "镀膜", ["word"] = { "阇" } },
}

return dup_table
