local dup_table = {
	["jihb"] = { ["phrase"] = "计划", ["word"] = { "积" } },
	["yixb"] = { ["phrase"] = "一下", ["word"] = { "翼", "悒" } },
	["yidj"] = { ["phrase"] = "一点", ["word"] = { "沂" } },
	["yisi"] = { ["phrase"] = "意思", ["word"] = { "矣" } },
	["iipl"] = { ["phrase"] = "视频", ["word"] = { "释" } },
	["guii"] = { ["phrase"] = "故事", ["word"] = { "辜" } },
	["bdbd"] = { ["phrase"] = "宝宝", ["word"] = { "刨" } },
	["zidy"] = { ["phrase"] = "自动", ["word"] = { "滋" } },
	["yudd"] = { ["phrase"] = "遇到", ["word"] = { "淤", "渝" } },
	["jike"] = { ["phrase"] = "即可", ["word"] = { "唧" } },
	["jhdi"] = { ["phrase"] = "降低", ["word"] = { "浆" } },
	["yqgo"] = { ["phrase"] = "英国", ["word"] = { "膺" } },
	["jjdd"] = { ["phrase"] = "见到", ["word"] = { "湔" } },
	["iiqi"] = { ["phrase"] = "时期", ["word"] = { "舐" } },
	["yikx"] = { ["phrase"] = "一块", ["word"] = { "噫", "翳" } },
	["yzxu"] = { ["phrase"] = "允许", ["word"] = { "恽" } },
	["xjde"] = { ["phrase"] = "显得", ["word"] = { "洗", "冼" } },
	["lqrr"] = { ["phrase"] = "令人", ["word"] = { "领" } },
	["vidq"] = { ["phrase"] = "指定", ["word"] = { "殖" } },
	["jiyi"] = { ["phrase"] = "记忆", ["word"] = { "计" } },
	["svii"] = { ["phrase"] = "随时", ["word"] = { "尿", "碎" } },
	["jlry"] = { ["phrase"] = "金融", ["word"] = { "仅" } },
	["yldd"] = { ["phrase"] = "引导", ["word"] = { "洇" } },
	["juml"] = { ["phrase"] = "居民", ["word"] = { "榉" } },
	["boii"] = { ["phrase"] = "博士", ["word"] = { "擘" } },
	["yfuu"] = { ["phrase"] = "演出", ["word"] = { "衍" } },
	["plvi"] = { ["phrase"] = "品质", ["word"] = { "颦" } },
	["hcbd"] = { ["phrase"] = "环保", ["word"] = { "痪" } },
	["jiut"] = { ["phrase"] = "集成", ["word"] = { "墼" } },
	["jjdq"] = { ["phrase"] = "鉴定", ["word"] = { "歼" } },
	["vize"] = { ["phrase"] = "职责", ["word"] = { "踯" } },
	["qici"] = { ["phrase"] = "其次", ["word"] = { "芪" } },
	["wwyc"] = { ["phrase"] = "委员", ["word"] = { "霨" } },
	["ydba"] = { ["phrase"] = "要把", ["word"] = { "疟" } },
	["viut"] = { ["phrase"] = "支撑", ["word"] = { "轾", "蛭" } },
	["jzdv"] = { ["phrase"] = "军队", ["word"] = { "龟" } },
	["tftd"] = { ["phrase"] = "探讨", ["word"] = { "坍" } },
	["xljj"] = { ["phrase"] = "新建", ["word"] = { "鑫" } },
	["jumj"] = { ["phrase"] = "局面", ["word"] = { "柜" } },
	["qidd"] = { ["phrase"] = "起到", ["word"] = { "沏" } },
	["fukc"] = { ["phrase"] = "付款", ["word"] = { "咐", "赙" } },
	["ydky"] = { ["phrase"] = "遥控", ["word"] = { "吆" } },
	["yfug"] = { ["phrase"] = "延长", ["word"] = { "魇" } },
	["mwmw"] = { ["phrase"] = "妹妹", ["word"] = { "枚" } },
	["bici"] = { ["phrase"] = "彼此", ["word"] = { "荜", "薜" } },
	["jici"] = { ["phrase"] = "几次", ["word"] = { "蒺" } },
	["iirr"] = { ["phrase"] = "使人", ["word"] = { "似" } },
	["vywu"] = { ["phrase"] = "中午", ["word"] = { "螽" } },
	["qndv"] = { ["phrase"] = "球队", ["word"] = { "龟" } },
	["vimq"] = { ["phrase"] = "知名", ["word"] = { "植" } },
	["jitj"] = { ["phrase"] = "几天", ["word"] = { "圾" } },
	["iifg"] = { ["phrase"] = "释放", ["word"] = { "拭" } },
	["yibr"] = { ["phrase"] = "一本", ["word"] = { "疑" } },
	["iitu"] = { ["phrase"] = "试图", ["word"] = { "螫" } },
	["rrrr"] = { ["phrase"] = "人人", ["word"] = { "任", "仞" } },
	["yida"] = { ["phrase"] = "一大", ["word"] = { "殪" } },
	["yiml"] = { ["phrase"] = "移民", ["word"] = { "驿" } },
	["bdzi"] = { ["phrase"] = "包子", ["word"] = { "趵" } },
	["bjli"] = { ["phrase"] = "便利", ["word"] = { "辨", "辩", "辫" } },
	["vudo"] = { ["phrase"] = "诸多", ["word"] = { "渚", "潴" } },
	["yiri"] = { ["phrase"] = "一日", ["word"] = { "佚" } },
	["qjjq"] = { ["phrase"] = "前景", ["word"] = { "钎" } },
	["viji"] = { ["phrase"] = "之际", ["word"] = { "帙" } },
	["jiyl"] = { ["phrase"] = "基因", ["word"] = { "霁" } },
	["jiir"] = { ["phrase"] = "机身", ["word"] = { "赍" } },
	["yixk"] = { ["phrase"] = "一笑", ["word"] = { "怡" } },
	["juqq"] = { ["phrase"] = "剧情", ["word"] = { "狙" } },
	["dgci"] = { ["phrase"] = "档次", ["word"] = { "菪" } },
	["jiho"] = { ["phrase"] = "激活", ["word"] = { "稽" } },
	["jihe"] = { ["phrase"] = "集合", ["word"] = { "嵇" } },
	["jilv"] = { ["phrase"] = "纪律", ["word"] = { "乩" } },
	["yeye"] = { ["phrase"] = "爷爷", ["word"] = { "邺" } },
	["qipj"] = { ["phrase"] = "欺骗", ["word"] = { "祈" } },
	["voli"] = { ["phrase"] = "着力", ["word"] = { "卓" } },
	["djfr"] = { ["phrase"] = "淀粉", ["word"] = { "靛" } },
	["juzi"] = { ["phrase"] = "句子", ["word"] = { "遽" } },
	["jida"] = { ["phrase"] = "极大", ["word"] = { "殛" } },
	["quuu"] = { ["phrase"] = "取出", ["word"] = { "衢" } },
	["yfve"] = { ["phrase"] = "沿着", ["word"] = { "鄢" } },
	["biii"] = { ["phrase"] = "笔试", ["word"] = { "辟" } },
	["mibu"] = { ["phrase"] = "弥补", ["word"] = { "蜜" } },
	["yuwo"] = { ["phrase"] = "与我", ["word"] = { "育" } },
	["ugnj"] = { ["phrase"] = "常年", ["word"] = { "嫦" } },
	["xizd"] = { ["phrase"] = "洗澡", ["word"] = { "蹊" } },
	["bizi"] = { ["phrase"] = "鼻子", ["word"] = { "避", "跸" } },
	["iiky"] = { ["phrase"] = "时空", ["word"] = { "嘘" } },
	["jiig"] = { ["phrase"] = "机上", ["word"] = { "戟" } },
	["kewr"] = { ["phrase"] = "课文", ["word"] = { "颏" } },
	["yunl"] = { ["phrase"] = "与您", ["word"] = { "妤" } },
	["iiln"] = { ["phrase"] = "十六", ["word"] = { "史" } },
	["fucy"] = { ["phrase"] = "服从", ["word"] = { "菔" } },
	["luvi"] = { ["phrase"] = "录制", ["word"] = { "舻", "箓" } },
	["bwpo"] = { ["phrase"] = "被迫", ["word"] = { "褙" } },
	["yuvy"] = { ["phrase"] = "语种", ["word"] = { "竽" } },
	["yuyx"] = { ["phrase"] = "预约", ["word"] = { "愚" } },
	["bjhc"] = { ["phrase"] = "变换", ["word"] = { "扁", "煸" } },
	["wuyx"] = { ["phrase"] = "五月", ["word"] = { "恶" } },
	["ylvg"] = { ["phrase"] = "印章", ["word"] = { "龈" } },
	["lnii"] = { ["phrase"] = "流失", ["word"] = { "碌" } },
	["jxwg"] = { ["phrase"] = "绝望", ["word"] = { "玦" } },
	["fufw"] = { ["phrase"] = "付费", ["word"] = { "抚", "敷" } },
	["qiir"] = { ["phrase"] = "起身", ["word"] = { "碛" } },
	["dide"] = { ["phrase"] = "低的", ["word"] = { "邸" } },
	["bivi"] = { ["phrase"] = "壁纸", ["word"] = { "筚" } },
	["xjee"] = { ["phrase"] = "限额", ["word"] = { "岘" } },
	["jidj"] = { ["phrase"] = "几点", ["word"] = { "汲" } },
	["jmiv"] = { ["phrase"] = "节水", ["word"] = { "碣" } },
	["jnjh"] = { ["phrase"] = "就将", ["word"] = { "灸" } },
	["iivr"] = { ["phrase"] = "是真", ["word"] = { "筮" } },
	["vidj"] = { ["phrase"] = "指点", ["word"] = { "滞" } },
	["irye"] = { ["phrase"] = "深夜", ["word"] = { "诜" } },
	["nfty"] = { ["phrase"] = "南通", ["word"] = { "赧" } },
	["qqif"] = { ["phrase"] = "青山", ["word"] = { "罄" } },
	["ugxk"] = { ["phrase"] = "畅销", ["word"] = { "惝" } },
	["jhdd"] = { ["phrase"] = "降到", ["word"] = { "奖" } },
	["qlfr"] = { ["phrase"] = "勤奋", ["word"] = { "揿" } },
	["jjro"] = { ["phrase"] = "减弱", ["word"] = { "僭" } },
	["ipbk"] = { ["phrase"] = "手表", ["word"] = { "兽" } },
	["iimj"] = { ["phrase"] = "失眠", ["word"] = { "柿" } },
	["vitq"] = { ["phrase"] = "只听", ["word"] = { "埴" } },
	["uumo"] = { ["phrase"] = "触摸", ["word"] = { "楮" } },
	["iian"] = { ["phrase"] = "是按", ["word"] = { "豕" } },
	["yixl"] = { ["phrase"] = "一心", ["word"] = { "怿", "翌" } },
	["dudd"] = { ["phrase"] = "督导", ["word"] = { "渎" } },
	["vifr"] = { ["phrase"] = "之分", ["word"] = { "贽" } },
	["jujk"] = { ["phrase"] = "聚焦", ["word"] = { "锯", "锔" } },
	["bovy"] = { ["phrase"] = "播种", ["word"] = { "簸" } },
	["bukf"] = { ["phrase"] = "不看", ["word"] = { "哺" } },
	["vidv"] = { ["phrase"] = "支队", ["word"] = { "沚" } },
	["bsii"] = { ["phrase"] = "百事", ["word"] = { "掰" } },
	["qqhx"] = { ["phrase"] = "情怀", ["word"] = { "綮", "黥" } },
	["syds"] = { ["phrase"] = "宋代", ["word"] = { "凇", "淞" } },
	["bidc"] = { ["phrase"] = "弊端", ["word"] = { "弊" } },
	["xhyy"] = { ["phrase"] = "享用", ["word"] = { "详" } },
	["lian"] = { ["phrase"] = "立案", ["word"] = { "吏" } },
	["vizi"] = { ["phrase"] = "之子", ["word"] = { "跖" } },
	["ycde"] = { ["phrase"] = "远的", ["word"] = { "沅" } },
	["yiyy"] = { ["phrase"] = "医用", ["word"] = { "议" } },
	["wfbd"] = { ["phrase"] = "晚报", ["word"] = { "剜" } },
	["viio"] = { ["phrase"] = "之说", ["word"] = { "智" } },
	["uaia"] = { ["phrase"] = "查杀", ["word"] = { "馇", "碴" } },
	["jujb"] = { ["phrase"] = "居家", ["word"] = { "飓" } },
	["dfdk"] = { ["phrase"] = "单调", ["word"] = { "澹" } },
	["dpba"] = { ["phrase"] = "都把", ["word"] = { "痘" } },
	["pwyl"] = { ["phrase"] = "配音", ["word"] = { "霈" } },
	["yijm"] = { ["phrase"] = "一节", ["word"] = { "镒" } },
	["vrtp"] = { ["phrase"] = "枕头", ["word"] = { "畛" } },
	["vryp"] = { ["phrase"] = "真有", ["word"] = { "诊" } },
	["qumq"] = { ["phrase"] = "取名", ["word"] = { "阒" } },
	["ludi"] = { ["phrase"] = "陆地", ["word"] = { "泸", "渌" } },
	["jnjl"] = { ["phrase"] = "就近", ["word"] = { "舅" } },
	["vfdv"] = { ["phrase"] = "战队", ["word"] = { "湛" } },
	["vtfa"] = { ["phrase"] = "蒸发", ["word"] = { "拯" } },
	["qjbi"] = { ["phrase"] = "铅笔", ["word"] = { "搴" } },
	["uajx"] = { ["phrase"] = "察觉", ["word"] = { "镲" } },
	["jbji"] = { ["phrase"] = "加急", ["word"] = { "镓" } },
	["yqcy"] = { ["phrase"] = "应从", ["word"] = { "英", "莹" } },
	["qitj"] = { ["phrase"] = "七天", ["word"] = { "起", "圻" } },
	["iiyg"] = { ["phrase"] = "式样", ["word"] = { "式", "试" } },
	["fuyd"] = { ["phrase"] = "服药", ["word"] = { "黻" } },
	["luzi"] = { ["phrase"] = "路子", ["word"] = { "逯" } },
	["gcdk"] = { ["phrase"] = "关掉", ["word"] = { "涫" } },
	["vupl"] = { ["phrase"] = "主频", ["word"] = { "竹" } },
	["wumw"] = { ["phrase"] = "妩媚", ["word"] = { "杌" } },
	["qiri"] = { ["phrase"] = "七日", ["word"] = { "俟" } },
	["yfjk"] = { ["phrase"] = "眼角", ["word"] = { "铅" } },
	["xkmw"] = { ["phrase"] = "小妹", ["word"] = { "骁" } },
	["ycdy"] = { ["phrase"] = "远东", ["word"] = { "湲" } },
	["ydxx"] = { ["phrase"] = "药学", ["word"] = { "爻" } },
	["djbd"] = { ["phrase"] = "电报", ["word"] = { "奠" } },
	["ypbq"] = { ["phrase"] = "有病", ["word"] = { "猷" } },
	["yizd"] = { ["phrase"] = "一早", ["word"] = { "逸", "劓" } },
	["jiee"] = { ["phrase"] = "饥饿", ["word"] = { "觊" } },
	["lqds"] = { ["phrase"] = "领带", ["word"] = { "泠" } },
	["hvxh"] = { ["phrase"] = "回想", ["word"] = { "恢" } },
	["yicy"] = { ["phrase"] = "已从", ["word"] = { "荑" } },
	["fwyf"] = { ["phrase"] = "肺炎", ["word"] = { "诽", "霏" } },
	["viky"] = { ["phrase"] = "指控", ["word"] = { "吱" } },
	["wwmw"] = { ["phrase"] = "唯美", ["word"] = { "闱" } },
	["wunw"] = { ["phrase"] = "屋内", ["word"] = { "物", "妩" } },
	["qidi"] = { ["phrase"] = "启迪", ["word"] = { "漆" } },
	["dimd"] = { ["phrase"] = "地貌", ["word"] = { "柢" } },
	["yfke"] = { ["phrase"] = "眼科", ["word"] = { "郾" } },
	["wodt"] = { ["phrase"] = "我等", ["word"] = { "渥" } },
	["sidj"] = { ["phrase"] = "四点", ["word"] = { "澌" } },
	["fudk"] = { ["phrase"] = "浮雕", ["word"] = { "涪" } },
	["yfyy"] = { ["phrase"] = "沿用", ["word"] = { "酽" } },
	["vefu"] = { ["phrase"] = "这幅", ["word"] = { "蛰", "蜇" } },
	["zidi"] = { ["phrase"] = "子弟", ["word"] = { "滓" } },
	["xlji"] = { ["phrase"] = "心急", ["word"] = { "锌" } },
	["vpye"] = { ["phrase"] = "昼夜", ["word"] = { "诌" } },
	["gedk"] = { ["phrase"] = "格调", ["word"] = { "哥" } },
	["yudk"] = { ["phrase"] = "语调", ["word"] = { "浴" } },
	["wugp"] = { ["phrase"] = "污垢", ["word"] = { "戊" } },
	["xiyd"] = { ["phrase"] = "西药", ["word"] = { "羲" } },
	["igdp"] = { ["phrase"] = "上都", ["word"] = { "殇", "觞" } },
	["jjbd"] = { ["phrase"] = "简报", ["word"] = { "剪" } },
	["buld"] = { ["phrase"] = "捕捞", ["word"] = { "卜" } },
	["piii"] = { ["phrase"] = "批示", ["word"] = { "辟", "鼙" } },
	["uefw"] = { ["phrase"] = "车费", ["word"] = { "撤" } },
	["hfrr"] = { ["phrase"] = "汉人", ["word"] = { "颔" } },
	["hvhx"] = { ["phrase"] = "毁坏", ["word"] = { "秽" } },
	["gfmg"] = { ["phrase"] = "赶忙", ["word"] = { "杆", "柑" } },
	["vudv"] = { ["phrase"] = "主队", ["word"] = { "注", "洙" } },
	["jhdy"] = { ["phrase"] = "江东", ["word"] = { "酱" } },
	["herr"] = { ["phrase"] = "何人", ["word"] = { "颌" } },
	["jidk"] = { ["phrase"] = "基调", ["word"] = { "奇" } },
	["jqlo"] = { ["phrase"] = "经络", ["word"] = { "靖" } },
	["bwfu"] = { ["phrase"] = "背负", ["word"] = { "辈" } },
	["tfji"] = { ["phrase"] = "谈及", ["word"] = { "镡" } },
	["yfyq"] = { ["phrase"] = "眼影", ["word"] = { "谳" } },
	["jidd"] = { ["phrase"] = "即到", ["word"] = { "剞" } },
	["xuno"] = { ["phrase"] = "许诺", ["word"] = { "婿" } },
	["ziky"] = { ["phrase"] = "自控", ["word"] = { "吱", "嗞" } },
	["xqxi"] = { ["phrase"] = "星系", ["word"] = { "性", "惺" } },
	["voyi"] = { ["phrase"] = "桌椅", ["word"] = { "酌" } },
	["butf"] = { ["phrase"] = "不谈", ["word"] = { "埔" } },
	["yuyd"] = { ["phrase"] = "余姚", ["word"] = { "谕" } },
	["gdjk"] = { ["phrase"] = "高教", ["word"] = { "镐", "锆" } },
	["xlxb"] = { ["phrase"] = "心下", ["word"] = { "衅" } },
	["irsi"] = { ["phrase"] = "深思", ["word"] = { "绅" } },
	["visi"] = { ["phrase"] = "致死", ["word"] = { "纸" } },
	["fwfw"] = { ["phrase"] = "飞飞", ["word"] = { "斐" } },
	["jnpa"] = { ["phrase"] = "就怕", ["word"] = { "臼" } },
	["iivu"] = { ["phrase"] = "石柱", ["word"] = { "虱" } },
	["yivc"] = { ["phrase"] = "一转", ["word"] = { "彝" } },
	["qidq"] = { ["phrase"] = "起订", ["word"] = { "汽", "汔" } },
	["bjzc"] = { ["phrase"] = "编纂", ["word"] = { "遍" } },
	["cfhp"] = { ["phrase"] = "餐后", ["word"] = { "黪" } },
	["uuuh"] = { ["phrase"] = "橱窗", ["word"] = { "蜍" } },
	["vuzu"] = { ["phrase"] = "驻足", ["word"] = { "躅" } },
	["wudj"] = { ["phrase"] = "五点", ["word"] = { "鋈" } },
	["frdd"] = { ["phrase"] = "分到", ["word"] = { "汾" } },
	["liml"] = { ["phrase"] = "利民", ["word"] = { "粒", "枥", "栎", "骊" } },
	["iiri"] = { ["phrase"] = "时日", ["word"] = { "什", "仕" } },
	["yfur"] = { ["phrase"] = "烟尘", ["word"] = { "颜", "赝" } },
	["jlll"] = { ["phrase"] = "紧邻", ["word"] = { "巾" } },
	["yxkx"] = { ["phrase"] = "越快", ["word"] = { "哕" } },
	["vuve"] = { ["phrase"] = "住着", ["word"] = { "邾", "竺" } },
	["humr"] = { ["phrase"] = "虎门", ["word"] = { "核" } },
	["kvzt"] = { ["phrase"] = "馈赠", ["word"] = { "逵", "跬" } },
	["qkxh"] = { ["phrase"] = "敲响", ["word"] = { "憔", "愀" } },
	["huxk"] = { ["phrase"] = "呼啸", ["word"] = { "怙" } },
	["modd"] = { ["phrase"] = "摸到", ["word"] = { "漠" } },
	["lndj"] = { ["phrase"] = "六点", ["word"] = { "鎏" } },
	["cflm"] = { ["phrase"] = "惨烈", ["word"] = { "粲" } },
	["xmsi"] = { ["phrase"] = "血丝", ["word"] = { "绁" } },
	["ifye"] = { ["phrase"] = "山野", ["word"] = { "讪", "鄯" } },
	["jldd"] = { ["phrase"] = "进到", ["word"] = { "浕" } },
	["difr"] = { ["phrase"] = "低分", ["word"] = { "提" } },
	["iiiu"] = { ["phrase"] = "实属", ["word"] = { "蚀" } },
	["ypyl"] = { ["phrase"] = "又因", ["word"] = { "幼" } },
	["xhgy"] = { ["phrase"] = "相公", ["word"] = { "庠" } },
	["ypuy"] = { ["phrase"] = "幼虫", ["word"] = { "蚰" } },
	["dugu"] = { ["phrase"] = "独孤", ["word"] = { "髑" } },
	["jlso"] = { ["phrase"] = "紧缩", ["word"] = { "缙" } },
	["jisv"] = { ["phrase"] = "脊髓", ["word"] = { "继" } },
	["jjmm"] = { ["phrase"] = "歼灭", ["word"] = { "槛" } },
	["jubq"] = { ["phrase"] = "句柄", ["word"] = { "疽" } },
	["pkxx"] = { ["phrase"] = "飘雪", ["word"] = { "票", "飘" } },
	["yihb"] = { ["phrase"] = "异化", ["word"] = { "熠" } },
	["qubf"] = { ["phrase"] = "去办", ["word"] = { "癯" } },
	["jigv"] = { ["phrase"] = "机柜", ["word"] = { "既" } },
	["vuky"] = { ["phrase"] = "主控", ["word"] = { "嘱" } },
	["yure"] = { ["phrase"] = "预热", ["word"] = { "觎" } },
	["lidd"] = { ["phrase"] = "力道", ["word"] = { "漓" } },
	["ldyp"] = { ["phrase"] = "老友", ["word"] = { "醪" } },
	["tddd"] = { ["phrase"] = "逃到", ["word"] = { "洮" } },
	["wutk"] = { ["phrase"] = "五条", ["word"] = { "圬" } },
	["ygry"] = { ["phrase"] = "羊绒", ["word"] = { "佯" } },
	["jjlj"] = { ["phrase"] = "简练", ["word"] = { "鉴" } },
	["uivu"] = { ["phrase"] = "吃住", ["word"] = { "蚩" } },
	["vimt"] = { ["phrase"] = "之梦", ["word"] = { "桎" } },
	["fukf"] = { ["phrase"] = "俯瞰", ["word"] = { "呋" } },
	["hvxm"] = { ["phrase"] = "诙谐", ["word"] = { "悔" } },
	["yydy"] = { ["phrase"] = "涌动", ["word"] = { "泳", "涌" } },
	["xmmd"] = { ["phrase"] = "鞋帽", ["word"] = { "楔" } },
	["ljjn"] = { ["phrase"] = "练就", ["word"] = { "镰" } },
	["uuiu"] = { ["phrase"] = "出书", ["word"] = { "础" } },
	["vtyl"] = { ["phrase"] = "正因", ["word"] = { "诤" } },
	["tfta"] = { ["phrase"] = "坍塌", ["word"] = { "坦" } },
	["iiyc"] = { ["phrase"] = "十元", ["word"] = { "诗" } },
	["lici"] = { ["phrase"] = "历次", ["word"] = { "藜" } },
	["jbjj"] = { ["phrase"] = "加减", ["word"] = { "钾", "铗" } },
	["lisf"] = { ["phrase"] = "离散", ["word"] = { "罹" } },
	["ksjb"] = { ["phrase"] = "铠甲", ["word"] = { "锴" } },
	["xzzi"] = { ["phrase"] = "荀子", ["word"] = { "迅" } },
	["hvdk"] = { ["phrase"] = "毁掉", ["word"] = { "汇", "洄" } },
	["yizy"] = { ["phrase"] = "一宗", ["word"] = { "迤" } },
	["jido"] = { ["phrase"] = "几多", ["word"] = { "脊" } },
	["dumo"] = { ["phrase"] = "镀膜", ["word"] = { "阇" } },
	["xmdu"] = { ["phrase"] = "亵渎", ["word"] = { "蟹" } },
	["siks"] = { ["phrase"] = "撕开", ["word"] = { "咝" } },
	["yiui"] = { ["phrase"] = "一尺", ["word"] = { "轶" } },
	["jlma"] = { ["phrase"] = "金马", ["word"] = { "槿" } },
	["iudi"] = { ["phrase"] = "属地", ["word"] = { "沭" } },
	["lndd"] = { ["phrase"] = "六道", ["word"] = { "浏" } },
	["jibi"] = { ["phrase"] = "击毙", ["word"] = { "疾" } },
	["qlkx"] = { ["phrase"] = "勤快", ["word"] = { "吣" } },
	["qise"] = { ["phrase"] = "起色", ["word"] = { "缉" } },
}

return dup_table
