local dup_table = {
    ["yixb"] = {["phrase"] = "一下", ["word"] = {"翼", "悒"}},
    ["yidj"] = {["phrase"] = "一点", ["word"] = {"沂"}},
    ["jihb"] = {["phrase"] = "计划", ["word"] = {"积"}},
    ["yisi"] = {["phrase"] = "意思", ["word"] = {"矣"}},
    ["iipl"] = {["phrase"] = "视频", ["word"] = {"释"}},
    ["guii"] = {["phrase"] = "故事", ["word"] = {"辜"}},
    ["bdbd"] = {["phrase"] = "宝宝", ["word"] = {"刨"}},
    ["zidy"] = {["phrase"] = "自动", ["word"] = {"滋"}},
    ["yudd"] = {["phrase"] = "遇到", ["word"] = {"淤", "渝"}},
    ["jike"] = {["phrase"] = "即可", ["word"] = {"唧"}},
    ["jhdi"] = {["phrase"] = "降低", ["word"] = {"浆"}},
    ["jlry"] = {["phrase"] = "金融", ["word"] = {"仅"}},
    ["yqgo"] = {["phrase"] = "英国", ["word"] = {"膺"}},
    ["jjdd"] = {["phrase"] = "见到", ["word"] = {"湔"}},
    ["iiqi"] = {["phrase"] = "时期", ["word"] = {"舐"}},
    ["yikx"] = {["phrase"] = "一块", ["word"] = {"噫", "翳"}},
    ["yzxu"] = {["phrase"] = "允许", ["word"] = {"恽"}},
    ["hcbd"] = {["phrase"] = "环保", ["word"] = {"痪"}},
    ["xjde"] = {["phrase"] = "显得", ["word"] = {"洗", "冼"}},
    ["lqrr"] = {["phrase"] = "令人", ["word"] = {"领"}},
    ["vidq"] = {["phrase"] = "指定", ["word"] = {"殖"}},
    ["jiyi"] = {["phrase"] = "记忆", ["word"] = {"计"}},
    ["svii"] = {["phrase"] = "随时", ["word"] = {"尿", "碎"}},
    ["yldd"] = {["phrase"] = "引导", ["word"] = {"洇"}},
    ["juml"] = {["phrase"] = "居民", ["word"] = {"榉"}},
    ["boii"] = {["phrase"] = "博士", ["word"] = {"擘"}},
    ["jjdq"] = {["phrase"] = "鉴定", ["word"] = {"歼"}},
    ["yfuu"] = {["phrase"] = "演出", ["word"] = {"衍"}},
    ["plvi"] = {["phrase"] = "品质", ["word"] = {"颦"}},
    ["jiut"] = {["phrase"] = "集成", ["word"] = {"墼"}},
    ["vize"] = {["phrase"] = "职责", ["word"] = {"踯"}},
    ["qici"] = {["phrase"] = "其次", ["word"] = {"芪"}},
    ["wwyc"] = {["phrase"] = "委员", ["word"] = {"霨"}},
    ["ydba"] = {["phrase"] = "要把", ["word"] = {"疟"}},
    ["viut"] = {["phrase"] = "支撑", ["word"] = {"轾", "蛭"}},
    ["jzdv"] = {["phrase"] = "军队", ["word"] = {"龟"}},
    ["tftd"] = {["phrase"] = "探讨", ["word"] = {"坍"}},
    ["xljj"] = {["phrase"] = "新建", ["word"] = {"鑫"}},
    ["jumj"] = {["phrase"] = "局面", ["word"] = {"柜"}},
    ["qidd"] = {["phrase"] = "起到", ["word"] = {"沏"}},
    ["fukc"] = {["phrase"] = "付款", ["word"] = {"咐", "赙"}},
    ["yfug"] = {["phrase"] = "延长", ["word"] = {"魇"}},
    ["mwmw"] = {["phrase"] = "妹妹", ["word"] = {"枚"}},
    ["bici"] = {["phrase"] = "彼此", ["word"] = {"荜", "薜"}},
    ["jici"] = {["phrase"] = "几次", ["word"] = {"蒺"}},
    ["iirr"] = {["phrase"] = "使人", ["word"] = {"似"}},
    ["vywu"] = {["phrase"] = "中午", ["word"] = {"螽"}},
    ["qndv"] = {["phrase"] = "球队", ["word"] = {"龟"}},
    ["vimq"] = {["phrase"] = "知名", ["word"] = {"植"}},
    ["jitj"] = {["phrase"] = "几天", ["word"] = {"圾"}},
    ["iifg"] = {["phrase"] = "释放", ["word"] = {"拭"}},
    ["yibr"] = {["phrase"] = "一本", ["word"] = {"疑"}},
    ["iitu"] = {["phrase"] = "试图", ["word"] = {"螫"}},
    ["rrrr"] = {["phrase"] = "人人", ["word"] = {"任", "仞"}},
    ["yida"] = {["phrase"] = "一大", ["word"] = {"殪"}},
    ["yiml"] = {["phrase"] = "移民", ["word"] = {"驿"}},
    ["bjli"] = {["phrase"] = "便利", ["word"] = {"辨", "辩", "辫"}},
    ["vudo"] = {["phrase"] = "诸多", ["word"] = {"渚", "潴"}},
    ["yiri"] = {["phrase"] = "一日", ["word"] = {"佚"}},
    ["qjjq"] = {["phrase"] = "前景", ["word"] = {"钎"}},
    ["viji"] = {["phrase"] = "之际", ["word"] = {"帙"}},
    ["jiyl"] = {["phrase"] = "基因", ["word"] = {"霁"}},
    ["jiir"] = {["phrase"] = "机身", ["word"] = {"赍"}},
    ["yixk"] = {["phrase"] = "一笑", ["word"] = {"怡"}},
    ["juqq"] = {["phrase"] = "剧情", ["word"] = {"狙"}},
    ["dgci"] = {["phrase"] = "档次", ["word"] = {"菪"}},
    ["jiho"] = {["phrase"] = "激活", ["word"] = {"稽"}},
    ["jihe"] = {["phrase"] = "集合", ["word"] = {"嵇"}},
    ["jilv"] = {["phrase"] = "纪律", ["word"] = {"乩"}},
    ["yeye"] = {["phrase"] = "爷爷", ["word"] = {"邺"}},
    ["qipj"] = {["phrase"] = "欺骗", ["word"] = {"祈"}},
    ["voli"] = {["phrase"] = "着力", ["word"] = {"卓"}},
    ["juzi"] = {["phrase"] = "句子", ["word"] = {"遽"}},
    ["igdp"] = {["phrase"] = "上都", ["word"] = {"殇", "觞"}},
    ["jida"] = {["phrase"] = "极大", ["word"] = {"殛"}},
    ["quuu"] = {["phrase"] = "取出", ["word"] = {"衢"}},
    ["yfve"] = {["phrase"] = "沿着", ["word"] = {"鄢"}},
    ["biii"] = {["phrase"] = "笔试", ["word"] = {"辟"}},
    ["mibu"] = {["phrase"] = "弥补", ["word"] = {"蜜"}},
    ["vidi"] = {["phrase"] = "之地", ["word"] = {"汁"}},
    ["yuwo"] = {["phrase"] = "与我", ["word"] = {"育"}},
    ["ugnj"] = {["phrase"] = "常年", ["word"] = {"嫦"}},
    ["xizd"] = {["phrase"] = "洗澡", ["word"] = {"蹊"}},
    ["bizi"] = {["phrase"] = "鼻子", ["word"] = {"避", "跸"}},
    ["iiky"] = {["phrase"] = "时空", ["word"] = {"嘘"}},
    ["jiig"] = {["phrase"] = "机上", ["word"] = {"戟"}},
    ["kewr"] = {["phrase"] = "课文", ["word"] = {"颏"}},
    ["yunl"] = {["phrase"] = "与您", ["word"] = {"妤"}},
    ["iiln"] = {["phrase"] = "十六", ["word"] = {"史"}},
    ["fucy"] = {["phrase"] = "服从", ["word"] = {"菔"}},
    ["jidj"] = {["phrase"] = "机电", ["word"] = {"汲"}},
    ["luvi"] = {["phrase"] = "录制", ["word"] = {"舻", "箓"}},
    ["bwpo"] = {["phrase"] = "被迫", ["word"] = {"褙"}},
    ["yuvy"] = {["phrase"] = "语种", ["word"] = {"竽"}},
    ["yuyx"] = {["phrase"] = "预约", ["word"] = {"愚"}},
    ["bjhc"] = {["phrase"] = "变换", ["word"] = {"扁", "煸"}},
    ["wuyx"] = {["phrase"] = "五月", ["word"] = {"恶"}},
    ["lnii"] = {["phrase"] = "流失", ["word"] = {"碌"}},
    ["jxwg"] = {["phrase"] = "绝望", ["word"] = {"玦"}},
    ["fufw"] = {["phrase"] = "付费", ["word"] = {"抚", "敷"}},
    ["vidj"] = {["phrase"] = "致电", ["word"] = {"滞"}},
    ["qiir"] = {["phrase"] = "起身", ["word"] = {"碛"}},
    ["ylvg"] = {["phrase"] = "印章", ["word"] = {"龈"}},
    ["dide"] = {["phrase"] = "低的", ["word"] = {"邸"}},
    ["bivi"] = {["phrase"] = "壁纸", ["word"] = {"筚"}},
    ["xjee"] = {["phrase"] = "限额", ["word"] = {"岘"}},
    ["ydky"] = {["phrase"] = "遥控", ["word"] = {"吆"}},
    ["jmiv"] = {["phrase"] = "节水", ["word"] = {"碣"}},
    ["jnjh"] = {["phrase"] = "就将", ["word"] = {"灸"}},
    ["iivr"] = {["phrase"] = "是真", ["word"] = {"筮"}},
    ["irye"] = {["phrase"] = "深夜", ["word"] = {"诜"}},
    ["nfty"] = {["phrase"] = "南通", ["word"] = {"赧"}},
    ["qqif"] = {["phrase"] = "青山", ["word"] = {"罄"}},
    ["ugxk"] = {["phrase"] = "畅销", ["word"] = {"惝"}},
    ["jhdd"] = {["phrase"] = "降到", ["word"] = {"奖"}},
    ["xxya"] = {["phrase"] = "血压", ["word"] = {"谑"}},
    ["qlfr"] = {["phrase"] = "勤奋", ["word"] = {"揿"}},
    ["jjro"] = {["phrase"] = "减弱", ["word"] = {"僭"}},
    ["djfr"] = {["phrase"] = "淀粉", ["word"] = {"靛"}},
    ["ipbk"] = {["phrase"] = "手表", ["word"] = {"兽"}},
    ["iimj"] = {["phrase"] = "失眠", ["word"] = {"柿"}},
    ["vitq"] = {["phrase"] = "只听", ["word"] = {"埴"}},
    ["uumo"] = {["phrase"] = "触摸", ["word"] = {"楮"}},
    ["dqyd"] = {["phrase"] = "定要", ["word"] = {"订", "酊"}},
    ["iian"] = {["phrase"] = "是按", ["word"] = {"豕"}},
    ["yixl"] = {["phrase"] = "一心", ["word"] = {"怿", "翌"}},
    ["dudd"] = {["phrase"] = "督导", ["word"] = {"渎"}},
    ["vifr"] = {["phrase"] = "之分", ["word"] = {"贽"}},
    ["jujk"] = {["phrase"] = "聚焦", ["word"] = {"锯", "锔"}},
    ["bovy"] = {["phrase"] = "播种", ["word"] = {"簸"}},
    ["bukf"] = {["phrase"] = "不看", ["word"] = {"哺"}},
    ["vidv"] = {["phrase"] = "支队", ["word"] = {"沚"}},
    ["qqhx"] = {["phrase"] = "情怀", ["word"] = {"綮", "黥"}},
    ["igtk"] = {["phrase"] = "上调", ["word"] = {"垧", "墒"}},
    ["syds"] = {["phrase"] = "宋代", ["word"] = {"凇", "淞"}},
    ["bidc"] = {["phrase"] = "弊端", ["word"] = {"弊"}},
    ["xhyy"] = {["phrase"] = "享用", ["word"] = {"详"}},
    ["lian"] = {["phrase"] = "立案", ["word"] = {"吏"}},
    ["iiri"] = {["phrase"] = "十日", ["word"] = {"什", "仕"}},
    ["vizi"] = {["phrase"] = "之子", ["word"] = {"跖"}},
    ["ycde"] = {["phrase"] = "远的", ["word"] = {"沅"}},
    ["yiyy"] = {["phrase"] = "医用", ["word"] = {"议"}},
    ["wfbd"] = {["phrase"] = "晚报", ["word"] = {"剜"}},
    ["viio"] = {["phrase"] = "之说", ["word"] = {"智"}},
    ["bihb"] = {["phrase"] = "壁画", ["word"] = {"秘", "秕"}},
    ["uaia"] = {["phrase"] = "查杀", ["word"] = {"馇", "碴"}},
    ["jujb"] = {["phrase"] = "居家", ["word"] = {"飓"}},
    ["dfdk"] = {["phrase"] = "单调", ["word"] = {"澹"}},
    ["dpba"] = {["phrase"] = "都把", ["word"] = {"痘"}},
    ["pwyl"] = {["phrase"] = "配音", ["word"] = {"霈"}},
    ["yijm"] = {["phrase"] = "一节", ["word"] = {"镒"}},
    ["vrtp"] = {["phrase"] = "枕头", ["word"] = {"畛"}},
    ["iuww"] = {["phrase"] = "数为", ["word"] = {"孰"}},
    ["vryp"] = {["phrase"] = "真有", ["word"] = {"诊"}},
    ["qumq"] = {["phrase"] = "取名", ["word"] = {"阒"}},
    ["ludi"] = {["phrase"] = "陆地", ["word"] = {"泸", "渌"}},
    ["jnjl"] = {["phrase"] = "就近", ["word"] = {"舅"}},
    ["vfdv"] = {["phrase"] = "战队", ["word"] = {"湛"}},
    ["rude"] = {["phrase"] = "入的", ["word"] = {"濡"}},
    ["vtfa"] = {["phrase"] = "蒸发", ["word"] = {"拯"}},
    ["qjbi"] = {["phrase"] = "铅笔", ["word"] = {"搴"}},
    ["uajx"] = {["phrase"] = "察觉", ["word"] = {"镲"}},
    ["yqcy"] = {["phrase"] = "应从", ["word"] = {"英", "莹"}},
    ["qitj"] = {["phrase"] = "七天", ["word"] = {"起", "圻"}},
    ["iiyg"] = {["phrase"] = "式样", ["word"] = {"式", "试"}},
    ["fuyd"] = {["phrase"] = "服药", ["word"] = {"黻"}},
    ["luzi"] = {["phrase"] = "路子", ["word"] = {"逯"}},
    ["gcdk"] = {["phrase"] = "关掉", ["word"] = {"涫"}},
    ["vupl"] = {["phrase"] = "主频", ["word"] = {"竹"}},
    ["wumw"] = {["phrase"] = "妩媚", ["word"] = {"杌"}},
    ["qiri"] = {["phrase"] = "七日", ["word"] = {"俟"}},
    ["yfjk"] = {["phrase"] = "眼角", ["word"] = {"铅"}},
    ["xkmw"] = {["phrase"] = "小妹", ["word"] = {"骁"}},
    ["hvxh"] = {["phrase"] = "会向", ["word"] = {"恢"}},
    ["ycdy"] = {["phrase"] = "远东", ["word"] = {"湲"}},
    ["ydxx"] = {["phrase"] = "药学", ["word"] = {"爻"}},
    ["bdzi"] = {["phrase"] = "包子", ["word"] = {"趵"}},
    ["djbd"] = {["phrase"] = "电报", ["word"] = {"奠"}},
    ["ypbq"] = {["phrase"] = "有病", ["word"] = {"猷"}},
    ["yizd"] = {["phrase"] = "一早", ["word"] = {"逸", "劓"}},
    ["jiee"] = {["phrase"] = "饥饿", ["word"] = {"觊"}},
    ["lqds"] = {["phrase"] = "领带", ["word"] = {"泠"}},
    ["sudi"] = {["phrase"] = "速递", ["word"] = {"涑", "觫"}},
    ["ieuu"] = {["phrase"] = "射出", ["word"] = {"厍"}},
    ["jbji"] = {["phrase"] = "甲级", ["word"] = {"镓"}},
    ["fwyf"] = {["phrase"] = "肺炎", ["word"] = {"诽", "霏"}},
    ["yicy"] = {["phrase"] = "已从", ["word"] = {"荑"}},
    ["nidd"] = {["phrase"] = "你到", ["word"] = {"溺"}},
    ["viky"] = {["phrase"] = "指控", ["word"] = {"吱"}},
    ["xmye"] = {["phrase"] = "鞋业", ["word"] = {"邪"}},
    ["wwmw"] = {["phrase"] = "唯美", ["word"] = {"闱"}},
    ["wunw"] = {["phrase"] = "屋内", ["word"] = {"物", "妩"}},
    ["qidi"] = {["phrase"] = "启迪", ["word"] = {"漆"}},
    ["dimd"] = {["phrase"] = "地貌", ["word"] = {"柢"}},
    ["yfke"] = {["phrase"] = "眼科", ["word"] = {"郾"}},
    ["wodt"] = {["phrase"] = "我等", ["word"] = {"渥"}},
    ["sidj"] = {["phrase"] = "四点", ["word"] = {"澌"}},
    ["fudk"] = {["phrase"] = "浮雕", ["word"] = {"涪"}},
    ["yfyy"] = {["phrase"] = "沿用", ["word"] = {"酽"}},
    ["vefu"] = {["phrase"] = "这幅", ["word"] = {"蛰", "蜇"}},
    ["zidi"] = {["phrase"] = "子弟", ["word"] = {"滓"}},
    ["vpye"] = {["phrase"] = "昼夜", ["word"] = {"诌"}},
    ["gedk"] = {["phrase"] = "格调", ["word"] = {"哥"}},
    ["yudk"] = {["phrase"] = "语调", ["word"] = {"浴"}},
    ["wugp"] = {["phrase"] = "污垢", ["word"] = {"戊"}},
    ["xiyd"] = {["phrase"] = "西药", ["word"] = {"羲"}},
    ["jjbd"] = {["phrase"] = "简报", ["word"] = {"剪"}},
    ["buld"] = {["phrase"] = "捕捞", ["word"] = {"卜"}},
    ["piii"] = {["phrase"] = "批示", ["word"] = {"辟", "鼙"}},
    ["uefw"] = {["phrase"] = "车费", ["word"] = {"撤"}},
    ["hfrr"] = {["phrase"] = "汉人", ["word"] = {"颔"}},
    ["dsrr"] = {["phrase"] = "待人", ["word"] = {"贷"}},
    ["hvhx"] = {["phrase"] = "毁坏", ["word"] = {"秽"}},
    ["gfmg"] = {["phrase"] = "赶忙", ["word"] = {"杆", "柑"}},
    ["jhdy"] = {["phrase"] = "江东", ["word"] = {"酱"}},
    ["vudv"] = {["phrase"] = "主队", ["word"] = {"注", "洙"}},
    ["herr"] = {["phrase"] = "何人", ["word"] = {"颌"}},
    ["jidk"] = {["phrase"] = "基调", ["word"] = {"奇"}},
    ["jqlo"] = {["phrase"] = "经络", ["word"] = {"靖"}},
    ["bwfu"] = {["phrase"] = "背负", ["word"] = {"辈"}},
    ["tfji"] = {["phrase"] = "谈及", ["word"] = {"镡"}},
    ["yfyq"] = {["phrase"] = "眼影", ["word"] = {"谳"}},
    ["jidd"] = {["phrase"] = "即到", ["word"] = {"剞"}},
    ["xuno"] = {["phrase"] = "许诺", ["word"] = {"婿"}},
    ["ziky"] = {["phrase"] = "自控", ["word"] = {"吱", "嗞"}},
    ["xqxi"] = {["phrase"] = "星系", ["word"] = {"性", "惺"}},
    ["voyi"] = {["phrase"] = "桌椅", ["word"] = {"酌"}},
    ["butf"] = {["phrase"] = "不谈", ["word"] = {"埔"}},
    ["yuyd"] = {["phrase"] = "余姚", ["word"] = {"谕"}},
    ["gdjk"] = {["phrase"] = "高教", ["word"] = {"镐", "锆"}},
    ["xlxb"] = {["phrase"] = "心下", ["word"] = {"衅"}},
    ["irsi"] = {["phrase"] = "深思", ["word"] = {"绅"}},
    ["visi"] = {["phrase"] = "致死", ["word"] = {"纸"}},
    ["fwfw"] = {["phrase"] = "飞飞", ["word"] = {"斐"}},
    ["jnpa"] = {["phrase"] = "就怕", ["word"] = {"臼"}},
    ["iiiu"] = {["phrase"] = "市属", ["word"] = {"蚀"}},
    ["xlji"] = {["phrase"] = "心肌", ["word"] = {"锌"}},
    ["iivu"] = {["phrase"] = "石柱", ["word"] = {"虱"}},
    ["yivc"] = {["phrase"] = "一转", ["word"] = {"彝"}},
    ["qidq"] = {["phrase"] = "起订", ["word"] = {"汽", "汔"}},
    ["bjzc"] = {["phrase"] = "编纂", ["word"] = {"遍"}},
    ["cfhp"] = {["phrase"] = "餐后", ["word"] = {"黪"}},
    ["uuuh"] = {["phrase"] = "橱窗", ["word"] = {"蜍"}},
    ["vuzu"] = {["phrase"] = "驻足", ["word"] = {"躅"}},
    ["wudj"] = {["phrase"] = "五点", ["word"] = {"鋈"}},
    ["wwdo"] = {["phrase"] = "为多", ["word"] = {"洧", "渭"}},
    ["frdd"] = {["phrase"] = "分到", ["word"] = {"汾"}},
    ["liml"] = {["phrase"] = "利民", ["word"] = {"粒", "枥", "栎", "骊"}},
    ["yfur"] = {["phrase"] = "烟尘", ["word"] = {"颜", "赝"}},
    ["jlll"] = {["phrase"] = "紧邻", ["word"] = {"巾"}},
    ["yxkx"] = {["phrase"] = "越快", ["word"] = {"哕"}},
    ["vuve"] = {["phrase"] = "住着", ["word"] = {"邾", "竺"}},
    ["humr"] = {["phrase"] = "虎门", ["word"] = {"核"}},
    ["kvzt"] = {["phrase"] = "馈赠", ["word"] = {"逵", "跬"}},
    ["qkxh"] = {["phrase"] = "敲响", ["word"] = {"憔", "愀"}},
    ["huxk"] = {["phrase"] = "呼啸", ["word"] = {"怙"}},
    ["modd"] = {["phrase"] = "摸到", ["word"] = {"漠"}},
    ["lndj"] = {["phrase"] = "六点", ["word"] = {"鎏"}},
    ["cflm"] = {["phrase"] = "惨烈", ["word"] = {"粲"}},
    ["ifye"] = {["phrase"] = "山野", ["word"] = {"讪", "鄯"}},
    ["jian"] = {["phrase"] = "吉安", ["word"] = {"棘"}},
    ["jldd"] = {["phrase"] = "进到", ["word"] = {"浕"}},
    ["difr"] = {["phrase"] = "低分", ["word"] = {"提"}},
    ["ypyl"] = {["phrase"] = "又因", ["word"] = {"幼"}},
    ["xhgy"] = {["phrase"] = "相公", ["word"] = {"庠"}},
    ["ypuy"] = {["phrase"] = "幼虫", ["word"] = {"蚰"}},
    ["dugu"] = {["phrase"] = "独孤", ["word"] = {"髑"}},
    ["jlso"] = {["phrase"] = "紧缩", ["word"] = {"缙"}},
    ["jisv"] = {["phrase"] = "脊髓", ["word"] = {"继"}},
    ["jjmm"] = {["phrase"] = "歼灭", ["word"] = {"槛"}},
    ["pkxx"] = {["phrase"] = "飘雪", ["word"] = {"票", "飘"}},
    ["yihb"] = {["phrase"] = "异化", ["word"] = {"熠"}},
    ["qubf"] = {["phrase"] = "去办", ["word"] = {"癯"}},
    ["jigv"] = {["phrase"] = "机柜", ["word"] = {"既"}},
    ["vuky"] = {["phrase"] = "主控", ["word"] = {"嘱"}},
    ["hcdd"] = {["phrase"] = "环岛", ["word"] = {"涣", "奂"}},
    ["yure"] = {["phrase"] = "预热", ["word"] = {"觎"}},
    ["lidd"] = {["phrase"] = "力道", ["word"] = {"漓"}},
    ["ldyp"] = {["phrase"] = "老友", ["word"] = {"醪"}},
    ["tddd"] = {["phrase"] = "逃到", ["word"] = {"洮"}},
    ["wutk"] = {["phrase"] = "五条", ["word"] = {"圬"}},
    ["livu"] = {["phrase"] = "立柱", ["word"] = {"蠡"}},
    ["ygry"] = {["phrase"] = "羊绒", ["word"] = {"佯"}},
    ["jjlj"] = {["phrase"] = "简练", ["word"] = {"鉴"}},
    ["uivu"] = {["phrase"] = "吃住", ["word"] = {"蚩"}},
    ["vimt"] = {["phrase"] = "之梦", ["word"] = {"桎"}},
    ["siri"] = {["phrase"] = "四日", ["word"] = {"俟"}},
    ["fukf"] = {["phrase"] = "俯瞰", ["word"] = {"呋"}},
    ["hvxm"] = {["phrase"] = "诙谐", ["word"] = {"悔"}},
    ["yydy"] = {["phrase"] = "涌动", ["word"] = {"泳", "涌"}},
    ["xmmd"] = {["phrase"] = "鞋帽", ["word"] = {"楔"}},
    ["eqde"] = {["phrase"] = "尔德", ["word"] = {"洱"}},
    ["bsii"] = {["phrase"] = "白石", ["word"] = {"掰"}},
    ["ljjn"] = {["phrase"] = "练就", ["word"] = {"镰"}},
    ["uuiu"] = {["phrase"] = "出书", ["word"] = {"础"}},
    ["vtyl"] = {["phrase"] = "正因", ["word"] = {"诤"}},
    ["tfta"] = {["phrase"] = "坍塌", ["word"] = {"坦"}},
    ["iiyc"] = {["phrase"] = "十元", ["word"] = {"诗"}},
    ["jmyg"] = {["phrase"] = "揭阳", ["word"] = {"讦"}},
    ["lici"] = {["phrase"] = "历次", ["word"] = {"藜"}},
    ["jbjj"] = {["phrase"] = "加减", ["word"] = {"钾", "铗"}},
    ["lisf"] = {["phrase"] = "离散", ["word"] = {"罹"}},
    ["ksjb"] = {["phrase"] = "铠甲", ["word"] = {"锴"}},
    ["xzzi"] = {["phrase"] = "荀子", ["word"] = {"迅"}},
    ["hvdk"] = {["phrase"] = "毁掉", ["word"] = {"汇", "洄"}},
    ["yizy"] = {["phrase"] = "一宗", ["word"] = {"迤"}},
    ["bulw"] = {["phrase"] = "布雷", ["word"] = {"瓿"}},
    ["jido"] = {["phrase"] = "几多", ["word"] = {"脊"}},
    ["dumo"] = {["phrase"] = "镀膜", ["word"] = {"阇"}},
    ["xmdu"] = {["phrase"] = "亵渎", ["word"] = {"蟹"}},
    ["siks"] = {["phrase"] = "撕开", ["word"] = {"咝"}},
    ["yiui"] = {["phrase"] = "一尺", ["word"] = {"轶"}},
    ["jlma"] = {["phrase"] = "金马", ["word"] = {"槿"}},
    ["iudi"] = {["phrase"] = "属地", ["word"] = {"沭"}},
    ["lndd"] = {["phrase"] = "六道", ["word"] = {"浏"}},
    ["jibi"] = {["phrase"] = "击毙", ["word"] = {"疾"}},
    ["qlkx"] = {["phrase"] = "勤快", ["word"] = {"吣"}},
    ["qise"] = {["phrase"] = "起色", ["word"] = {"缉"}},
    ["sids"] = {["phrase"] = "丝带", ["word"] = {"汜"}},
    ["yfhh"] = {["phrase"] = "炎黄", ["word"] = {"炎", "焱"}},
    ["yfmj"] = {["phrase"] = "颜面", ["word"] = {"阎"}},
    ["jubq"] = {["phrase"] = "句柄", ["word"] = {"疽"}},
    ["tfix"] = {["phrase"] = "坦率", ["word"] = {"忐"}},
    ["viix"] = {["phrase"] = "直率", ["word"] = {"志"}},
    ["miyz"] = {["phrase"] = "密云", ["word"] = {"谜", "醚"}},
    ["keui"] = {["phrase"] = "可耻", ["word"] = {"蝌"}},
    ["yidm"] = {["phrase"] = "一叠", ["word"] = {"溢"}},
    ["qjdo"] = {["phrase"] = "千多", ["word"] = {"潜"}},
    ["eqaa"] = {["phrase"] = "儿啊", ["word"] = {"二", "耳"}},
    ["qnqj"] = {["phrase"] = "秋千", ["word"] = {"犰"}},
    ["wwqn"] = {["phrase"] = "为求", ["word"] = {"猥"}},
    ["qjjk"] = {["phrase"] = "欠缴", ["word"] = {"铅"}},
    ["qikx"] = {["phrase"] = "砌块", ["word"] = {"嘁"}},
    ["iddk"] = {["phrase"] = "烧掉", ["word"] = {"召"}},
    ["tomd"] = {["phrase"] = "脱毛", ["word"] = {"驮"}},
    ["vafa"] = {["phrase"] = "闸阀", ["word"] = {"揸"}},
    ["yiyq"] = {["phrase"] = "亦应", ["word"] = {"谊"}},
    ["quty"] = {["phrase"] = "趋同", ["word"] = {"趣"}},
    ["iiir"] = {["phrase"] = "食神", ["word"] = {"贳"}},
    ["xijh"] = {["phrase"] = "西江", ["word"] = {"舄"}},
    ["dfba"] = {["phrase"] = "丹巴", ["word"] = {"疸"}},
    ["yiky"] = {["phrase"] = "一空", ["word"] = {"匜", "咦", "咿"}},
    ["ypdy"] = {["phrase"] = "游动", ["word"] = {"油"}},
    ["hbmi"] = {["phrase"] = "画谜", ["word"] = {"桦", "骅"}},
    ["xhdo"] = {["phrase"] = "想多", ["word"] = {"湘"}},
    ["vifw"] = {["phrase"] = "直飞", ["word"] = {"执"}},
    ["ksxq"] = {["phrase"] = "开行", ["word"] = {"忾"}},
    ["xiix"] = {["phrase"] = "蟋蟀", ["word"] = {"硒"}},
    ["xuyx"] = {["phrase"] = "续约", ["word"] = {"诩"}},
    ["yiuy"] = {["phrase"] = "一重", ["word"] = {"役", "蚁"}},
    ["mige"] = {["phrase"] = "米格", ["word"] = {"弭"}},
    ["hyug"] = {["phrase"] = "红肠", ["word"] = {"虹"}},
    ["lida"] = {["phrase"] = "利达", ["word"] = {"澧"}},
    ["xmsi"] = {["phrase"] = "血丝", ["word"] = {"绁"}},
    ["bwle"] = {["phrase"] = "背了", ["word"] = {"邶"}},
    ["yuyy"] = {["phrase"] = "御用", ["word"] = {"谀"}},
    ["dojl"] = {["phrase"] = "躲进", ["word"] = {"铎"}},
    ["tomo"] = {["phrase"] = "唾沫", ["word"] = {"椭"}},
    ["luqi"] = {["phrase"] = "撸起", ["word"] = {"氯"}},
    ["xmdj"] = {["phrase"] = "鞋垫", ["word"] = {"瀣"}},
    ["qlrd"] = {["phrase"] = "侵扰", ["word"] = {"禽"}},
    ["zoky"] = {["phrase"] = "做空", ["word"] = {"嘬"}},
    ["yzls"] = {["phrase"] = "运来", ["word"] = {"耘"}},
    ["ljda"] = {["phrase"] = "联大", ["word"] = {"殓"}},
    ["aibj"] = {["phrase"] = "癌变", ["word"] = {"皑"}},
    ["xlci"] = {["phrase"] = "新词", ["word"] = {"莘"}},
    ["zdzo"] = {["phrase"] = "造作", ["word"] = {"遭"}},
    ["fupq"] = {["phrase"] = "抚平", ["word"] = {"袱"}},
    ["bidw"] = {["phrase"] = "必得", ["word"] = {"敝"}},
    ["digd"] = {["phrase"] = "底稿", ["word"] = {"底", "骶"}},
    ["vrji"] = {["phrase"] = "真迹", ["word"] = {"针"}},
    ["tuio"] = {["phrase"] = "图说", ["word"] = {"屠"}},
    ["yauy"] = {["phrase"] = "蚜虫", ["word"] = {"蚜"}},
    ["iucy"] = {["phrase"] = "树丛", ["word"] = {"菽"}},
    ["uaka"] = {["phrase"] = "插卡", ["word"] = {"喳"}},
    ["vgji"] = {["phrase"] = "张继", ["word"] = {"幛"}},
    ["jqxx"] = {["phrase"] = "经学", ["word"] = {"惊", "憬"}},
    ["wwty"] = {["phrase"] = "胃痛", ["word"] = {"圩"}},
    ["dmzi"] = {["phrase"] = "碟子", ["word"] = {"迭", "跌"}},
    ["jqle"] = {["phrase"] = "静了", ["word"] = {"竞", "竟"}},
    ["gdmi"] = {["phrase"] = "高密", ["word"] = {"槔"}},
    ["jblm"] = {["phrase"] = "假劣", ["word"] = {"驾", "架"}},
    ["kebk"] = {["phrase"] = "课标", ["word"] = {"客", "疴"}},
    ["uude"] = {["phrase"] = "处得", ["word"] = {"刍"}},
    ["bibi"] = {["phrase"] = "比比", ["word"] = {"毕"}},
    ["khke"] = {["phrase"] = "旷课", ["word"] = {"贶"}},
    ["yuda"] = {["phrase"] = "愈大", ["word"] = {"鱼", "渔"}},
    ["uumk"] = {["phrase"] = "出苗", ["word"] = {"樗"}},
    ["libl"] = {["phrase"] = "李斌", ["word"] = {"疬"}},
    ["xjbm"] = {["phrase"] = "先别", ["word"] = {"痫"}},
    ["hcbu"] = {["phrase"] = "缓步", ["word"] = {"宦"}},
    ["yiry"] = {["phrase"] = "仪容", ["word"] = {"仪", "伊", "依"}},
    ["dotu"] = {["phrase"] = "多图", ["word"] = {"埵"}},
    ["buvc"] = {["phrase"] = "不转", ["word"] = {"簿"}},
    ["lhdg"] = {["phrase"] = "两党", ["word"] = {"良"}},
    ["soci"] = {["phrase"] = "所赐", ["word"] = {"莎"}},
    ["jldy"] = {["phrase"] = "今冬", ["word"] = {"津", "浸"}},
    ["xidd"] = {["phrase"] = "铣刀", ["word"] = {"溪"}},
    ["yppf"] = {["phrase"] = "优盘", ["word"] = {"牖"}},
    ["hfxx"] = {["phrase"] = "汉学", ["word"] = {"憾"}},
    ["pudi"] = {["phrase"] = "铺地", ["word"] = {"瀑"}},
    ["yfie"] = {["phrase"] = "衍射", ["word"] = {"砚"}},
    ["ifdo"] = {["phrase"] = "闪躲", ["word"] = {"潸"}},
    ["wuyl"] = {["phrase"] = "无垠", ["word"] = {"雾"}},
    ["hudi"] = {["phrase"] = "湖底", ["word"] = {"户", "斛"}},
    ["yfry"] = {["phrase"] = "岩溶", ["word"] = {"俨"}},
    ["bfbw"] = {["phrase"] = "半杯", ["word"] = {"癍"}},
    ["utmt"] = {["phrase"] = "承蒙", ["word"] = {"柽"}},
    ["hcsy"] = {["phrase"] = "欢送", ["word"] = {"缓", "缳"}},
    ["fuuz"] = {["phrase"] = "富春", ["word"] = {"蜉"}},
    ["podd"] = {["phrase"] = "坡道", ["word"] = {"泼"}},
    ["nydn"] = {["phrase"] = "弄丢", ["word"] = {"农", "浓"}},
    ["xidj"] = {["phrase"] = "西点", ["word"] = {"浠", "淅"}},
    ["viif"] = {["phrase"] = "至善", ["word"] = {"雉"}},
    ["yqke"] = {["phrase"] = "迎客", ["word"] = {"郢"}},
    ["yell"] = {["phrase"] = "椰林", ["word"] = {"野"}},
    ["jjve"] = {["phrase"] = "见者", ["word"] = {"舰", "笕"}},
    ["bagd"] = {["phrase"] = "拔高", ["word"] = {"魃"}},
    ["yxka"] = {["phrase"] = "月卡", ["word"] = {"曰", "月"}},
    ["yyry"] = {["phrase"] = "雍容", ["word"] = {"佣", "俑"}},
    ["yiix"] = {["phrase"] = "一甩", ["word"] = {"懿"}},
    ["jjyg"] = {["phrase"] = "建阳", ["word"] = {"艰", "戬"}},
    ["yfdd"] = {["phrase"] = "烟道", ["word"] = {"淹", "奄"}},
    ["jmdk"] = {["phrase"] = "戒掉", ["word"] = {"洁"}},
    ["yibm"] = {["phrase"] = "一别", ["word"] = {"益"}},
    ["tfff"] = {["phrase"] = "摊贩", ["word"] = {"摊"}},
    ["jkbw"] = {["phrase"] = "脚背", ["word"] = {"敫"}},
    ["boft"] = {["phrase"] = "波峰", ["word"] = {"播"}},
    ["ruce"] = {["phrase"] = "如厕", ["word"] = {"薷"}},
    ["lisd"] = {["phrase"] = "离骚", ["word"] = {"缡"}},
    ["ycky"] = {["phrase"] = "圆孔", ["word"] = {"圜"}},
    ["qiqx"] = {["phrase"] = "奇缺", ["word"] = {"綦", "憩"}},
    ["xbqj"] = {["phrase"] = "下潜", ["word"] = {"狭", "狎"}},
    ["fupj"] = {["phrase"] = "负片", ["word"] = {"凫"}},
    ["bmda"] = {["phrase"] = "别打", ["word"] = {"鳖"}},
    ["mwve"] = {["phrase"] = "没辙", ["word"] = {"郿"}},
    ["hffg"] = {["phrase"] = "韩方", ["word"] = {"捍"}},
    ["xkvs"] = {["phrase"] = "小寨", ["word"] = {"箫"}},
    ["ierr"] = {["phrase"] = "摄人", ["word"] = {"歙"}},
    ["doku"] = {["phrase"] = "多苦", ["word"] = {"咄"}},
    ["fuut"] = {["phrase"] = "府城", ["word"] = {"辐", "蝠"}},
    ["jlrv"] = {["phrase"] = "金瑞", ["word"] = {"今"}},
    ["fuhz"] = {["phrase"] = "复婚", ["word"] = {"稃"}},
    ["qmxj"] = {["phrase"] = "切线", ["word"] = {"惬"}},
    ["dydd"] = {["phrase"] = "东道", ["word"] = {"冻"}},
    ["lybi"] = {["phrase"] = "隆鼻", ["word"] = {"窿", "癃"}},
    ["xkds"] = {["phrase"] = "小袋", ["word"] = {"潇"}},
    ["bfww"] = {["phrase"] = "班委", ["word"] = {"班", "斑"}},
    ["wuan"] = {["phrase"] = "武安", ["word"] = {"鹉"}},
    ["sybr"] = {["phrase"] = "松本", ["word"] = {"颂"}},
    ["xjce"] = {["phrase"] = "献策", ["word"] = {"苋"}},
    ["wujk"] = {["phrase"] = "五角", ["word"] = {"铻", "鼯"}},
    ["yuhd"] = {["phrase"] = "愈好", ["word"] = {"燠"}},
    ["ypla"] = {["phrase"] = "又拉", ["word"] = {"由", "卣"}},
    ["xqci"] = {["phrase"] = "行刺", ["word"] = {"荥"}},
    ["fwfu"] = {["phrase"] = "肺腑", ["word"] = {"蜚"}},
    ["fuda"] = {["phrase"] = "福大", ["word"] = {"滏"}},
    ["fupi"] = {["phrase"] = "麸皮", ["word"] = {"阜"}},
    ["hvcs"] = {["phrase"] = "徽菜", ["word"] = {"荟"}},
    ["ypro"] = {["phrase"] = "有若", ["word"] = {"侑"}},
    ["livd"] = {["phrase"] = "利爪", ["word"] = {"篱"}},
    ["jjdj"] = {["phrase"] = "检点", ["word"] = {"渐", "溅"}},
    ["yihx"] = {["phrase"] = "一坏", ["word"] = {"移", "黟"}},
    ["wftg"] = {["phrase"] = "晚唐", ["word"] = {"塆"}},
    ["limw"] = {["phrase"] = "李梅", ["word"] = {"粝"}},
    ["idvo"] = {["phrase"] = "烧灼", ["word"] = {"筲", "艄"}},
    ["lujk"] = {["phrase"] = "鹿角", ["word"] = {"铝"}},
    ["vipr"] = {["phrase"] = "直喷", ["word"] = {"质"}},
    ["xige"] = {["phrase"] = "洗个", ["word"] = {"觋"}},
    ["gfmw"] = {["phrase"] = "甘美", ["word"] = {"橄"}},
    ["jqvd"] = {["phrase"] = "京兆", ["word"] = {"刭"}},
    ["jjma"] = {["phrase"] = "见吗", ["word"] = {"检"}},
    ["jkml"] = {["phrase"] = "教民", ["word"] = {"骄"}},
    ["mobd"] = {["phrase"] = "墨宝", ["word"] = {"寞", "瘼"}},
    ["jjbk"] = {["phrase"] = "简表", ["word"] = {"謇"}},
    ["libw"] = {["phrase"] = "立碑", ["word"] = {"疠"}},
    ["ugxm"] = {["phrase"] = "长些", ["word"] = {"氅"}},
    ["diid"] = {["phrase"] = "低烧", ["word"] = {"氐", "砥"}},
    ["lqks"] = {["phrase"] = "另开", ["word"] = {"呤", "囹"}},
    ["uumw"] = {["phrase"] = "触媒", ["word"] = {"杵"}},
    ["ugxu"] = {["phrase"] = "长须", ["word"] = {"怅"}},
    ["pitp"] = {["phrase"] = "劈头", ["word"] = {"坯"}},
    ["sivv"] = {["phrase"] = "丝锥", ["word"] = {"巳"}},
    ["gygf"] = {["phrase"] = "公干", ["word"] = {"巩"}},
    ["xcwr"] = {["phrase"] = "选文", ["word"] = {"璇"}},
    ["qian"] = {["phrase"] = "奇案", ["word"] = {"妻"}},
    ["tfdi"] = {["phrase"] = "探底", ["word"] = {"潭"}},
    ["xidy"] = {["phrase"] = "西东", ["word"] = {"玺"}},
    ["hedk"] = {["phrase"] = "喝掉", ["word"] = {"河", "涸"}},
    ["qipi"] = {["phrase"] = "漆皮", ["word"] = {"祇"}},
    ["subi"] = {["phrase"] = "速比", ["word"] = {"窣"}},
    ["gvmj"] = {["phrase"] = "柜面", ["word"] = {"柜"}},
    ["uthw"] = {["phrase"] = "呈黑", ["word"] = {"程"}},
    ["tudd"] = {["phrase"] = "屠刀", ["word"] = {"兔"}},
    ["yuxk"] = {["phrase"] = "玉箫", ["word"] = {"誉"}},
    ["yubr"] = {["phrase"] = "愚笨", ["word"] = {"欲"}},
    ["tfbf"] = {["phrase"] = "探班", ["word"] = {"瘫"}},
    ["yixc"] = {["phrase"] = "已选", ["word"] = {"羿"}},
    ["lmdd"] = {["phrase"] = "列岛", ["word"] = {"列", "冽", "洌"}},
    ["llrr"] = {["phrase"] = "邻人", ["word"] = {"赁"}},
    ["xmfr"] = {["phrase"] = "泄愤", ["word"] = {"撷"}},
    ["jise"] = {["phrase"] = "基色", ["word"] = {"缉"}},
    ["gfdg"] = {["phrase"] = "敢当", ["word"] = {"泔"}},
    ["gcbk"] = {["phrase"] = "贯标", ["word"] = {"官"}},
    ["yauu"] = {["phrase"] = "压出", ["word"] = {"衙"}},
    ["yikv"] = {["phrase"] = "一窥", ["word"] = {"呓"}},
    ["ypye"] = {["phrase"] = "油液", ["word"] = {"邮"}},
    ["wwen"] = {["phrase"] = "韦恩", ["word"] = {"隈"}},
    ["djib"] = {["phrase"] = "电刷", ["word"] = {"碘"}},
    ["jjdo"] = {["phrase"] = "见多", ["word"] = {"涧"}},
    ["qjdj"] = {["phrase"] = "前店", ["word"] = {"浅"}},
    ["qizd"] = {["phrase"] = "起早", ["word"] = {"蹊"}},
    ["bdcs"] = {["phrase"] = "包菜", ["word"] = {"苞"}},
    ["lnit"] = {["phrase"] = "刘胜", ["word"] = {"馏"}},
    ["ycta"] = {["phrase"] = "愿他", ["word"] = {"垣"}},
    ["iddo"] = {["phrase"] = "稍多", ["word"] = {"潲"}},
    ["sitc"] = {["phrase"] = "四团", ["word"] = {"寺"}},
    ["yily"] = {["phrase"] = "一龙", ["word"] = {"毅"}},
    ["jimj"] = {["phrase"] = "基面", ["word"] = {"机", "极"}},
    ["yfuf"] = {["phrase"] = "眼馋", ["word"] = {"雁"}},
    ["diyd"] = {["phrase"] = "低腰", ["word"] = {"诋"}},
    ["mumd"] = {["phrase"] = "母猫", ["word"] = {"模"}},
    ["duvs"] = {["phrase"] = "赌债", ["word"] = {"厾"}},
    ["yupd"] = {["phrase"] = "浴袍", ["word"] = {"禹"}},
    ["jbll"] = {["phrase"] = "驾临", ["word"] = {"甲"}},
    ["mmvi"] = {["phrase"] = "灭之", ["word"] = {"篾"}},
    ["lulx"] = {["phrase"] = "虏掠", ["word"] = {"卤"}},
    ["ycee"] = {["phrase"] = "员额", ["word"] = {"元", "院"}},
    ["wwkf"] = {["phrase"] = "未看", ["word"] = {"唯"}},
    ["gftg"] = {["phrase"] = "甘棠", ["word"] = {"赶", "坩"}},
    ["hfge"] = {["phrase"] = "焊割", ["word"] = {"邗", "邯"}},
    ["ycuy"] = {["phrase"] = "原虫", ["word"] = {"辕"}},
    ["xikh"] = {["phrase"] = "锡矿", ["word"] = {"熙"}},
    ["uipj"] = {["phrase"] = "翅片", ["word"] = {"褫"}},
    ["dpbd"] = {["phrase"] = "豆包", ["word"] = {"窦"}},
    ["dozy"] = {["phrase"] = "多宗", ["word"] = {"踱"}},
    ["gucg"] = {["phrase"] = "谷仓", ["word"] = {"菰"}},
    ["xjih"] = {["phrase"] = "鲜爽", ["word"] = {"燹"}},
    ["xiir"] = {["phrase"] = "喜神", ["word"] = {"屣"}},
    ["ylqk"] = {["phrase"] = "银翘", ["word"] = {"狺"}},
    ["bjkc"] = {["phrase"] = "变宽", ["word"] = {"匾"}},
    ["jisd"] = {["phrase"] = "祭扫", ["word"] = {"罽"}},
    ["liud"] = {["phrase"] = "历朝", ["word"] = {"蜊"}},
    ["xuwr"] = {["phrase"] = "徐闻", ["word"] = {"顼"}},
    ["lkjl"] = {["phrase"] = "辽金", ["word"] = {"钌"}},
    ["irdv"] = {["phrase"] = "神对", ["word"] = {"沈"}},
    ["yfup"] = {["phrase"] = "眼瞅", ["word"] = {"彦"}},
    ["hpri"] = {["phrase"] = "后日", ["word"] = {"侯", "候"}},
    ["lwyl"] = {["phrase"] = "雷音", ["word"] = {"诔"}},
    ["jibo"] = {["phrase"] = "极薄", ["word"] = {"瘠"}},
    ["yuqh"] = {["phrase"] = "愈强", ["word"] = {"狳"}},
    ["hbri"] = {["phrase"] = "华日", ["word"] = {"华"}},
    ["ffct"] = {["phrase"] = "范曾", ["word"] = {"藩"}},
    ["xmio"] = {["phrase"] = "邪说", ["word"] = {"屑"}},
    ["hoky"] = {["phrase"] = "火控", ["word"] = {"嚄"}},
    ["yuua"] = {["phrase"] = "鱼叉", ["word"] = {"蜮"}},
    ["huhb"] = {["phrase"] = "胡话", ["word"] = {"扈"}},
    ["yfyp"] = {["phrase"] = "焉有", ["word"] = {"严", "谚"}},
    ["vumo"] = {["phrase"] = "铸模", ["word"] = {"槠"}},
    ["jnfa"] = {["phrase"] = "旧法", ["word"] = {"韭"}},
    ["iady"] = {["phrase"] = "沙东", ["word"] = {"裟"}},
    ["fujn"] = {["phrase"] = "负疚", ["word"] = {"幞"}},
    ["qiao"] = {["phrase"] = "奇奥", ["word"] = {"鳍"}},
    ["utmu"] = {["phrase"] = "瞠目", ["word"] = {"枨"}},
    ["gdmk"] = {["phrase"] = "高妙", ["word"] = {"槁"}},
    ["fuff"] = {["phrase"] = "复返", ["word"] = {"扶", "拂", "麸"}},
    ["moci"] = {["phrase"] = "末次", ["word"] = {"摹", "蘑"}},
    ["jmir"] = {["phrase"] = "洁身", ["word"] = {"颉"}},
    ["ffif"] = {["phrase"] = "翻山", ["word"] = {"矾"}},
    ["jnbj"] = {["phrase"] = "就便", ["word"] = {"究", "疚"}},
    ["iico"] = {["phrase"] = "失措", ["word"] = {"蓍"}},
    ["lfdj"] = {["phrase"] = "蓝点", ["word"] = {"澜"}},
    ["ylbo"] = {["phrase"] = "音波", ["word"] = {"窨"}},
    ["fuuf"] = {["phrase"] = "妇产", ["word"] = {"辅", "蚨"}},
    ["migf"] = {["phrase"] = "蜜柑", ["word"] = {"靡"}},
    ["wwao"] = {["phrase"] = "维奥", ["word"] = {"鲔"}},
    ["ximw"] = {["phrase"] = "洗煤", ["word"] = {"檄"}},
    ["xjue"] = {["phrase"] = "闲扯", ["word"] = {"蚬"}},
    ["gejl"] = {["phrase"] = "各进", ["word"] = {"镉"}},
    ["bwlo"] = {["phrase"] = "贝罗", ["word"] = {"背"}},
    ["dyxk"] = {["phrase"] = "洞箫", ["word"] = {"恫"}},
    ["jika"] = {["phrase"] = "集卡", ["word"] = {"戢"}},
    ["iumd"] = {["phrase"] = "梳毛", ["word"] = {"术"}},
    ["hgdj"] = {["phrase"] = "航电", ["word"] = {"沆"}},
    ["qxif"] = {["phrase"] = "确山", ["word"] = {"雀"}},
    ["ygdy"] = {["phrase"] = "阳东", ["word"] = {"殃", "洋", "漾", "泱"}},
    ["lndt"] = {["phrase"] = "六等", ["word"] = {"溜"}},
    ["gudg"] = {["phrase"] = "鼓荡", ["word"] = {"觚"}},
    ["wwdf"] = {["phrase"] = "味淡", ["word"] = {"潍"}},
    ["yghy"] = {["phrase"] = "洋红", ["word"] = {"秧", "烊"}},
    ["ggfg"] = {["phrase"] = "港方", ["word"] = {"扛", "缸"}},
    ["jlya"] = {["phrase"] = "金牙", ["word"] = {"谨"}},
    ["vuml"] = {["phrase"] = "住民", ["word"] = {"杼"}},
    ["lqmw"] = {["phrase"] = "菱镁", ["word"] = {"棱"}},
    ["xkdo"] = {["phrase"] = "小朵", ["word"] = {"消", "淆"}},
    ["tgxm"] = {["phrase"] = "淌血", ["word"] = {"棠"}},
    ["mtqn"] = {["phrase"] = "梦秋", ["word"] = {"獴"}},
    ["mdce"] = {["phrase"] = "茅厕", ["word"] = {"茆"}},
    -- ["duke"] = {["phrase"] = "赌客", ["word"] = {"嘟"}},
    -- ["ufji"] = {["phrase"] = "禅机", ["word"] = {"镡"}},
    -- ["ciyg"] = {["phrase"] = "刺痒", ["word"] = {"差"}},
    -- ["furf"] = {["phrase"] = "复燃", ["word"] = {"佛"}},
    -- ["vucv"] = {["phrase"] = "珠翠", ["word"] = {"茱"}},
    -- ["lyli"] = {["phrase"] = "龙里", ["word"] = {"砻"}},
    -- ["jhgu"] = {["phrase"] = "讲古", ["word"] = {"强"}},
    -- ["jmif"] = {["phrase"] = "界山", ["word"] = {"截"}},
    -- ["xmdy"] = {["phrase"] = "谢东", ["word"] = {"泻"}},
    -- ["wunk"] = {["phrase"] = "无尿", ["word"] = {"牾"}},
    -- ["ypuz"] = {["phrase"] = "游春", ["word"] = {"蝣"}},
    -- ["yuih"] = {["phrase"] = "玉霜", ["word"] = {"熨"}},
    -- ["utut"] = {["phrase"] = "成城", ["word"] = {"蛏"}},
    -- ["htuu"] = {["phrase"] = "哼出", ["word"] = {"行", "衡"}},
    -- ["vflg"] = {["phrase"] = "战狼", ["word"] = {"战"}},
    -- ["vumd"] = {["phrase"] = "猪毛", ["word"] = {"术"}},
    -- ["svzi"] = {["phrase"] = "穗子", ["word"] = {"遂", "邃"}},
    -- ["liyl"] = {["phrase"] = "丽音", ["word"] = {"雳"}},
    -- ["tydk"] = {["phrase"] = "同调", ["word"] = {"洞"}},
    -- ["iudv"] = {["phrase"] = "属对", ["word"] = {"殊"}},
    -- ["qjeq"] = {["phrase"] = "前儿", ["word"] = {"阡"}},
    -- ["ycke"] = {["phrase"] = "远客", ["word"] = {"园"}},
    -- ["yikb"] = {["phrase"] = "一跨", ["word"] = {"邑"}},
    -- ["tvhz"] = {["phrase"] = "退婚", ["word"] = {"煺"}},
    -- ["gunn"] = {["phrase"] = "牯牛", ["word"] = {"鹄"}},
    -- ["yfuz"] = {["phrase"] = "艳春", ["word"] = {"蜒"}},
    -- ["hyds"] = {["phrase"] = "红带", ["word"] = {"泓"}},
    -- ["jzye"] = {["phrase"] = "菌液", ["word"] = {"郡"}},
    -- ["jivo"] = {["phrase"] = "几桌", ["word"] = {"籍"}},
    -- ["xcdy"] = {["phrase"] = "旋动", ["word"] = {"泫"}},
    -- ["gujk"] = {["phrase"] = "故交", ["word"] = {"钴", "锢"}},
    -- ["jini"] = {["phrase"] = "基尼", ["word"] = {"嫉"}},
    -- ["jjbr"] = {["phrase"] = "简本", ["word"] = {"蹇"}},
    -- ["jqcd"] = {["phrase"] = "劲草", ["word"] = {"荆"}},
    -- ["bjsc"] = {["phrase"] = "变酸", ["word"] = {"编", "弁"}},
    -- ["jiny"] = {["phrase"] = "积脓", ["word"] = {"妓"}},
    -- ["yqbr"] = {["phrase"] = "影本", ["word"] = {"颖", "颍"}},
    -- ["dzkt"] = {["phrase"] = "蹲坑", ["word"] = {"吨", "囤"}},
    -- ["qkgo"] = {["phrase"] = "敲过", ["word"] = {"鞘"}},
    -- ["kegg"] = {["phrase"] = "克刚", ["word"] = {"髁"}},
    -- ["xipk"] = {["phrase"] = "戏票", ["word"] = {"禧"}},
    -- ["hddi"] = {["phrase"] = "好迪", ["word"] = {"濠"}},
    -- ["hfdk"] = {["phrase"] = "函调", ["word"] = {"涵"}},
    -- ["jjlt"] = {["phrase"] = "渐冷", ["word"] = {"坚"}},
    -- ["dzzo"] = {["phrase"] = "蹲坐", ["word"] = {"遁"}},
    -- ["tgre"] = {["phrase"] = "烫热", ["word"] = {"傥"}},
    -- ["furc"] = {["phrase"] = "服软", ["word"] = {"付", "俯", "傅"}},
    -- ["kedm"] = {["phrase"] = "刻碟", ["word"] = {"溘"}},
    -- ["yusy"] = {["phrase"] = "狱讼", ["word"] = {"纡"}},
    -- ["xmir"] = {["phrase"] = "斜身", ["word"] = {"颉"}},
    -- ["ycxn"] = {["phrase"] = "元修", ["word"] = {"鸳"}},
    -- ["htwu"] = {["phrase"] = "蘅芜", ["word"] = {"珩"}},
    -- ["ieqk"] = {["phrase"] = "涉侨", ["word"] = {"舌", "猞"}},
    -- ["hfbg"] = {["phrase"] = "汉邦", ["word"] = {"罕"}},
    -- ["dgip"] = {["phrase"] = "党首", ["word"] = {"砀"}},
    -- ["yuma"] = {["phrase"] = "玉马", ["word"] = {"阈"}},
    -- ["idci"] = {["phrase"] = "烧瓷", ["word"] = {"芍"}},
    -- ["wwhw"] = {["phrase"] = "微黑", ["word"] = {"炜"}},
    -- ["yidk"] = {["phrase"] = "移调", ["word"] = {"漪"}},
    -- ["zidk"] = {["phrase"] = "紫貂", ["word"] = {"咨"}},
    -- ["qice"] = {["phrase"] = "凄恻", ["word"] = {"葺"}},
    -- ["yfnk"] = {["phrase"] = "验尿", ["word"] = {"妍"}},
    -- ["vddk"] = {["phrase"] = "着调", ["word"] = {"召", "沼"}},
    -- ["gfyg"] = {["phrase"] = "赶羊", ["word"] = {"酐"}},
    -- ["tzit"] = {["phrase"] = "吞声", ["word"] = {"饨"}},
    -- ["lugh"] = {["phrase"] = "露光", ["word"] = {"庐"}},
    -- ["ypbo"] = {["phrase"] = "又播", ["word"] = {"宥"}},
    -- ["jbly"] = {["phrase"] = "甲龙", ["word"] = {"袈"}},
    -- ["mkce"] = {["phrase"] = "妙策", ["word"] = {"藐"}},
    -- ["hudg"] = {["phrase"] = "湖荡", ["word"] = {"瓠"}},
    -- ["tucd"] = {["phrase"] = "吐槽", ["word"] = {"菟"}},
    -- ["kvxl"] = {["phrase"] = "亏心", ["word"] = {"悝"}},
    -- ["tmjk"] = {["phrase"] = "铁脚", ["word"] = {"帖"}},
    -- ["cvxi"] = {["phrase"] = "翠喜", ["word"] = {"悴", "翠"}},
    -- ["pubf"] = {["phrase"] = "铺板", ["word"] = {"匍"}},
    -- ["xqxb"] = {["phrase"] = "姓夏", ["word"] = {"兴"}},
    -- ["jkkh"] = {["phrase"] = "骄狂", ["word"] = {"噍"}},
    -- ["fupd"] = {["phrase"] = "副炮", ["word"] = {"祓"}},
    -- ["jila"] = {["phrase"] = "急拉", ["word"] = {"亟"}},
    -- ["cofg"] = {["phrase"] = "错放", ["word"] = {"搓"}},
    -- ["gukg"] = {["phrase"] = "谷糠", ["word"] = {"呱"}},
    -- ["yqci"] = {["phrase"] = "英雌", ["word"] = {"荥"}},
    -- ["icma"] = {["phrase"] = "拴马", ["word"] = {"闩"}},
    -- ["uiiw"] = {["phrase"] = "吃谁", ["word"] = {"敕"}},
    -- ["gubk"] = {["phrase"] = "姑表", ["word"] = {"谷", "痼"}},
    -- ["yucy"] = {["phrase"] = "郁葱", ["word"] = {"芋", "萸"}},
    -- ["ifna"] = {["phrase"] = "姗娜", ["word"] = {"嬗"}},
    -- ["iirc"] = {["phrase"] = "湿软", ["word"] = {"侍"}},
    -- ["yfdk"] = {["phrase"] = "阉掉", ["word"] = {"沿"}},
    -- ["xuky"] = {["phrase"] = "虚空", ["word"] = {"吁", "嘘"}},
    -- ["ylcd"] = {["phrase"] = "阴曹", ["word"] = {"茵"}},
    -- ["suxx"] = {["phrase"] = "俗学", ["word"] = {"愫"}},
    -- ["rudk"] = {["phrase"] = "入调", ["word"] = {"洳"}},
    -- ["xzci"] = {["phrase"] = "训词", ["word"] = {"蕈"}},
    -- ["lumi"] = {["phrase"] = "禄米", ["word"] = {"栌"}},
    -- ["yaky"] = {["phrase"] = "轧空", ["word"] = {"呀", "哑"}},
    -- ["gfvg"] = {["phrase"] = "干仗", ["word"] = {"竿"}},
    -- ["gpmk"] = {["phrase"] = "勾描", ["word"] = {"枸"}},
    -- ["yguy"] = {["phrase"] = "恙虫", ["word"] = {"徉", "蛘"}},
    -- ["divy"] = {["phrase"] = "地中", ["word"] = {"笛"}},
    -- ["bwkr"] = {["phrase"] = "被啃", ["word"] = {"贝", "呗"}},
    -- ["gunk"] = {["phrase"] = "孤鸟", ["word"] = {"姑", "牯"}},
    -- ["idho"] = {["phrase"] = "烧火", ["word"] = {"稍"}},
    -- ["zymr"] = {["phrase"] = "宗门", ["word"] = {"枞"}},
    -- ["pibi"] = {["phrase"] = "疲敝", ["word"] = {"癖"}},
    -- ["tfdk"] = {["phrase"] = "弹掉", ["word"] = {"澹"}},
    -- ["njfu"] = {["phrase"] = "黏附", ["word"] = {"撵", "辇"}},
    -- ["yqdy"] = {["phrase"] = "颍东", ["word"] = {"滢"}},
    -- ["itio"] = {["phrase"] = "声说", ["word"] = {"省"}},
    -- ["xkkz"] = {["phrase"] = "小捆", ["word"] = {"哮"}},
    -- ["mike"] = {["phrase"] = "米克", ["word"] = {"嘧"}},
    -- ["jidz"] = {["phrase"] = "几顿", ["word"] = {"洎"}},
    -- ["zfwo"] = {["phrase"] = "赞我", ["word"] = {"昝"}},
    -- ["fubj"] = {["phrase"] = "复变", ["word"] = {"斧"}},
    -- ["gudo"] = {["phrase"] = "骨朵", ["word"] = {"汩"}},
    -- ["jqdg"] = {["phrase"] = "精当", ["word"] = {"泾"}},
    -- ["bdvs"] = {["phrase"] = "报摘", ["word"] = {"龅"}},
    -- ["vuql"] = {["phrase"] = "竹琴", ["word"] = {"助"}},
    -- ["eeke"] = {["phrase"] = "恶客", ["word"] = {"鄂"}},
    -- ["iuso"] = {["phrase"] = "数所", ["word"] = {"署"}},
    -- ["vgdi"] = {["phrase"] = "章帝", ["word"] = {"漳"}},
    -- ["yfdt"] = {["phrase"] = "烟灯", ["word"] = {"湮"}},
    -- ["xqke"] = {["phrase"] = "刑克", ["word"] = {"邢"}},
    -- ["hvxu"] = {["phrase"] = "会须", ["word"] = {"辉", "翚"}},
    -- ["eenk"] = {["phrase"] = "屙尿", ["word"] = {"婀"}},
    -- ["hemr"] = {["phrase"] = "阖门", ["word"] = {"核", "阂"}},
    -- ["tjdk"] = {["phrase"] = "舔掉", ["word"] = {"湉"}},
    -- ["jmfr"] = {["phrase"] = "解纷", ["word"] = {"捷"}},
    -- ["ydbl"] = {["phrase"] = "姚滨", ["word"] = {"窈"}},
    -- ["tjdp"] = {["phrase"] = "甜豆", ["word"] = {"殄"}},
    -- ["yuky"] = {["phrase"] = "育空", ["word"] = {"吁", "喁"}},
    -- ["sadi"] = {["phrase"] = "萨蒂", ["word"] = {"挲"}},
    -- ["ksmj"] = {["phrase"] = "开面", ["word"] = {"闿"}},
    -- ["yfmk"] = {["phrase"] = "烟苗", ["word"] = {"檐"}},
    -- ["hvds"] = {["phrase"] = "回带", ["word"] = {"浍"}},
    -- ["yedk"] = {["phrase"] = "椰雕", ["word"] = {"冶"}},
    -- ["quhw"] = {["phrase"] = "黢黑", ["word"] = {"黢"}},
    -- ["qjhw"] = {["phrase"] = "浅黑", ["word"] = {"虔"}},
    -- ["kemg"] = {["phrase"] = "科盲", ["word"] = {"棵", "骒"}},
    -- ["vfdk"] = {["phrase"] = "占掉", ["word"] = {"沾", "詹"}},
    -- ["qmxn"] = {["phrase"] = "且休", ["word"] = {"慊"}},
    -- ["qcbw"] = {["phrase"] = "圈杯", ["word"] = {"痊"}},
    -- ["tsse"] = {["phrase"] = "泰瑟", ["word"] = {"邰"}},
    -- ["juxb"] = {["phrase"] = "锯下", ["word"] = {"惧"}},
    -- ["ffpt"] = {["phrase"] = "帆篷", ["word"] = {"番"}},
    -- ["xihx"] = {["phrase"] = "膝踝", ["word"] = {"熄"}},
    -- ["cymr"] = {["phrase"] = "囱门", ["word"] = {"枞"}},
    -- ["lihh"] = {["phrase"] = "蛎黄", ["word"] = {"黧"}},
    -- ["jbbk"] = {["phrase"] = "假表", ["word"] = {"痂"}},
    -- ["xjye"] = {["phrase"] = "涎液", ["word"] = {"酰"}},
    -- ["iidq"] = {["phrase"] = "实定", ["word"] = {"殖"}},
    -- ["yfmd"] = {["phrase"] = "颜貌", ["word"] = {"阉", "阏"}},
    -- ["jnmj"] = {["phrase"] = "酒面", ["word"] = {"柩", "桕"}},
    -- ["ptip"] = {["phrase"] = "蓬首", ["word"] = {"砰", "彭"}},
    -- ["vaia"] = {["phrase"] = "扎煞", ["word"] = {"馇"}},
    -- ["xuso"] = {["phrase"] = "须索", ["word"] = {"绪"}},
    -- ["guio"] = {["phrase"] = "告朔", ["word"] = {"瞽"}},
    -- ["qimj"] = {["phrase"] = "期勉", ["word"] = {"杞", "桤"}},
    -- ["vpdy"] = {["phrase"] = "周董", ["word"] = {"皱"}},
    -- ["uprf"] = {["phrase"] = "惆然", ["word"] = {"雠"}},
    -- ["hetm"] = {["phrase"] = "贺帖", ["word"] = {"盍"}},
    -- ["irlo"] = {["phrase"] = "沈落", ["word"] = {"肾"}},
    -- ["ypcy"] = {["phrase"] = "幽丛", ["word"] = {"莸"}},
    -- ["siva"] = {["phrase"] = "四扎", ["word"] = {"丝"}},
    -- ["fusd"] = {["phrase"] = "拂扫", ["word"] = {"绂"}},
    -- ["zpft"] = {["phrase"] = "走风", ["word"] = {"奏", "揍"}},
    -- ["iedo"] = {["phrase"] = "舍堕", ["word"] = {"奢"}},
    -- ["fuba"] = {["phrase"] = "副把", ["word"] = {"釜"}},
    -- ["coit"] = {["phrase"] = "搓绳", ["word"] = {"矬"}},
    -- ["monm"] = {["phrase"] = "莫涅", ["word"] = {"嬷"}},
    -- ["mwmo"] = {["phrase"] = "煤末", ["word"] = {"楣"}},
    -- ["tokd"] = {["phrase"] = "托靠", ["word"] = {"鼍"}},
    -- ["pitj"] = {["phrase"] = "辟田", ["word"] = {"圮"}},
    -- ["vurv"] = {["phrase"] = "烛蕊", ["word"] = {"住", "侏"}},
    -- ["dkkd"] = {["phrase"] = "吊拷", ["word"] = {"叼"}},
    -- ["hvko"] = {["phrase"] = "恢廓", ["word"] = {"贿"}},
    -- ["jivb"] = {["phrase"] = "棘爪", ["word"] = {"箕"}},
    -- ["djir"] = {["phrase"] = "电渗", ["word"] = {"颠"}},
    -- ["ffht"] = {["phrase"] = "帆桁", ["word"] = {"燔"}},
    -- ["xipd"] = {["phrase"] = "吸跑", ["word"] = {"夕", "奚", "禊"}},
    -- ["pkdz"] = {["phrase"] = "朴钝", ["word"] = {"殍"}},
    -- ["pdbs"] = {["phrase"] = "抛摆", ["word"] = {"疱"}},
    -- ["jjgz"] = {["phrase"] = "奸棍", ["word"] = {"鞬", "鞯"}},
    -- ["jjvo"] = {["phrase"] = "简擢", ["word"] = {"简"}},
    -- ["nmky"] = {["phrase"] = "捏控", ["word"] = {"嗫"}},
    -- ["iipf"] = {["phrase"] = "实盘", ["word"] = {"失"}},
    -- ["xmdm"] = {["phrase"] = "躞蹀", ["word"] = {"渫"}},
    -- ["xqip"] = {["phrase"] = "姓寿", ["word"] = {"饧"}},
    -- ["qjbr"] = {["phrase"] = "椠本", ["word"] = {"歉"}},
    -- ["fugr"] = {["phrase"] = "复根", ["word"] = {"腐"}},
    -- ["xqkp"] = {["phrase"] = "姓寇", ["word"] = {"形"}},
    -- ["xzdi"] = {["phrase"] = "训迪", ["word"] = {"汛"}},
    -- ["humi"] = {["phrase"] = "忽米", ["word"] = {"槲"}},
    -- ["pdds"] = {["phrase"] = "庖代", ["word"] = {"泡", "匏"}},
    -- ["lumo"] = {["phrase"] = "戮没", ["word"] = {"橹", "氇"}},
    -- ["psdf"] = {["phrase"] = "排氮", ["word"] = {"湃"}},
    -- ["xink"] = {["phrase"] = "犀鸟", ["word"] = {"嬉"}},
    -- ["luuy"] = {["phrase"] = "卤虫", ["word"] = {"律"}},
    -- ["jqco"] = {["phrase"] = "惊错", ["word"] = {"菁"}},
    -- ["lnmt"] = {["phrase"] = "刘猛", ["word"] = {"榴", "骝"}},
    -- ["fucz"] = {["phrase"] = "富村", ["word"] = {"莩"}},
    -- ["aofu"] = {["phrase"] = "熬稃", ["word"] = {"螯"}},
    -- ["gcwf"] = {["phrase"] = "观玩", ["word"] = {"瓘"}},
    -- ["yuzd"] = {["phrase"] = "舆皂", ["word"] = {"逾"}},
    -- ["yfnh"] = {["phrase"] = "雁娘", ["word"] = {"燕", "嫣"}},
    -- ["jqcg"] = {["phrase"] = "京仓", ["word"] = {"茎"}},
    -- ["fucc"] = {["phrase"] = "伏窜", ["word"] = {"苻"}},
    -- ["frmd"] = {["phrase"] = "分茅", ["word"] = {"粉", "棼"}},
    -- ["jiry"] = {["phrase"] = "即戎", ["word"] = {"伎"}},
    -- ["yelp"] = {["phrase"] = "夜漏", ["word"] = {"曳"}},
    -- ["dava"] = {["phrase"] = "大札", ["word"] = {"笪"}},
    -- ["tjqx"] = {["phrase"] = "天阙", ["word"] = {"舔"}},
    -- ["mwnm"] = {["phrase"] = "媒孽", ["word"] = {"媒"}},
    -- ["kebg"] = {["phrase"] = "客帮", ["word"] = {"窠"}},
    -- ["hcda"] = {["phrase"] = "宦达", ["word"] = {"洹"}},
    -- ["xzuo"] = {["phrase"] = "巡绰", ["word"] = {"循", "徇"}},
    -- ["ffmf"] = {["phrase"] = "帆幔", ["word"] = {"梵"}},
    -- ["huhh"] = {["phrase"] = "忽荒", ["word"] = {"烀"}},
    -- ["uupo"] = {["phrase"] = "怵迫", ["word"] = {"褚"}},
    -- ["hzdi"] = {["phrase"] = "昏第", ["word"] = {"溷"}},
    -- ["khdu"] = {["phrase"] = "旷度", ["word"] = {"夼"}},
    -- ["qkif"] = {["phrase"] = "桥山", ["word"] = {"雀"}},
    -- ["djbr"] = {["phrase"] = "殿本", ["word"] = {"癫"}},
    -- ["diqh"] = {["phrase"] = "氐羌", ["word"] = {"狄"}},
    -- ["fupt"] = {["phrase"] = "浮棚", ["word"] = {"福"}},
    -- ["yauv"] = {["phrase"] = "牙槌", ["word"] = {"轧"}},
    -- ["huho"] = {["phrase"] = "狐惑", ["word"] = {"煳"}},
    -- ["gvms"] = {["phrase"] = "瑰迈", ["word"] = {"桧"}},
    -- ["licd"] = {["phrase"] = "立草", ["word"] = {"莉", "蓠"}},
    -- ["jqmg"] = {["phrase"] = "精芒", ["word"] = {"粳"}},
    -- ["vvmf"] = {["phrase"] = "缀满", ["word"] = {"椎", "骓"}},
    -- ["xjzz"] = {["phrase"] = "县尊", ["word"] = {"跹"}},
    -- ["sodi"] = {["phrase"] = "缩地", ["word"] = {"挲"}},
    -- ["xzdc"] = {["phrase"] = "讯断", ["word"] = {"浔"}},
    -- ["tddj"] = {["phrase"] = "讨店", ["word"] = {"滔"}},
    -- ["dazz"] = {["phrase"] = "达尊", ["word"] = {"跶"}},
    -- ["vrmr"] = {["phrase"] = "阵门", ["word"] = {"桢"}},
    -- ["pwkp"] = {["phrase"] = "陪口", ["word"] = {"呸"}},
    -- ["tddf"] = {["phrase"] = "陶诞", ["word"] = {"淘"}},
    -- ["yghp"] = {["phrase"] = "阳侯", ["word"] = {"炀"}},
    -- ["ygyx"] = {["phrase"] = "阳月", ["word"] = {"恙"}},
    -- ["ylce"] = {["phrase"] = "隐恻", ["word"] = {"茚"}},
    -- ["lqye"] = {["phrase"] = "灵液", ["word"] = {"酃"}},
    -- ["yuto"] = {["phrase"] = "鹬鸵", ["word"] = {"堉"}},
    -- ["yiro"] = {["phrase"] = "一若", ["word"] = {"佾"}},
    -- ["vyrv"] = {["phrase"] = "中瑞", ["word"] = {"仲"}},
    -- ["ftee"] = {["phrase"] = "丰额", ["word"] = {"酆"}},
    -- ["wudk"] = {["phrase"] = "乌雕", ["word"] = {"污", "浯"}},
    -- ["wubk"] = {["phrase"] = "五彪", ["word"] = {"痦", "寤"}},
    -- ["jmbl"] = {["phrase"] = "介宾", ["word"] = {"疥"}},
    -- ["lqcs"] = {["phrase"] = "令才", ["word"] = {"苓"}},
    -- ["yivv"] = {["phrase"] = "仪缀", ["word"] = {"乙", "已"}},
    -- ["xndo"] = {["phrase"] = "休惰", ["word"] = {"滫"}},
    -- ["irdp"] = {["phrase"] = "伸抖", ["word"] = {"渗"}},
    -- ["yuzy"] = {["phrase"] = "余纵", ["word"] = {"迂", "遇"}},
    -- ["yurd"] = {["phrase"] = "余饶", ["word"] = {"俞"}},
    -- ["nqdd"] = {["phrase"] = "佞道", ["word"] = {"泞"}},
    -- ["qjyz"] = {["phrase"] = "佥允", ["word"] = {"谴"}},
    -- ["uuzo"] = {["phrase"] = "储佐", ["word"] = {"躇"}},
    -- ["yzss"] = {["phrase"] = "允塞", ["word"] = {"纭"}},
    -- ["yzkr"] = {["phrase"] = "允肯", ["word"] = {"员"}},
    -- ["gybk"] = {["phrase"] = "公表", ["word"] = {"宫"}},
    -- ["gcfr"] = {["phrase"] = "关汾", ["word"] = {"掼"}},
    -- ["jxfg"] = {["phrase"] = "决放", ["word"] = {"抉"}},
    -- ["jxdy"] = {["phrase"] = "决洞", ["word"] = {"角"}},
    -- ["qitt"] = {["phrase"] = "凄疼", ["word"] = {"畦"}},
    -- ["frrr"] = {["phrase"] = "分任", ["word"] = {"偾"}},
    -- ["xqkd"] = {["phrase"] = "刑拷", ["word"] = {"刑"}},
    -- ["uudf"] = {["phrase"] = "初旦", ["word"] = {"雏"}},
    -- ["uury"] = {["phrase"] = "初荣", ["word"] = {"俶"}},
    -- ["bdhs"] = {["phrase"] = "剥害", ["word"] = {"炮"}},
    -- ["qlcv"] = {["phrase"] = "勤悴", ["word"] = {"芩"}},
    -- ["bwio"] = {["phrase"] = "北朔", ["word"] = {"臂"}},
    -- ["kvee"] = {["phrase"] = "匮饿", ["word"] = {"岿"}},
    -- ["iipt"] = {["phrase"] = "十朋", ["word"] = {"矢"}},
    -- ["bwiz"] = {["phrase"] = "卑顺", ["word"] = {"孛"}},
    -- ["iuwt"] = {["phrase"] = "叔翁", ["word"] = {"塾"}},
    -- ["quix"] = {["phrase"] = "取帅", ["word"] = {"躯"}},
    -- ["jirv"] = {["phrase"] = "吉瑞", ["word"] = {"偈"}},
    -- ["dsry"] = {["phrase"] = "呆容", ["word"] = {"代", "袋"}},
    -- ["yysy"] = {["phrase"] = "咏颂", ["word"] = {"甬"}},
    -- ["aicv"] = {["phrase"] = "哀悴", ["word"] = {"蔼"}},
    -- ["ugro"] = {["phrase"] = "唱偌", ["word"] = {"倡"}},
    -- ["ifhd"] = {["phrase"] = "善好", ["word"] = {"剡"}},
    -- ["ifhx"] = {["phrase"] = "善怀", ["word"] = {"扇", "煽"}},
    -- ["ifmp"] = {["phrase"] = "善谋", ["word"] = {"杉"}},
    -- ["jjrz"] = {["phrase"] = "坚润", ["word"] = {"健"}},
    -- ["qhpu"] = {["phrase"] = "墙铺", ["word"] = {"襁"}},
    -- ["ufdz"] = {["phrase"] = "孱钝", ["word"] = {"潺"}},
    -- ["zybr"] = {["phrase"] = "宗本", ["word"] = {"疭"}},
    -- ["xcda"] = {["phrase"] = "宣答", ["word"] = {"渲"}},
    -- ["zsbi"] = {["phrase"] = "宰弼", ["word"] = {"宰"}},
    -- ["suvr"] = {["phrase"] = "宿疹", ["word"] = {"簌"}},
    -- ["jihw"] = {["phrase"] = "寂嘿", ["word"] = {"稷"}},
    -- ["qlry"] = {["phrase"] = "寝容", ["word"] = {"侵", "衾"}},
    -- ["ifcy"] = {["phrase"] = "山丛", ["word"] = {"芟"}},
    -- ["ifbl"] = {["phrase"] = "山宾", ["word"] = {"单"}},
    -- ["lcwr"] = {["phrase"] = "峦纹", ["word"] = {"脔"}},
    -- ["dizy"] = {["phrase"] = "帝宗", ["word"] = {"迪"}},
    -- ["ugao"] = {["phrase"] = "常奥", ["word"] = {"鲳"}},
    -- ["ypjy"] = {["phrase"] = "幽扃", ["word"] = {"铀", "鼬"}},
    -- ["vhdi"] = {["phrase"] = "庄地", ["word"] = {"壮"}},
    -- ["yqcu"] = {["phrase"] = "应猝", ["word"] = {"萤"}},
    -- ["yilx"] = {["phrase"] = "异略", ["word"] = {"意", "翊"}},
    -- ["yltt"] = {["phrase"] = "引藤", ["word"] = {"堙"}},
    -- ["mibj"] = {["phrase"] = "弭变", ["word"] = {"幂"}},
    -- ["qhyg"] = {["phrase"] = "强羊", ["word"] = {"羟"}},
    -- ["gvmt"] = {["phrase"] = "归梦", ["word"] = {"闺", "桂"}},
    -- ["yqkf"] = {["phrase"] = "影刊", ["word"] = {"罂"}},
    -- ["xzdo"] = {["phrase"] = "徇铎", ["word"] = {"殉", "洵"}},
    -- ["yuud"] = {["phrase"] = "御朝", ["word"] = {"蝓"}},
    -- ["ugru"] = {["phrase"] = "怅如", ["word"] = {"伥"}},
    -- ["ycte"] = {["phrase"] = "怨慝", ["word"] = {"垸"}},
    -- ["ypko"] = {["phrase"] = "悠阔", ["word"] = {"囿"}},
    -- ["wfce"] = {["phrase"] = "惋恻", ["word"] = {"莞"}},
    -- ["hvkh"] = {["phrase"] = "惠贶", ["word"] = {"咴"}},
    -- ["bigg"] = {["phrase"] = "愎戆", ["word"] = {"弼"}},
    -- ["gebq"] = {["phrase"] = "戈兵", ["word"] = {"疙"}},
    -- ["dsri"] = {["phrase"] = "戴日", ["word"] = {"傣"}},
    -- ["pumo"] = {["phrase"] = "扑摸", ["word"] = {"氆"}},
    -- ["pudc"] = {["phrase"] = "扑断", ["word"] = {"溥"}},
    -- ["tomu"] = {["phrase"] = "托慕", ["word"] = {"柝"}},
    -- ["piba"] = {["phrase"] = "批把", ["word"] = {"丕"}},
    -- ["uthp"] = {["phrase"] = "承候", ["word"] = {"秤"}},
    -- ["jica"] = {["phrase"] = "挤擦", ["word"] = {"蕺"}},
    -- ["coft"] = {["phrase"] = "挫锋", ["word"] = {"挫"}},
    -- ["voff"] = {["phrase"] = "捉翻", ["word"] = {"擢"}},
    -- ["bojb"] = {["phrase"] = "搏颊", ["word"] = {"钵", "铂"}},
    -- ["vibt"] = {["phrase"] = "支绷", ["word"] = {"窒"}},
    -- ["vfmj"] = {["phrase"] = "旃冕", ["word"] = {"栈"}},
    -- ["wupg"] = {["phrase"] = "无旁", ["word"] = {"午"}},
    -- ["mdsu"] = {["phrase"] = "昴宿", ["word"] = {"蝥", "蟊"}},
    -- ["kvko"] = {["phrase"] = "暌阔", ["word"] = {"喟"}},
    -- ["iunx"] = {["phrase"] = "暑疟", ["word"] = {"恕"}},
    -- ["quen"] = {["phrase"] = "曲恩", ["word"] = {"娶"}},
    -- ["fucf"] = {["phrase"] = "服惨", ["word"] = {"芙", "茀"}},
    -- ["mody"] = {["phrase"] = "末冬", ["word"] = {"没", "殁"}},
    -- ["bkjh"] = {["phrase"] = "标奖", ["word"] = {"镳"}},
    -- ["iudc"] = {["phrase"] = "树端", ["word"] = {"澍"}},
    -- ["liln"] = {["phrase"] = "栗留", ["word"] = {"鹂"}},
    -- ["gemk"] = {["phrase"] = "格苗", ["word"] = {"阁", "格"}},
    -- ["jjcu"] = {["phrase"] = "检促", ["word"] = {"茧"}},
    -- ["bipi"] = {["phrase"] = "比譬", ["word"] = {"裨"}},
    -- ["mdso"] = {["phrase"] = "毛索", ["word"] = {"瞀"}},
    -- ["ircv"] = {["phrase"] = "沈悴", ["word"] = {"葚"}},
    -- ["qidm"] = {["phrase"] = "沏迭", ["word"] = {"柒"}},
    -- ["zekv"] = {["phrase"] = "泽葵", ["word"] = {"咋"}},
    -- ["hybk"] = {["phrase"] = "洪飙", ["word"] = {"訇"}},
    -- ["yubg"] = {["phrase"] = "渔榜", ["word"] = {"窳"}},
    -- ["hocf"] = {["phrase"] = "火蚕", ["word"] = {"藿"}},
    -- ["jkix"] = {["phrase"] = "焦衰", ["word"] = {"饺"}},
    -- ["wwix"] = {["phrase"] = "猥衰", ["word"] = {"慰"}},
    -- ["qyge"] = {["phrase"] = "琼阁", ["word"] = {"邛"}},
    -- ["ydzf"] = {["phrase"] = "瑶簪", ["word"] = {"遥"}},
    -- ["gbqn"] = {["phrase"] = "瓜丘", ["word"] = {"鸹"}},
    -- ["hupk"] = {["phrase"] = "瓠瓢", ["word"] = {"祜"}},
    -- ["pfpt"] = {["phrase"] = "畔朋", ["word"] = {"番"}},
    -- ["iult"] = {["phrase"] = "疏冷", ["word"] = {"墅"}},
    -- ["jkih"] = {["phrase"] = "皎爽", ["word"] = {"礁"}},
    -- ["hdti"] = {["phrase"] = "皓体", ["word"] = {"壕"}},
    -- ["xhmn"] = {["phrase"] = "相缪", ["word"] = {"橡"}},
    -- ["mjdd"] = {["phrase"] = "眠倒", ["word"] = {"渑"}},
    -- ["rvci"] = {["phrase"] = "睿慈", ["word"] = {"蕤"}},
    -- ["jlna"] = {["phrase"] = "矜纳", ["word"] = {"堇"}},
    -- ["jink"] = {["phrase"] = "祭鸟", ["word"] = {"犄"}},
    -- ["lird"] = {["phrase"] = "离桡", ["word"] = {"例", "俐"}},
    -- ["qnqy"] = {["phrase"] = "秋蛩", ["word"] = {"裘"}},
    -- ["migx"] = {["phrase"] = "秘怪", ["word"] = {"弥", "縻"}},
    -- ["yikr"] = {["phrase"] = "移垦", ["word"] = {"颐"}},
    -- ["kvir"] = {["phrase"] = "窥深", ["word"] = {"馈"}},
    -- ["tymk"] = {["phrase"] = "童妙", ["word"] = {"桐"}},
    -- ["somi"] = {["phrase"] = "索秘", ["word"] = {"桫"}},
    -- ["yxpd"] = {["phrase"] = "约炮", ["word"] = {"乐"}},
    -- ["lowf"] = {["phrase"] = "罗纨", ["word"] = {"雒"}},
    -- ["cvmm"] = {["phrase"] = "翠篾", ["word"] = {"毳"}},
    -- ["pjmk"] = {["phrase"] = "翩眇", ["word"] = {"骈"}},
    -- ["vpsc"] = {["phrase"] = "舟算", ["word"] = {"纣"}},
    -- ["jjzz"] = {["phrase"] = "荐撙", ["word"] = {"踺"}},
    -- ["rybj"] = {["phrase"] = "荣忭", ["word"] = {"冗"}},
    -- ["yqwf"] = {["phrase"] = "萦宛", ["word"] = {"赢", "嬴"}},
    -- ["pukf"] = {["phrase"] = "蒲龛", ["word"] = {"圃"}},
    -- ["huwo"] = {["phrase"] = "虎幄", ["word"] = {"瑚"}},
    -- ["xugv"] = {["phrase"] = "虚诡", ["word"] = {"魆"}},
    -- ["mfdy"] = {["phrase"] = "蛮峒", ["word"] = {"漫"}},
    -- ["piid"] = {["phrase"] = "蜱蛸", ["word"] = {"劈"}},
    -- ["jcjn"] = {["phrase"] = "蠲救", ["word"] = {"镌"}},
    -- ["xjnm"] = {["phrase"] = "衔啮", ["word"] = {"娴"}},
    -- ["cspp"] = {["phrase"] = "裁剖", ["word"] = {"彩"}},
    -- ["xiih"] = {["phrase"] = "西爽", ["word"] = {"熹"}},
    -- ["fudz"] = {["phrase"] = "覆敦", ["word"] = {"浮"}},
    -- ["furz"] = {["phrase"] = "覆润", ["word"] = {"俘"}},
    -- ["vakv"] = {["phrase"] = "诈愧", ["word"] = {"咋"}},
    -- ["vama"] = {["phrase"] = "诈马", ["word"] = {"查", "楂"}},
    -- ["xhvo"] = {["phrase"] = "详酌", ["word"] = {"箱"}},
    -- ["hzib"] = {["phrase"] = "诨耍", ["word"] = {"馄"}},
    -- ["ufiz"] = {["phrase"] = "谄顺", ["word"] = {"孱"}},
    -- ["jlne"] = {["phrase"] = "谨讷", ["word"] = {"觐"}},
    -- ["udko"] = {["phrase"] = "超阔", ["word"] = {"嘲"}},
    -- ["vcib"] = {["phrase"] = "转耍", ["word"] = {"馔"}},
    -- ["vckv"] = {["phrase"] = "转馈", ["word"] = {"啭"}},
    -- ["pibk"] = {["phrase"] = "辟摽", ["word"] = {"否", "痞"}},
    -- ["qjcc"] = {["phrase"] = "迁窜", ["word"] = {"荨"}},
    -- ["mido"] = {["phrase"] = "迷夺", ["word"] = {"汨"}},
    -- ["dzzw"] = {["phrase"] = "遁贼", ["word"] = {"蹾"}},
    -- ["xmzy"] = {["phrase"] = "邪宗", ["word"] = {"躞"}},
    -- ["dzwr"] = {["phrase"] = "钝闻", ["word"] = {"趸"}},
    -- ["lwyc"] = {["phrase"] = "镭源", ["word"] = {"酹"}},
    -- ["lpmn"] = {["phrase"] = "陋谬", ["word"] = {"娄", "楼"}},
    -- ["qxmt"] = {["phrase"] = "雀蒙", ["word"] = {"阕"}},
    -- ["yayy"] = {["phrase"] = "雅咏", ["word"] = {"讶"}},
    -- ["aiky"] = {["phrase"] = "霭空", ["word"] = {"嗳"}},
    -- ["fwkf"] = {["phrase"] = "飞瞰", ["word"] = {"匪", "啡"}},
    -- ["liaa"] = {["phrase"] = "骊阿", ["word"] = {"鳢"}},
    -- ["hhwo"] = {["phrase"] = "黄幄", ["word"] = {"肓"}},
    -- ["vglp"] = {["phrase"] = "张楼", ["word"] = {"彰"}},
    -- ["ljdz"] = {["phrase"] = "连墩", ["word"] = {"涟"}},
    -- ["lgdo"] = {["phrase"] = "浪多", ["word"] = {"朗"}},
    -- ["lumk"] = {["phrase"] = "鲁苗", ["word"] = {"闾", "榈"}},
    -- ["muco"] = {["phrase"] = "穆厝", ["word"] = {"暮", "苜"}},
    -- ["wukt"] = {["phrase"] = "乌坑", ["word"] = {"吴"}},
    -- ["tqcz"] = {["phrase"] = "汀村", ["word"] = {"莛"}},
    -- ["vgmi"] = {["phrase"] = "张咪", ["word"] = {"樟"}},
    -- ["tdkf"] = {["phrase"] = "陶侃", ["word"] = {"啕"}},
    -- ["xuty"] = {["phrase"] = "徐桐", ["word"] = {"墟", "圩"}},
    -- ["liwa"] = {["phrase"] = "里瓦", ["word"] = {"立"}},
    -- ["pucf"] = {["phrase"] = "仆参", ["word"] = {"葡", "蒲", "莆"}},
    -- ["gygr"] = {["phrase"] = "公根", ["word"] = {"贡"}},
    -- ["ycce"] = {["phrase"] = "圆测", ["word"] = {"芫"}},
    -- ["lhdm"] = {["phrase"] = "凉碟", ["word"] = {"梁", "粱"}},
    -- ["qila"] = {["phrase"] = "耆腊", ["word"] = {"亟"}},
    -- ["uikd"] = {["phrase"] = "赤尻", ["word"] = {"哧"}}
}

return dup_table
