name: glim
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      # - opencc # It doesn't support arm64 yet
      - opencc-python-reimplemented
      - pypinyin
      - jupyter
