import re
import json

Extra_No_Auto = ['洧', '沩', '嵬', '瘐', '嵎', '匜', '枥', '眄', '毂', '榖', '觳', '縠', '鼙', '靺', '莆', '桤', '槭', '螈', ]

Glyph_mappings = {
    "I": {
        "a": {"map": "a"},
        "b": {"map": "b"},
        "c": {"map": "c"},
        "d": {"map": "d"},
        "e": {"map": "e"},
        "f": {"map": "f"},
        "g": {"map": "g"},
        "h": {"map": "h"},
        "i": {"map": "i"},
        "j": {"map": "j"},
        "k": {"map": "k"},
        "l": {"map": "l"},
        "m": {"map": "m"},
        "n": {"map": "n"},
        "o": {"map": "o"},
        "p": {"map": "p"},
        "q": {"map": "q"},
        "r": {"map": "r"},
        "s": {"map": "s"},
        "t": {"map": "t"},
        "u": {"map": "u"},
        "v": {"map": "v"},
        "w": {"map": "w"},
        "x": {"map": "x"},
        "y": {"map": "y"},
        "z": {"map": "z"},
    },
    "II": {
        "a": {"map": "a"},
        "b": {"map": "b"},
        "c": {"map": "c"},
        "d": {"map": "d"},
        "e": {"map": "e"},
        "f": {"map": "f"},
        "g": {"map": "g"},
        "h": {"map": "h"},
        "i": {"map": "u"},
        "j": {"map": "j"},
        "k": {"map": "k"},
        "l": {"map": "l"},
        "m": {"map": "m"},
        "n": {"map": "n"},
        "o": {"map": "o"},
        "p": {"map": "p"},
        "q": {"map": "q"},
        "r": {"map": "r"},
        "s": {"map": "s"},
        "t": {"map": "t"},
        "u": {"map": "i"},
        "v": {"map": "v"},
        "w": {"map": "w"},
        "x": {"map": "x"},
        "y": {"map": "y"},
        "z": {"map": "z"},
    },
}

Sing_ch = {
    "a": "啊",
    "bu": "不",
    "cai": "才",
    "de": "的",
    "er": "二",
    "fei": "飞",
    "ge": "个",
    "he": "和",
    "chu": "出",
    "jiu": "就",
    "ke": "可",
    "le": "了",
    "mei": "没",
    "ni": "你",
    "o": "哦",
    "ping": "平",
    "qu": "去",
    "ren": "人",
    "san": "三",
    "ta": "他",
    "shi": "是",
    "zhe": "这",
    "wo": "我",
    "xiao": "小",
    "yi": "一",
    "zai": "在",
}

Algebras = {
    "flypy": [
        ["^a$", "aa"],
        ["^o$", "oo"],
        ["^e$", "ee"],
        ["^ang$", "ah"],
        ["^ch", "I"],
        ["^sh", "U"],
        ["^zh", "V"],
        ["(\w)iang", "\\1L"],
        ["(\w)uang", "\\1L"],
        ["(\w)iong", "\\1S"],
        ["(\w)ang", "\\1H"],
        ["(\w)eng", "\\1G"],
        ["(\w)ong", "\\1S"],
        ["(\w)ian", "\\1M"],
        ["(\w)iao", "\\1N"],
        ["(\w)ing", "\\1K"],
        ["(\w)uai", "\\1K"],
        ["(\w)uan", "\\1R"],
        ["(\w)ai", "\\1D"],
        ["(\w)an", "\\1J"],
        ["(\w)ao", "\\1C"],
        ["(\w)ei", "\\1W"],
        ["(\w)en", "\\1F"],
        ["(\w)ia", "\\1X"],
        ["(\w)ie", "\\1P"],
        ["(\w)in", "\\1B"],
        ["(\w)iu", "\\1Q"],
        ["(\w)ou", "\\1Z"],
        ["(\w)ua", "\\1X"],
        ["(\w)ue", "\\1T"],
        ["(\w)ui", "\\1V"],
        ["(\w)un", "\\1Y"],
        ["(\w)uo", "\\1O"],
        ["(\w)ve", "\\1T"],
    ],
    "natural": [
        ["^a$", "aa"],
        ["^o$", "oo"],
        ["^e$", "ee"],
        ["^ang$", "ah"],
        ["^ch", "I"],
        ["^sh", "U"],
        ["^zh", "V"],
        ["(\w)iang", "\\1D"],
        ["(\w)uang", "\\1D"],
        ["(\w)iong", "\\1S"],
        ["(\w)ang", "\\1H"],
        ["(\w)eng", "\\1G"],
        ["(\w)ong", "\\1S"],
        ["(\w)ian", "\\1M"],
        ["(\w)iao", "\\1C"],
        ["(\w)ing", "\\1Y"],
        ["(\w)uai", "\\1Y"],
        ["(\w)uan", "\\1R"],
        ["(\w)ai", "\\1L"],
        ["(\w)an", "\\1J"],
        ["(\w)ao", "\\1K"],
        ["(\w)ei", "\\1Z"],
        ["(\w)en", "\\1F"],
        ["(\w)ia", "\\1W"],
        ["(\w)ie", "\\1X"],
        ["(\w)in", "\\1N"],
        ["(\w)iu", "\\1Q"],
        ["(\w)ou", "\\1B"],
        ["(\w)ua", "\\1W"],
        ["(\w)ue", "\\1T"],
        ["(\w)ui", "\\1V"],
        ["(\w)un", "\\1P"],
        ["(\w)uo", "\\1O"],
        ["(\w)ve", "\\1T"],
    ],
    "ms": [
        ["^a$", "aa"],
        ["^o$", "oo"],
        ["^e$", "ee"],
        ["^ang$", "ah"],
        ["^ch", "I"],
        ["^sh", "U"],
        ["^zh", "V"],
        ["(\w)iang", "\\1D"],
        ["(\w)uang", "\\1D"],
        ["(\w)iong", "\\1S"],
        ["(\w)ang", "\\1H"],
        ["(\w)eng", "\\1G"],
        ["(\w)ong", "\\1S"],
        ["(\w)ian", "\\1M"],
        ["(\w)iao", "\\1C"],
        ["(\w)ing", "\\1;"],
        ["(\w)uai", "\\1Y"],
        ["(\w)uan", "\\1R"],
        ["(\w)ai", "\\1L"],
        ["(\w)an", "\\1J"],
        ["(\w)ao", "\\1K"],
        ["(\w)ei", "\\1Z"],
        ["(\w)en", "\\1F"],
        ["(\w)ia", "\\1W"],
        ["(\w)ie", "\\1X"],
        ["(\w)in", "\\1N"],
        ["(\w)iu", "\\1Q"],
        ["(\w)ou", "\\1B"],
        ["(\w)ua", "\\1W"],
        ["(\w)ue", "\\1T"],
        ["(\w)ui", "\\1V"],
        ["(\w)un", "\\1P"],
        ["(\w)uo", "\\1O"],
        ["(\w)ve", "\\1T"],
        ["(\w)v", "\\1Y"],
    ],
    "pyjj": [
        ["^a$", "aa"],
        ["^o$", "oo"],
        ["^e$", "ee"],
        ["^er$", "eq"],
        ["^ang$", "ag"],
        ["^ch", "U"],
        ["^sh", "I"],
        ["^zh", "V"],
        ["(\w)iang", "\\1H"],
        ["(\w)uang", "\\1H"],
        ["(\w)iong", "\\1Y"],
        ["(\w)ang", "\\1G"],
        ["(\w)eng", "\\1T"],
        ["(\w)ong", "\\1Y"],
        ["(\w)ian", "\\1J"],
        ["(\w)iao", "\\1K"],
        ["(\w)ing", "\\1Q"],
        ["(\w)uai", "\\1X"],
        ["(\w)uan", "\\1C"],
        ["(\w)ai", "\\1S"],
        ["(\w)an", "\\1F"],
        ["(\w)ao", "\\1D"],
        ["(\w)ei", "\\1W"],
        ["(\w)en", "\\1R"],
        ["(\w)ia", "\\1B"],
        ["(\w)ie", "\\1M"],
        ["(\w)in", "\\1L"],
        ["(\w)iu", "\\1N"],
        ["(\w)ou", "\\1P"],
        ["(\w)ua", "\\1B"],
        ["(\w)ue", "\\1X"],
        ["(\w)ui", "\\1V"],
        ["(\w)un", "\\1Z"],
        ["(\w)uo", "\\1O"],
        ["(\w)ve", "\\1X"],
    ],
    "chole": [
        ["^j", "E"],
        ["^a$", "aa"],
        ["^o$", "oo"],
        ["^e$", "ee"],
        ["^ei$", "ew"],
        ["^en$", "es"],
        ["^ang$", "al"],
        ["^ch", "U"],
        ["^sh", "I"],
        ["^zh", "V"],
        ["(\w)iang", "\\1Y"],
        ["(\w)uang", "\\1Y"],
        ["(\w)iong", "\\1M"],
        ["(\w)ang", "\\1L"],
        ["(\w)eng", "\\1P"],
        ["(\w)ong", "\\1M"],
        ["(\w)ian", "\\1N"],
        ["(\w)iao", "\\1J"],
        ["(\w)ing", "\\1F"],
        ["(\w)uai", "\\1F"],
        ["(\w)uan", "\\1H"],
        ["(\w)ai", "\\1Z"],
        ["(\w)an", "\\1T"],
        ["(\w)ao", "\\1D"],
        ["(\w)ei", "\\1W"],
        ["(\w)en", "\\1S"],
        ["(\w)ia", "\\1X"],
        ["(\w)ie", "\\1K"],
        ["(\w)in", "\\1C"],
        ["(\w)iu", "\\1Q"],
        ["(\w)ou", "\\1R"],
        ["(\w)ua", "\\1X"],
        ["(\w)ue", "\\1G"],
        ["(\w)ui", "\\1V"],
        ["(\w)un", "\\1B"],
        ["(\w)uo", "\\1O"],
        ["(\w)ve", "\\1G"],
    ],
}

Layouts = {
    "flypy": {"mapping": "I", "algebra": "flypy"},
    "natural": {"mapping": "I", "algebra": "natural"},
    "ms": {"mapping": "I", "algebra": "ms"},
    "pyjj": {"mapping": "II", "algebra": "pyjj"},
    "chole": {"mapping": "II", "algebra": "chole"},
}


def glyph_encoding(mapping, glyph_json="../assets/xiaohe-8105.json"):
    glyph_dict = {}
    dict_json = json.load(open(glyph_json, "r"))
    for i in dict_json:
        if i["level"] == "1" or i["level"] == "2":
            glyph_dict[i["character"]] = {
                "gl1": mapping[i["first_py"]]["map"],
                "gl2": mapping[i["last_py"]]["map"],
            }

    return glyph_dict


def py_full_double_converter(py, algebra):
    for alg in algebra:
        pattern = alg[0]
        repl = alg[1]
        py = re.sub(pattern, repl, py)
    return py.lower()
