#!/bin/bash

INIT_DIR=$(dirname $(readlink -f "$0"))

skip_update=false
skip_gen=false
reset_custom=false
update_sogou=false
update_emoji=false
update_duplicate=false

while getopts "cdesug" opt; do
  case $opt in
    c) reset_custom=true;;
    d) update_duplicate=true;;
    e) update_emoji=true;;
    s) update_sogou=true;;
    u) skip_update=true;;
    g) skip_gen=true;;
  esac
done
shift $((OPTIND -1))

cd $INIT_DIR; cd ..; mkdir -p cache; cd cache

_clone_or_pull () {
  if [[ -d ./$1 ]]; then
    cd ./$1; echo "Updating $1..."; git pull; cd - >/dev/null
  else git clone --depth 1 $2
  fi
}

_update_emoji() {
  cp ../src/{emoji.js,package.json} .
  yarn add gemoji --latest
  local version=$(yarn info gemoji version --silent)
  GEMOJI_VER=$version node emoji.js
  cp ./emoji.dict.yaml ..
}

update_dicts_basic() {
  _clone_or_pull rime-pinyin-simp 'https://github.com/rime/rime-pinyin-simp'
  _clone_or_pull rime-essay 'https://github.com/rime/rime-essay'
  _clone_or_pull phrase-pinyin-data 'https://github.com/mozillazg/phrase-pinyin-data'
  _clone_or_pull fcitx5-pinyin-zhwiki 'https://github.com/felixonmars/fcitx5-pinyin-zhwiki'
  _clone_or_pull rime-ice 'https://github.com/iDvel/rime-ice'
  zhw_latest=$(grep 'github.com' ./fcitx5-pinyin-zhwiki/recipe.yaml | awk -F '::' '{print $2}')
  echo $zhw_latest
  local zhw_ver="./zhwiki_latest.txt"
  [[ -f $zhw_ver ]] && zhw_last=$(cat $zhw_ver) || touch $zhw_ver
  [[ $zhw_last == $zhw_latest ]] && echo "zhwiki is up to date" || {
    echo "Downloading latest zhwiki..."
    echo $zhw_latest > $zhw_ver
    curl -o zhwiki.dict.yaml -OL $zhw_latest 
  }
  cat ./phrase-pinyin-data/large_pinyin.txt | sed "s/ \?#.*//;s/: /\\t/" > pdb.txt
  cp ./rime-essay/essay.txt .
  cp ./rime-pinyin-simp/pinyin_simp.dict.yaml .
  cp ./rime-ice/cn_dicts/main.dict.yaml .
  $update_emoji && _update_emoji
}

gen_dicts_basic() {
  $skip_gen && skip="--no-gen" || skip="--gen"
  ../src/glim_dict_gen.py $skip
  ../src/glim_charset_gen.py
  ../src/glim_encode.py
  cp ./glim_phrase.dict.yaml ../dicts
  cp ./zhwiki.dict.yaml ../dicts
}

$skip_update || update_dicts_basic
gen_dicts_basic

$update_duplicate && {
  ../src/glim_duplicate.py
  stylua ./lua/duplicate/
  mv ./lua/duplicate/*.lua ../lua/tables/duplicate/
}
$reset_custom && cp ../assets/glim.custom.yaml .. || exit 0
